CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmontonDetails_FormGN24]
ON [dbo].[WorkPermitEdmontonDetails]
([FormGN24Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmontonDetails_FormGN6]
ON [dbo].[WorkPermitEdmontonDetails]
([FormGN6Id])
WHERE (FormGN6Id IS NOT NULL)
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO


GO

