  
  
IF OBJECT_ID('InsertPermitRequestFortHillsSAPImportData', 'P') IS NOT NULL
DROP PROC InsertPermitRequestFortHillsSAPImportData
GO 
   
    
CREATE Procedure [dbo].[InsertPermitRequestFortHillsSAPImportData]    
(    
 @Id bigint Output,    
 @BatchId bigint,    
 @BatchItemCreatedAt datetime,    
 @WorkOrderNumber varchar(25),    
 @OperationNumber varchar(4),    
 @SubOperationNumber varchar(4) = NULL,    
 @PriorityId int,    
 @EndDate datetime,    
 @Description varchar(8000),     
 @Company varchar(50) = NULL,      
 @Occupation varchar(50),    
 @SAPWorkCentre varchar(40) = NULL,    
 @NumberOfWorkers int = NULL,    
 @WorkPermitTypeId int,     
 @FunctionalLocationId int,    
 @Location varchar(100),    
 @FlameResistantWorkWear  bit,  
 @ChemicalSuit  bit,  
 @FireWatch  bit,  
 @FireBlanket  bit,  
 @SuppliedBreathingAir  bit,  
 @AirMover  bit,  
 @PersonalFlotationDevice  bit,  
 @HearingProtection  bit,  
 @Other1  varchar(30),  
 @MonoGoggles  bit,  
 @ConfinedSpaceMoniter  bit,  
 @FireExtinguisher  bit,  
 @SparkContainment  bit,  
 @BottleWatch  bit,  
 @StandbyPerson  bit,  
 @WorkingAlone  bit,  
 @SafetyGloves  bit,  
 @Other2  varchar(30),  
 @FaceShield  bit,  
 @FallProtection  bit,  
 @ChargedFireHouse  bit,  
 @CoveredSewer  bit,  
 @AirPurifyingRespirator  bit,  
 @SingalPerson  bit,  
 @CommunicationDevice  bit,  
 @ReflectiveStrips  bit,  
 @Other3  varchar(30),  
 @ConfinedSpace  bit,  
 @ConfinedSpaceClass  varchar(25),  
 @GroundDisturbance  bit,  
 @FireProtectionAuthorization  bit,  
 @CriticalOrSeriousLifts  bit,  
 @VehicleEntry  bit,  
 @IndustrialRadiography  bit,  
 @ElectricalEncroachment  bit,  
 @MSDS  bit,  
 @OthersPartE  varchar(30),  
    
     
 @DoNotMerge bit    
    )    
AS    
    
INSERT INTO PermitRequestFortHillsSAPImportData    
(     
 BatchId,    
 BatchItemCreatedAt,  
 WorkOrderNumber,    
 OperationNumber,    
 SubOperationNumber,     
 PriorityId,    
 EndDate,    
 TaskDescription,     
 Company,      
 Occupation,    
 SAPWorkCentre,    
 NumberOfWorkers,    
 WorkPermitTypeId,     
 FunctionalLocationId,    
 Location,    
 FlameResistantWorkWear,  
 ChemicalSuit,  
 FireWatch,  
 FireBlanket,  
 SuppliedBreathingAir,  
 AirMover,  
 PersonalFlotationDevice,  
 HearingProtection,  
 Other1,  
 MonoGoggles,  
 ConfinedSpaceMoniter,  
 FireExtinguisher,  
 SparkContainment,  
 BottleWatch,  
 StandbyPerson,  
 WorkingAlone,  
 SafetyGloves,  
 Other2,  
 FaceShield,  
 FallProtection,  
 ChargedFireHouse,  
 CoveredSewer,  
 AirPurifyingRespirator,  
 SingalPerson,  
 CommunicationDevice,  
 ReflectiveStrips,  
 Other3,  
 ConfinedSpace,  
 ConfinedSpaceClass,  
 GroundDisturbance,  
 FireProtectionAuthorization,  
 CriticalOrSeriousLifts,  
 VehicleEntry,  
 IndustrialRadiography,  
 ElectricalEncroachment,  
 MSDS,  
 OthersPartE,  
  
 DoNotMerge    
)    
VALUES    
(     
 @BatchId,    
 @BatchItemCreatedAt,    
 @WorkOrderNumber,    
 @OperationNumber,    
 @SubOperationNumber,     
 @PriorityId,    
 @EndDate,    
 @Description,     
 @Company,      
 @Occupation,    
 @SAPWorkCentre,    
 @NumberOfWorkers,    
 @WorkPermitTypeId,     
 @FunctionalLocationId,    
 @Location,    
 @FlameResistantWorkWear,  
 @ChemicalSuit,  
 @FireWatch,  
 @FireBlanket,  
 @SuppliedBreathingAir,  
 @AirMover,  
 @PersonalFlotationDevice,  
 @HearingProtection,  
 @Other1,  
 @MonoGoggles,  
 @ConfinedSpaceMoniter,  
 @FireExtinguisher,  
 @SparkContainment,  
 @BottleWatch,  
 @StandbyPerson,  
 @WorkingAlone,  
 @SafetyGloves,  
 @Other2,  
 @FaceShield,  
 @FallProtection,  
 @ChargedFireHouse,  
 @CoveredSewer,  
 @AirPurifyingRespirator,  
 @SingalPerson,  
 @CommunicationDevice,  
 @ReflectiveStrips,  
 @Other3,  
 @ConfinedSpace,  
 @ConfinedSpaceClass,  
 @GroundDisturbance,  
 @FireProtectionAuthorization,  
 @CriticalOrSeriousLifts,  
 @VehicleEntry,  
 @IndustrialRadiography,  
 @ElectricalEncroachment,  
 @MSDS,  
 @OthersPartE,  
   
   
 @DoNotMerge    
)    
SET @Id= SCOPE_IDENTITY()     
    
GRANT EXEC ON [InsertPermitRequestFortHillsSAPImportData] TO PUBLIC 