//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Suncor.Olt.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfragisticsStringResources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfragisticsStringResources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Suncor.Olt.Client.Localization.InfragisticsStringResources_fr", typeof(InfragisticsStringResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string FilterDialogAllComboItem {
            get {
                return ResourceManager.GetString("FilterDialogAllComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string FilterDialogAnyComboItem {
            get {
                return ResourceManager.GetString("FilterDialogAnyComboItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre basé sur {0} des conditions suivantes :.
        /// </summary>
        public static string FilterDialogApplyLabelText {
            get {
                return ResourceManager.GetString("FilterDialogApplyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Annuler.
        /// </summary>
        public static string FilterDialogCancelButtonText {
            get {
                return ResourceManager.GetString("FilterDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;jouter.
        /// </summary>
        public static string FilterDialogConditionAddButtonText {
            get {
                return ResourceManager.GetString("FilterDialogConditionAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Supprimer.
        /// </summary>
        public static string FilterDialogConditionDeleteButtonText {
            get {
                return ResourceManager.GetString("FilterDialogConditionDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string FilterDialogOkButtonText {
            get {
                return ResourceManager.GetString("FilterDialogOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre personnalisé.
        /// </summary>
        public static string FilterDialogTitle {
            get {
                return ResourceManager.GetString("FilterDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string FilterUIProvider_CancelButton {
            get {
                return ResourceManager.GetString("FilterUIProvider_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le filtre.
        /// </summary>
        public static string FilterUIProvider_Menu_ClearFilter {
            get {
                return ResourceManager.GetString("FilterUIProvider_Menu_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filtres par date.
        /// </summary>
        public static string FilterUIProvider_Menu_DateFilters {
            get {
                return ResourceManager.GetString("FilterUIProvider_Menu_DateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filtres par numéro.
        /// </summary>
        public static string FilterUIProvider_Menu_NumberFilters {
            get {
                return ResourceManager.GetString("FilterUIProvider_Menu_NumberFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filtres textuels.
        /// </summary>
        public static string FilterUIProvider_Menu_TextFilters {
            get {
                return ResourceManager.GetString("FilterUIProvider_Menu_TextFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string FilterUIProvider_OKButton {
            get {
                return ResourceManager.GetString("FilterUIProvider_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glisser ici un en-tête de colonne pour regrouper à partir de cette colonne..
        /// </summary>
        public static string GroupByBoxDefaultPrompt {
            get {
                return ResourceManager.GetString("GroupByBoxDefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour inverser l&apos;ordre de tri.
        /// </summary>
        public static string GroupByButtonToolTip {
            get {
                return ResourceManager.GetString("GroupByButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [caption] : [value] ([count] [count,articles,article,articles]).
        /// </summary>
        public static string LDR_Layout_mask {
            get {
                return ResourceManager.GetString("LDR_Layout_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vides.
        /// </summary>
        public static string RowFilterDialogBlanksItem {
            get {
                return ResourceManager.GetString("RowFilterDialogBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est vide.
        /// </summary>
        public static string RowFilterDialogDBNullItem {
            get {
                return ResourceManager.GetString("RowFilterDialogDBNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte vide.
        /// </summary>
        public static string RowFilterDialogEmptyTextItem {
            get {
                return ResourceManager.GetString("RowFilterDialogEmptyTextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contient.
        /// </summary>
        public static string RowFilterDropDown_Operator_Contains {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne contient pas.
        /// </summary>
        public static string RowFilterDropDown_Operator_DoesNotContain {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne se termine pas par.
        /// </summary>
        public static string RowFilterDropDown_Operator_DoesNotEndWith {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne correspond pas.
        /// </summary>
        public static string RowFilterDropDown_Operator_DoesNotMatch {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne commence pas par.
        /// </summary>
        public static string RowFilterDropDown_Operator_DoesNotStartWith {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se termine par.
        /// </summary>
        public static string RowFilterDropDown_Operator_EndsWith {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non similaire.
        /// </summary>
        public static string RowFilterDropDown_Operator_NotLike {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_NotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence par.
        /// </summary>
        public static string RowFilterDropDown_Operator_StartsWith {
            get {
                return ResourceManager.GetString("RowFilterDropDown_Operator_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Tous).
        /// </summary>
        public static string RowFilterDropDownAllItem {
            get {
                return ResourceManager.GetString("RowFilterDropDownAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Vides).
        /// </summary>
        public static string RowFilterDropDownBlanksItem {
            get {
                return ResourceManager.GetString("RowFilterDropDownBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est égal à.
        /// </summary>
        public static string RowFilterDropDownEquals {
            get {
                return ResourceManager.GetString("RowFilterDropDownEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur à.
        /// </summary>
        public static string RowFilterDropDownGreaterThan {
            get {
                return ResourceManager.GetString("RowFilterDropDownGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supérieur ou égal à.
        /// </summary>
        public static string RowFilterDropDownGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("RowFilterDropDownGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur à.
        /// </summary>
        public static string RowFilterDropDownLessThan {
            get {
                return ResourceManager.GetString("RowFilterDropDownLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur ou égal à.
        /// </summary>
        public static string RowFilterDropDownLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("RowFilterDropDownLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similaire.
        /// </summary>
        public static string RowFilterDropDownLike {
            get {
                return ResourceManager.GetString("RowFilterDropDownLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspond à une expression ordinaire.
        /// </summary>
        public static string RowFilterDropDownMatch {
            get {
                return ResourceManager.GetString("RowFilterDropDownMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;est pas égal à.
        /// </summary>
        public static string RowFilterDropDownNotEquals {
            get {
                return ResourceManager.GetString("RowFilterDropDownNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Avril.
        /// </summary>
        public static string SpecialFilterOperand_April {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aoû&amp;t.
        /// </summary>
        public static string SpecialFilterOperand_August {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Décembre.
        /// </summary>
        public static string SpecialFilterOperand_December {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Février.
        /// </summary>
        public static string SpecialFilterOperand_February {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Janvier.
        /// </summary>
        public static string SpecialFilterOperand_January {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jui&amp;llet.
        /// </summary>
        public static string SpecialFilterOperand_July {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&amp;uin.
        /// </summary>
        public static string SpecialFilterOperand_June {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mois dern&amp;ier.
        /// </summary>
        public static string SpecialFilterOperand_LastMonth {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le trimestre d&amp;ernier.
        /// </summary>
        public static string SpecialFilterOperand_LastQuarter {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La semaine de&amp;rnière.
        /// </summary>
        public static string SpecialFilterOperand_LastWeek {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;année der&amp;nière.
        /// </summary>
        public static string SpecialFilterOperand_LastYear {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Mars.
        /// </summary>
        public static string SpecialFilterOperand_March {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&amp;i.
        /// </summary>
        public static string SpecialFilterOperand_May {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mois &amp;prochain.
        /// </summary>
        public static string SpecialFilterOperand_NextMonth {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le trimestre pr&amp;ochain.
        /// </summary>
        public static string SpecialFilterOperand_NextQuarter {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_NextQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La semaine pro&amp;chaine.
        /// </summary>
        public static string SpecialFilterOperand_NextWeek {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;année proc&amp;haine.
        /// </summary>
        public static string SpecialFilterOperand_NextYear {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Novembre.
        /// </summary>
        public static string SpecialFilterOperand_November {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Octobre.
        /// </summary>
        public static string SpecialFilterOperand_October {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;1er trimestre.
        /// </summary>
        public static string SpecialFilterOperand_Quarter1 {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Quarter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;2e trimestre.
        /// </summary>
        public static string SpecialFilterOperand_Quarter2 {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Quarter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;3e trimestre.
        /// </summary>
        public static string SpecialFilterOperand_Quarter3 {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Quarter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;4e trimestre.
        /// </summary>
        public static string SpecialFilterOperand_Quarter4 {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Quarter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Septembre.
        /// </summary>
        public static string SpecialFilterOperand_September {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le &amp;mois en cours.
        /// </summary>
        public static string SpecialFilterOperand_ThisMonth {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le &amp;trimestre en cours.
        /// </summary>
        public static string SpecialFilterOperand_ThisQuarter {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La &amp;semaine en cours.
        /// </summary>
        public static string SpecialFilterOperand_ThisWeek {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;&amp;année en cours.
        /// </summary>
        public static string SpecialFilterOperand_ThisYear {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au&amp;jourd&apos;hui.
        /// </summary>
        public static string SpecialFilterOperand_Today {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Demain.
        /// </summary>
        public static string SpecialFilterOperand_Tomorrow {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;année en cours - à ce jour.
        /// </summary>
        public static string SpecialFilterOperand_YearToDate {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_YearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hier.
        /// </summary>
        public static string SpecialFilterOperand_Yesterday {
            get {
                return ResourceManager.GetString("SpecialFilterOperand_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Après le....
        /// </summary>
        public static string UltraGridFilterUIProvider_AfterOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_AfterOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les dates dans la pé&amp;riode.
        /// </summary>
        public static string UltraGridFilterUIProvider_AllDatesInPeriod_Menu {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_AllDatesInPeriod_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;vant....
        /// </summary>
        public static string UltraGridFilterUIProvider_BeforeOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_BeforeOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Commence le....
        /// </summary>
        public static string UltraGridFilterUIProvider_BeginsWithOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_BeginsWithOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entre....
        /// </summary>
        public static string UltraGridFilterUIProvider_BetweenOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_BetweenOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con&amp;tient....
        /// </summary>
        public static string UltraGridFilterUIProvider_ContainsOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_ContainsOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filtre personnalisé....
        /// </summary>
        public static string UltraGridFilterUIProvider_CustomFilter {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_CustomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ne contient pas….
        /// </summary>
        public static string UltraGridFilterUIProvider_DoesNotContainOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_DoesNotContainOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;est &amp;pas égal à....
        /// </summary>
        public static string UltraGridFilterUIProvider_DoesNotEqualOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_DoesNotEqualOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ter&amp;mine le....
        /// </summary>
        public static string UltraGridFilterUIProvider_EndsWithOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_EndsWithOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est é&amp;gal à....
        /// </summary>
        public static string UltraGridFilterUIProvider_EqualsOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_EqualsOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est &amp;supérieur à....
        /// </summary>
        public static string UltraGridFilterUIProvider_GreaterThanOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_GreaterThanOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est supérieur &amp;ou égal à....
        /// </summary>
        public static string UltraGridFilterUIProvider_GreaterThanOrEqualToOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_GreaterThanOrEqualToOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est &amp;inférieur à....
        /// </summary>
        public static string UltraGridFilterUIProvider_LessThanOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_LessThanOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inférieur o&amp;u égal à....
        /// </summary>
        public static string UltraGridFilterUIProvider_LessThanOrEqualToOperand {
            get {
                return ResourceManager.GetString("UltraGridFilterUIProvider_LessThanOrEqualToOperand", resourceCulture);
            }
        }
    }
}
