

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'GETWORKPERMITSIGN_HISTORY')
	BEGIN
		DROP PROCEDURE [dbo].[GETWORKPERMITSIGN_HISTORY]
	END
	
GO
CREATE Procedure [dbo].[GETWORKPERMITSIGN_HISTORY]    
(    
 @WorkPermitId Varchar(100)

 
     
)    
AS    
 
 SELECT * FROM  WORKPERMITSIGN_HISTORY WHERE WorkPermitId=@WorkPermitId 
UNION ALL
SELECT * FROM  WORKPERMITSIGN WHERE WorkPermitId=@WorkPermitId 
 
 
    
GRANT EXEC ON [GETWORKPERMITSIGN] TO PUBLIC       