CREATE NONCLUSTERED INDEX [IDX_RestrictionLocationItem_RestrictionLocation]
ON [dbo].[RestrictionLocationItem]
([RestrictionLocationId])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO


CREATE CLUSTERED INDEX [IDX_FormGN1History]
ON [dbo].[FormGN1History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO


CREATE CLUSTERED INDEX [IDX_TradeChecklistHistory]
ON [dbo].[TradeChecklistHistory]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IDX_DeviationAlertResponseReasonCodeAssignment_DeviationAlertResponse]
ON [dbo].[DeviationAlertResponseReasonCodeAssignment]
([DeviationAlertResponseId])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IDX_DeviationAlert_StartDateTime]
ON [dbo].[DeviationAlert]
([StartDateTime] , [FunctionalLocationID] , [EndDateTime])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE,
DROP_EXISTING = ON
)
ON [PRIMARY];
GO


GO

