if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermitEdmonton]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertWorkPermitEdmonton]
GO

CREATE Procedure [dbo].[InsertWorkPermitEdmonton]                  
(                  
 @Id bigint Output,                  
 @PermitNumber bigint Output,                  
 @PermitRequestId bigint = NULL,                  
                   
 @PriorityId int,                  
 @WorkPermitStatusId int,                  
 @DataSourceId int,                  
 @IssuedToSuncor bit,                  
 @IssuedToCompany bit,                  
 @Company varchar(50) = NULL,                  
 @Occupation varchar(50),                  
 @GroupId bigint,                  
 @NumberOfWorkers int = NULL,                  
 @WorkPermitTypeId int,                  
 @DurationPermit bit,                  
 @FunctionalLocationId bigint,                  
 @Location varchar(50),                  
 @AreaLabelId bigint = NULL,                  
                   
 @RequestedStartDateTime datetime,                  
 @IssuedDateTime datetime = NULL,                  
 @ExpiredDateTime datetime,                  
 @WorkOrderNumber varchar(12) = NULL,
 @ClonedFormDetailEdmonton varchar(100) = NULL,   
 @OperationNumber varchar(max) = NULL,                  
 @SubOperationNumber varchar(max) = NULL,                  
 @TaskDescription varchar(8000) = NULL,                  
 @HazardsAndOrRequirements varchar(2000) = NULL,                    
 @CreatedDateTime datetime,                  
 @CreatedByUserId bigint,                  
 @PermitRequestCreatedByUserId bigint = NULL,                  
 @LastModifiedByUserId bigint,                  
 @LastModifiedDateTime datetime,                   
 @ShouldCreatePermitNumber bit,                  
                  
 @UsePreviousPermitAnswered bit,                  
                    
 @AlkylationEntry bit,                  
 @AlkylationEntryClassOfClothing varchar(25) = NULL,                  
 @FlarePitEntry bit,                  
 @FlarePitEntryType varchar(25) = NULL,                  
 @ConfinedSpace bit,                  
 @ConfinedSpaceCardNumber varchar(10) = NULL,                  
 @ConfinedSpaceClass varchar(25) = NULL,                  
 @RescuePlan bit,                  
 @RescuePlanFormNumber varchar(10) = NULL,                   
 @VehicleEntry bit,                  
 @VehicleEntryTotal int = NULL,                  
 @VehicleEntryType varchar(30) = NULL,                  
 @SpecialWork bit,                  
 @SpecialWorkFormNumber varchar(10) = NULL,                  
 @SpecialWorkType int = NULL,                  
                   
 @GN59 bit,                  
 @FormGN59Id bigint = NULL,                  
 @GN7 bit,                  
 @FormGN7Id bigint = NULL,                  
 @GN24 bit,                  
 @FormGN24Id bigint = NULL,                  
 @GN6 bit,                  
 @FormGN6Id bigint = NULL,                  
 @GN75A bit,                  
 @FormGN75AId bigint = NULL,                  
                  
 @GN27 int,                  
 @GN11 int,                  
 @GN75_Deprecated int,                  
 @GN24_Deprecated int,                  
 @GN6_Deprecated int,                  
                    
 @GN1 bit,                  
 @FormGN1Id bigint = NULL,                  
 @FormGN1TradeChecklistId bigint = NULL,                  
 @FormGN1TradeChecklistDisplayNumber varchar(32) = NULL,                  
                      
 @OtherAreasAndOrUnitsAffected bit,                  
    @OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,                  
 @OtherAreasAndOrUnitsAffectedPersonNotified varchar(30) = NULL,                  
                  
 @StatusOfPipingEquipmentSectionNotApplicableToJob bit,                  
 @ProductNormallyInPipingEquipment varchar(50) = NULL,                  
 @IsolationValvesLocked bit = NULL,                  
 @DepressuredDrained bit = NULL,                  
 @Ventilated bit = NULL,                  
 @Purged bit = NULL,                  
 @BlindedAndTagged bit = NULL,                  
 @DoubleBlockAndBleed bit = NULL,                  
 @ElectricalLockout bit = NULL,                  
 @MechanicalLockout bit = NULL,                  
 @BlindSchematicAvailable bit = NULL,                  
                   
 @ZeroEnergyFormNumber varchar(10) = NULL,                  
 @LockBoxNumber varchar(10) = NULL,                  
 @JobsiteEquipmentInspected bit,                  
 @ConfinedSpaceWorkSectionNotApplicableToJob bit,                   
 @QuestionOneResponse bit,                  
 @QuestionTwoResponse bit = NULL,         
 @QuestionTwoAResponse bit,                  
 @QuestionTwoBResponse bit,                  
 @QuestionThreeResponse bit,                  
 @QuestionFourResponse bit = NULL,                  
        
 @GasTestsSectionNotApplicableToJob bit,                  
 @WorkerToProvideGasTestData bit,                  
 @OperatorGasDetectorNumber varchar(30) = NULL,                  
 @GasTestDataLine1CombustibleGas varchar(30) = NULL,             
 @GasTestDataLine1Oxygen varchar(10) = NULL,                  
 @GasTestDataLine1ToxicGas varchar(30) = NULL,                  
 @GasTestDataLine1Time datetime = NULL,                  
 @GasTestDataLine2CombustibleGas varchar(30) = NULL,                  
@GasTestDataLine2Oxygen varchar(10) = NULL,                  
 @GasTestDataLine2ToxicGas varchar(30) = NULL,                  
 @GasTestDataLine2Time datetime = NULL,                  
 @GasTestDataLine3CombustibleGas varchar(30) = NULL,                  
 @GasTestDataLine3Oxygen varchar(10) = NULL,                  
 @GasTestDataLine3ToxicGas varchar(30) = NULL,                  
 @GasTestDataLine3Time datetime = NULL,                  
 @GasTestDataLine4CombustibleGas varchar(30) = NULL,                  
 @GasTestDataLine4Oxygen varchar(10) = NULL,                  
 @GasTestDataLine4ToxicGas varchar(30) = NULL,                  
 @GasTestDataLine4Time datetime = NULL,                  
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob bit,                  
                   
 @FaceShield bit,                  
 @Goggles bit,                  
 @RubberBoots bit,                  
 @RubberGloves bit,                   
 @RubberSuit bit,                  
                   
 @SafetyHarnessLifeline bit,                  
 @HighVoltagePPE bit,                  
 @Other1Checked bit,                  
 @Other1 varchar(15) = NULL,                  
 @EquipmentGrounded bit,                  
                   
 @FireBlanket bit,                  
 @FireExtinguisher bit,                  
 @FireMonitorManned bit,                  
 @FireWatch bit,                  
 @SewersDrainsCovered bit,                  
                   
 @SteamHose bit,                  
 @Other2Checked bit,                  
 @Other2 varchar(15) = NULL,                  
 @AirPurifyingRespirator bit,                  
 @BreathingAirApparatus bit,                  
                   
 @DustMask bit,                  
 @LifeSupportSystem bit,                  
 @SafetyWatch bit,                  
 @ContinuousGasMonitor bit,                  
 @WorkersMonitor bit,                  
 @WorkersMonitorNumber varchar(10) = NULL,                  
                   
 @BumpTestMonitorPriorToUse bit,                  
 @Other3Checked bit,                  
 @Other3 varchar(15) = NULL,                  
 @AirMover bit,                  
 @BarriersSigns bit,                  
                   
 @RadioChannel bit,                  
 @RadioChannelNumber varchar(10) = NULL,                  
 @AirHorn bit,                  
 @MechVentilationComfortOnly bit,                  
 @AsbestosMMCPrecautions bit,                  
 @Other4Checked bit,                  
 @Other4 varchar(15) = NULL,                  
 @PermitAcceptor varchar(30) = NULL,                  
 @ShiftSupervisor varchar(30) = NULL,                   
 @UseCurrentPermitNumberForZeroEnergyFormNumber bit  ,            
             
 @RoadAccessOnPermit bit ,              
 @RoadAccessOnPermitFormNumber varchar(10) = NULL,              
 @RoadAccessOnPermitType varchar(50) = NULL,          
           
@SpecialWorkName VARCHAR(100)              
)                  
AS                  
  
DECLARE @NewPermitNumber bigint                  
IF @ShouldCreatePermitNumber = 1                  
 BEGIN                  
  EXEC @NewPermitNumber = GetNewSeqVal_WorkPermitEdmontonPermitNumberSequence                  
 END                  
ELSE                  
 BEGIN                  
  SET @NewPermitNumber = NULL                  
 END                  
                  
IF @ShouldCreatePermitNumber = 1 AND @UseCurrentPermitNumberForZeroEnergyFormNumber = 1                  
 BEGIN                  
  SELECT @ZeroEnergyFormNumber = CAST(@NewPermitNumber as varchar(10))                  
 END                  
                   
                  
INSERT INTO WorkPermitEdmonton                  
(                  
 PermitNumber,                  
 PermitRequestId,                  
 WorkPermitStatusId,                  
 DataSourceId,                  
 PriorityId,                  
 IssuedToSuncor,                  
 IssuedToCompany,                  
 Company,                  
 Occupation,                  
 GroupId,                  
 NumberOfWorkers,                  
 WorkPermitTypeId,                  
 DurationPermit,                  
 FunctionalLocationId,                  
 Location,                  
 AreaLabelId,                  
 RequestedStartDateTime,                  
 IssuedDateTime,                  
 ExpiredDateTime,                  
 WorkOrderNumber, 
 ClonedFormDetailEdmonton, 
 OperationNumber,                  
 SubOperationNumber,                  
 TaskDescription,                  
 HazardsAndOrRequirements,                     
 CreatedDateTime,                  
 CreatedByUserId,                  
 PermitRequestCreatedByUserId,                  
 LastModifiedByUserId,                  
 LastModifiedDateTime,                  
 UsePreviousPermitAnswered,                  
 Deleted               
)                  
VALUES                  
(                  
 @NewPermitNumber,                   
 @PermitRequestId,                  
 @WorkPermitStatusId,                  
 @DataSourceId,                  
 @PriorityId,                  
 @IssuedToSuncor,                  
 @IssuedToCompany,                  
 @Company,                  
 @Occupation,                  
 @GroupId,                  
 @NumberOfWorkers,                  
 @WorkPermitTypeId,                  
 @DurationPermit,                  
 @FunctionalLocationId,                  
 @Location,                  
 @AreaLabelId,                  
 @RequestedStartDateTime,                  
 @IssuedDateTime,                  
 @ExpiredDateTime,                  
 @WorkOrderNumber,   
 @ClonedFormDetailEdmonton,    
 @OperationNumber,                  
 @SubOperationNumber,                  
 @TaskDescription,                  
 @HazardsAndOrRequirements,                      
 @CreatedDateTime,                  
 @CreatedByUserId,                  
 @PermitRequestCreatedByUserId,                  
 @LastModifiedByUserId,                  
 @LastModifiedDateTime,                  
 @UsePreviousPermitAnswered,                  
 0                  
);                  
                  
SET @Id=SCOPE_IDENTITY();                   
SET @PermitNumber = @NewPermitNumber             
           
-- Added new  for Special Work            
  
If Not Exists  (Select CompanyName from SpecialWork Where WorkPermitID = @Id)        
   Begin   
  If @SpecialWorkName IS NULL OR RTRIM(LTRIM(@SpecialWorkName)) = ''  
   Begin  
    SET @SpecialWorkType = Null  
   End  
        Else  
   Begin  
    INSERT INTO SpecialWork Values ( @SpecialWorkName, 8, @Id, Null)             
    SET @SpecialWorkType = SCOPE_IDENTITY()   
   End               
   End        
Else        
 Begin       
 Update  SpecialWork      
 Set CompanyName = @SpecialWorkName      
 Where WorkPermitID = @Id       
        
 Set @SpecialWorkType = (Select ID from SpecialWork Where WorkPermitID = @Id)        
End     
           
-- Till here                 
                  
insert into WorkPermitEdmontonDetails                  
(                  
 WorkPermitEdmontonId,                   
                   
 AlkylationEntry,                  
 AlkylationEntryClassOfClothing,                  
 FlarePitEntry,                  
 FlarePitEntryType,                  
 ConfinedSpace,                  
 ConfinedSpaceCardNumber,                  
 ConfinedSpaceClass,                  
 RescuePlan,                  
 RescuePlanFormNumber,                  
    VehicleEntry,                   
 VehicleEntryTotal,                  
 VehicleEntryType,                   
 SpecialWork,                  
 SpecialWorkFormNumber,                  
 SpecialWorkType,                   
 GN59,                  
 FormGN59Id,                   
 GN7,                  
 FormGN7Id,                  
 GN24,                  
 FormGN24Id,             
 GN6,                  
 FormGN6Id,                  
 GN75A,                  
 FormGN75AId,                  
                  
 GN27,                  
 GN11,                  
 GN75_Deprecated,                  
 GN24_Deprecated,                  
 GN6_Deprecated,                  
                  
 GN1,                  
 FormGN1Id,                  
 FormGN1TradeChecklistId,                  
 FormGN1TradeChecklistDisplayNumber,                  
                    
 OtherAreasAndOrUnitsAffected,                  
 OtherAreasAndOrUnitsAffectedArea,                  
 OtherAreasAndOrUnitsAffectedPersonNotified,                  
                   
 StatusOfPipingEquipmentSectionNotApplicableToJob,                  
 ProductNormallyInPipingEquipment,                  
 IsolationValvesLocked,                  
 DepressuredDrained,                  
 Ventilated,                  
 Purged,                  
 BlindedAndTagged,                  
 DoubleBlockAndBleed,                  
 ElectricalLockout,                  
 MechanicalLockout,                  
 BlindSchematicAvailable,                  
 ZeroEnergyFormNumber,                  
 LockBoxNumber,                  
 JobsiteEquipmentInspected,                  
 ConfinedSpaceWorkSectionNotApplicableToJob,                  
 QuestionOneResponse,                  
 QuestionTwoResponse,                  
 QuestionTwoAResponse,                  
 QuestionTwoBResponse,                  
 QuestionThreeResponse,                  
 QuestionFourResponse,                  
 GasTestsSectionNotApplicableToJob,                  
 WorkerToProvideGasTestData,                  
 OperatorGasDetectorNumber,                  
 GasTestDataLine1CombustibleGas,                  
 GasTestDataLine1Oxygen,                  
 GasTestDataLine1ToxicGas,                  
 GasTestDataLine1Time,                  
 GasTestDataLine2CombustibleGas,                  
 GasTestDataLine2Oxygen,                  
 GasTestDataLine2ToxicGas,                  
 GasTestDataLine2Time,                  
 GasTestDataLine3CombustibleGas,                  
 GasTestDataLine3Oxygen,                  
 GasTestDataLine3ToxicGas,                  
 GasTestDataLine3Time,                  
 GasTestDataLine4CombustibleGas,                  
 GasTestDataLine4Oxygen,                  
 GasTestDataLine4ToxicGas,                  
 GasTestDataLine4Time,                  
 WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,                  
 FaceShield,                  
 Goggles,                  
 RubberBoots,                  
 RubberGloves,                
 RubberSuit,                  
 SafetyHarnessLifeline,                  
 HighVoltagePPE,                  
 Other1Checked,                  
 Other1,                  
 EquipmentGrounded,                  
 FireBlanket,                  
 FireExtinguisher,                  
 FireMonitorManned,                  
 FireWatch,                  
 SewersDrainsCovered,                  
 SteamHose,                  
 Other2Checked,                  
 Other2,                  
 AirPurifyingRespirator,                  
 BreathingAirApparatus,                  
 DustMask,                  
 LifeSupportSystem,                  
 SafetyWatch,                  
 ContinuousGasMonitor,                  
 WorkersMonitor,                  
 WorkersMonitorNumber,                  
 BumpTestMonitorPriorToUse,                  
 Other3Checked,                  
 Other3,                  
 AirMover,                  
 BarriersSigns,                  
 RadioChannel,                  
 RadioChannelNumber,                  
 AirHorn,                  
 MechVentilationComfortOnly,                  
 AsbestosMMCPrecautions,                  
 Other4Checked,                  
 Other4,                   
 PermitAcceptor,                  
 ShiftSupervisor,                   
 UseCurrentPermitNumberForZeroEnergyFormNumber,            
             
 RoadAccessOnPermit1 ,              
 RoadAccessOnPermitFormNumber1,              
 RoadAccessOnPermitType1         )                  
values                  
(                  
 @Id,                   
 @AlkylationEntry,                  
 @AlkylationEntryClassOfClothing,                  
 @FlarePitEntry,                  
 @FlarePitEntryType,       
 @ConfinedSpace,                  
 @ConfinedSpaceCardNumber,                  
 @ConfinedSpaceClass,                  
 @RescuePlan,                  
 @RescuePlanFormNumber,                  
 @VehicleEntry,                  
 @VehicleEntryTotal,                  
 @VehicleEntryType,                   
 @SpecialWork,                  
 @SpecialWorkFormNumber,                  
 @SpecialWorkType,                   
                   
 @GN59,                  
 @FormGN59Id,                   
 @GN7,                  
 @FormGN7Id,                  
 @GN24,                  
 @FormGN24Id,                  
 @GN6,                  
 @FormGN6Id,                  
 @GN75A,                  
 @FormGN75AId,                  
                   
 @GN27,                  
 @GN11,                  
 @GN75_Deprecated,                  
 @GN24_Deprecated,                  
 @GN6_Deprecated,                  
                   
 @GN1,                  
 @FormGN1Id,                  
 @FormGN1TradeChecklistId,                  
 @FormGN1TradeChecklistDisplayNumber,                  
                    
 @OtherAreasAndOrUnitsAffected,                  
 @OtherAreasAndOrUnitsAffectedArea,                  
 @OtherAreasAndOrUnitsAffectedPersonNotified,                  
 @StatusOfPipingEquipmentSectionNotApplicableToJob,                  
@ProductNormallyInPipingEquipment,                  
 @IsolationValvesLocked,                  
 @DepressuredDrained,                  
 @Ventilated,                  
 @Purged,                  
 @BlindedAndTagged,                  
 @DoubleBlockAndBleed,                  
 @ElectricalLockout,                  
 @MechanicalLockout,                  
 @BlindSchematicAvailable,                  
 @ZeroEnergyFormNumber,                  
 @LockBoxNumber,                  
 @JobsiteEquipmentInspected,                  
 @ConfinedSpaceWorkSectionNotApplicableToJob,                  
 @QuestionOneResponse,                  
 @QuestionTwoResponse,                  
 @QuestionTwoAResponse,                  
 @QuestionTwoBResponse,                  
 @QuestionThreeResponse,                  
 @QuestionFourResponse,                  
 @GasTestsSectionNotApplicableToJob,                  
 @WorkerToProvideGasTestData,                  
 @OperatorGasDetectorNumber,                  
 @GasTestDataLine1CombustibleGas,                  
 @GasTestDataLine1Oxygen,                  
 @GasTestDataLine1ToxicGas,                  
 @GasTestDataLine1Time,                  
 @GasTestDataLine2CombustibleGas,                  
 @GasTestDataLine2Oxygen,                  
 @GasTestDataLine2ToxicGas,                  
 @GasTestDataLine2Time,                  
 @GasTestDataLine3CombustibleGas,                  
 @GasTestDataLine3Oxygen,                  
 @GasTestDataLine3ToxicGas,                  
 @GasTestDataLine3Time,                  
 @GasTestDataLine4CombustibleGas,                  
 @GasTestDataLine4Oxygen,                  
 @GasTestDataLine4ToxicGas,                  
 @GasTestDataLine4Time,                  
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,                  
 @FaceShield,                  
 @Goggles,                  
 @RubberBoots,                  
 @RubberGloves,                  
 @RubberSuit,                  
 @SafetyHarnessLifeline,                  
 @HighVoltagePPE,                  
 @Other1Checked,                  
 @Other1,                  
 @EquipmentGrounded,                  
 @FireBlanket,                  
 @FireExtinguisher,                  
 @FireMonitorManned,                  
 @FireWatch,                  
 @SewersDrainsCovered,                  
 @SteamHose,                  
 @Other2Checked,                  
 @Other2,                  
 @AirPurifyingRespirator,                  
 @BreathingAirApparatus,                  
 @DustMask,                  
 @LifeSupportSystem,                  
 @SafetyWatch,                  
 @ContinuousGasMonitor,                  
 @WorkersMonitor,                  
 @WorkersMonitorNumber,                  
 @BumpTestMonitorPriorToUse,                  
 @Other3Checked,                  
 @Other3,                  
 @AirMover,                  
 @BarriersSigns,                  
 @RadioChannel,                  
 @RadioChannelNumber,                  
 @AirHorn,                  
 @MechVentilationComfortOnly,                  
 @AsbestosMMCPrecautions,                  
 @Other4Checked,                  
 @Other4,                   
 @PermitAcceptor,                  
 @ShiftSupervisor,                   
 @UseCurrentPermitNumberForZeroEnergyFormNumber,            
 @RoadAccessOnPermit ,              
 @RoadAccessOnPermitFormNumber,              
 @RoadAccessOnPermitType                 
)  
GO

GRANT EXEC ON InsertWorkPermitEdmonton TO PUBLIC
GO