   
IF OBJECT_ID('UpdateWorkPermitFortHills', 'P') IS NOT NULL
DROP PROC UpdateWorkPermitFortHills
GO   
                        
CREATE Procedure [dbo].UpdateWorkPermitFortHills                                                  
(                                                  
@Id bigint Output,                                                                 
@PermitRequestId bigint = NULL,                              
@WorkPermitStatusId int,                              
--@DataSourceId int,                                                
@Company varchar(50) = NULL,                                                  
@Occupation varchar(50),                                                                    
@NumberOfWorkers int = NULL,                                                  
@WorkPermitTypeId int,                                                
@FunctionalLocationId bigint,                                                  
@Location varchar(50),                                
@RequestedStartDateTime datetime,                               
@IssuedDateTime datetime = NULL,                               
@ExpiredDateTime datetime,                              
@PermitNumber bigint Output,                                                 
@WorkOrderNumber varchar(12) = NULL,                                                  
@OperationNumber varchar(max) = NULL,                                                  
@SubOperationNumber varchar(max) = NULL,                                                  
@TaskDescription varchar(8000) = NULL,                                                  
@HazardsAndOrRequirements varchar(2000) = NULL,                                                    
@LastModifiedByUserId bigint,                                                  
@LastModifiedDateTime datetime,                          
@IssuedToSuncor bit,                                                  
@IssuedToCompany bit,                                  
@GroupId bigint,                          
@PermitRequestCreatedByUserId bigint = NULL,                                                
@PriorityId int,              
@IssuedByUserId bigint = NULL,                          
                                                           
@ShouldCreatePermitNumber bit,                           
                                
@EquipmentNo int,                              
@Craft varchar(25),                              
@CrewSize int ,                              
@JobCoordinator varchar(25),                              
@CoOrdContactNumber varchar(10),                              
@EmergencyAssemblyArea varchar(25),                              
@EmergencyMeetingPoint varchar(25),                              
@EmergencyContactNumber varchar(10),                              
@Locknumber varchar(10),                        
@LockBoxnumberChecked bit,                            
@IsolationNumber varchar(10),                              
@RevalidationDateTime datetime,                               
@ExtensionDateTime datetime,   
@ExtensionReasonPartJ varchar(100)=NULL,
@ExtendedByUser bigint = NULL,                             
@FlameResistantWorkWear bit,                              
@ChemicalSuit bit,                              
@FireWatch bit,                              
@FireBlanket bit,                              
@SuppliedBreathingAir bit,                              
@AirMover bit,                              
@PersonalFlotationDevice bit,                              
@HearingProtection bit,                              
@Other1 varchar(30),                              
@MonoGoggles bit,                              
@ConfinedSpaceMoniter bit,                              
@FireExtinguisher bit,                              
@SparkContainment bit,                              
@BottleWatch bit,                              
@StandbyPerson bit,                              
@WorkingAlone bit,                              
@SafetyGloves bit,                              
@Other2 varchar(30),                              
@FaceShield bit,                              
@FallProtection bit,          
@ChargedFireHouse bit,                              
@CoveredSewer bit,                              
@AirPurifyingRespirator bit,                              
@SingalPerson bit,                              
@CommunicationDevice bit,                              
@ReflectiveStrips bit,                              
@Other3 varchar(30),                                  
@ConfinedSpace bit,                              
@ConfinedSpaceClass varchar(25),                             
@GoundDisturbance bit,                              
@FireProtectionAuthorization bit,                              
@CriticalOrSeriousLifts bit ,                           
@VehicleEntry bit,                              
@IndustrialRadiography bit,                              
@ElectricalEncroachment bit,                              
@MSDS bit,                   
@OthersPartE varchar(30),                              
@MechanicallyIsolated bit,                              
@BlindedOrBlanked bit,                              
@DoubleBlockedandBled bit,                              
@DrainedAndDepressurised bit,                              
@PurgedorNeutralised bit,                              
@ElectricallyIsolated bit,                              
@TestBumped bit,                              
@NuclearSource bit,                              
@ReceiverStafingRequirements bit,                 
                
@Frequency varchar(10) = NULL,      
@Continuous BIT,                  
@TesterName VARCHAR(50) = NULL,                  
@Oxygen bit = NULL,                  
@LEL bit = NULL,                  
@H2SPPM bit = NULL,                  
@CoPPM bit = NULL,                  
@So2PPM bit = NULL,                  
@Other1PartGValue VARCHAR(50) = NULL,                  
@Other2PartGValue VARCHAR(50) = NULL,                  
@PermitIssuer VARCHAR(50) = NULL,        
@AreaAuthority VARCHAR(50) = NULL,        
@CoAuthorizingIssuer VARCHAR(50) = NULL,        
@AddationalAuthority VARCHAR(50) = NULL,        
@PermitIssuerContact VARCHAR(10) = NULL,        
@AreaAuthorityContact VARCHAR(10) = NULL,        
@CoAuthorizingIssuerContact VARCHAR(10) = NULL,        
@AddationalAuthorityContact VARCHAR(10) = NULL,        
@IsFieldTourRequired bit,        
@FieldTourConductedBy VARCHAR(50) = NULL,                
                            
@PermitAcceptor varchar(30) = NULL,                                                
@ShiftSupervisor varchar(30) = NULL,                  
@PartCWorkSectionNotApplicable Bit,                  
@PartDWorkSectionNotApplicable Bit,                  
@PartEWorkSectionNotApplicable Bit,                 
@PartFWorkSectionNotApplicable BIT,                
@PartGWorkSectionNotApplicable BIT                              
)                                                  
AS                            
BEGIN                                   
                                              
IF @ShouldCreatePermitNumber = 1                                              
 BEGIN                             
  EXEC @PermitNumber = GetNewSeqVal_WorkPermitFortHillsPermitNumberSequence                                              
 END                                              
ELSE                                              
 BEGIN                       
  SET @PermitNumber = (select PermitNumber from WorkPermitFortHills WHERE Id = @Id)                                              
 END                                              
                                               
                                                 
                        
Update WorkPermitFortHills   SET                                               
                                                                  
PermitRequestId = @PermitRequestId,                          
WorkPermitStatusId = @WorkPermitStatusId,                          
--DataSourceId = @DataSourceId,                          
Company = @Company,                          
Occupation = @Occupation,                          
NumberOfWorkers = @NumberOfWorkers,                          
WorkPermitTypeId = @WorkPermitTypeId,                          
FunctionalLocationId = @FunctionalLocationId,                          
Location = @Location,                          
RequestedStartDateTime = @RequestedStartDateTime,                          
IssuedDateTime = @IssuedDateTime,                          
ExpiredDateTime = @ExpiredDateTime,                          
PermitNumber = @PermitNumber,                          
WorkOrderNumber = @WorkOrderNumber,                          
OperationNumber = @OperationNumber,                          
SubOperationNumber = @SubOperationNumber,            
TaskDescription = @TaskDescription,                          
HazardsAndOrRequirements = @HazardsAndOrRequirements,                          
LastModifiedByUserId = @LastModifiedByUserId,                          
LastModifiedDateTime = @LastModifiedDateTime,                          
IssuedToSuncor = @IssuedToSuncor,                          
IssuedToCompany = @IssuedToCompany,                          
GroupId = @GroupId,                          
PermitRequestCreatedByUserId = @PermitRequestCreatedByUserId,                      
LockBoxnumberChecked =@LockBoxnumberChecked ,                          
PriorityId = @PriorityId,                  
PartCWorkSectionNotApplicable = @PartCWorkSectionNotApplicable,                  
PartDWorkSectionNotApplicable = @PartDWorkSectionNotApplicable,                  
PartEWorkSectionNotApplicable = @PartEWorkSectionNotApplicable,           
PartFWorkSectionNotApplicable = @PartFWorkSectionNotApplicable,                  
PartGWorkSectionNotApplicable = @PartGWorkSectionNotApplicable,               
IssuedByUserId = @IssuedByUserId                  
 WHERE Id = @Id                                        
                                       
                                                
                                                              
UPDATE  WorkPermitFortHillsDetails SET                                                  
EquipmentNo = @EquipmentNo,                          
Craft = @Craft,                          
CrewSize = @CrewSize,                          
JobCoordinator = @JobCoordinator,                          
CoOrdContactNumber = @CoOrdContactNumber,                          
EmergencyAssemblyArea = @EmergencyAssemblyArea,                          
EmergencyMeetingPoint = @EmergencyMeetingPoint,                          
EmergencyContactNumber = @EmergencyContactNumber,                          
Locknumber = @Locknumber,                          
IsolationNumber = @IsolationNumber,                          
RevalidationDateTime = @RevalidationDateTime,                          
ExtensionDateTime = @ExtensionDateTime,    
ExtensionReasonPartJ = @ExtensionReasonPartJ,  
ExtendedByUser=@ExtendedByUser,
FlameResistantWorkWear = @FlameResistantWorkWear,                          
ChemicalSuit = @ChemicalSuit,                          
FireWatch = @FireWatch,                          
FireBlanket = @FireBlanket,                          
SuppliedBreathingAir = @SuppliedBreathingAir,                          
AirMover = @AirMover,                          
PersonalFlotationDevice = @PersonalFlotationDevice,                          
HearingProtection = @HearingProtection,                          
Other1 = @Other1,                          
MonoGoggles = @MonoGoggles,                          
ConfinedSpaceMoniter = @ConfinedSpaceMoniter,                          
FireExtinguisher = @FireExtinguisher,                          
SparkContainment = @SparkContainment,                          
BottleWatch = @BottleWatch,                          
StandbyPerson = @StandbyPerson,                          
WorkingAlone = @WorkingAlone,                          
SafetyGloves = @SafetyGloves,                          
Other2 = @Other2,                          
FaceShield = @FaceShield,                          
FallProtection = @FallProtection,                          
ChargedFireHouse = @ChargedFireHouse,         
CoveredSewer = @CoveredSewer,                          
AirPurifyingRespirator = @AirPurifyingRespirator,                          
SingalPerson = @SingalPerson,                          
CommunicationDevice = @CommunicationDevice,                          
ReflectiveStrips = @ReflectiveStrips,                          
Other3 = @Other3,                          
ConfinedSpace = @ConfinedSpace,                          
ConfinedSpaceClass = @ConfinedSpaceClass,     
GoundDisturbance = @GoundDisturbance,                          
FireProtectionAuthorization = @FireProtectionAuthorization,                          
CriticalOrSeriousLifts = @CriticalOrSeriousLifts,                          
VehicleEntry = @VehicleEntry,                          
IndustrialRadiography = @IndustrialRadiography,                          
ElectricalEncroachment = @ElectricalEncroachment,                          
MSDS = @MSDS,                       
OthersPartE = @OthersPartE,                          
MechanicallyIsolated = @MechanicallyIsolated,                          
BlindedOrBlanked = @BlindedOrBlanked,                          
DoubleBlockedandBled = @DoubleBlockedandBled,                          
DrainedAndDepressurised = @DrainedAndDepressurised,                          
PurgedorNeutralised = @PurgedorNeutralised,                          
ElectricallyIsolated = @ElectricallyIsolated,                          
TestBumped = @TestBumped,                          
NuclearSource = @NuclearSource,                          
ReceiverStafingRequirements = @ReceiverStafingRequirements,                  
Frequency =@Frequency ,      
Continuous=@Continuous,                
TesterName=@TesterName,                
Oxygen=@Oxygen,                
LEL=@LEL,                
H2SPPM =@H2SPPM,                
CoPPM =@CoPPM,                
So2PPM=@So2PPM,                 
Other1PartGValue=@Other1PartGValue,                
Other2PartGValue=@Other2PartGValue,                 
PermitIssuer=@PermitIssuer,        
AreaAuthority=@AreaAuthority,        
CoAuthorizingIssuer=@CoAuthorizingIssuer,        
AddationalAuthority=@AddationalAuthority,        
PermitIssuerContact=@PermitIssuerContact,        
AreaAuthorityContact=@AreaAuthorityContact,        
CoAuthorizingIssuerContact=@CoAuthorizingIssuerContact,        
AddationalAuthorityContact=@AddationalAuthorityContact,        
IsFieldTourRequired=@IsFieldTourRequired,        
FieldTourConductedBy=@FieldTourConductedBy,                    
PermitAcceptor = @PermitAcceptor,                          
ShiftSupervisor = @ShiftSupervisor                        
WHERE WorkPermitFortHillsId = @Id                            
                              
END             
            
GRANT EXEC ON UpdateWorkPermitFortHills TO PUBLIC 
