// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.

using Com.Suncor.Olt.Common.Fixtures;
using NUnit.Framework;

namespace Com.Suncor.Olt.Common.Domain
{
    /// <summary>
    /// Understands how to test Positions
    ///</summary>
    [TestFixture]
    public class RoleTest
    {
        [Test]
        public void ToStringShouldReturnPositionName()
        {
            Assert.AreEqual("Supervisor", RoleFixture.CreateSupervisorRole().ToString());
        }
    }
}
