

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'GETLENELCONNECTIONANDQUERY')
	BEGIN
		DROP PROCEDURE [dbo].[GETLENELCONNECTIONANDQUERY]
	END
	
GO
CREATE Procedure [dbo].[GETLENELCONNECTIONANDQUERY]    
  AS
 
SELECT 'Data Source=SQLPRDCGY140-LS;Initial Catalog=LNLMSPRD;User Id=OLTUser;Password=OltUser@12;MultipleActiveResultSets=True;Connection Timeout=60'AS Connection
      , 'SELECT top 1 BDG.Id,BDG.TYPE AS ''CARDTYPE'',EM.FIRSTNAME,EM.LASTNAME FROM dbo.BADGE BDG JOIN EMP EM ON EM.ID=BDG.EMPID AND BDG.Id=@BadgeId AND BDG.STATUS=1' AS QUERY
 
    