

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'GETWORKPERMITMUDSIGN_HISTORY')
	BEGIN
		DROP PROCEDURE [dbo].[GETWORKPERMITMUDSIGN_HISTORY]
	END
	
GO
CREATE Procedure [dbo].[GETWORKPERMITMUDSIGN_HISTORY]    
(    
 @WorkPermitId Varchar(100)

 
     
)    
AS    
 
 SELECT * FROM  WORKPERMITMUDSSIGN_HISTORY WHERE WorkPermitId=@WorkPermitId 
 UNION ALL
SELECT * FROM  WORKPERMITMUDSSIGN WHERE WorkPermitId=@WorkPermitId 
 
 
    
GRANT EXEC ON [GETWORKPERMITMUDSIGN_HISTORY] TO PUBLIC       