if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertPermitRequestLubes]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertPermitRequestLubes]
GO

CREATE Procedure [dbo].[InsertPermitRequestLubes]
(
	@Id bigint Output,
	@Company varchar(50) = NULL,
	@SourceId int,
	@CompletionStatusId int,
	@IssuedToSuncor bit,
	@IssuedToCompany bit,
	@Trade varchar(50),
	@SAPWorkCentre varchar(40),
	@NumberOfWorkers int = NULL,
	@RequestedByGroupId bigint,
	@WorkPermitTypeId int,
	@IsVehicleEntry bit,
	@FunctionalLocationId bigint,
	@Location varchar(50),
	@Description varchar(max),
	@SapDescription varchar(max) = NULL,

	@ConfinedSpace bit,
	@ConfinedSpaceClass varchar(50),
	@RescuePlan bit,
	@ConfinedSpaceSafetyWatchChecklist bit,

	@SpecialWork bit,
	@SpecialWorkType varchar(50),

	@RequestedStartDate datetime,
	@RequestedStartTimeDay datetime = NULL,
	@RequestedStartTimeNight datetime = NULL,
	@EndDate datetime,

	@WorkOrderNumber varchar(12) = NULL,
	
	@HighEnergy tinyint,
    @CriticalLift tinyint,
    @Excavation tinyint,
    @EnergyControlPlan tinyint,
    @EquivalencyProc tinyint,
    @TestPneumatic tinyint,
    @LiveFlareWork tinyint,
    @EntryAndControlPlan tinyint,
	@EnergizedElectrical tinyint,
	
	@HazardHydrocarbonGas bit,
	@HazardHydrocarbonLiquid bit,
	@HazardHydrogenSulphide bit,
	@HazardInertGasAtmosphere bit,
	@HazardOxygenDeficiency bit,
	@HazardRadioactiveSources bit,
	@HazardUndergroundOverheadHazards bit,
	@HazardDesignatedSubstance bit,

	@OtherHazardsAndOrRequirements varchar(max) = NULL,	
	@OtherAreasAndOrUnitsAffected bit,
	@OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,
	@OtherAreasAndOrUnitsAffectedPersonNotified varchar(30) = NULL,	

	@SpecificRequirementsSectionNotApplicableToJob bit,

	@AttendedAtAllTimes bit,
	@EyeProtection bit,
	@FallProtectionEquipment bit,
	@FullBodyHarnessRetrieval bit,
	@HearingProtection bit,
	@ProtectiveClothing bit,
	@Other1Checked bit,
	@Other1Value varchar(15) = NULL,

	@EquipmentBondedGrounded bit,
	@FireBlanket bit,
	@FireFightingEquipment bit,
	@FireWatch bit,
	@HydrantPermit bit,
	@WaterHose bit,
	@SteamHose bit,
	@Other2Checked bit,
	@Other2Value varchar(15) = NULL,

	@AirMover bit,
	@ContinuousGasMonitor bit,
	@DrowningProtection bit,
	@RespiratoryProtection bit,
	@Other3Checked bit,
	@Other3Value varchar(15) = NULL,

	@AdditionalLighting bit,
	@DesignateHotOrColdCutChecked bit,
	@DesignateHotOrColdCutValue varchar(6),
	@HoistingEquipment bit,
	@Ladder bit,
	@MotorizedEquipment bit,
	@Scaffold bit,
	@ReferToTipsProcedure bit,
	
	@GasDetectorBumpTested bit,
	
	@LastImportedByUserId bigint = NULL,
	@LastImportedDateTime datetime = NULL,
	@LastSubmittedByUserId bigint = NULL,
	@LastSubmittedDateTime datetime = NULL,
	@CreatedByUserId bigint,
	@CreatedDateTime datetime,
	@LastModifiedByUserId bigint,
	@LastModifiedDateTime datetime,
	@CreatedByRoleId bigint = NULL,
	@IsModified bit
)
AS

INSERT INTO PermitRequestLubes
(
	Company,
	DataSourceId,
	CompletionStatusId,
	IssuedToSuncor,
	IssuedToCompany,
	Trade,
	SAPWorkCentre,
	NumberOfWorkers,
	RequestedByGroupId,
	WorkPermitTypeId,
	IsVehicleEntry,
	FunctionalLocationId,
	Location,
	Description,
	SapDescription,

	ConfinedSpace,
	ConfinedSpaceClass,
	RescuePlan,
	ConfinedSpaceSafetyWatchChecklist,

	SpecialWork,
	SpecialWorkType,

	RequestedStartDate,
	RequestedStartTimeDay,
	RequestedStartTimeNight,
	EndDate,

	WorkOrderNumber,
	
	HighEnergy,
	CriticalLift,
	Excavation,
	EnergyControlPlan,
	EquivalencyProc,
	TestPneumatic,
	LiveFlareWork,
	EntryAndControlPlan,
	EnergizedElectrical,

	HazardHydrocarbonGas,
	HazardHydrocarbonLiquid,
	HazardHydrogenSulphide,
	HazardInertGasAtmosphere,
	HazardOxygenDeficiency,
	HazardRadioactiveSources,
	HazardUndergroundOverheadHazards,
	HazardDesignatedSubstance,

	OtherHazardsAndOrRequirements,
	OtherAreasAndOrUnitsAffected,
	OtherAreasAndOrUnitsAffectedArea,
	OtherAreasAndOrUnitsAffectedPersonNotified	,

	SpecificRequirementsSectionNotApplicableToJob,

	AttendedAtAllTimes,
	EyeProtection,
	FallProtectionEquipment,
	FullBodyHarnessRetrieval,
	HearingProtection,
	ProtectiveClothing,
	Other1Checked,
	Other1Value,

	EquipmentBondedGrounded,
	FireBlanket,
	FireFightingEquipment,
	FireWatch,
	HydrantPermit,
	WaterHose,
	SteamHose,
	Other2Checked,
	Other2Value,

	AirMover,
	ContinuousGasMonitor,
	DrowningProtection,
	RespiratoryProtection,
	Other3Checked,
	Other3Value,

	AdditionalLighting,
	DesignateHotOrColdCutChecked,
	DesignateHotOrColdCutValue,
	HoistingEquipment,
	Ladder,
	MotorizedEquipment,
	Scaffold,
	ReferToTipsProcedure,
	
	GasDetectorBumpTested,

	LastImportedByUserId,
	LastImportedDateTime,
	LastSubmittedByUserId,
	LastSubmittedDateTime,
	CreatedByUserId,
	CreatedDateTime,
	LastModifiedByUserId,
	LastModifiedDateTime,
	CreatedByRoleId,
	IsModified,
	Deleted
)
VALUES
(
	@Company,
	@SourceId,
	@CompletionStatusId,
	@IssuedToSuncor,
	@IssuedToCompany,
	@Trade,
	@SAPWorkCentre,
	@NumberOfWorkers,
	@RequestedByGroupId,
	@WorkPermitTypeId,
	@IsVehicleEntry,
	@FunctionalLocationId,
	@Location,
	@Description,
	@SapDescription,

	@ConfinedSpace,
	@ConfinedSpaceClass,
	@RescuePlan,
	@ConfinedSpaceSafetyWatchChecklist,

	@SpecialWork,
	@SpecialWorkType,

	@RequestedStartDate,
	@RequestedStartTimeDay,
	@RequestedStartTimeNight,
	@EndDate,

	@WorkOrderNumber,
	
	@HighEnergy,
	@CriticalLift,
	@Excavation,
	@EnergyControlPlan,
	@EquivalencyProc,
	@TestPneumatic,
	@LiveFlareWork,
	@EntryAndControlPlan,
	@EnergizedElectrical,

	@HazardHydrocarbonGas,
	@HazardHydrocarbonLiquid,
	@HazardHydrogenSulphide,
	@HazardInertGasAtmosphere,
	@HazardOxygenDeficiency,
	@HazardRadioactiveSources,
	@HazardUndergroundOverheadHazards,
	@HazardDesignatedSubstance,

	@OtherHazardsAndOrRequirements,
	@OtherAreasAndOrUnitsAffected,
	@OtherAreasAndOrUnitsAffectedArea,
	@OtherAreasAndOrUnitsAffectedPersonNotified	,

	@SpecificRequirementsSectionNotApplicableToJob,

	@AttendedAtAllTimes,
	@EyeProtection,
	@FallProtectionEquipment,
	@FullBodyHarnessRetrieval,
	@HearingProtection,
	@ProtectiveClothing,
	@Other1Checked,
	@Other1Value,

	@EquipmentBondedGrounded,
	@FireBlanket,
	@FireFightingEquipment,
	@FireWatch,
	@HydrantPermit,
	@WaterHose,
	@SteamHose,
	@Other2Checked,
	@Other2Value,

	@AirMover,
	@ContinuousGasMonitor,
	@DrowningProtection,
	@RespiratoryProtection,
	@Other3Checked,
	@Other3Value,

	@AdditionalLighting,
	@DesignateHotOrColdCutChecked,
	@DesignateHotOrColdCutValue,
	@HoistingEquipment,
	@Ladder,
	@MotorizedEquipment,
	@Scaffold,
	@ReferToTipsProcedure,
	
	@GasDetectorBumpTested,

	@LastImportedByUserId,
	@LastImportedDateTime,
	@LastSubmittedByUserId,
	@LastSubmittedDateTime,
	@CreatedByUserId,
	@CreatedDateTime,
	@LastModifiedByUserId,
	@LastModifiedDateTime,
	@CreatedByRoleId,
	@IsModified,
	0
);

SET @Id=SCOPE_IDENTITY(); 

