if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermitLubes]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertWorkPermitLubes]
GO

CREATE Procedure [dbo].[InsertWorkPermitLubes]
(
	@Id bigint Output,
	@PermitNumber bigint Output,
	
	@ShouldCreatePermitNumber bit,	
	@PermitRequestId bigint = NULL,
	@DataSourceId int,
	@WorkPermitStatus int,
	@CreatedDateTime datetime,
	@CreatedByUserId bigint,
	@PermitRequestSubmittedByUserId	bigint,
	
	@IssuedToSuncor bit,
	@IssuedToCompany bit,
	@Company varchar(50) = NULL,
	@Trade varchar(50),
	@NumberOfWorkers int = NULL,
	@RequestedByGroupId bigint,
	
	@WorkPermitTypeId int,
	@IsVehicleEntry bit,
	@FunctionalLocationId bigint,
	@Location varchar(50),
	
	@ConfinedSpace bit,
	@ConfinedSpaceClass varchar(50),
	@RescuePlan bit,
	@ConfinedSpaceSafetyWatchChecklist bit,
	
	@SpecialWork bit,
	@SpecialWorkType varchar(50),
	@HazardousWorkApproverAdvised bit,
	@AdditionalFollowupRequired bit,
	
	@StartDateTime datetime,
	@ExpireDateTime datetime,
	
	@WorkOrderNumber varchar(12) = NULL,
	@OperationNumber varchar(max) = NULL,
	@SubOperationNumber varchar(max) = NULL,
	
	@HighEnergy tinyint,
    @CriticalLift tinyint,
    @Excavation tinyint,
    @EnergyControlPlanFormRequirement tinyint,
    @EquivalencyProc tinyint,
    @TestPneumatic tinyint,
    @LiveFlareWork tinyint,
    @EntryAndControlPlan tinyint,
	@EnergizedElectrical tinyint,
	
	@TaskDescription varchar(max) = NULL,
	
	@HazardHydrocarbonGas bit,
	@HazardHydrocarbonLiquid bit,
	@HazardHydrogenSulphide bit,
	@HazardInertGasAtmosphere bit,
	@HazardOxygenDeficiency bit,
	@HazardRadioactiveSources bit,
	@HazardUndergroundOverheadHazards bit,
	@HazardDesignatedSubstance bit,
	
	@OtherHazardsAndOrRequirements varchar(max) = NULL,
	
	@OtherAreasAndOrUnitsAffected bit,
	@OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,
	@OtherAreasAndOrUnitsAffectedPersonNotified varchar(50) = NULL,
	
	@WorkPreparationsCompletedSectionNotApplicableToJob bit,
	@ProductNormallyInPipingEquipment varchar(50) = NULL,
	
	@DepressuredDrained bit = NULL,
	@WaterWashed bit = NULL,
	@ChemicallyWashed bit = NULL,
	@Steamed bit = NULL,
	@Purged bit = NULL,
	@Disconnected bit = NULL,
	@DepressuredAndVented bit = NULL,
	@Ventilated bit = NULL,
	@Blanked bit = NULL,
	@DrainsCovered bit = NULL,
	@AreaBarricated bit = NULL,
	@EnergySourcesLockedOutTaggedOut bit = NULL,
	@EnergyControlPlan varchar(50) = NULL,
	@LockBoxNumber varchar(50) = NULL,
	@OtherPreparations varchar(50) = NULL,
	
	@SpecificRequirementsSectionNotApplicableToJob bit,
	@AttendedAtAllTimes bit,
	@EyeProtection bit,
	@FallProtectionEquipment bit,
	@FullBodyHarnessRetrieval bit,
	@HearingProtection bit,
	@ProtectiveClothing bit,
	@Other1Checked bit,
	@Other1Value varchar(50) = NULL,

	@EquipmentBondedGrounded bit,
	@FireBlanket bit,
	@FireFightingEquipment bit,
	@FireWatch bit,
	@HydrantPermit bit,
	@WaterHose bit,
	@SteamHose bit,
	@Other2Checked bit,
	@Other2Value varchar(50) = NULL,

	@AirMover bit,
	@ContinuousGasMonitor bit,
	@DrowningProtection bit,
	@RespiratoryProtection bit,
	@Other3Checked bit,
	@Other3Value varchar(50) = NULL,

	@AdditionalLighting bit,
	@DesignateHotOrColdCutChecked bit,
	@DesignateHotOrColdCutValue varchar(50),
	@HoistingEquipment bit,
	@Ladder bit,
	@MotorizedEquipment bit,
	@Scaffold bit,
	@ReferToTipsProcedure bit,
	
	@GasDetectorBumpTested bit,
	@AtmosphericGasTestRequired bit,
	
	@UsePreviousPermitAnswered bit,

	@LastModifiedByUserId bigint,
	@LastModifiedDateTime datetime,
	@Version varchar(10) = null
)
AS

DECLARE @NewPermitNumber bigint
IF @ShouldCreatePermitNumber = 1
	BEGIN
		EXEC @NewPermitNumber = GetNewSeqVal_WorkPermitLubesPermitNumberSequence
	END
ELSE
	BEGIN
		SET @NewPermitNumber = NULL
	END	

INSERT INTO WorkPermitLubes
(
	PermitRequestId,
	DataSourceId,
	WorkPermitStatus,
	CreatedDateTime,
	CreatedByUserId,
	PermitRequestSubmittedByUserId,
	PermitNumber, 	
	IssuedToSuncor,
	IssuedToCompany,
	Company,
	Trade,
	NumberOfWorkers,
	RequestedByGroupId,
	WorkPermitTypeId,
	IsVehicleEntry,
	FunctionalLocationId,
	Location,	
	ConfinedSpace,
	ConfinedSpaceClass,
	RescuePlan,
	ConfinedSpaceSafetyWatchChecklist,
	SpecialWork,
	SpecialWorkType,
	HazardousWorkApproverAdvised,
	AdditionalFollowupRequired,	
	StartDateTime,	
	ExpireDateTime,
	WorkOrderNumber,
	OperationNumber,
	SubOperationNumber,
	HighEnergy,
    CriticalLift,
    Excavation,
    EnergyControlPlanFormRequirement,
    EquivalencyProc,
    TestPneumatic,
    LiveFlareWork,
    EntryAndControlPlan,
	EnergizedElectrical,
	TaskDescription,		
	HazardHydrocarbonGas,
	HazardHydrocarbonLiquid,
	HazardHydrogenSulphide,
	HazardInertGasAtmosphere,
	HazardOxygenDeficiency,
	HazardRadioactiveSources,
	HazardUndergroundOverheadHazards,
	HazardDesignatedSubstance,
	OtherHazardsAndOrRequirements,		
	OtherAreasAndOrUnitsAffected,
	OtherAreasAndOrUnitsAffectedArea,	
	OtherAreasAndOrUnitsAffectedPersonNotified,		
	WorkPreparationsCompletedSectionNotApplicableToJob,
	ProductNormallyInPipingEquipment,		              
	DepressuredDrained,   
	WaterWashed,
	ChemicallyWashed,	
	Steamed,   
	Purged,   
	Disconnected,   
	DepressuredAndVented,   
	Ventilated,   
	Blanked,   
	DrainsCovered,   
	AreaBarricated,   
	EnergySourcesLockedOutTaggedOut,   
	EnergyControlPlan,	
	LockBoxNumber,	
	OtherPreparations,	
	SpecificRequirementsSectionNotApplicableToJob,
	AttendedAtAllTimes,
	EyeProtection,
	FallProtectionEquipment,
	FullBodyHarnessRetrieval,
	HearingProtection,
	ProtectiveClothing,
	Other1Checked,
	Other1Value,	
	EquipmentBondedGrounded,
	FireBlanket,
	FireFightingEquipment,
	FireWatch,
	HydrantPermit,
	WaterHose,
	SteamHose,
	Other2Checked,
	Other2Value,	
	AirMover,
	ContinuousGasMonitor,
	DrowningProtection,
	RespiratoryProtection,
	Other3Checked,
	Other3Value,	 
	AdditionalLighting,
	DesignateHotOrColdCutChecked,
	DesignateHotOrColdCutValue,	
	HoistingEquipment,
	Ladder,
	MotorizedEquipment,
	Scaffold,
	ReferToTipsProcedure,
	GasDetectorBumpTested,
	AtmosphericGasTestRequired,
	UsePreviousPermitAnswered,
	LastModifiedByUserId,
	LastModifiedDateTime,
	Version,
	Deleted
)
VALUES
(
	@PermitRequestId,
	@DataSourceId,
	@WorkPermitStatus,
	@CreatedDateTime,
	@CreatedByUserId,
	@PermitRequestSubmittedByUserId,
	@NewPermitNumber, 	
	@IssuedToSuncor,
	@IssuedToCompany,
	@Company,
	@Trade,
	@NumberOfWorkers,
	@RequestedByGroupId,	
	@WorkPermitTypeId,
	@IsVehicleEntry,
	@FunctionalLocationId,
	@Location,	
	@ConfinedSpace,
	@ConfinedSpaceClass,
	@RescuePlan,
	@ConfinedSpaceSafetyWatchChecklist,
	@SpecialWork,
	@SpecialWorkType,
	@HazardousWorkApproverAdvised,
	@AdditionalFollowupRequired,	
	@StartDateTime,	
	@ExpireDateTime,
	@WorkOrderNumber,
	@OperationNumber,
	@SubOperationNumber,
	@HighEnergy,
    @CriticalLift,
    @Excavation,
    @EnergyControlPlanFormRequirement,
    @EquivalencyProc,
    @TestPneumatic,
    @LiveFlareWork,
    @EntryAndControlPlan,
	@EnergizedElectrical,
	@TaskDescription,		
	@HazardHydrocarbonGas,
	@HazardHydrocarbonLiquid,
	@HazardHydrogenSulphide,
	@HazardInertGasAtmosphere,
	@HazardOxygenDeficiency,
	@HazardRadioactiveSources,
	@HazardUndergroundOverheadHazards,
	@HazardDesignatedSubstance,
	@OtherHazardsAndOrRequirements,		
	@OtherAreasAndOrUnitsAffected,
	@OtherAreasAndOrUnitsAffectedArea,	
	@OtherAreasAndOrUnitsAffectedPersonNotified,		
	@WorkPreparationsCompletedSectionNotApplicableToJob,
	@ProductNormallyInPipingEquipment,		              
	@DepressuredDrained,   
	@WaterWashed,
	@ChemicallyWashed,
	@Steamed,   
	@Purged,   
	@Disconnected,   
	@DepressuredAndVented,   
	@Ventilated,   
	@Blanked,   
	@DrainsCovered,   
	@AreaBarricated,   
	@EnergySourcesLockedOutTaggedOut,   
	@EnergyControlPlan,	
	@LockBoxNumber,	
	@OtherPreparations,	
	@SpecificRequirementsSectionNotApplicableToJob,
	@AttendedAtAllTimes,
	@EyeProtection,
	@FallProtectionEquipment,
	@FullBodyHarnessRetrieval,
	@HearingProtection,
	@ProtectiveClothing,
	@Other1Checked,
	@Other1Value,	
	@EquipmentBondedGrounded,
	@FireBlanket,
	@FireFightingEquipment,
	@FireWatch,
	@HydrantPermit,
	@WaterHose,
	@SteamHose,
	@Other2Checked,
	@Other2Value,	
	@AirMover,
	@ContinuousGasMonitor,
	@DrowningProtection,
	@RespiratoryProtection,
	@Other3Checked,
	@Other3Value,	 
	@AdditionalLighting,
	@DesignateHotOrColdCutChecked,
	@DesignateHotOrColdCutValue,	
	@HoistingEquipment,
	@Ladder,
	@MotorizedEquipment,
	@Scaffold,
	@ReferToTipsProcedure,
	@GasDetectorBumpTested,
	@AtmosphericGasTestRequired,
	@UsePreviousPermitAnswered,
	@LastModifiedByUserId,
	@LastModifiedDateTime,
	@Version,
	0
);

SET @Id=SCOPE_IDENTITY(); 
SET @PermitNumber = @NewPermitNumber


