if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermitLubesHistory]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertWorkPermitLubesHistory]
GO

CREATE Procedure [dbo].[InsertWorkPermitLubesHistory]
(
	@Id bigint,
					
	@WorkPermitStatus int,
	
	@DocumentLinks varchar(max) = NULL,
	@PermitNumber bigint = NULL,
	
	@IssuedToSuncor bit,
	@IssuedToCompany bit,
	@Company varchar(50) = NULL,
	@Trade varchar(50),
	@NumberOfWorkers int = NULL,
	@RequestedByGroup varchar(50) = NULL,
	
	@IssuedByUserId bigint = NULL,
	@IssuedDateTime datetime = NULL,
	
	@WorkPermitTypeId int,
	@IsVehicleEntry bit,
	@FunctionalLocation varchar(200),
	@Location varchar(50),
	
	@ConfinedSpace bit,
	@ConfinedSpaceClass varchar(50),
	@RescuePlan bit,
	@ConfinedSpaceSafetyWatchChecklist bit,
	
	@SpecialWork bit,
	@SpecialWorkType varchar(50),
	@HazardousWorkApproverAdvised bit,
	@AdditionalFollowupRequired bit,
	
	@StartDateTime datetime,
	@ExpireDateTime datetime,
	
	@WorkOrderNumber varchar(12) = NULL,
	@OperationNumber varchar(4) = NULL,
	@SubOperationNumber varchar(4) = NULL,
	
	@HighEnergy tinyint,
    @CriticalLift tinyint,
    @Excavation tinyint,
    @EnergyControlPlanFormRequirement tinyint,
    @EquivalencyProc tinyint,
    @TestPneumatic tinyint,
    @LiveFlareWork tinyint,
    @EntryAndControlPlan tinyint,
	@EnergizedElectrical tinyint,
	
	@TaskDescription varchar(max) = NULL,
	
	@HazardHydrocarbonGas bit,
	@HazardHydrocarbonLiquid bit,
	@HazardHydrogenSulphide bit,
	@HazardInertGasAtmosphere bit,
	@HazardOxygenDeficiency bit,
	@HazardRadioactiveSources bit,
	@HazardUndergroundOverheadHazards bit,
	@HazardDesignatedSubstance bit,
	
	@OtherHazardsAndOrRequirements varchar(max) = NULL,
	
	@OtherAreasAndOrUnitsAffected bit,
	@OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,
	@OtherAreasAndOrUnitsAffectedPersonNotified varchar(50) = NULL,
	
	@WorkPreparationsCompletedSectionNotApplicableToJob bit,
	@ProductNormallyInPipingEquipment varchar(50) = NULL,
	
	@DepressuredDrained varchar(10),
	@WaterWashed varchar(10),
	@ChemicallyWashed varchar(10),
	@Steamed varchar(10),
	@Purged varchar(10),
	@Disconnected varchar(10),
	@DepressuredAndVented varchar(10),
	@Ventilated varchar(10),
	@Blanked varchar(10),
	@DrainsCovered varchar(10),
	@AreaBarricated varchar(10),
	@EnergySourcesLockedOutTaggedOut varchar(10),
	
	@EnergyControlPlan varchar(50) = NULL,
	@LockBoxNumber varchar(50) = NULL,
	@OtherPreparations varchar(50) = NULL,
	
	@SpecificRequirementsSectionNotApplicableToJob bit,
	@AttendedAtAllTimes bit,
	@EyeProtection bit,
	@FallProtectionEquipment bit,
	@FullBodyHarnessRetrieval bit,
	@HearingProtection bit,
	@ProtectiveClothing bit,
	@Other1Checked bit,
	@Other1Value varchar(50) = NULL,

	@EquipmentBondedGrounded bit,
	@FireBlanket bit,
	@FireFightingEquipment bit,
	@FireWatch bit,
	@HydrantPermit bit,
	@WaterHose bit,
	@SteamHose bit,
	@Other2Checked bit,
	@Other2Value varchar(50) = NULL,

	@AirMover bit,
	@ContinuousGasMonitor bit,
	@DrowningProtection bit,
	@RespiratoryProtection bit,
	@Other3Checked bit,
	@Other3Value varchar(50) = NULL,

	@AdditionalLighting bit,
	@DesignateHotOrColdCutChecked bit,
	@DesignateHotOrColdCutValue varchar(50),
	@HoistingEquipment bit,
	@Ladder bit,
	@MotorizedEquipment bit,
	@Scaffold bit,
	@ReferToTipsProcedure bit,
	
	@GasDetectorBumpTested bit,
	@AtmosphericGasTestRequired bit,

	@LastModifiedByUserId bigint,
	@LastModifiedDateTime datetime	
)
AS

INSERT INTO WorkPermitLubesHistory
(	
	Id,	
	WorkPermitStatus,
	DocumentLinks,
	PermitNumber,
	IssuedByUserId,
	IssuedDateTime,
	IssuedToSuncor,
	IssuedToCompany,
	Company,
	Trade,
	NumberOfWorkers,
	RequestedByGroup,
	WorkPermitTypeId,
	IsVehicleEntry,
	FunctionalLocation,
	Location,	
	ConfinedSpace,
	ConfinedSpaceClass,
	RescuePlan,
	ConfinedSpaceSafetyWatchChecklist,
	SpecialWork,
	SpecialWorkType,
	HazardousWorkApproverAdvised,
	AdditionalFollowupRequired,	
	StartDateTime,	
	ExpireDateTime,
	WorkOrderNumber,
	OperationNumber,
	SubOperationNumber,
	HighEnergy,
    CriticalLift,
    Excavation,
    EnergyControlPlanFormRequirement,
    EquivalencyProc,
    TestPneumatic,
    LiveFlareWork,
    EntryAndControlPlan,
	EnergizedElectrical,
	TaskDescription,		
	HazardHydrocarbonGas,
	HazardHydrocarbonLiquid,
	HazardHydrogenSulphide,
	HazardInertGasAtmosphere,
	HazardOxygenDeficiency,
	HazardRadioactiveSources,
	HazardUndergroundOverheadHazards,
	HazardDesignatedSubstance,
	OtherHazardsAndOrRequirements,		
	OtherAreasAndOrUnitsAffected,
	OtherAreasAndOrUnitsAffectedArea,	
	OtherAreasAndOrUnitsAffectedPersonNotified,		
	WorkPreparationsCompletedSectionNotApplicableToJob,
	ProductNormallyInPipingEquipment,		              
	DepressuredDrained,   
	WaterWashed,
	ChemicallyWashed,
	Steamed,   
	Purged,   
	Disconnected,   
	DepressuredAndVented,   
	Ventilated,   
	Blanked,   
	DrainsCovered,   
	AreaBarricated,   
	EnergySourcesLockedOutTaggedOut,   
	EnergyControlPlan,	
	LockBoxNumber,	
	OtherPreparations,	
	SpecificRequirementsSectionNotApplicableToJob,
	AttendedAtAllTimes,
	EyeProtection,
	FallProtectionEquipment,
	FullBodyHarnessRetrieval,
	HearingProtection,
	ProtectiveClothing,
	Other1Checked,
	Other1Value,	
	EquipmentBondedGrounded,
	FireBlanket,
	FireFightingEquipment,
	FireWatch,
	HydrantPermit,
	WaterHose,
	SteamHose,
	Other2Checked,
	Other2Value,	
	AirMover,
	ContinuousGasMonitor,
	DrowningProtection,
	RespiratoryProtection,
	Other3Checked,
	Other3Value,	 
	AdditionalLighting,
	DesignateHotOrColdCutChecked,
	DesignateHotOrColdCutValue,	
	HoistingEquipment,
	Ladder,
	MotorizedEquipment,
	Scaffold,
	ReferToTipsProcedure,	
	GasDetectorBumpTested,
	AtmosphericGasTestRequired,
	LastModifiedByUserId,
	LastModifiedDateTime	
)
VALUES
(	
	@Id,	
	@WorkPermitStatus,	
	@DocumentLinks,
	@PermitNumber,
	@IssuedByUserId,
	@IssuedDateTime,
	@IssuedToSuncor,
	@IssuedToCompany,
	@Company,
	@Trade,
	@NumberOfWorkers,
	@RequestedByGroup,	
	@WorkPermitTypeId,
	@IsVehicleEntry,
	@FunctionalLocation,
	@Location,	
	@ConfinedSpace,
	@ConfinedSpaceClass,
	@RescuePlan,
	@ConfinedSpaceSafetyWatchChecklist,
	@SpecialWork,
	@SpecialWorkType,
	@HazardousWorkApproverAdvised,
	@AdditionalFollowupRequired,	
	@StartDateTime,	
	@ExpireDateTime,
	@WorkOrderNumber,
	@OperationNumber,
	@SubOperationNumber,
	@HighEnergy,
    @CriticalLift,
    @Excavation,
    @EnergyControlPlanFormRequirement,
    @EquivalencyProc,
    @TestPneumatic,
    @LiveFlareWork,
    @EntryAndControlPlan,
	@EnergizedElectrical,
	@TaskDescription,		
	@HazardHydrocarbonGas,
	@HazardHydrocarbonLiquid,
	@HazardHydrogenSulphide,
	@HazardInertGasAtmosphere,
	@HazardOxygenDeficiency,
	@HazardRadioactiveSources,
	@HazardUndergroundOverheadHazards,
	@HazardDesignatedSubstance,
	@OtherHazardsAndOrRequirements,		
	@OtherAreasAndOrUnitsAffected,
	@OtherAreasAndOrUnitsAffectedArea,	
	@OtherAreasAndOrUnitsAffectedPersonNotified,		
	@WorkPreparationsCompletedSectionNotApplicableToJob,
	@ProductNormallyInPipingEquipment,		              
	@DepressuredDrained,   
	@WaterWashed,
	@ChemicallyWashed,
	@Steamed,   
	@Purged,   
	@Disconnected,   
	@DepressuredAndVented,   
	@Ventilated,   
	@Blanked,   
	@DrainsCovered,   
	@AreaBarricated,   
	@EnergySourcesLockedOutTaggedOut,   
	@EnergyControlPlan,	
	@LockBoxNumber,	
	@OtherPreparations,	
	@SpecificRequirementsSectionNotApplicableToJob,
	@AttendedAtAllTimes,
	@EyeProtection,
	@FallProtectionEquipment,
	@FullBodyHarnessRetrieval,
	@HearingProtection,
	@ProtectiveClothing,
	@Other1Checked,
	@Other1Value,	
	@EquipmentBondedGrounded,
	@FireBlanket,
	@FireFightingEquipment,
	@FireWatch,
	@HydrantPermit,
	@WaterHose,
	@SteamHose,
	@Other2Checked,
	@Other2Value,	
	@AirMover,
	@ContinuousGasMonitor,
	@DrowningProtection,
	@RespiratoryProtection,
	@Other3Checked,
	@Other3Value,	 
	@AdditionalLighting,
	@DesignateHotOrColdCutChecked,
	@DesignateHotOrColdCutValue,	
	@HoistingEquipment,
	@Ladder,
	@MotorizedEquipment,
	@Scaffold,
	@ReferToTipsProcedure,
	@GasDetectorBumpTested,
	@AtmosphericGasTestRequired,
	@LastModifiedByUserId,
	@LastModifiedDateTime	
)



