if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermit]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[InsertWorkPermit]

GO

CREATE Procedure [dbo].[InsertWorkPermit]
(
    @Id bigint Output,
    @PermitNumber varchar(50) Output,
    @Version varchar(10),
    @LastModifiedDateTime datetime,
    @LastModifiedUserId bigint = NULL,
    @ApprovedByUserId bigint = NULL,
    @CreatedByUserId bigint,
    @IsOperations bit,
    @SourceId int,

    @SpecialRescueOrFallNotApplicable bit,
    @SpecialRescueOrFallOtherDescription varchar(50)= NULL,
    @SpecialRescueOrFallRescueDevice bit,
    @SpecialRescueOrFallYoYo bit,
    @SpecialRescueOrFallLifeline bit,
    @SpecialRescueOrFallBodyHarness bit,
	
	@SpecialFallOtherDescription varchar(50) = NULL,
	@SpecialFallRestraint bit,
	@SpecialFallSelfRetractingDevice bit,
	@SpecialFallTieoffRequired bit = NULL,

    @SpecialHandProtectionNotApplicable bit,
    @SpecialHandProtectionOtherDescription varchar(50)= NULL,
    @SpecialHandProtectionLeather bit,
    @SpecialHandProtectionChemicalGloves bit,
    @SpecialHandProtectionWelding bit,
    @SpecialHandProtectionHighVoltage bit,
    @SpecialHandProtectionPVC bit,
    @SpecialHandProtectionNitrile bit,
    @SpecialHandProtectionNaturalRubber bit,
    @SpecialHandProtectionChemicalNeprene bit,

    @SpecialProtectiveFootwearNotApplicable bit,
    @SpecialProtectiveFootwearOtherDescription varchar(50)= NULL,
    @SpecialProtectiveFootwearToeGuard bit,
    @SpecialProtectiveFootwearChemicalImperviousBoots bit,
    @SpecialProtectiveFootwearMetatarsalGuard bit,

    @SpecialProtectiveClothingTypeNotApplicable bit,
    @SpecialProtectiveClothingTypeOtherDescripton varchar(50)= NULL,
    @SpecialProtectiveClothingTypeTyvekSuit bit,
	@SpecialProtectiveClothingTypeKapplerSuit bit,
	@SpecialProtectiveClothingTypeElectricalFlashGear bit,
	@SpecialProtectiveClothingTypeCorrosiveClothing bit,    
    @SpecialProtectiveClothingTypeCausticWear bit,
	@SpecialProtectiveClothingTypePaperCoveralls bit,
    @SpecialProtectiveClothingTypeAcidClothingTypeID int = NULL,
    @SpecialProtectiveClothingTypeAcidClothing bit,
    @SpecialProtectiveClothingTypeRainPants bit,
    @SpecialProtectiveClothingTypeRainCoat bit,

    @SpecialEyeOrFaceProtectionNotApplicable bit,
    @SpecialEyeOrFaceProtectionOtherDescription varchar(50)= NULL,
    @SpecialEyeOrFaceProtectionFaceshield bit,
    @SpecialEyeOrFaceProtectionGoggles bit,

    @RespitoryProtectionRequirementsNotApplicable bit,
    @RespitoryProtectionRequirementsRespiratoryCartridgeTypeDescription varchar(50)= NULL,
    @RespitoryProtectionRequirementsRespiratoryCartridgeTypeId bigint= NULL,     
    @RespitoryProtectionRequirementsOtherDescription varchar(50)= NULL,
    @RespitoryProtectionRequirementsAirHood bit,
    @RespitoryProtectionRequirementsDustMask bit,
    @RespitoryProtectionRequirementsFullFaceRespirator bit,
    @RespitoryProtectionRequirementsHalfFaceRespirator bit,
    @RespitoryProtectionRequirementsSCBA bit,
    @RespitoryProtectionRequirementsAirCartOrAirLine bit,

    @FireConfinedSpaceNotApplicable bit,
    @FireConfinedSpaceOtherDescription varchar(50)= NULL,
    @FireConfinedSpaceHoleWatchNumber varchar(50)= NULL,    
    @FireConfinedSpaceFireWatchNumber varchar(50)= NULL,
    @FireConfinedSpaceSpotterNumber varchar(50)= NULL,    
    @FireConfinedSpaceWatchmen bit,
    @FireConfinedSpaceSteamHose bit,
    @FireConfinedSpaceWaterHose bit,
    @FireConfinedSpaceSparkContainment bit,
    @FireConfinedSpaceFireResistantTarp bit,
    @FireConfinedSpaceC02Extinguisher bit,
    @FireConfinedSpace20ABCorDryChemicalExtinguisher bit,
    @GasTestConstantMonitoringRequired bit,
	@GasTestForkliftNotUsed bit,
    @GasTestTestTime datetime= NULL,
    @GasTestConfinedSpaceTestTime datetime= NULL,
    @GasTestSystemEntryTestTime datetime= NULL,
    @GasTestFrequencyOrDuration varchar(50)= NULL,
    @RadiationSealedSourceIsolationNumberOfSources int = NULL,
    @RadiationSealedSourceIsolationOpen bit,
    @RadiationSealedSourceIsolationLOTO bit,
    @RadiationSealedSourceIsolationNotApplicable bit,
    @JobSitePreparationLightingElectricalRequirementOtherDescription varchar(50)= NULL,
    @JobSitePreparationLightingElectricalRequirementGeneratorLights bit,
    @JobSitePreparationLightingElectricalRequirement110VWithGFCI bit,
    @JobSitePreparationLightingElectricalRequirementLowVoltage12V bit,
    @JobSitePreparationLightingElectricalRequirementNotApplicable bit,
    @JobSitePreparationAreaPreparationOtherDescription varchar(50)= NULL,
    @JobSitePreparationAreaPreparationPreopBoundaryRopeTape bit,
    @JobSitePreparationAreaPreparationRadiationRope bit,    
    @JobSitePreparationAreaPreparationNonEssentialEvac bit,
    @JobSitePreparationAreaPreparationBarricade bit,
    @JobSitePreparationAreaPreparationNotApplicable bit,
    
    @JobSitePreparationSewerIsolationMethodOtherDescription varchar(50)= NULL,
    @JobSitePreparationSewerIsolationMethodBlindedOrBlanked bit,
    @JobSitePreparationSewerIsolationMethodPlugged bit,
    @JobSitePreparationSewerIsolationMethodSealedOrCovered bit,
    @JobSitePreparationSewerIsolationMethodNotApplicable bit,
    @JobSitePreparationPermitReceiverFieldOrEquipmentOrientation bit = NULL,
	@IsControlRoomContactedOrNot bit = NULL, --vibhor
	@ClonedFormDetailSarnia varchar(100) = NULL,
	@ClonedFormDetailDenver varchar(100) = NULL,
    @JobSitePreparationPermitReceiverFieldOrEquipmentOrientationNotApplicable bit,
    @JobSitePreparationPermitReceiverRequiresOrientationComments varchar(400)= NULL,
    
    @JobSitePreparationVestedBuddySystemInEffect bit = NULL,
    @JobSitePreparationVestedBuddySystemInEffectNotApplicable bit,
    
    @JobSitePreparationSurroundingConditionsAffectOrContaminated bit = NULL,
    @JobSitePreparationSurroundingConditionsAffectOrContaminatedNotApplicable bit,
    @JobSitePreparationSurroundingConditionsAffectAreaComments varchar(400)= NULL,    
        
    @JobSitePreparationCriticalConditionRemainJobSite bit = NULL,
    @JobSitePreparationCriticalConditionRemainJobSiteNotApplicable bit,
    @JobSitePreparationCriticalConditionsComments varchar(400)= NULL,
    
    @JobSitePreparationWeldingGroundWireInTestArea bit = NULL,
    @JobSitePreparationWeldingGroundWireInTestAreaNotApplicable bit,
	@ControlRoomContactedNotApplicable bit, --vibhor
    @JobSitePreparationWeldingGroundWireNotWithinGasTestAreaComments varchar(400)= NULL,
    
    @JobSitePreparationBondingOrGroundingRequired bit = NULL,
    @JobSitePreparationBondingOrGroundingRequiredNotApplicable bit,
    @JobSitePreparationBondingGroundingNotRequiredComments varchar(400)= NULL,
    
    @JobSitePreparationFlowRequiredForJobNotApplicable bit = NULL,
    @JobSitePreparationFlowRequiredForJob bit = NULL,    
    @JobSitePreparationFlowRequiredComments varchar(400)= NULL,
    
    @EquipmentIsolationMethodOtherDescription varchar(50)= NULL,
    @EquipmentIsolationMethodLOTO bit,
    @EquipmentIsolationMethodMudderPlugs bit,
    @EquipmentIsolationMethodSeparation bit,
    @EquipmentIsolationMethodBlindedorBlanked bit,
    @EquipmentIsolationMethodBlockedIn bit,
    @EquipmentIsolationMethodCarBer bit,
    @EquipmentIsolationMethodNotApplicable bit,
    @EquipmentPreviousContentsOtherDescription varchar(50)= NULL,
    @EquipmentPreviousContentsH2S bit,
    @EquipmentPreviousContentsCaustic bit,
    @EquipmentPreviousContentsAcid bit,
    @EquipmentPreviousContentsHydrocarbon bit,
    @EquipmentPreviousContentsNotApplicable bit,
	@EquipmentAsbestosGasketsNotApplicable bit,
	@EquipmentAsbestosGaskets bit = NULL,
    @EquipmentConditionPurgedDescription varchar(50)= NULL,
    @EquipmentConditionPurged bit,
    @EquipmentConditionPurgedN2 bit,
    @EquipmentConditionPurgedSteamed bit,
    @EquipmentConditionPurgedAir bit,
    @EquipmentConditionNeutralized bit,
    @EquipmentConditionH20Washed bit,
    @EquipmentConditionVentilated bit,
    @EquipmentConditionCleaned bit,
    @EquipmentConditionDrained bit,
    @EquipmentConditionDepressured bit,
    @EquipmentConditionNotApplicable bit,
    @EquipmentConditionOtherDescription varchar(50)= NULL,    
	@EquipmentConditionPurgedChecked bit, --vibhor
    @EquipmentIsOutOfService bit = NULL,
    @EquipmentInServiceComments varchar(400)= NULL,
    
    @EquipmentLeakingValves bit = NULL,
    @EquipmentLeakingValvesNotApplicable bit,
    @EquipmentLeakingValvesComments varchar(400)= NULL,
	@EquipmentInAsbestosHazardPresentComments varchar(400)= NULL, --vibhor
	
        
    @EquipmentStillContainsResidual bit = NULL,
    @EquipmentStillContainsResidualNotApplicable bit,
    @EquipmentStillContainsResidualComments varchar(400)= NULL,
    
    @EquipmentVentilationMethodForced bit,
    @EquipmentVentilationMethodLocalExhaust bit,
    @EquipmentVentilationMethodNaturalDraft bit,
    @EquipmentVentilationMethodNotApplicable bit,
    
    @ElectricTestBump bit = NULL,
    @ElectricTestBumpNotApplicable bit,
    @EquipmentNoElectricalTestBumpComments varchar(400)= NULL,    
    @ElectricIsolationMethodWiring bit,
    @ElectricIsolationMethodLOTO bit,
    @ElectricIsolationMethodNotApplicable bit,

    @EquipmentIsHazardousEnergyIsolationRequiredNotApplicable bit,
    @EquipmentIsHazardousEnergyIsolationRequired bit = NULL,
    @EquipmentLockOutMethodId bigint = NULL,
    @EquipmentLockOutMethodComments varchar(600) = NULL,
    @EquipmentEnergyIsolationPlanNumber varchar(100) = NULL,
    @EquipmentConditionsOfEIPSatisfied bit = NULL,
    @EquipmentConditionsOfEIPNotSatisfiedComments varchar(400) = NULL,

    @AsbestosHazardsConsideredNotApplicable bit,
    @AsbestosHazardsConsidered bit = NULL,

    @ToolsOtherToolsDescription varchar(50)= NULL,
    @ToolsWelder bit,
    @ToolsChemicals bit,
    @ToolsTorch bit,
    @ToolsPortLighting bit,
    @ToolsHotTapMachine bit,
    @ToolsTamper bit,
    @ToolsManlift bit,
    @ToolsHEPAVacuum bit,
    @ToolsForklift bit,
    @ToolsCompressor bit,
    @ToolsVehicle bit,
    @ToolsScaffolding bit,
    @ToolsLanda bit,
    @ToolsHeavyEquipment bit,
    @ToolsElectricTools bit,
    @ToolsCementSaw bit,
    @ToolsVacuumTruck bit,
    @ToolsJackhammer bit,
    @ToolsHandTools bit,
    @ToolsCraneOrCarrydeck bit,
    @ToolsAirTools bit,
    @CoAuthorizationRequired bit=NULL,
    @CommunicationByOtherDescription varchar(50)= NULL,
    @CoAuthorizationDescription varchar(50) = NULL,
    @CommunicationRadioColor varchar(20)= NULL,
    @CommunicationRadioChannelOrBand varchar(20)= NULL,
    @IsWorkPermitCommunicationNotApplicable bit,
    @CommunicationByRadio bit = NULL,
    @JobStepDescription VARCHAR(MAX) = NULL,
    @CraftOrTradeID bigint = NULL,
    @CraftOrTradeOther varchar(50) = NULL,
    @ContractorCompanyName varchar(50)= NULL,
    @ContactPersonnel varchar(50)= NULL,
    @AdditionalOtherFormsOrAssessmentsOrAuthorizations varchar(50)= NULL,
    @AdditionalMSDS bit,
    @AdditionalWaiverOrDeviation bit,
    @AdditionalWaiverOrDeviationDescription varchar(50)= NULL,
    @AdditionalBurnOrOpenFlameAssessment bit,
    @AdditionalBurnOrOpenFlameAssessmentDescription varchar(50)= NULL,
    @AdditionalElectrical bit,
    @AdditionalElectricalDescription varchar(50)= NULL,
    @AdditionalRoadClosure bit,
    @AdditionalAsbestosHandling bit,
    @AdditionalAsbestosHandlingDescription varchar(50)= NULL,
    @AdditionalPJSROrSafetyPause bit,
    @AdditionalBlankOrBlindLists bit,
    @AdditionalSpecialWasteDisposal bit,
    @AdditionalHotTap bit,
    @AdditionalExcavation bit,
    @AdditionalExcavationDescription varchar(50)= NULL,
    @AdditionalCriticalLift bit,
    @AdditionalCriticalLiftDescription varchar(50)= NULL,
    @AdditionalFlareEntry bit,
    @AdditionalCSEAssessmentOrAuthorization bit,
    @AdditionalCSEAssessmentOrAuthorizationDescription varchar(50)= NULL,
    @AdditionalRadiationApproval bit,
    @AdditionalOnlineLeakRepairForm bit,
	@AdditionalIsEnergizedElectricalForm bit,
	@AdditionalIsNotApplicable bit,
	
    @PermitRadiationSealed bit,
    @PermitRadiationRadiography bit,
    @PermitAsbestos bit,
    @PermitExcavation bit,
    @PermitElectricalWork bit,
    @PermitCriticalLift bit,
    @PermitSystemEntry bit,
    @PermitBurnOrOpenFlame bit,
	@PermitFreshAir bit, --Vibhor
	@ControlRoomContacted bit, --vibhor
    @PermitHotTap bit,
    @PermitVehicleEntry bit,
    @PermitBreathingAirOrSCBA bit,
    @PermitConfinedSpaceEntry bit,
    @PermitInertConfinedSpaceEntry bit,
    @PermitLeadAbatement bit,

    @SpecialPrecautionsOrConsiderationsDescription VARCHAR(MAX)= NULL,
    @WorkOrderDescription VARCHAR(MAX)= NULL,
    @WorkPermitTypeClassificationId bigint,
    @WorkPermitTypeId bigint,
    @PermitValidDateTime datetime=NULL,
    @EndDateTime datetime = NULL,
    @StartDateTime datetime,
	@StartTimeNotApplicable bit,
    @StartAndOrEndTimesFinalized BIT,
    @WorkOrderNumber varchar(50)=NULL,
    @FunctionalLocationId bigint,
    @WorkPermitStatusId bigint,
    @SapOperationId bigint = NULL,

@PreExcavationAuthorization									bit,
@SuspendedWorkPlatform 										bit,
@HotTurnoverApproval 										bit,
@ConfinedSpaceEntryAuthorizationForm 						bit,
@PreExcavationAuthorizationForm 								bit,
@SupplementalJobSiteSignInForm 								bit,
@SystemEntryGasTestLogFrom 									bit,
@HeatStressMonitoringForm 									bit,
@CriticalLiftApprovalForm 									bit,
@PjsrSecondSection 											bit,
@DeviationRequestForm 										bit,
@RoadClosureform 											bit,
@RadiographyApprovalForm 									bit,
@ConfinedSpaceEntryTrackingLog 								bit,
@FlareLineChecklists 										bit,
@HotTurnoverApprovalForm 									bit,
@IndustrialHygieneAreaRealTimeSamplingForm 					bit,
@CraneSuspendedWorkPlatformChecklist 						bit,
@ConfinedSpaceEntryAuthorizationFormSecondSection 			bit,
@NASecondSection bit,




	@WorkAssignmentId bigint = NULL
)
AS

DECLARE @NewPermitNumber varchar(50)
DECLARE @DivisionName varchar(25)
DECLARE @WorkPermitCountForSite bigint

--Generate the new permit number based on Site Name and the next available 'number'
--Generate the new number part by counting the number of work permits with given site id and adding 1
SET @DivisionName = 
	(
		select 
			COALESCE(fa.FullHierarchy, f.FullHierarchy)
		from
			FunctionalLocation f
			LEFT OUTER JOIN FunctionalLocationAncestor a on a.Id = f.Id and a.AncestorLevel = 1
			LEFT OUTER JOIN FunctionalLocation fa on fa.Id = a.AncestorId
		where
			f.Id = @FunctionalLocationId
	)
SET @WorkPermitCountForSite = 
	(
		select 
			count(*) 
		from 
			workpermit 
			inner join functionallocation 
				ON workpermit.functionallocationid = functionallocation.[id] 
			where
				functionallocation.siteid = (
												select 
													siteid 
												from 
													functionallocation 
												where 
													id = @FunctionalLocationId
											)
	)

SET @NewPermitNumber =  @DivisionName + '-'+ REPLACE(str(@WorkPermitCountForSite+1),' ','0')

INSERT INTO WorkPermit
(
	Version,
    LastModifiedDate,
    LastModifiedUserId,
    CreatedByUserId,
    IsOperations,
    ApprovedByUserId, 
    SourceId, 

    SpecialRescueOrFallNotApplicable,
    SpecialRescueOrFallOtherDescription, 
    SpecialRescueOrFallRescueDevice, 
    SpecialRescueOrFallYoYo, 
    SpecialRescueOrFallLifeline, 
    SpecialRescueOrFallBodyHarness, 
	
	SpecialFallOtherDescription,
	SpecialFallRestraint,
	SpecialFallSelfRetractingDevice,
	SpecialFallTieoffRequired,

    SpecialHandProtectionNotApplicable,
    SpecialHandProtectionOtherDescription, 
    SpecialHandProtectionLeather, 
    SpecialHandProtectionChemicalGloves, 
    SpecialHandProtectionWelding, 
    SpecialHandProtectionHighVoltage, 
    SpecialHandProtectionPVC, 
    SpecialHandProtectionNitrile, 
    SpecialHandProtectionNaturalRubber, 
    SpecialHandProtectionChemicalNeprene, 

    SpecialProtectiveFootwearNotApplicable,
    SpecialProtectiveFootwearOtherDescription, 
    SpecialProtectiveFootwearToeGuard, 
    SpecialProtectiveFootwearChemicalImperviousBoots,
    SpecialProtectiveFootwearMetatarsalGuard, 

    SpecialProtectiveClothingTypeNotApplicable,
    SpecialProtectiveClothingTypeOtherDescripton,    
    SpecialProtectiveClothingTypeTyvekSuit,
	SpecialProtectiveClothingTypeKapplerSuit,
	SpecialProtectiveClothingTypeElectricalFlashGear,
	SpecialProtectiveClothingTypeCorrosiveClothing,	
    SpecialProtectiveClothingTypeCausticWear,
    SpecialProtectiveClothingTypePaperCoveralls,
    SpecialProtectiveClothingTypeAcidClothingTypeID, 
    SpecialProtectiveClothingTypeAcidClothing, 
    SpecialProtectiveClothingTypeRainPants, 
    SpecialProtectiveClothingTypeRainCoat, 
    
    SpecialEyeOrFaceProtectionNotApplicable,
    SpecialEyeOrFaceProtectionOtherDescription, 
    SpecialEyeOrFaceProtectionFaceshield, 
    SpecialEyeOrFaceProtectionGoggles, 

    RespitoryProtectionRequirementsNotApplicable,
    RespitoryProtectionRequirementsRespiratoryCartridgeTypeDescription, 
    RespitoryProtectionRequirementsRespiratoryCartridgeTypeId,
    RespitoryProtectionRequirementsOtherDescription, 
    RespitoryProtectionRequirementsAirHood, 
    RespitoryProtectionRequirementsDustMask, 
    RespitoryProtectionRequirementsFullFaceRespirator, 
    RespitoryProtectionRequirementsHalfFaceRespirator, 
    RespitoryProtectionRequirementsSCBA, 
    RespitoryProtectionRequirementsAirCartOrAirLine,
    
    FireConfinedSpaceNotApplicable,
    FireConfinedSpaceOtherDescription,
    FireConfinedSpaceHoleWatchNumber,
    FireConfinedSpaceFireWatchNumber,
    FireConfinedSpaceSpotterNumber,
    FireConfinedSpaceWatchmen, 
    FireConfinedSpaceSteamHose, 
    FireConfinedSpaceWaterHose, 
    FireConfinedSpaceSparkContainment, 
    FireConfinedSpaceFireResistantTarp, 
    FireConfinedSpaceC02Extinguisher, 
    FireConfinedSpace20ABCorDryChemicalExtinguisher, 
    GasTestConstantMonitoringRequired,
	GasTestForkliftNotUsed,
    GasTestTestTime,
    GasTestConfinedSpaceTestTime,
    GasTestSystemEntryTestTime,
    GasTestFrequencyOrDuration,
    RadiationSealedSourceIsolationNumberOfSources,
    RadiationSealedSourceIsolationOpen,
    RadiationSealedSourceIsolationLOTO,
    RadiationSealedSourceIsolationNotApplicable,
    JobSitePreparationLightingElectricalRequirementOtherDescription,
    JobSitePreparationLightingElectricalRequirementGeneratorLights, 
    JobSitePreparationLightingElectricalRequirement110VWithGFCI,
    JobSitePreparationLightingElectricalRequirementLowVoltage12V,
    JobSitePreparationLightingElectricalRequirementNotApplicable,
    JobSitePreparationAreaPreparationOtherDescription,
    JobSitePreparationAreaPreparationPreopBoundaryRopeTape,
    JobSitePreparationAreaPreparationRadiationRope,
    JobSitePreparationAreaPreparationNonEssentialEvac,
    JobSitePreparationAreaPreparationBarricade,
    JobSitePreparationAreaPreparationNotApplicable,
    JobSitePreparationSewerIsolationMethodOtherDescription,
    JobSitePreparationSewerIsolationMethodBlindedOrBlanked,
    JobSitePreparationSewerIsolationMethodPlugged,
    JobSitePreparationSewerIsolationMethodSealedOrCovered,
    JobSitePreparationSewerIsolationMethodNotApplicable,
    JobSitePreparationPermitReceiverFieldOrEquipmentOrientation,
	IsControlRoomContactedOrNot,--vibhor
	ClonedFormDetailSarnia,
	ClonedFormDetailDenver,
    JobSitePreparationPermitReceiverFieldOrEquipmentOrientationNotApplicable,
    JobSitePreparationVestedBuddySystemInEffect,
    JobSitePreparationVestedBuddySystemInEffectNotApplicable,
    JobSitePreparationSurroundingConditionsAffectOrContaminated,
    JobSitePreparationSurroundingConditionsAffectOrContaminatedNotApplicable,
    JobSitePreparationCriticalConditionRemainJobSite,
    JobSitePreparationCriticalConditionRemainJobSiteNotApplicable,
    JobSitePreparationWeldingGroundWireInTestArea,
    JobSitePreparationWeldingGroundWireInTestAreaNotApplicable,
    JobSitePreparationBondingOrGroundingRequired,
    JobSitePreparationBondingOrGroundingRequiredNotApplicable,
    JobSitePreparationFlowRequiredForJobNotApplicable,
    JobSitePreparationFlowRequiredForJob,
	ControlRoomContactedNotApplicable, --vibhor
    EquipmentIsolationMethodOtherDescription,
    EquipmentIsolationMethodLOTO,
    EquipmentIsolationMethodMudderPlugs,
    EquipmentIsolationMethodSeparation,
    EquipmentIsolationMethodBlindedorBlanked,
    EquipmentIsolationMethodBlockedIn,
    EquipmentIsolationMethodCarBer,
    EquipmentIsolationMethodNotApplicable,
    EquipmentPreviousContentsOtherDescription,
    EquipmentPreviousContentsH2S,
    EquipmentPreviousContentsCaustic,
    EquipmentPreviousContentsAcid,
    EquipmentPreviousContentsHydrocarbon,
    EquipmentPreviousContentsNotApplicable,
	EquipmentAsbestosGasketsNotApplicable,
	EquipmentAsbestosGaskets,
    EquipmentConditionPurgedDescription,
    EquipmentConditionPurged,
    EquipmentConditionPurgedN2,
    EquipmentConditionPurgedSteamed,
    EquipmentConditionPurgedAir,
    EquipmentConditionNeutralized,
    EquipmentConditionH20Washed,
    EquipmentConditionVentilated,
    EquipmentConditionCleaned,
    EquipmentConditionDrained,
    EquipmentConditionDepressured,
    EquipmentConditionNotApplicable,
    EquipmentConditionOtherDescription,
    EquipmentIsOutOfService,
    EquipmentLeakingValves,
	EquipmentConditionPurgedChecked, --vibhor
    EquipmentLeakingValvesNotApplicable,
    EquipmentStillContainsResidual,
    EquipmentStillContainsResidualNotApplicable,
    EquipmentVentilationMethodForced,
    EquipmentVentilationMethodLocalExhaust,
    EquipmentVentilationMethodNaturalDraft,
    EquipmentVentilationMethodNotApplicable,
    ElectricTestBump,
    ElectricTestBumpNotApplicable,
    ElectricIsolationMethodWiring,
    ElectricIsolationMethodLOTO,
    ElectricIsolationMethodNotApplicable,
    EquipmentIsHazardousEnergyIsolationRequiredNotApplicable,
    EquipmentIsHazardousEnergyIsolationRequired,
    EquipmentLockOutMethodId,
    EquipmentLockOutMethodComments,
    EquipmentEnergyIsolationPlanNumber,
    EquipmentConditionsOfEIPSatisfied,
    EquipmentConditionsOfEIPNotSatisfiedComments,
    AsbestosHazardsConsideredNotApplicable,
    AsbestosHazardsConsidered,
    ToolsOtherToolsDescription,
    ToolsWelder,
    ToolsChemicals,
    ToolsTorch,
    ToolsPortLighting,
    ToolsHotTapMachine,
    ToolsTamper,
    ToolsManlift,
    ToolsHEPAVacuum,
    ToolsForklift,
    ToolsCompressor,
    ToolsVehicle,
    ToolsScaffolding,
    ToolsLanda,
    ToolsHeavyEquipment,
    ToolsElectricTools,
    ToolsCementSaw,
    ToolsVacuumTruck,
    ToolsJackhammer,
    ToolsHandTools,
    ToolsCraneOrCarrydeck,
    ToolsAirTools,
    CoAuthorizationDescription,
    CoAuthorizationRequired,
    CommunicationByOtherDescription,
    CommunicationRadioColor,
    CommunicationRadioChannelOrBand,
    IsWorkPermitCommunicationNotApplicable,
    CommunicationByRadio,
    JobStepDescription,
    CraftOrTradeOther,
    CraftOrTradeID,
    ContractorCompanyName,
    ContactPersonnel,
    AdditionalOtherFormsOrAssessmentsOrAuthorizations,
    AdditionalMSDS,
    AdditionalWaiverOrDeviation,
    AdditionalWaiverOrDeviationDescription,
    AdditionalBurnOrOpenFlameAssessment,
    AdditionalBurnOrOpenFlameAssessmentDescription,
    AdditionalElectrical,
    AdditionalElectricalDescription,
    AdditionalRoadClosure,
    AdditionalAsbestosHandling,
    AdditionalAsbestosHandlingDescription,
    AdditionalPJSROrSafetyPause,
    AdditionalBlankOrBlindLists,
    AdditionalSpecialWasteDisposal,
    AdditionalHotTap,
    AdditionalExcavation,
    AdditionalExcavationDescription,    
    AdditionalCriticalLift,
    AdditionalCriticalLiftDescription,    
    AdditionalFlareEntry,
    AdditionalCSEAssessmentOrAuthorization,
    AdditionalCSEAssessmentOrAuthorizationDescription,
    AdditionalRadiationApproval,
    AdditionalOnlineLeakRepairForm,
	AdditionalIsEnergizedElectricalForm,
	AdditionalIsNotApplicable,

    PermitRadiationSealed,
    PermitRadiationRadiography,
    PermitAsbestos,
    PermitExcavation,
    PermitElectricalWork,
    PermitCriticalLift,
    PermitSystemEntry,
    PermitBurnOrOpenFlame,
	PermitFreshAir, --vibhor
	ControlRoomContacted, --vibhor
    PermitHotTap,
    PermitVehicleEntry,
    PermitBreathingAirOrSCBA,
    PermitConfinedSpaceEntry,
    PermitInertConfinedSpaceEntry,
    PermitLeadAbatement,

    SpecialPrecautionsOrConsiderationsDescription,
    WorkOrderDescription,
    WorkPermitTypeClassificationId,
    WorkPermitTypeId,
    PermitValidDateTime,
    EndDateTime,
    StartDateTime,
	StartTimeNotApplicable,
    StartAndOrEndTimesFinalized,
    WorkOrderNumber,
    PermitNumber,
    FunctionalLocationId,
    WorkPermitStatusId,
    EquipmentStillContainsResidualComments,
    EquipmentInServiceComments,
    EquipmentNoElectricalTestBumpComments,
    EquipmentLeakingValvesComments,
    JobSitePreparationFlowRequiredComments,
    JobSitePreparationBondingGroundingNotRequiredComments,
    JobSitePreparationWeldingGroundWireNotWithinGasTestAreaComments,
    JobSitePreparationSurroundingConditionsAffectAreaComments,
	EquipmentInAsbestosHazardPresentComments, --vibhor
	
    JobSitePreparationCriticalConditionsComments,
    JobSitePreparationPermitReceiverRequiresOrientationComments,
    SapOperationId,

PreExcavationAuthorization						,
SuspendedWorkPlatform 							,
HotTurnoverApproval 							,
ConfinedSpaceEntryAuthorizationForm 			,
PreExcavationAuthorizationForm 					,
SupplementalJobSiteSignInForm 					,
SystemEntryGasTestLogFrom 						,
HeatStressMonitoringForm 						,
CriticalLiftApprovalForm 						,
PjsrSecondSection 								,
DeviationRequestForm 							,
RoadClosureform 								,
RadiographyApprovalForm 						,
ConfinedSpaceEntryTrackingLog 					,
FlareLineChecklists 							,
HotTurnoverApprovalForm 						,
IndustrialHygieneAreaRealTimeSamplingForm 		,
CraneSuspendedWorkPlatformChecklist 			,
ConfinedSpaceEntryAuthorizationFormSecondSection, 
NASecondSection,


	WorkAssignmentId
)
VALUES
(
	@Version,
    @LastModifiedDateTime,
    @CreatedByUserId,
    @CreatedByUserId,
    @IsOperations,
    @ApprovedByUserId,
    @SourceId,

    @SpecialRescueOrFallNotApplicable,
    @SpecialRescueOrFallOtherDescription,
    @SpecialRescueOrFallRescueDevice,
    @SpecialRescueOrFallYoYo,
    @SpecialRescueOrFallLifeline,
    @SpecialRescueOrFallBodyHarness,
	
	@SpecialFallOtherDescription,
	@SpecialFallRestraint,
	@SpecialFallSelfRetractingDevice,
	@SpecialFallTieoffRequired,

    @SpecialHandProtectionNotApplicable,
    @SpecialHandProtectionOtherDescription,
    @SpecialHandProtectionLeather,
    @SpecialHandProtectionChemicalGloves,
    @SpecialHandProtectionWelding,
    @SpecialHandProtectionHighVoltage,
    @SpecialHandProtectionPVC,
    @SpecialHandProtectionNitrile,
    @SpecialHandProtectionNaturalRubber,
    @SpecialHandProtectionChemicalNeprene,

    @SpecialProtectiveFootwearNotApplicable,
    @SpecialProtectiveFootwearOtherDescription,
    @SpecialProtectiveFootwearToeGuard,
    @SpecialProtectiveFootwearChemicalImperviousBoots,
    @SpecialProtectiveFootwearMetatarsalGuard,

    @SpecialProtectiveClothingTypeNotApplicable,
    @SpecialProtectiveClothingTypeOtherDescripton,    
    @SpecialProtectiveClothingTypeTyvekSuit,
	@SpecialProtectiveClothingTypeKapplerSuit,
	@SpecialProtectiveClothingTypeElectricalFlashGear,
	@SpecialProtectiveClothingTypeCorrosiveClothing,	    
    @SpecialProtectiveClothingTypeCausticWear,
	@SpecialProtectiveClothingTypePaperCoveralls,
    @SpecialProtectiveClothingTypeAcidClothingTypeID,
    @SpecialProtectiveClothingTypeAcidClothing,
    @SpecialProtectiveClothingTypeRainPants,
    @SpecialProtectiveClothingTypeRainCoat,

    @SpecialEyeOrFaceProtectionNotApplicable,
    @SpecialEyeOrFaceProtectionOtherDescription,
    @SpecialEyeOrFaceProtectionFaceshield,
    @SpecialEyeOrFaceProtectionGoggles,

    @RespitoryProtectionRequirementsNotApplicable,
    @RespitoryProtectionRequirementsRespiratoryCartridgeTypeDescription,
    @RespitoryProtectionRequirementsRespiratoryCartridgeTypeId,
    @RespitoryProtectionRequirementsOtherDescription,
    @RespitoryProtectionRequirementsAirHood,
    @RespitoryProtectionRequirementsDustMask,
    @RespitoryProtectionRequirementsFullFaceRespirator,
    @RespitoryProtectionRequirementsHalfFaceRespirator,
    @RespitoryProtectionRequirementsSCBA,
    @RespitoryProtectionRequirementsAirCartOrAirLine,

    @FireConfinedSpaceNotApplicable,
    @FireConfinedSpaceOtherDescription,
    @FireConfinedSpaceHoleWatchNumber,
    @FireConfinedSpaceFireWatchNumber,
    @FireConfinedSpaceSpotterNumber,    
    @FireConfinedSpaceWatchmen,
    @FireConfinedSpaceSteamHose,
    @FireConfinedSpaceWaterHose,
    @FireConfinedSpaceSparkContainment,
    @FireConfinedSpaceFireResistantTarp,
    @FireConfinedSpaceC02Extinguisher,
    @FireConfinedSpace20ABCorDryChemicalExtinguisher,
    @GasTestConstantMonitoringRequired,
	@GasTestForkliftNotUsed,
    @GasTestTestTime,
    @GasTestConfinedSpaceTestTime,
    @GasTestSystemEntryTestTime,    
    @GasTestFrequencyOrDuration,
    @RadiationSealedSourceIsolationNumberOfSources,
    @RadiationSealedSourceIsolationOpen,
    @RadiationSealedSourceIsolationLOTO,
    @RadiationSealedSourceIsolationNotApplicable,
    @JobSitePreparationLightingElectricalRequirementOtherDescription,
    @JobSitePreparationLightingElectricalRequirementGeneratorLights,
    @JobSitePreparationLightingElectricalRequirement110VWithGFCI,
    @JobSitePreparationLightingElectricalRequirementLowVoltage12V,
    @JobSitePreparationLightingElectricalRequirementNotApplicable,
    @JobSitePreparationAreaPreparationOtherDescription,
    @JobSitePreparationAreaPreparationPreopBoundaryRopeTape,
    @JobSitePreparationAreaPreparationRadiationRope,
    @JobSitePreparationAreaPreparationNonEssentialEvac,
    @JobSitePreparationAreaPreparationBarricade,
    @JobSitePreparationAreaPreparationNotApplicable,
    
    @JobSitePreparationSewerIsolationMethodOtherDescription,
    @JobSitePreparationSewerIsolationMethodBlindedOrBlanked,
    @JobSitePreparationSewerIsolationMethodPlugged,
    @JobSitePreparationSewerIsolationMethodSealedOrCovered,
    @JobSitePreparationSewerIsolationMethodNotApplicable,
    @JobSitePreparationPermitReceiverFieldOrEquipmentOrientation,
	@IsControlRoomContactedOrNot,--vibhor
	@ClonedFormDetailSarnia,
	@ClonedFormDetailDenver,
    @JobSitePreparationPermitReceiverFieldOrEquipmentOrientationNotApplicable,
    @JobSitePreparationVestedBuddySystemInEffect,
    @JobSitePreparationVestedBuddySystemInEffectNotApplicable,
    @JobSitePreparationSurroundingConditionsAffectOrContaminated,
    @JobSitePreparationSurroundingConditionsAffectOrContaminatedNotApplicable,
    @JobSitePreparationCriticalConditionRemainJobSite,
    @JobSitePreparationCriticalConditionRemainJobSiteNotApplicable,
    @JobSitePreparationWeldingGroundWireInTestArea,
    @JobSitePreparationWeldingGroundWireInTestAreaNotApplicable,
    @JobSitePreparationBondingOrGroundingRequired,
    @JobSitePreparationBondingOrGroundingRequiredNotApplicable,
    @JobSitePreparationFlowRequiredForJobNotApplicable,
    @JobSitePreparationFlowRequiredForJob,
	@ControlRoomContactedNotApplicable, --vibhor
    @EquipmentIsolationMethodOtherDescription,
    @EquipmentIsolationMethodLOTO,
    @EquipmentIsolationMethodMudderPlugs,
    @EquipmentIsolationMethodSeparation,
    @EquipmentIsolationMethodBlindedorBlanked,
    @EquipmentIsolationMethodBlockedIn,
    @EquipmentIsolationMethodCarBer,
    @EquipmentIsolationMethodNotApplicable,
    @EquipmentPreviousContentsOtherDescription,
    @EquipmentPreviousContentsH2S,
    @EquipmentPreviousContentsCaustic,
    @EquipmentPreviousContentsAcid,
    @EquipmentPreviousContentsHydrocarbon,
    @EquipmentPreviousContentsNotApplicable,
	@EquipmentAsbestosGasketsNotApplicable,
	@EquipmentAsbestosGaskets,
    @EquipmentConditionPurgedDescription,
    @EquipmentConditionPurged,
    @EquipmentConditionPurgedN2,
    @EquipmentConditionPurgedSteamed,
    @EquipmentConditionPurgedAir,
    @EquipmentConditionNeutralized,
    @EquipmentConditionH20Washed,
    @EquipmentConditionVentilated,
    @EquipmentConditionCleaned,
    @EquipmentConditionDrained,
    @EquipmentConditionDepressured,
    @EquipmentConditionNotApplicable,
    @EquipmentConditionOtherDescription,
    @EquipmentIsOutOfService,
    @EquipmentLeakingValves,
	@EquipmentConditionPurgedChecked, --vibhor
    @EquipmentLeakingValvesNotApplicable,    
    @EquipmentStillContainsResidual,
    @EquipmentStillContainsResidualNotApplicable,
    @EquipmentVentilationMethodForced,
    @EquipmentVentilationMethodLocalExhaust,
    @EquipmentVentilationMethodNaturalDraft,
    @EquipmentVentilationMethodNotApplicable,
    @ElectricTestBump,
    @ElectricTestBumpNotApplicable,
    @ElectricIsolationMethodWiring,
    @ElectricIsolationMethodLOTO,
    @ElectricIsolationMethodNotApplicable,
    @EquipmentIsHazardousEnergyIsolationRequiredNotApplicable,
    @EquipmentIsHazardousEnergyIsolationRequired,
    @EquipmentLockOutMethodId,
    @EquipmentLockOutMethodComments,
    @EquipmentEnergyIsolationPlanNumber,
    @EquipmentConditionsOfEIPSatisfied,
    @EquipmentConditionsOfEIPNotSatisfiedComments,
    @AsbestosHazardsConsideredNotApplicable,
    @AsbestosHazardsConsidered,
    @ToolsOtherToolsDescription,
    @ToolsWelder,
    @ToolsChemicals,
    @ToolsTorch,
    @ToolsPortLighting,
    @ToolsHotTapMachine,
    @ToolsTamper,
    @ToolsManlift,
    @ToolsHEPAVacuum,
    @ToolsForklift,
    @ToolsCompressor,
    @ToolsVehicle,
    @ToolsScaffolding,
    @ToolsLanda,
    @ToolsHeavyEquipment,
    @ToolsElectricTools,
    @ToolsCementSaw,
    @ToolsVacuumTruck,
    @ToolsJackhammer,
    @ToolsHandTools,
    @ToolsCraneOrCarrydeck,
    @ToolsAirTools,
    @CoAuthorizationDescription,
    @CoAuthorizationRequired,
    @CommunicationByOtherDescription,
    @CommunicationRadioColor,
    @CommunicationRadioChannelOrBand,
    @IsWorkPermitCommunicationNotApplicable,
    @CommunicationByRadio,
    @JobStepDescription,
    @CraftOrTradeOther,
    @CraftOrTradeID,
    @ContractorCompanyName,
    @ContactPersonnel,
    @AdditionalOtherFormsOrAssessmentsOrAuthorizations,
    @AdditionalMSDS,
    @AdditionalWaiverOrDeviation,
    @AdditionalWaiverOrDeviationDescription,
    @AdditionalBurnOrOpenFlameAssessment,
    @AdditionalBurnOrOpenFlameAssessmentDescription,
    @AdditionalElectrical,
    @AdditionalElectricalDescription,
    @AdditionalRoadClosure,
    @AdditionalAsbestosHandling,
    @AdditionalAsbestosHandlingDescription,
    @AdditionalPJSROrSafetyPause,
    @AdditionalBlankOrBlindLists,
    @AdditionalSpecialWasteDisposal,
    @AdditionalHotTap,
    @AdditionalExcavation,
    @AdditionalExcavationDescription,
    @AdditionalCriticalLift,
    @AdditionalCriticalLiftDescription,
    @AdditionalFlareEntry,
    @AdditionalCSEAssessmentOrAuthorization,
    @AdditionalCSEAssessmentOrAuthorizationDescription,
    @AdditionalRadiationApproval,
    @AdditionalOnlineLeakRepairForm,
	@AdditionalIsEnergizedElectricalForm,
	@AdditionalIsNotApplicable,

    @PermitRadiationSealed,
    @PermitRadiationRadiography,
    @PermitAsbestos,
    @PermitExcavation,
    @PermitElectricalWork,
    @PermitCriticalLift,
    @PermitSystemEntry,
    @PermitBurnOrOpenFlame,
	@PermitFreshAir, --vibhor
	@ControlRoomContacted, --vibhor
    @PermitHotTap,
    @PermitVehicleEntry,
    @PermitBreathingAirOrSCBA,
    @PermitConfinedSpaceEntry,
    @PermitInertConfinedSpaceEntry,
    @PermitLeadAbatement,

    @SpecialPrecautionsOrConsiderationsDescription,
    @WorkOrderDescription,
    @WorkPermitTypeClassificationId,
    @WorkPermitTypeId,
    @PermitValidDateTime,
    @EndDateTime,
    @StartDateTime,
	@StartTimeNotApplicable,
    @StartAndOrEndTimesFinalized,
    @WorkOrderNumber,
    @NewPermitNumber,
    @FunctionalLocationId,
    @WorkPermitStatusId,
    @EquipmentStillContainsResidualComments,
    @EquipmentInServiceComments,
    @EquipmentNoElectricalTestBumpComments,
    @EquipmentLeakingValvesComments,
    @JobSitePreparationFlowRequiredComments,
    @JobSitePreparationBondingGroundingNotRequiredComments,
    @JobSitePreparationWeldingGroundWireNotWithinGasTestAreaComments,
    @JobSitePreparationSurroundingConditionsAffectAreaComments,
	@EquipmentInAsbestosHazardPresentComments, --vibhor
	
    @JobSitePreparationCriticalConditionsComments,
    @JobSitePreparationPermitReceiverRequiresOrientationComments,
    @SapOperationId,

@PreExcavationAuthorization							,
@SuspendedWorkPlatform 								,
@HotTurnoverApproval 								,
@ConfinedSpaceEntryAuthorizationForm 				,
@PreExcavationAuthorizationForm 					,
@SupplementalJobSiteSignInForm 						,
@SystemEntryGasTestLogFrom 							,
@HeatStressMonitoringForm 							,
@CriticalLiftApprovalForm 							,
@PjsrSecondSection 									,
@DeviationRequestForm 								,
@RoadClosureform 									,
@RadiographyApprovalForm 							,
@ConfinedSpaceEntryTrackingLog 						,
@FlareLineChecklists 								,
@HotTurnoverApprovalForm 							,
@IndustrialHygieneAreaRealTimeSamplingForm 			,
@CraneSuspendedWorkPlatformChecklist 				,
@ConfinedSpaceEntryAuthorizationFormSecondSection 	,
@NASecondSection,


	@WorkAssignmentId
);
SET @Id= SCOPE_IDENTITY() 
SET @PermitNumber = @NewPermitNumber

GO

GRANT EXEC ON InsertWorkPermit TO PUBLIC
GO
