    
IF OBJECT_ID('InsertWorkPermitFortHills', 'P') IS NOT NULL
DROP PROC InsertWorkPermitFortHills
GO 
    
                    
CREATE Procedure [dbo].[InsertWorkPermitFortHills]                                      
(                                      
 @Id bigint Output,                                                     
 @PermitRequestId bigint = NULL,                  
 @WorkPermitStatusId int,                  
 @DataSourceId int,                                    
 @Company varchar(50) = NULL,                                      
 @Occupation varchar(50),                                                        
 @NumberOfWorkers int = NULL,                                      
 @WorkPermitTypeId int,                                    
 @FunctionalLocationId bigint,                                      
 @Location varchar(50),                    
 @RequestedStartDateTime datetime,                   
 @IssuedDateTime datetime = NULL,                   
 @ExpiredDateTime datetime,                  
 @PermitNumber bigint Output,                                     
 @WorkOrderNumber varchar(12) = NULL,                                      
 @OperationNumber varchar(max) = NULL,                                      
 @SubOperationNumber varchar(max) = NULL,                                      
 @TaskDescription varchar(8000) = NULL,                                      
 @HazardsAndOrRequirements varchar(2000) = NULL,                                        
 @CreatedDateTime datetime,                                      
 @CreatedByUserId bigint,                                                       
 @LastModifiedByUserId bigint,                                      
 @LastModifiedDateTime datetime,                  
 --@Deleted,                  
 @IssuedToSuncor bit,                                      
 @IssuedToCompany bit,                      
 @GroupId bigint,                   
 --@IssuedByUserId bigint,                                     
 @PermitRequestCreatedByUserId bigint = NULL,                                    
 @PriorityId int,         
 @PartGWorkSectionNotApplicable bit,          
 @PartFWorkSectionNotApplicable bit,          
 @PartEWorkSectionNotApplicable bit,          
 @PartDWorkSectionNotApplicable bit,          
 @PartCWorkSectionNotApplicable bit,                             
                                       
 @ClonedFormDetailFortHills varchar(100) = NULL,                      
                                  
@ShouldCreatePermitNumber bit,                  
                                                        
--@WorkPermitFortHillsId bigint ,                  
@EquipmentNo int ,                  
@Craft varchar,                  
@CrewSize int ,                  
@JobCoordinator varchar (25),                
@CoOrdContactNumber varchar (10),                  
@EmergencyAssemblyArea varchar (25),                  
@EmergencyMeetingPoint varchar (25),                  
@EmergencyContactNumber varchar (10),                  
@Locknumber varchar (10),                  
@IsolationNumber varchar (10),                  
@LockBoxnumberChecked bit,                  
@RevalidationDateTime datetime,                   
@ExtensionDateTime datetime,                  
                  
                  
--@SAPDescription varchar,                  
                  
@FlameResistantWorkWear bit,                  
@ChemicalSuit bit,                  
@FireWatch bit,                  
@FireBlanket bit,                  
@SuppliedBreathingAir bit,                  
@AirMover bit,                  
@PersonalFlotationDevice bit,                  
@HearingProtection bit,                  
@Other1 varchar (30),                  
@MonoGoggles bit,                  
@ConfinedSpaceMoniter bit,                  
@FireExtinguisher bit,                  
@SparkContainment bit,                  
@BottleWatch bit,                  
@StandbyPerson bit,                  
@WorkingAlone bit,                  
@SafetyGloves bit,                  
@Other2 varchar (30),                  
@FaceShield bit,                  
@FallProtection bit,                  
@ChargedFireHouse bit,                  
@CoveredSewer bit,          
@AirPurifyingRespirator bit,                  
@SingalPerson bit,                  
@CommunicationDevice bit,                  
@ReflectiveStrips bit,                  
@Other3 varchar (30),                  
                  
@ConfinedSpace bit,                  
@ConfinedSpaceClass varchar (25),                  
@GoundDisturbance bit,                  
@FireProtectionAuthorization bit,                  
@CriticalOrSeriousLifts bit ,                  
@VehicleEntry bit,                  
@IndustrialRadiography bit,                  
@ElectricalEncroachment bit,                  
@MSDS bit,                  
@OthersPartE varchar(30),                  
                  
@MechanicallyIsolated bit,                  
@BlindedOrBlanked bit,                  
@DoubleBlockedandBled bit,                  
@DrainedAndDepressurised bit,                  
@PurgedorNeutralised bit,                  
@ElectricallyIsolated bit,                  
@TestBumped bit,                  
@NuclearSource bit,                  
@ReceiverStafingRequirements bit,                  
--@SAPWorkCentre varchar,                  
--@DoNotMerge bit,                  
--@CompletionStatusId int,                  
--@LastImportedByUserId bigint,                  
--@LastImportedDateTime datetime,                  
--@LastSubmittedByUserId bigint,                  
--@LastSubmittedDateTime datetime,                  
--@IsModified bit,                 
@Frequency varchar(10) = NULL,  
@Continuous   BIT,  
@TesterName VARCHAR(50) = NULL,        
@Oxygen bit = NULL,        
@LEL bit = NULL,        
@H2SPPM bit = NULL,        
@CoPPM bit = NULL,        
@So2PPM bit = NULL,        
@Other1PartGValue VARCHAR(50) = NULL,        
@Other2PartGValue VARCHAR(50) = NULL,    
@PermitIssuer VARCHAR(50) = NULL,    
@AreaAuthority VARCHAR(50) = NULL,    
@CoAuthorizingIssuer VARCHAR(50) = NULL,    
@AddationalAuthority VARCHAR(50) = NULL,    
@PermitIssuerContact VARCHAR(10) = NULL,    
@AreaAuthorityContact VARCHAR(10) = NULL,    
@CoAuthorizingIssuerContact VARCHAR(10) = NULL,    
@AddationalAuthorityContact VARCHAR(10) = NULL,    
@IsFieldTourRequired bit,    
@FieldTourConductedBy VARCHAR(50) = NULL,            
        
@PermitAcceptor varchar(30) = NULL,                                    
@ShiftSupervisor varchar(30) = NULL                
)                                      
AS                                      
BEGIN                   
DECLARE @NewPermitNumber bigint                                      
IF @ShouldCreatePermitNumber = 1                                      
 BEGIN                                      
  EXEC @NewPermitNumber = GetNewSeqVal_WorkPermitFortHillsPermitNumberSequence                                      
 END                           
ELSE                                      
 BEGIN                                      
  SET @NewPermitNumber = NULL                                      
 END                                      
                                 
                                                          
INSERT INTO WorkPermitFortHills                                      
(                                                       
PermitRequestId,  WorkPermitStatusId, 
ClonedFormDetailFortHills,                 
DataSourceId,                  
Company,                  
Occupation,                  
NumberOfWorkers,                  
WorkPermitTypeId,                  
FunctionalLocationId,                  
Location,                  
RequestedStartDateTime,                  
IssuedDateTime,                  
ExpiredDateTime,                  
PermitNumber,                  
WorkOrderNumber,                  
OperationNumber,                  
SubOperationNumber,                  
TaskDescription,                  
HazardsAndOrRequirements,                  
CreatedDateTime,                  
CreatedByUserId,                  
LastModifiedByUserId,                  
LastModifiedDateTime,                  
Deleted,                  
IssuedToSuncor,                  
IssuedToCompany,                  
GroupId,                  
--IssuedByUserId,                  
PermitRequestCreatedByUserId,                  
PriorityId,              
LockBoxnumberChecked,          
PartCWorkSectionNotApplicable,          
PartDWorkSectionNotApplicable,          
PartEWorkSectionNotApplicable,        
PartFWorkSectionNotApplicable,        
PartGWorkSectionNotApplicable         
)                                      
VALUES                 
(                                                          
 @PermitRequestId,                               
 @WorkPermitStatusId,  
 @ClonedFormDetailFortHills  ,  
 @DataSourceId,                  
 @Company,                  
 @Occupation,                  
 @NumberOfWorkers,                  
 @WorkPermitTypeId,                  
 @FunctionalLocationId,                             
 @Location,                           
 @RequestedStartDateTime,                                 
 @IssuedDateTime,                  
 @ExpiredDateTime,                  
 @NewPermitNumber,                  
 @WorkOrderNumber,                  
 @OperationNumber,                  
 @SubOperationNumber,                  
 @TaskDescription,                  
 @HazardsAndOrRequirements,                  
 @CreatedDateTime,                  
 @CreatedByUserId,                  
 @LastModifiedByUserId,                  
 @LastModifiedDateTime,                  
 0,                  
 @IssuedToSuncor,                  
 @IssuedToCompany,                  
 @GroupId,                  
 --@IssuedByUserId,                  
 @PermitRequestCreatedByUserId,                  
 @PriorityId,              
 @LockBoxnumberChecked,          
 @PartCWorkSectionNotApplicable,          
 @PartDWorkSectionNotApplicable,          
 @PartEWorkSectionNotApplicable,        
 @PartFWorkSectionNotApplicable,        
 @PartGWorkSectionNotApplicable            
);                                      
                   
                                      
SET @Id = SCOPE_IDENTITY();                                       
SET @PermitNumber = @NewPermitNumber                                 
                  
                                                  
insert into WorkPermitFortHillsDetails                                      
(                                      
WorkPermitFortHillsId,                  
EquipmentNo,                  
Craft,                  
CrewSize,                  
JobCoordinator,                  
CoOrdContactNumber,                  
EmergencyAssemblyArea,                  
EmergencyMeetingPoint,                  
EmergencyContactNumber,                  
Locknumber,                  
IsolationNumber,                  
RevalidationDateTime,                  
ExtensionDateTime,                    
--SAPDescription,                  
FlameResistantWorkWear,                  
ChemicalSuit,                  
FireWatch,                  
FireBlanket,                  
SuppliedBreathingAir,                  
AirMover,                  
PersonalFlotationDevice,                  
HearingProtection,                  
Other1,                  
MonoGoggles,                  
ConfinedSpaceMoniter,                  
FireExtinguisher,                  
SparkContainment,                  
BottleWatch,                  
StandbyPerson,                  
WorkingAlone,                  
SafetyGloves,                  
Other2,                  
FaceShield,                  
FallProtection,                  
ChargedFireHouse,                  
CoveredSewer,                  
AirPurifyingRespirator,                  
SingalPerson,                  
CommunicationDevice,                  
ReflectiveStrips,                  
Other3,                  
ConfinedSpace,                  
ConfinedSpaceClass,                  
GoundDisturbance,                  
FireProtectionAuthorization,                  
CriticalOrSeriousLifts,                  
VehicleEntry,                  
IndustrialRadiography,                  
ElectricalEncroachment,                  
MSDS,                  
OthersPartE,                  
MechanicallyIsolated,                  
BlindedOrBlanked,     
DoubleBlockedandBled,                  
DrainedAndDepressurised,                  
PurgedorNeutralised,                  
ElectricallyIsolated,                  
TestBumped,                  
NuclearSource,                  
ReceiverStafingRequirements,                  
--SAPWorkCentre,                  
--DoNotMerge,                  
--CompletionStatusId,                  
--LastImportedByUserId,                  
--LastImportedDateTime,                  
--LastSubmittedByUserId,                  
--LastSubmittedDateTime,                  
--IsModified,         
Frequency,  
Continuous,        
TesterName,        
Oxygen,       
LEL,        
H2SPPM,        
CoPPM,        
So2PPM,        
Other1PartGValue,        
Other2PartGValue,       
PermitIssuer,    
AreaAuthority,    
COAuthorizingIssuer,    
AddationalAuthority,    
PermitIssuerContact,    
AreaAuthorityContact,    
COAuthorizingIssuerContact,    
AddationalAuthorityContact,    
IsFieldTourRequired,    
FieldTourConductedBy,            
PermitAcceptor,                                    
ShiftSupervisor                
 )                                      
values                                      
(                                      
@Id,                                       
@EquipmentNo,                  
@Craft,                  
@CrewSize,                  
@JobCoordinator,                  
@CoOrdContactNumber,                  
@EmergencyAssemblyArea,                  
@EmergencyMeetingPoint,                  
@EmergencyContactNumber,                  
@Locknumber,                  
@IsolationNumber,                  
@RevalidationDateTime,                   
@ExtensionDateTime,                  
@FlameResistantWorkWear,                  
@ChemicalSuit,                  
@FireWatch,                  
@FireBlanket,                  
@SuppliedBreathingAir,                  
@AirMover,                  
@PersonalFlotationDevice,                  
@HearingProtection,                  
@Other1,                  
@MonoGoggles,                  
@ConfinedSpaceMoniter,                  
@FireExtinguisher,                  
@SparkContainment,                  
@BottleWatch,                  
@StandbyPerson,                  
@WorkingAlone,                  
@SafetyGloves,                  
@Other2,                  
@FaceShield,                  
@FallProtection,                  
@ChargedFireHouse,                  
@CoveredSewer,                  
@AirPurifyingRespirator,                  
@SingalPerson,                  
@CommunicationDevice,                  
@ReflectiveStrips,                  
@Other3,                  
@ConfinedSpace,                  
@ConfinedSpaceClass,                  
@GoundDisturbance,                  
@FireProtectionAuthorization,                  
@CriticalOrSeriousLifts,                  
@VehicleEntry,                  
@IndustrialRadiography,                  
@ElectricalEncroachment,                  
@MSDS,                  
@OthersPartE,                  
@MechanicallyIsolated,                  
@BlindedOrBlanked,                  
@DoubleBlockedandBled,                  
@DrainedAndDepressurised,                  
@PurgedorNeutralised,                  
@ElectricallyIsolated,                  
@TestBumped,                  
@NuclearSource,                  
@ReceiverStafingRequirements,                  
--@SAPWorkCentre,                  
--@DoNotMerge,                  
--@CompletionStatusId,                  
--@LastImportedByUserId,                  
--@LastImportedDateTime,                  
--@LastSubmittedByUserId,                  
--@LastSubmittedDateTime,                  
--@IsModified,        
@Frequency,  
@Continuous,        
@TesterName,        
@Oxygen,        
@LEL,        
@H2SPPM,        
@CoPPM,        
@So2PPM,        
@Other1PartGValue,        
@Other2PartGValue,    
@PermitIssuer,    
@AreaAuthority,    
@CoAuthorizingIssuer,    
@AddationalAuthority,    
@PermitIssuerContact,    
@AreaAuthorityContact,    
@CoAuthorizingIssuerContact,    
@AddationalAuthorityContact,    
@IsFieldTourRequired,    
@FieldTourConductedBy,            
@PermitAcceptor,                
@ShiftSupervisor                
)                   
                  
END       
      
      

GRANT EXEC ON InsertWorkPermitFortHills TO PUBLIC 