if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertConfinedSpaceHistory]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertConfinedSpaceHistory]
GO

CREATE Procedure [dbo].[InsertConfinedSpaceHistory]
(
	@Id bigint,
	@ConfinedSpaceNumber bigint,
	@ConfinedSpaceStatus int,
	@StartDateTime datetime,
	@EndDateTime datetime,
	@FunctionalLocationId bigint,
	@LastModifiedDateTime datetime,
	@LastModifiedByUserId bigint,
	@H2S bit,
	@Hydrocarbure bit,
	@Ammoniaque bit,
	@Corrosif bit, 
	@CorrosifValue VARCHAR(50),
	@Aromatique bit, 
	@AromatiqueValue VARCHAR(50),
	@AutresSubstances bit, 
	@AutresSubstancesValue VARCHAR(50),
	@ObtureOuDebranche bit,
	@DepressuriseEtVidange bit,
	@EnPresenceDeGazInerte bit,
	@PurgeALaVapeur bit,
	@DessinsRequis bit, 
	@DessinsRequisValue VARCHAR(50),
	@PlanDeSauvetage bit,
	@CablesChauffantsMisHorsTension bit,
	@InterrupteursElectriquesVerrouilles bit,
	@PurgeParUnGazInerte bit,
	@RinceAlEau bit,
	@VentilationMecanique bit,
	@BouchesDegoutProtegees bit,
	@PossibiliteDeSulfureDeFer bit,
	@AereVentile bit,
	@AutreConditions bit, 
	@AutreConditionsValue VARCHAR(50),
	@VentilationNaturelle bit,
	@InstructionsSpeciales VARCHAR(450)
)
AS



INSERT INTO ConfinedSpaceHistory
(
	Id,
	ConfinedSpaceNumber,
	ConfinedSpaceStatus,
	StartDateTime,
	EndDateTime,
	FunctionalLocationId,
	H2S,
	Hydrocarbure,
	Ammoniaque,
	Corrosif, 
	CorrosifValue,
	Aromatique, 
	AromatiqueValue,
	AutresSubstances, 
	AutresSubstancesValue,
	ObtureOuDebranche,
	DepressuriseEtVidange,
	EnPresenceDeGazInerte,
	PurgeALaVapeur,
	DessinsRequis, 
	DessinsRequisValue,
	PlanDeSauvetage,
	CablesChauffantsMisHorsTension,
	InterrupteursElectriquesVerrouilles,
	PurgeParUnGazInerte,
	RinceAlEau,
	VentilationMecanique,
	BouchesDegoutProtegees,
	PossibiliteDeSulfureDeFer,
	AereVentile,
	AutreConditions, 
	AutreConditionsValue,
	VentilationNaturelle,
	InstructionsSpeciales,
	LastModifiedDateTime,
	LastModifiedByUserId
)
VALUES
(
	@Id,
	@ConfinedSpaceNumber,
	@ConfinedSpaceStatus,
	@StartDateTime,
	@EndDateTime,
	@FunctionalLocationId,
	@H2S,
	@Hydrocarbure,
	@Ammoniaque,
	@Corrosif, 
	@CorrosifValue,
	@Aromatique, 
	@AromatiqueValue,
	@AutresSubstances, 
	@AutresSubstancesValue,
	@ObtureOuDebranche,
	@DepressuriseEtVidange,
	@EnPresenceDeGazInerte,
	@PurgeALaVapeur,
	@DessinsRequis, 
	@DessinsRequisValue,
	@PlanDeSauvetage,
	@CablesChauffantsMisHorsTension,
	@InterrupteursElectriquesVerrouilles,
	@PurgeParUnGazInerte,
	@RinceAlEau,
	@VentilationMecanique,
	@BouchesDegoutProtegees,
	@PossibiliteDeSulfureDeFer,
	@AereVentile,
	@AutreConditions, 
	@AutreConditionsValue,
	@VentilationNaturelle,
	@InstructionsSpeciales,
	@LastModifiedDateTime,
	@LastModifiedByUserId
)
GO 