IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'INSERTUPDATEWORKPERMITSIGN')
	BEGIN
		DROP PROCEDURE [dbo].[INSERTUPDATEWORKPERMITSIGN]
	END
	
GO
CREATE Procedure [dbo].[INSERTUPDATEWORKPERMITSIGN]    
(    
 @WorkPermitId Varchar(100),
 @ISSUER_FNAME  Nvarchar(500),
 @ISSUER_LNAME   Nvarchar(500),
 @ISSUER_BADGENUMBER NVARCHAR(100),
 @ISSUER_BADGETYPE VARCHAR(100),
 @ISSUER_SOURCE   VARCHAR(100),
 @NEXT_LVL_ISSUER_FNAME  Nvarchar(500),
 @NEXT_LVL_ISSUER_LNAME  Nvarchar(500),
 @NEXT_LVL_ISSUER_BADGENYMBER NVARCHAR(100),
 @NEXT_LVL_ISSUER_BADGETYPE VARCHAR(100),
 @NEXT_LVL_ISSUER_SOURCE VARCHAR(100),
 @PERMIT_RECEIVER_FNAME  Nvarchar(500),
 @PERMIT_RECEIVER_LNAME  Nvarchar(500),
 @PERMIT_RECEIVER_BADGENYMBER NVARCHAR(100),
 @PERMIT_RECEIVER_BADGETYPE VARCHAR(100),
 @PERMIT_RECEIVER_SOURCE VARCHAR(100),
 @CROSS_ZONE_AUTHO_FNAME  Nvarchar(500),
 @CROSS_ZONE_AUTHO_LNAME  Nvarchar(500),
 @CROSS_ZONE_AUTHO_BADGENYMBER NVARCHAR(100),
 @CROSS_ZONE_AUTHO_BADGETYPE VARCHAR(100),
 @CROSS_ZONE_AUTHO_SOURCE VARCHAR(100),
 @IMMIDIATE_FNAME  Nvarchar(500),
 @IMMIDIATE_LNAME  Nvarchar(500),
 @IMMIDIATE_BADGENYMBER NVARCHAR(100),
 @IMMIDIATE_BADGETYPE VARCHAR(100),
 @IMMIDIATE_SOURCE VARCHAR(100),
 @CONFINED_FNAME  Nvarchar(500),
 @CONFINED_LNAME  Nvarchar(500),
 @CONFINED_BADGENYMBER NVARCHAR(100),
 @CONFINED_BADGETYPE VARCHAR(100),
 @CONFINED_SOURCE VARCHAR(500),
 @UpdatedBy INT,
 @CreatedBy INT,
 @CreatedDate Datetime,
 @UpdatedDate Datetime,
 @SiteId Int

 
     
)    
AS    
    
 if EXISTS(Select * from WORKPERMITSIGN WHERE WorkPermitId=@WorkPermitId) 
 BEGIN
 
 -----------START HISTORY--------------------------
 INSERT INTO WORKPERMITSIGN_HISTORY
 (
	 WorkPermitId ,
	 ISSUER_FNAME  ,
	 ISSUER_LNAME   ,
	 ISSUER_BADGENUMBER ,
	 ISSUER_BADGETYPE ,
	 ISSUER_SOURCE  ,
	 NEXT_LVL_ISSUER_FNAME  ,
	 NEXT_LVL_ISSUER_LNAME  ,
	 NEXT_LVL_ISSUER_BADGENUMBER,
	 NEXT_LVL_ISSUER_BADGETYPE ,
	 NEXT_LVL_ISSUER_SOURCE,
	 PERMIT_RECEIVER_FNAME,
	 PERMIT_RECEIVER_LNAME,
	 PERMIT_RECEIVER_BADGENUMBER , 
	 PERMIT_RECEIVER_BADGETYPE ,
	 PERMIT_RECEIVER_SOURCE ,
	 CROSS_ZONE_AUTHO_FNAME  ,
	 CROSS_ZONE_AUTHO_LNAME ,
	 CROSS_ZONE_AUTHO_BADGENUMBER,
	 CROSS_ZONE_AUTHO_BADGETYPE,
	 CROSS_ZONE_AUTHO_SOURCE ,
	 IMMIDIATE_FNAME ,
	 IMMIDIATE_LNAME ,
	 IMMIDIATE_BADGENUMBER,
	 IMMIDIATE_BADGETYPE,
	 IMMIDIATE_SOURCE,
	 CONFINED_FNAME,
	 CONFINED_LNAME,
	 CONFINED_BADGENUMBER,
	 CONFINED_BADGETYPE,
	 CONFINED_SOURCE,
	 Deleted ,
	 UpdatedBy ,
	 CreatedBy ,
	 CreatedDate ,
	 UpdatedDate ,
	 SiteId )
	 
	 SELECT
	  WorkPermitId ,
	 ISSUER_FNAME  ,
	 ISSUER_LNAME   ,
	 ISSUER_BADGENUMBER ,
	 ISSUER_BADGETYPE ,
	 ISSUER_SOURCE  ,
	 NEXT_LVL_ISSUER_FNAME  ,
	 NEXT_LVL_ISSUER_LNAME  ,
	 NEXT_LVL_ISSUER_BADGENUMBER,
	 NEXT_LVL_ISSUER_BADGETYPE ,
	 NEXT_LVL_ISSUER_SOURCE,
	 PERMIT_RECEIVER_FNAME,
	 PERMIT_RECEIVER_LNAME,
	 PERMIT_RECEIVER_BADGENUMBER , 
	 PERMIT_RECEIVER_BADGETYPE ,
	 PERMIT_RECEIVER_SOURCE ,
	 CROSS_ZONE_AUTHO_FNAME  ,
	 CROSS_ZONE_AUTHO_LNAME ,
	 CROSS_ZONE_AUTHO_BADGENUMBER,
	 CROSS_ZONE_AUTHO_BADGETYPE,
	 CROSS_ZONE_AUTHO_SOURCE ,
	 IMMIDIATE_FNAME ,
	 IMMIDIATE_LNAME ,
	 IMMIDIATE_BADGENUMBER,
	 IMMIDIATE_BADGETYPE,
	 IMMIDIATE_SOURCE,
	 CONFINED_FNAME,
	 CONFINED_LNAME,
	 CONFINED_BADGENUMBER,
	 CONFINED_BADGETYPE,
	 CONFINED_SOURCE,
	 Deleted ,
	 UpdatedBy ,
	 CreatedBy ,
	 CreatedDate ,
	 UpdatedDate ,
	 SiteId 
	 FROM WORKPERMITSIGN
	 WHERE WorkPermitId=@WorkPermitId
  
 ----------End HIstory-----------
 
 UPDATE WORKPERMITSIGN
 SET
 
  ISSUER_FNAME=@ISSUER_FNAME ,
  ISSUER_LNAME =@ISSUER_LNAME,
  ISSUER_BADGENUMBER=@ISSUER_BADGENUMBER,
  ISSUER_BADGETYPE=@ISSUER_BADGETYPE,
  ISSUER_SOURCE=@ISSUER_SOURCE ,
 
 NEXT_LVL_ISSUER_FNAME=@NEXT_LVL_ISSUER_FNAME,
 NEXT_LVL_ISSUER_LNAME=@NEXT_LVL_ISSUER_LNAME,
 NEXT_LVL_ISSUER_BADGENUMBER=@NEXT_LVL_ISSUER_BADGENYMBER,
 NEXT_LVL_ISSUER_BADGETYPE=@NEXT_LVL_ISSUER_BADGETYPE,
 NEXT_LVL_ISSUER_SOURCE=@NEXT_LVL_ISSUER_SOURCE,
 
 PERMIT_RECEIVER_FNAME=@PERMIT_RECEIVER_FNAME,
 PERMIT_RECEIVER_LNAME=@PERMIT_RECEIVER_LNAME,
 PERMIT_RECEIVER_BADGENUMBER=@PERMIT_RECEIVER_BADGENYMBER,
 PERMIT_RECEIVER_BADGETYPE= @PERMIT_RECEIVER_BADGETYPE,
 PERMIT_RECEIVER_SOURCE =@PERMIT_RECEIVER_SOURCE ,
 
 CROSS_ZONE_AUTHO_FNAME=@CROSS_ZONE_AUTHO_FNAME,
 CROSS_ZONE_AUTHO_LNAME=@CROSS_ZONE_AUTHO_LNAME,
 CROSS_ZONE_AUTHO_BADGENUMBER=@CROSS_ZONE_AUTHO_BADGENYMBER,
 CROSS_ZONE_AUTHO_BADGETYPE=@CROSS_ZONE_AUTHO_BADGETYPE,
 CROSS_ZONE_AUTHO_SOURCE=@CROSS_ZONE_AUTHO_SOURCE,
 
 IMMIDIATE_FNAME= @IMMIDIATE_FNAME ,
 IMMIDIATE_LNAME=@IMMIDIATE_LNAME,
 IMMIDIATE_BADGENUMBER=@IMMIDIATE_BADGENYMBER,
 IMMIDIATE_BADGETYPE= @IMMIDIATE_BADGETYPE,
 IMMIDIATE_SOURCE=@IMMIDIATE_SOURCE,
 
 CONFINED_FNAME= @CONFINED_FNAME,
 CONFINED_LNAME=@CONFINED_LNAME,
 CONFINED_BADGENUMBER=@CONFINED_BADGENYMBER,
 CONFINED_BADGETYPE=@CONFINED_BADGETYPE,
 CONFINED_SOURCE=@CONFINED_SOURCE,
 
 UpdatedBy=@UpdatedBy,
 CreatedBy=@CreatedBy,
 CreatedDate=@CreatedDate,
 UpdatedDate=@UpdatedDate,
 SiteId=@SiteId
 WHERE WorkPermitId=@WorkPermitId 
 
 END
 ELSE
 BEGIN
 INSERT WORKPERMITSIGN
 (
  WorkPermitId,
  
  ISSUER_FNAME ,
  ISSUER_LNAME ,
  ISSUER_BADGENUMBER,
  ISSUER_BADGETYPE ,
  ISSUER_SOURCE ,
  
  
 NEXT_LVL_ISSUER_FNAME,
 NEXT_LVL_ISSUER_LNAME,
 NEXT_LVL_ISSUER_BADGENUMBER,
 NEXT_LVL_ISSUER_BADGETYPE,
 NEXT_LVL_ISSUER_SOURCE ,
 
 PERMIT_RECEIVER_FNAME,
 PERMIT_RECEIVER_LNAME,
 PERMIT_RECEIVER_BADGENUMBER,
 PERMIT_RECEIVER_BADGETYPE,
 PERMIT_RECEIVER_SOURCE ,
 
 CROSS_ZONE_AUTHO_FNAME,
 CROSS_ZONE_AUTHO_LNAME,
 CROSS_ZONE_AUTHO_BADGENUMBER,
 CROSS_ZONE_AUTHO_BADGETYPE,
 CROSS_ZONE_AUTHO_SOURCE,
 
 IMMIDIATE_FNAME ,
 IMMIDIATE_LNAME,
 IMMIDIATE_BADGENUMBER,
 IMMIDIATE_BADGETYPE,
 IMMIDIATE_SOURCE,
 
 CONFINED_FNAME,
 CONFINED_LNAME,
 CONFINED_BADGENUMBER,
 CONFINED_BADGETYPE,
 CONFINED_SOURCE,
 
 UpdatedBy,
 CreatedBy,
 CreatedDate,
 UpdatedDate,
 SiteId)
 
 Values
 (
  @WorkPermitId,
  @ISSUER_FNAME ,
 @ISSUER_LNAME ,
 @ISSUER_BADGENUMBER,
 @ISSUER_BADGETYPE ,
 @ISSUER_SOURCE ,
 
 @NEXT_LVL_ISSUER_FNAME,
 @NEXT_LVL_ISSUER_LNAME,
 @NEXT_LVL_ISSUER_BADGENYMBER,
 @NEXT_LVL_ISSUER_BADGETYPE,
 @NEXT_LVL_ISSUER_SOURCE ,
 
 @PERMIT_RECEIVER_FNAME,
 @PERMIT_RECEIVER_LNAME,
 @PERMIT_RECEIVER_BADGENYMBER,
 @PERMIT_RECEIVER_BADGETYPE,
 @PERMIT_RECEIVER_SOURCE ,
 
 @CROSS_ZONE_AUTHO_FNAME,
 @CROSS_ZONE_AUTHO_LNAME,
 @CROSS_ZONE_AUTHO_BADGENYMBER,
 @CROSS_ZONE_AUTHO_BADGETYPE,
 @CROSS_ZONE_AUTHO_SOURCE,
 
 @IMMIDIATE_FNAME ,
 @IMMIDIATE_LNAME,
 @IMMIDIATE_BADGENYMBER,
 @IMMIDIATE_BADGETYPE,
 @IMMIDIATE_SOURCE,
 
 @CONFINED_FNAME,
 @CONFINED_LNAME,
 @CONFINED_BADGENYMBER,
 @CONFINED_BADGETYPE,
 @CONFINED_SOURCE,
 
 
 @UpdatedBy,
 @CreatedBy,
 @CreatedDate,
 @UpdatedDate,
 @SiteId
 )
 END  

    
GRANT EXEC ON [INSERTUPDATEWORKPERMITSIGN] TO PUBLIC       