 
  
IF OBJECT_ID('InsertWorkPermitFortHillsHistory', 'P') IS NOT NULL
DROP PROC InsertWorkPermitFortHillsHistory
GO 

      
CREATE Procedure [dbo].InsertWorkPermitFortHillsHistory                
(                
@Id  bigint,    
--@PermitRequestId  bigint,    
@WorkPermitStatusId  int,    
@DataSourceId  int,    
@Company  varchar(50),    
@Occupation  varchar(50),    
@NumberOfWorkers  int,    
@WorkPermitTypeId  int,    
@FunctionalLocation  varchar(50),    
@Location  varchar(50),    
@RequestedStartDateTime  datetime,    
@IssuedDateTime  datetime,    
@ExpiredDateTime  datetime,    
@PermitNumber  bigint,    
@WorkOrderNumber  varchar(25),    
@OperationNumber  varchar,    
@SubOperationNumber  varchar,    
@TaskDescription  varchar,    
@HazardsAndOrRequirements  varchar(2000),    
--@CreatedDateTime  datetime,    
--@CreatedByUserId  bigint,    
@LastModifiedByUserId  bigint,    
@LastModifiedDateTime  datetime,    
--@Deleted  bit,    
@IssuedToSuncor  bit,    
@IssuedToCompany  bit,    
@Group  varchar(50),    
--@IssuedByUserId  bigint,    
--@PermitRequestCreatedByUserId  bigint,    
@PriorityId  int,    
--@WorkPermitFortHillsId  bigint,    
@EquipmentNo  int,    
@Craft  varchar(25),    
@CrewSize  int,    
@JobCoordinator  varchar(25),    
@CoOrdContactNumber  varchar(10),    
@EmergencyAssemblyArea  varchar(25),    
@EmergencyMeetingPoint  varchar(25),    
@EmergencyContactNumber  varchar(10),    
@Locknumber  varchar(10),    
@IsolationNumber  varchar(10),    
@RevalidationDateTime  datetime,    
@ExtensionDateTime  datetime,    
--@SAPDescription  varchar(MAX),    
@FlameResistantWorkWear  bit,    
@ChemicalSuit  bit,    
@FireWatch  bit,    
@FireBlanket  bit,    
@SuppliedBreathingAir  bit,    
@AirMover  bit,    
@PersonalFlotationDevice  bit,    
@HearingProtection  bit,    
@Other1  varchar(30),    
@MonoGoggles  bit,    
@ConfinedSpaceMoniter  bit,    
@FireExtinguisher  bit,    
@SparkContainment  bit,    
@BottleWatch  bit,    
@StandbyPerson  bit,    
@WorkingAlone  bit,    
@SafetyGloves  bit,    
@Other2  varchar(30),    
@FaceShield  bit,    
@FallProtection  bit,    
@ChargedFireHouse  bit,    
@CoveredSewer  bit,    
@AirPurifyingRespirator  bit,    
@SingalPerson  bit,    
@CommunicationDevice  bit,    
@ReflectiveStrips  bit,    
@Other3  varchar(30),    
@ConfinedSpace  bit,    
@ConfinedSpaceClass  varchar(25),    
@GoundDisturbance  bit,    
@FireProtectionAuthorization  bit,    
@CriticalOrSeriousLifts  bit,    
@VehicleEntry  bit,    
@IndustrialRadiography  bit,    
@ElectricalEncroachment  bit,    
@MSDS  bit,    
@OthersPartE  varchar(30),    
@MechanicallyIsolated  bit,    
@BlindedOrBlanked  bit,    
@DoubleBlockedandBled  bit,    
@DrainedAndDepressurised  bit,    
@PurgedorNeutralised  bit,    
@ElectricallyIsolated  bit,    
@TestBumped  bit,    
@NuclearSource  bit,    
@ReceiverStafingRequirements  bit,    
@PermitAcceptor  varchar(30),    
@ShiftSupervisor  varchar(30)              
)                
AS                
                    
INSERT INTO WorkPermitFortHillsHistory                
(                
Id,    
--PermitRequestId,    
WorkPermitStatusId,    
DataSourceId,    
Company,    
Occupation,    
NumberOfWorkers,    
WorkPermitTypeId,    
FunctionalLocation,    
Location,    
RequestedStartDateTime,    
IssuedDateTime,    
ExpiredDateTime,    
PermitNumber,    
WorkOrderNumber,    
OperationNumber,    
SubOperationNumber,    
TaskDescription,    
HazardsAndOrRequirements,    
--CreatedDateTime,    
--CreatedByUserId,    
LastModifiedByUserId,    
LastModifiedDateTime,    
--Deleted,    
IssuedToSuncor,    
IssuedToCompany,    
[Group],    
--IssuedByUserId,    
--PermitRequestCreatedByUserId,    
PriorityId,    
--WorkPermitFortHillsId,    
EquipmentNo,    
Craft,    
CrewSize,    
JobCoordinator,    
CoOrdContactNumber,    
EmergencyAssemblyArea,    
EmergencyMeetingPoint,    
EmergencyContactNumber,    
Locknumber,    
IsolationNumber,    
RevalidationDateTime,    
ExtensionDateTime,    
--SAPDescription,    
FlameResistantWorkWear,    
ChemicalSuit,    
FireWatch,    
FireBlanket,    
SuppliedBreathingAir,    
AirMover,    
PersonalFlotationDevice,    
HearingProtection,    
Other1,    
MonoGoggles,    
ConfinedSpaceMoniter,    
FireExtinguisher,    
SparkContainment,    
BottleWatch,    
StandbyPerson,    
WorkingAlone,    
SafetyGloves,    
Other2,    
FaceShield,    
FallProtection,    
ChargedFireHouse,    
CoveredSewer,    
AirPurifyingRespirator,    
SingalPerson,    
CommunicationDevice,    
ReflectiveStrips,    
Other3,    
ConfinedSpace,    
ConfinedSpaceClass,    
GoundDisturbance,    
FireProtectionAuthorization,    
CriticalOrSeriousLifts,    
VehicleEntry,    
IndustrialRadiography,    
ElectricalEncroachment,    
MSDS,    
OthersPartE,    
MechanicallyIsolated,    
BlindedOrBlanked,    
DoubleBlockedandBled,    
DrainedAndDepressurised,    
PurgedorNeutralised,    
ElectricallyIsolated,    
TestBumped,    
NuclearSource,    
ReceiverStafingRequirements,    
PermitAcceptor,    
ShiftSupervisor    
                
)                
VALUES                
(                
 @Id,    
--@PermitRequestId,    
@WorkPermitStatusId,    
@DataSourceId,    
@Company,    
@Occupation,    
@NumberOfWorkers,    
@WorkPermitTypeId,    
@FunctionalLocation,    
@Location,    
@RequestedStartDateTime,    
@IssuedDateTime,    
@ExpiredDateTime,    
@PermitNumber,    
@WorkOrderNumber,    
@OperationNumber,    
@SubOperationNumber,    
@TaskDescription,    
@HazardsAndOrRequirements,    
--@CreatedDateTime,    
--@CreatedByUserId,    
@LastModifiedByUserId,    
@LastModifiedDateTime,    
--@Deleted,    
@IssuedToSuncor,    
@IssuedToCompany,    
@Group,    
--@IssuedByUserId,    
--@PermitRequestCreatedByUserId,    
@PriorityId,    
--@WorkPermitFortHillsId,    
@EquipmentNo,    
@Craft,    
@CrewSize,    
@JobCoordinator,    
@CoOrdContactNumber,    
@EmergencyAssemblyArea,    
@EmergencyMeetingPoint,    
@EmergencyContactNumber,    
@Locknumber,    
@IsolationNumber,    
@RevalidationDateTime,    
@ExtensionDateTime,    
--@SAPDescription,    
@FlameResistantWorkWear,    
@ChemicalSuit,    
@FireWatch,    
@FireBlanket,    
@SuppliedBreathingAir,    
@AirMover,    
@PersonalFlotationDevice,    
@HearingProtection,    
@Other1,    
@MonoGoggles,    
@ConfinedSpaceMoniter,    
@FireExtinguisher,    
@SparkContainment,    
@BottleWatch,    
@StandbyPerson,    
@WorkingAlone,    
@SafetyGloves,    
@Other2,    
@FaceShield,    
@FallProtection,    
@ChargedFireHouse,    
@CoveredSewer,    
@AirPurifyingRespirator,    
@SingalPerson,    
@CommunicationDevice,    
@ReflectiveStrips,    
@Other3,    
@ConfinedSpace,    
@ConfinedSpaceClass,    
@GoundDisturbance,    
@FireProtectionAuthorization,    
@CriticalOrSeriousLifts,    
@VehicleEntry,    
@IndustrialRadiography,    
@ElectricalEncroachment,    
@MSDS,    
@OthersPartE,    
@MechanicallyIsolated,    
@BlindedOrBlanked,    
@DoubleBlockedandBled,    
@DrainedAndDepressurised,    
@PurgedorNeutralised,    
@ElectricallyIsolated,    
@TestBumped,    
@NuclearSource,    
@ReceiverStafingRequirements,    
@PermitAcceptor,    
@ShiftSupervisor    
) 

GRANT EXEC ON InsertWorkPermitFortHillsHistory TO PUBLIC  