if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermitEdmontonHistory]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[InsertWorkPermitEdmontonHistory]

GO

CREATE Procedure [dbo].[InsertWorkPermitEdmontonHistory]          
(          
 @Id bigint,          
 @PermitNumber bigint = NULL,          
           
 @WorkPermitStatusId int,           
 @DataSourceId int,          
 @PriorityId int,          
 @IssuedToSuncor bit,          
 @IssuedToCompany bit,          
 @Company varchar(50) = NULL,          
 @Occupation varchar(50),          
 @Group varchar(50),          
 @NumberOfWorkers int = NULL,          
 @WorkPermitTypeId int,          
 @DurationPermit bit,          
 @FunctionalLocation varchar(200),          
 @Location varchar(50),          
 @AreaLabel varchar(40) = NULL,          
 @DocumentLinks varchar(max) = NULL,          
           
 @RequestedStartDateTime datetime,          
 @IssuedDateTime datetime = NULL,          
 @ExpiredDateTime datetime,          
 @WorkOrderNumber varchar(12) = NULL,          
 @OperationNumber varchar(max) = NULL,          
 @SubOperationNumber varchar(max) = NULL,          
 @TaskDescription varchar(8000) = NULL,          
 @HazardsAndOrRequirements varchar(2000) = NULL,            
 @LastModifiedByUserId bigint,          
 @LastModifiedDateTime datetime,           
            
 @AlkylationEntry bit,          
 @AlkylationEntryClassOfClothing varchar(25) = NULL,          
 @FlarePitEntry bit,          
 @FlarePitEntryType varchar(25) = NULL,          
 @ConfinedSpace bit,          
 @ConfinedSpaceCardNumber varchar(10) = NULL,          
 @ConfinedSpaceClass varchar(25) = NULL,          
 @RescuePlan bit,          
 @RescuePlanFormNumber varchar(10) = NULL,          
 @VehicleEntry bit,          
 @VehicleEntryTotal int = NULL,          
 @VehicleEntryType varchar(30) = NULL,           
 @SpecialWork bit,          
 @SpecialWorkFormNumber varchar(10) = NULL,          
 @SpecialWorkType varchar(100) = NULL,          
 @GN59 bit,          
 @FormGN59Id bigint = NULL,            
 @GN7 bit,          
 @FormGN7Id bigint = NULL,          
 @GN24 bit,          
 @FormGN24Id bigint = NULL,          
 @GN6 bit,          
 @FormGN6Id bigint = NULL,          
 @GN75A bit,          
 @FormGN75AId bigint = NULL,          
 @GN1 bit,          
 @FormGN1TradeChecklistDisplayNumber varchar(32) = NULL,          
 @GN27 varchar(50),          
 @GN11 varchar(50),          
 @GN75_Deprecated varchar(50),          
 @GN24_Deprecated varchar(50),          
 @GN6_Deprecated varchar(50),          
           
    @OtherAreasAndOrUnitsAffected bit,          
    @OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,          
 @OtherAreasAndOrUnitsAffectedPersonNotified varchar(30) = NULL,          
          
 @StatusOfPipingEquipmentSectionNotApplicableToJob bit,          
 @ProductNormallyInPipingEquipment varchar(50) = NULL,          
 @IsolationValvesLocked varchar(10),          
 @DepressuredDrained varchar(10),          
 @Ventilated varchar(10),          
 @Purged varchar(10),          
 @BlindedAndTagged varchar(10),          
 @DoubleBlockAndBleed varchar(10),          
 @ElectricalLockout varchar(10),          
 @MechanicalLockout varchar(10),          
 @BlindSchematicAvailable varchar(10),          
           
 @ZeroEnergyFormNumber varchar(10) = NULL,          
 @LockBoxNumber varchar(10) = NULL,          
 @JobsiteEquipmentInspected bit,          
 @ConfinedSpaceWorkSectionNotApplicableToJob bit,           
 @QuestionOneResponse varchar(10),          
 @QuestionTwoResponse varchar(10),          
 @QuestionTwoAResponse varchar(10),          
 @QuestionTwoBResponse varchar(10),          
 @QuestionThreeResponse varchar(10),          
 @QuestionFourResponse varchar(10),          
           
 @GasTestsSectionNotApplicableToJob bit,          
 @WorkerToProvideGasTestData bit,          
 @OperatorGasDetectorNumber varchar(50) = NULL,          
 @GasTestDataLine1CombustibleGas varchar(30) = NULL,          
 @GasTestDataLine1Oxygen varchar(10) = NULL,          
 @GasTestDataLine1ToxicGas varchar(30) = NULL,          
 @GasTestDataLine1Time datetime = NULL,          
 @GasTestDataLine2CombustibleGas varchar(30) = NULL,          
 @GasTestDataLine2Oxygen varchar(10) = NULL,          
 @GasTestDataLine2ToxicGas varchar(30) = NULL,          
 @GasTestDataLine2Time datetime = NULL,          
 @GasTestDataLine3CombustibleGas varchar(30) = NULL,          
@GasTestDataLine3Oxygen varchar(10) = NULL,          
 @GasTestDataLine3ToxicGas varchar(30) = NULL,          
 @GasTestDataLine3Time datetime = NULL,          
 @GasTestDataLine4CombustibleGas varchar(30) = NULL,          
 @GasTestDataLine4Oxygen varchar(10) = NULL,          
 @GasTestDataLine4ToxicGas varchar(30) = NULL,          
 @GasTestDataLine4Time datetime = NULL,          
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob bit,          
           
 @FaceShield bit,          
 @Goggles bit,          
 @RubberBoots bit,          
 @RubberGloves bit,           
 @RubberSuit bit,          
           
 @SafetyHarnessLifeline bit,          
 @HighVoltagePPE bit,          
 @Other1Checked bit,          
 @Other1 varchar(15) = NULL,          
 @EquipmentGrounded bit,          
           
 @FireBlanket bit,          
 @FireExtinguisher bit,          
 @FireMonitorManned bit,          
 @FireWatch bit,          
 @SewersDrainsCovered bit,          
           
 @SteamHose bit,          
 @Other2Checked bit,          
 @Other2 varchar(15) = NULL,          
 @AirPurifyingRespirator bit,          
 @BreathingAirApparatus bit,          
           
 @DustMask bit,          
 @LifeSupportSystem bit,          
 @SafetyWatch bit,          
 @ContinuousGasMonitor bit,          
 @WorkersMonitor bit,          
 @WorkersMonitorNumber varchar(10) = NULL,          
           
 @BumpTestMonitorPriorToUse bit,          
 @Other3Checked bit,          
 @Other3 varchar(15) = NULL,          
 @AirMover bit,          
 @BarriersSigns bit,          
           
 @RadioChannel bit,          
 @RadioChannelNumber varchar(10) = NULL,          
 @AirHorn bit,          
 @MechVentilationComfortOnly bit,          
 @AsbestosMMCPrecautions bit,          
 @Other4Checked bit,          
 @Other4 varchar(15) = NULL,          
           
 @UseCurrentPermitNumberForZeroEnergyFormNumber bit,          
 @PermitAcceptor varchar(30) = NULL,          
 @ShiftSupervisor varchar(30) = NULL ,    
     
 @RoadAccessOnPermit bit ,      
 @RoadAccessOnPermitFormNumber varchar(10) = NULL,      
 @RoadAccessOnPermitType varchar(50) = NULL,  
   
 @SpecialWorkName VARCHAR(100)           
)          
AS          
  
  
if(@SpecialWorkType Is Null)  
Begin   
 SET @SpecialWorkType = @SpecialWorkName  
End  
  
          
INSERT INTO WorkPermitEdmontonHistory          
(          
    Id,          
 PermitNumber,          
 WorkPermitStatusId,          
 DataSourceId,          
 PriorityId,          
 IssuedToSuncor,          
 IssuedToCompany,          
 Company,          
 Occupation,          
 [Group],          
 NumberOfWorkers,          
 WorkPermitTypeId,          
 DurationPermit,          
 FunctionalLocation,          
 Location,          
 AreaLabel,          
 RequestedStartDateTime,          
 IssuedDateTime,          
 ExpiredDateTime,          
 WorkOrderNumber,          
 OperationNumber,          
 SubOperationNumber,          
 TaskDescription,          
 HazardsAndOrRequirements,             
 LastModifiedByUserId,          
 LastModifiedDateTime,          
 DocumentLinks,          
           
 AlkylationEntry,          
 AlkylationEntryClassOfClothing,          
 FlarePitEntry,          
 FlarePitEntryType,          
 ConfinedSpace,          
 ConfinedSpaceCardNumber,          
 ConfinedSpaceClass,          
 RescuePlan,          
 RescuePlanFormNumber,          
 VehicleEntry,          
 VehicleEntryTotal,          
 VehicleEntryType,           
 SpecialWork,          
 SpecialWorkFormNumber,          
 SpecialWorkType,           
 GN59,          
 FormGN59Id,           
 GN7,          
 FormGN7Id,          
 GN24,          
 FormGN24Id,          
    GN6,          
 FormGN6Id,          
    GN75A,          
 FormGN75AId,          
 GN1,          
 FormGN1TradeChecklistDisplayNumber,           
 GN27,          
 GN11,          
 GN75_Deprecated,          
 GN24_Deprecated,          
 GN6_Deprecated,          
          
 OtherAreasAndOrUnitsAffected,          
 OtherAreasAndOrUnitsAffectedArea,          
 OtherAreasAndOrUnitsAffectedPersonNotified,          
           
 StatusOfPipingEquipmentSectionNotApplicableToJob,          
 ProductNormallyInPipingEquipment,          
 IsolationValvesLocked,          
 DepressuredDrained,          
 Ventilated,          
 Purged,          
 BlindedAndTagged,          
 DoubleBlockAndBleed,          
 ElectricalLockout,          
 MechanicalLockout,          
 BlindSchematicAvailable,          
 ZeroEnergyFormNumber,          
 LockBoxNumber,          
 JobsiteEquipmentInspected,          
 ConfinedSpaceWorkSectionNotApplicableToJob,          
 QuestionOneResponse,          
 QuestionTwoResponse,          
 QuestionTwoAResponse,          
 QuestionTwoBResponse,          
 QuestionThreeResponse,          
 QuestionFourResponse,          
 GasTestsSectionNotApplicableToJob,          
 WorkerToProvideGasTestData,          
 OperatorGasDetectorNumber,          
 GasTestDataLine1CombustibleGas,          
 GasTestDataLine1Oxygen,          
 GasTestDataLine1ToxicGas,          
 GasTestDataLine1Time,          
 GasTestDataLine2CombustibleGas,          
 GasTestDataLine2Oxygen,          
 GasTestDataLine2ToxicGas,          
 GasTestDataLine2Time,          
 GasTestDataLine3CombustibleGas,          
 GasTestDataLine3Oxygen,          
 GasTestDataLine3ToxicGas,          
 GasTestDataLine3Time,          
 GasTestDataLine4CombustibleGas,          
 GasTestDataLine4Oxygen,          
 GasTestDataLine4ToxicGas,          
 GasTestDataLine4Time,          
 WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,          
 FaceShield,          
 Goggles,          
 RubberBoots,          
 RubberGloves,          
 RubberSuit,          
 SafetyHarnessLifeline,          
 HighVoltagePPE,          
 Other1Checked,          
 Other1,          
 EquipmentGrounded,          
 FireBlanket,          
 FireExtinguisher,          
 FireMonitorManned,          
 FireWatch,          
 SewersDrainsCovered,          
 SteamHose,          
 Other2Checked,          
 Other2,          
 AirPurifyingRespirator,          
 BreathingAirApparatus,          
 DustMask,          
 LifeSupportSystem,          
 SafetyWatch,          
 ContinuousGasMonitor,          
 WorkersMonitor,          
 WorkersMonitorNumber,          
 BumpTestMonitorPriorToUse,          
 Other3Checked,          
 Other3,          
 AirMover,          
 BarriersSigns,          
 RadioChannel,          
 RadioChannelNumber,          
 AirHorn,          
 MechVentilationComfortOnly,          
 AsbestosMMCPrecautions,          
 Other4Checked,          
 Other4,          
           
 UseCurrentPermitNumberForZeroEnergyFormNumber,          
 PermitAcceptor,          
 ShiftSupervisor,    
     
 RoadAccessOnPermit1 ,      
 RoadAccessOnPermitFormNumber1,      
 RoadAccessOnPermitType1           
)          
VALUES          
(          
@Id,          
 @PermitNumber,          
 @WorkPermitStatusId,          
 @DataSourceId,          
 @PriorityId,          
 @IssuedToSuncor,          
 @IssuedToCompany,          
 @Company,          
 @Occupation,          
 @Group,          
 @NumberOfWorkers,          
 @WorkPermitTypeId,          
 @DurationPermit,          
 @FunctionalLocation,          
 @Location,          
 @AreaLabel,          
 @RequestedStartDateTime,          
 @IssuedDateTime,          
 @ExpiredDateTime,          
 @WorkOrderNumber,          
 @OperationNumber,          
 @SubOperationNumber,          
 @TaskDescription,          
 @HazardsAndOrRequirements,          
 @LastModifiedByUserId,          
 @LastModifiedDateTime,          
 @DocumentLinks,          
           
 @AlkylationEntry,          
 @AlkylationEntryClassOfClothing,          
 @FlarePitEntry,          
 @FlarePitEntryType,          
 @ConfinedSpace,          
 @ConfinedSpaceCardNumber,          
 @ConfinedSpaceClass,          
 @RescuePlan,          
 @RescuePlanFormNumber,           
 @VehicleEntry,          
 @VehicleEntryTotal,          
 @VehicleEntryType,           
 @SpecialWork,          
 @SpecialWorkFormNumber,          
 @SpecialWorkType,           
 @GN59,          
 @FormGN59Id,           
 @GN7,          
 @FormGN7Id,          
 @GN24,          
 @FormGN24Id,          
 @GN6,          
 @FormGN6Id,          
 @GN75A,          
 @FormGN75AId,          
 @GN1,          
 @FormGN1TradeChecklistDisplayNumber,          
 @GN27,          
 @GN11,          
 @GN75_Deprecated,          
 @GN24_Deprecated,          
 @GN6_Deprecated,          
 @OtherAreasAndOrUnitsAffected,          
 @OtherAreasAndOrUnitsAffectedArea,          
 @OtherAreasAndOrUnitsAffectedPersonNotified,          
 @StatusOfPipingEquipmentSectionNotApplicableToJob,          
 @ProductNormallyInPipingEquipment,          
 @IsolationValvesLocked,          
 @DepressuredDrained,          
 @Ventilated,          
 @Purged,          
 @BlindedAndTagged,          
 @DoubleBlockAndBleed,          
 @ElectricalLockout,          
 @MechanicalLockout,          
 @BlindSchematicAvailable,          
 @ZeroEnergyFormNumber,          
 @LockBoxNumber,          
 @JobsiteEquipmentInspected,          
 @ConfinedSpaceWorkSectionNotApplicableToJob,          
 @QuestionOneResponse,          
 @QuestionTwoResponse,          
 @QuestionTwoAResponse,          
 @QuestionTwoBResponse,          
 @QuestionThreeResponse,          
 @QuestionFourResponse,          
 @GasTestsSectionNotApplicableToJob,          
 @WorkerToProvideGasTestData,          
 @OperatorGasDetectorNumber,          
 @GasTestDataLine1CombustibleGas,          
 @GasTestDataLine1Oxygen,          
 @GasTestDataLine1ToxicGas,          
 @GasTestDataLine1Time,          
 @GasTestDataLine2CombustibleGas,          
 @GasTestDataLine2Oxygen,          
 @GasTestDataLine2ToxicGas,          
 @GasTestDataLine2Time,          
 @GasTestDataLine3CombustibleGas,          
 @GasTestDataLine3Oxygen,          
 @GasTestDataLine3ToxicGas,          
 @GasTestDataLine3Time,          
 @GasTestDataLine4CombustibleGas,          
 @GasTestDataLine4Oxygen,          
 @GasTestDataLine4ToxicGas,          
 @GasTestDataLine4Time,          
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,          
 @FaceShield,          
 @Goggles,          
 @RubberBoots,          
 @RubberGloves,          
 @RubberSuit,          
 @SafetyHarnessLifeline,          
 @HighVoltagePPE,          
 @Other1Checked,          
 @Other1,          
 @EquipmentGrounded,          
 @FireBlanket,          
 @FireExtinguisher,          
 @FireMonitorManned,          
 @FireWatch,          
 @SewersDrainsCovered,          
 @SteamHose,          
 @Other2Checked,          
 @Other2,          
 @AirPurifyingRespirator,          
 @BreathingAirApparatus,          
 @DustMask,          
 @LifeSupportSystem,          
 @SafetyWatch,          
 @ContinuousGasMonitor,          
 @WorkersMonitor,          
 @WorkersMonitorNumber,          
 @BumpTestMonitorPriorToUse,          
 @Other3Checked,          
 @Other3,          
 @AirMover,          
 @BarriersSigns,          
 @RadioChannel,          
 @RadioChannelNumber,          
 @AirHorn,          
 @MechVentilationComfortOnly,          
 @AsbestosMMCPrecautions,          
 @Other4Checked,          
 @Other4,          
           
 @UseCurrentPermitNumberForZeroEnergyFormNumber,          
 @PermitAcceptor,          
 @ShiftSupervisor  ,    
     
 @RoadAccessOnPermit ,      
 @RoadAccessOnPermitFormNumber,      
 @RoadAccessOnPermitType         
)  
GO

GRANT EXEC ON InsertWorkPermitEdmontonHistory TO PUBLIC
GO
