if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertWorkPermitMontrealHistory]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[InsertWorkPermitMontrealHistory]

GO

CREATE Procedure [dbo].[InsertWorkPermitMontrealHistory]
(
-- Columns from WorkPermitMontreal table
@Id bigint,
@WorkPermitStatusId int = NULL,
@WorkPermitTypeId int = NULL,
@Template varchar(150) = NULL,
@StartDateTime dateTime,
@EndDateTime dateTime,
@PermitNumber bigint = NULL,
@WorkOrderNumber VARCHAR(12) = NULL,
@FunctionalLocations VARCHAR(MAX) = NULL,
@Trade varchar(100)= NULL,
@Description VARCHAR(400) = NULL,
@RequestedByGroup varchar(100) = NULL,
@LastModifiedDateTime dateTime,
@LastModifiedByUserId bigint = NULL,
@IssuedDateTime datetime = NULL,

-- Columns from WorkPermitMontrealDetails
@H2S bit,
@Hydrocarbure bit,
@Ammoniaque bit,
@Corrosif bit,
@CorrosifValue VARCHAR(100) = NULL,
@Aromatique bit,
@AromatiqueValue VARCHAR(100) = NULL,
@AutresSubstances bit,
@AutresSubstancesValue VARCHAR(100) = NULL,

@ObtureOuDeBranche bit,
@DepressuriseEtVidange bit,
@EnPresenceDeGazInerte bit,
@PurgeALaVapeur bit,
@RinceALEau bit,
@Excavation bit,
@DessinsRequis bit,
@DessinsRequisValue VARCHAR(100) = NULL,
@CablesChauffantsMisHorsTension bit,
@PompeOuVerinPneumatique bit,

@ChaineEtCadenasseOuScelle bit,
@InterrupteursElectriquesVerrouilles bit,
@PurgeParUnGazInerte bit,
@OutilsElectriquesOuABatteries bit,
@BoiteEnergieZero bit,
@BoiteEnergieZeroValue VARCHAR(100) = NULL,
@OutilsPneumatiques bit,
@MoteurACombustionInterne bit,
@TravauxSuperposes bit,

@FormulaireDespaceClosAffiche bit,
@FormulaireDespaceClosAfficheValue VARCHAR(100) = NULL,
@ExisteIlUneAnalyseDeTache bit,
@PossibiliteDeSulfureDeFer bit,
@AereVentile bit,
@SoudureALelectricite bit,
@BrulageAAcetylene bit,
@Nacelle bit,
@AutreConditions bit,
@AutreConditionsValue VARCHAR(100) = NULL,

@LunettesMonocoques bit,
@HarnaisDeSecurite bit,
@EcranFacial bit,
@ProtectionAuditive bit,
@Trepied bit,
@DispositifAntiChute bit,
@ProtectionRespiratoire bit,
@ProtectionRespiratoireValue VARCHAR(100) = NULL,
@Habits bit,
@HabitsValue VARCHAR(100) = NULL,
@AutreProtection bit,
@AutreProtectionValue VARCHAR(100) = NULL,

@Extincteur bit,
@BouchesDegoutProtegees bit,
@CouvertureAntiEtincelles bit,
@SurveillantPourEtincelles bit,
@PareEtincelles bit,
@MiseAlaTerrePresDuLieuDeTravail bit,
@BoyauAVapeur bit,
@AutresEquipementDincendie bit,
@AutresEquipementDincendieValue VARCHAR(100) = NULL,

@Ventulateur bit,
@Barrieres bit,
@Surveillant bit,
@SurveillantValue VARCHAR(100) = NULL,
@RadioEmetteur bit,
@PerimetreDeSecurite bit,
@DetectionContinueDesGaz bit,
@DetectionContinueDesGazValue VARCHAR(100) = NULL,
@KlaxonSonore bit,
@Localiser bit,
@Amiante bit,
@AutreEquipementsSecurite bit,
@AutreEquipementsSecuriteValue VARCHAR(100) = NULL,

@InstructionsSpeciales VARCHAR(500) = NULL,
@SignatureOperateurSurLeTerrain bit,
@DetectionDesGazs bit,
@SignatureContremaitre bit,
@SignatureAutorise bit,
@NettoyageTransfertHorsSite bit,

-- Other
@DocumentLinks varchar(max) = null
)
AS

INSERT INTO WorkPermitMontrealHistory
(
    Id,
	WorkPermitTypeId,
	Template,
	WorkPermitStatusId,
	StartDateTime,
	EndDateTime,
	PermitNumber,
	WorkOrderNumber,
	FunctionalLocations,
	Trade,
	Description,
	RequestedByGroup,
	LastModifiedDateTime,
	LastModifiedByUserId,
	IssuedDateTime,
	-- Details
	H2S,
	Hydrocarbure,
	Ammoniaque,
	Corrosif,
	CorrosifValue,
	Aromatique,
	AromatiqueValue,
	AutresSubstances,
	AutresSubstancesValue,
	
	ObtureOuDebranche,
	DepressuriseEtVidange,
	EnPresenceDeGazInerte,
	PurgeALaVapeur,
	RinceALeau,
	Excavation,
	DessinsRequis,
	DessinsRequisValue,
	CablesChauffantsMisHorsTension,
	PompeOuVerinPneumatique,
	
	ChaineEtCadenasseOuScelle,
	InterrupteursElectriquesVerrouilles,
	PurgeParUnGazInerte,
	OutilsElectriquesOuABatteries,
	BoiteEnergieZero,
	BoiteEnergieZeroValue,
	OutilsPneumatiques,
	MoteurACombustionInterne,
	TravauxSuperPoses,
	
	FormulaireDespaceClosAffiche,
	FormulaireDespaceClosAfficheValue,
	ExisteIlUneAnalyseDeTache,
	PossibiliteDeSulfureDeFer,
	AereVentile,
	SoudureALelectricite,
	BrulageAAcetylene,
	Nacelle,
	AutreConditions,
	AutreConditionsValue,
	
	LunettesMonocoques,
	HarnaisDeSecurite,
	EcranFacial,
	ProtectionAuditive,
	Trepied,
	DispositifAntichute,
	ProtectionRespiratoire,
	ProtectionRespiratoireValue,
	Habits,
	HabitsValue,
	AutreProtection,
	AutreProtectionValue,
	
	Extincteur,
	BouchesDegoutProtegees,
	CouvertureAntiEtincelles,
	SurveillantPouretincelles,
	PareEtincelles,
	MiseAlaTerrePresDuLieuDeTravail,
	BoyauAVapeur,
	AutresEquipementDincendie,
	AutresEquipementDincendieValue,
	
	Ventulateur,
	Barrieres,
	Surveillant,
	SurveillantValue,
	RadioEmetteur,
	PerimetreDeSecurite,
	DetectionContinueDesGaz,
	DetectionContinueDesGazValue,
	KlaxonSonore,
	Localiser,
	Amiante,
	AutreEquipementsSecurite,
	AutreEquipementsSecuriteValue,
	
	InstructionsSpeciales,
	SignatureOperateurSurLeTerrain,
	DetectionDesGazs,
	SignatureContremaitre,
	SignatureAutorise,
	NettoyageTransfertHorsSite,
	
	DocumentLinks
)
VALUES
(
    @Id,
	@WorkPermitTypeId,
	@Template,
	@WorkPermitStatusId,
	@StartDateTime,
	@EndDateTime,
	@PermitNumber,
	@WorkOrderNumber,
	@FunctionalLocations,
	@Trade,
	@Description,
	@RequestedByGroup,
	@LastModifiedDateTime,
	@LastModifiedByUserId,
	@IssuedDateTime,
	-- Details
	@H2S,
	@Hydrocarbure,
	@Ammoniaque,
	@Corrosif,
	@CorrosifValue,
	@Aromatique,
	@AromatiqueValue,
	@AutresSubstances,
	@AutresSubstancesValue,
	
	@ObtureOuDebranche,
	@DepressuriseEtVidange,
	@EnPresenceDeGazInerte,
	@PurgeALaVapeur,
	@RinceALeau,
	@Excavation,
	@DessinsRequis,
	@DessinsRequisValue,
	@CablesChauffantsMisHorsTension,
	@PompeOuVerinPneumatique,
	
	@ChaineEtCadenasseOuScelle,
	@InterrupteursElectriquesVerrouilles,
	@PurgeParUnGazInerte,
	@OutilsElectriquesOuABatteries,
	@BoiteEnergieZero,
	@BoiteEnergieZeroValue,
	@OutilsPneumatiques,
	@MoteurACombustionInterne,
	@TravauxSuperPoses,
	
	@FormulaireDespaceClosAffiche,
	@FormulaireDespaceClosAfficheValue,
	@ExisteIlUneAnalyseDeTache,
	@PossibiliteDeSulfureDeFer,
	@AereVentile,
	@SoudureALelectricite,
	@BrulageAAcetylene,
	@Nacelle,
	@AutreConditions,
	@AutreConditionsValue,
	
	@LunettesMonocoques,
	@HarnaisDeSecurite,
	@EcranFacial,
	@ProtectionAuditive,
	@Trepied,
	@DispositifAntichute,
	@ProtectionRespiratoire,
	@ProtectionRespiratoireValue,
	@Habits,
	@HabitsValue,
	@AutreProtection,
	@AutreProtectionValue,
	
	@Extincteur,
	@BouchesDegoutProtegees,
	@CouvertureAntiEtincelles,
	@SurveillantPouretincelles,
	@PareEtincelles,
	@MiseAlaTerrePresDuLieuDeTravail,
	@BoyauAVapeur,
	@AutresEquipementDincendie,
	@AutresEquipementDincendieValue,
	
	@Ventulateur,
	@Barrieres,
	@Surveillant,
	@SurveillantValue,
	@RadioEmetteur,
	@PerimetreDeSecurite,
	@DetectionContinueDesGaz,
	@DetectionContinueDesGazValue,
	@KlaxonSonore,
	@Localiser,
	@Amiante,
	@AutreEquipementsSecurite,
	@AutreEquipementsSecuriteValue,
	
	@InstructionsSpeciales,
	@SignatureOperateurSurLeTerrain,
	@DetectionDesGazs,
	@SignatureContremaitre,
	@SignatureAutorise,
	@NettoyageTransfertHorsSite,
	
	@DocumentLinks
);

GO

GRANT EXEC ON InsertWorkPermitMontrealHistory TO PUBLIC
GO
