
  
IF OBJECT_ID('UpdatePermitRequestFortHills', 'P') IS NOT NULL
DROP PROC UpdatePermitRequestFortHills
GO                
                  
CREATE Procedure [dbo].[UpdatePermitRequestFortHills]                              
    (                              
@Id bigint Output,                 
@IssuedToSuncor bit,                
@IssuedToCompany bit,                
@Company varchar(50) =   NULL,                
@Occupation varchar(50),                
@NumberOfWorkers int =  NULL,                
@GroupId bigint ,                
--@SourceId int ,                
@WorkOrderNumber varchar(25) =  NULL,                
@WorkPermitTypeId int ,                
@PriorityId int ,                 
@FunctionalLocationId bigint ,                
@Location varchar(100) ,                
@RequestedStartDate datetime ,                
@RequestedEndDate datetime ,                         
@EquipmentNo  int =  NULL,                          
@JobCoordinator varchar(25) =  NULL,                
@CoOrdContactNumber varchar(10) =  NULL,    
@LockBoxnumberChecked bit,                
@Description varchar(max) =  NULL,      
@SAPDescription varchar(8000) = NULL,                       
@FlameResistantWorkWear bit =  NULL,                
@ChemicalSuit bit,                
@FireWatch bit,                
@FireBlanket bit,                
@SuppliedBreathingAir bit,                
@AirMover bit,                
@PersonalFlotationDevice bit,                
@HearingProtection bit,                
@Other1 varchar(30) =  NULL,                
@MonoGoggles bit ,                
@ConfinedSpaceMoniter bit ,                
@FireExtinguisher bit ,                
@SparkContainment bit ,                
@BottleWatch bit ,                
@StandbyPerson bit ,                
@WorkingAlone bit ,                
@SafetyGloves bit ,                
@Other2 varchar(30) =  NULL,                
@FaceShield bit ,                
@FallProtection bit ,                
@ChargedFireHouse bit ,           
@CoveredSewer bit,          
@AirPurifyingRespirator bit,                
@SingalPerson bit ,                
@CommunicationDevice bit ,                
@ReflectiveStrips bit ,                
@Other3 varchar(30) =  NULL,                
@HazardsAndOrRequirements varchar(max) =  NULL,                
@ConfinedSpace bit ,                
@ConfinedSpaceClass varchar(25) =  NULL,                
@GoundDisturbance bit ,                
@FireProtectionAuthorization bit ,                
@CriticalOrSeriousLifts bit ,                
@VehicleEntry bit ,                
@IndustrialRadiography bit ,                
@ElectricalEncroachment bit ,                
@MSDS bit ,                
@OthersPartE varchar(30) =  NULL,                
@MechanicallyIsolated bit ,                
@BlindedOrBlanked bit ,                
@DoubleBlockedandBled bit ,                
@DrainedAndDepressurised bit ,                
@PurgedorNeutralised bit ,                
@ElectricallyIsolated bit ,                
@TestBumped bit ,                
@NuclearSource bit ,                
@ReceiverStafingRequirements bit ,                
@SAPWorkCentre varchar(40) =  NULL,                
@CompletionStatusId int ,                
@LastImportedByUserId bigint =  NULL,                
@LastImportedDateTime datetime =  NULL,                
@LastSubmittedByUserId bigint =  NULL,                
@LastSubmittedDateTime datetime =  NULL,                      
@LastModifiedByUserId bigint ,                
@LastModifiedDateTime datetime ,                
@IsModified bit,    
@PartCWorkSectionNotApplicableToJob bit,    
@PartDWorkSectionNotApplicableToJob bit,    
@PartEWorkSectionNotApplicableToJob bit    
 )                              
AS                              
                                   
                              
Update PermitRequestFortHills                              
set         
                            
 IssuedToSuncor  =  @IssuedToSuncor,        
 IssuedToCompany  =  @IssuedToCompany,        
 Company  =  @Company,        
 Occupation  =  @Occupation,        
 NumberOfWorkers  =  @NumberOfWorkers,        
 GroupId  =  @GroupId,        
 --SourceId  =  @SourceId,        
 WorkOrderNumber  =  @WorkOrderNumber,        
 WorkPermitTypeId  =  @WorkPermitTypeId,        
 PriorityId  =  @PriorityId,        
 FunctionalLocationId  =  @FunctionalLocationId,        
 Location  =  @Location,        
 RequestedStartDate  =  @RequestedStartDate,        
 RequestedEndDate  =  @RequestedEndDate,       
 EquipmentNo  =  @EquipmentNo,           
 JobCoordinator  =  @JobCoordinator,        
 CoOrdContactNumber  =  @CoOrdContactNumber,        
 LockBoxnumberChecked = @LockBoxnumberChecked,       
 TaskDescription  =  @Description,        
 SAPDescription = @SAPDescription,      
 FlameResistantWorkWear  =  @FlameResistantWorkWear,        
 ChemicalSuit  =  @ChemicalSuit,        
 FireWatch  =  @FireWatch,        
 FireBlanket  =  @FireBlanket,        
 SuppliedBreathingAir  =  @SuppliedBreathingAir,        
 AirMover  =  @AirMover,        
 PersonalFlotationDevice  =  @PersonalFlotationDevice,        
 HearingProtection  =  @HearingProtection,        
 Other1  =  @Other1,        
 MonoGoggles  =  @MonoGoggles,        
 ConfinedSpaceMoniter  =  @ConfinedSpaceMoniter,        
 FireExtinguisher  =  @FireExtinguisher,        
 SparkContainment  =  @SparkContainment,        
 BottleWatch  =  @BottleWatch,        
 StandbyPerson  =  @StandbyPerson,        
 WorkingAlone  =  @WorkingAlone,        
 SafetyGloves  =  @SafetyGloves,        
 Other2  =  @Other2,        
 FaceShield  =  @FaceShield,        
 FallProtection  =  @FallProtection,        
 ChargedFireHouse  =  @ChargedFireHouse,        
 CoveredSewer  =  @CoveredSewer,        
 AirPurifyingRespirator  =  @AirPurifyingRespirator,        
 SingalPerson  =  @SingalPerson,        
 CommunicationDevice  =  @CommunicationDevice,        
 ReflectiveStrips  =  @ReflectiveStrips,        
 Other3  =  @Other3,        
 HazardsAndOrRequirements  =  @HazardsAndOrRequirements,        
 ConfinedSpace  =  @ConfinedSpace,        
 ConfinedSpaceClass  =  @ConfinedSpaceClass,        
 GoundDisturbance  =  @GoundDisturbance,        
 FireProtectionAuthorization  =  @FireProtectionAuthorization,        
 CriticalOrSeriousLifts  =  @CriticalOrSeriousLifts,        
 VehicleEntry  =  @VehicleEntry,        
 IndustrialRadiography  =  @IndustrialRadiography,        
 ElectricalEncroachment  =  @ElectricalEncroachment,        
 MSDS  =  @MSDS,        
 OthersPartE  =  @OthersPartE,        
 MechanicallyIsolated  =  @MechanicallyIsolated,        
 BlindedOrBlanked  =  @BlindedOrBlanked,        
 DoubleBlockedandBled  =  @DoubleBlockedandBled,        
 DrainedAndDepressurised  =  @DrainedAndDepressurised,        
 PurgedorNeutralised  =  @PurgedorNeutralised,        
 ElectricallyIsolated  =  @ElectricallyIsolated,        
 TestBumped  =  @TestBumped,        
 NuclearSource  =  @NuclearSource,        
 ReceiverStafingRequirements  =  @ReceiverStafingRequirements,        
 SAPWorkCentre  =  @SAPWorkCentre,        
 CompletionStatusId  =  @CompletionStatusId,        
 LastImportedByUserId  =  @LastImportedByUserId,        
 LastImportedDateTime  =  @LastImportedDateTime,        
 LastSubmittedByUserId  =  @LastSubmittedByUserId,        
 LastSubmittedDateTime  =  @LastSubmittedDateTime,        
 LastModifiedByUserId  =  @LastModifiedByUserId,        
 LastModifiedDateTime  =  @LastModifiedDateTime,        
 IsModified  =  @IsModified,     
 PartCWorkSectionNotApplicable = @PartCWorkSectionNotApplicableToJob,    
 PartDWorkSectionNotApplicable = @PartDWorkSectionNotApplicableToJob,    
 PartEWorkSectionNotApplicable = @PartEWorkSectionNotApplicableToJob    
                
                             
WHERE Id = @Id                            
                         
                              
GRANT EXEC ON UpdatePermitRequestFortHills TO PUBLIC   