if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[UpdateWorkPermitMuds]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[UpdateWorkPermitMuds]
Go
CREATE Procedure [dbo].[UpdateWorkPermitMuds]          
(          
 @Id bigint,          
 @PermitNumber bigint Output,          
 @ShouldCreatePermitNumber bit,          
 @WorkPermitStatusId tinyint,          
 @WorkPermitTypeId bigint,          
 @RequestedByGroupId varchar(50) = NULL,           
 @StartDateTime DateTime,          
 @EndDateTime DateTime,          
 @TemplateId bigint = NULL,          
 @WorkOrderNumber VARCHAR(12) = NULL,          
 @Trade varchar(100),       
 @CompanyName varchar(100),         
 @CompanyName_1 varchar(100),        
 @CompanyName_2 varchar(100),       
 @Description VARCHAR(400),          
 @LastModifiedDateTime DateTime,          
 @LastModifiedByUserId bigint,          
 @IssuedDateTime datetime = null,       
 @WorkPermitCloseComments varchar(500)=NULL,  
 @WorkpermitClosedById bigint =null,
 @ActionItemCloseById bigint=null,
 @PermitCloseDateTime datetime=null,
 @ActionItemCloseDateTime datetime=null,
 @ActionItemCheckboxchecked bit=null,    
@NbTravail varchar(50),      
@FormationCheck bit,      
@NomsEnt varchar(50),      
@NomsEnt_1 varchar(50),      
@NomsEnt_2 varchar(50),      
@NomsEnt_3 varchar(50),      
@Surveilant varchar(50),         
         
@RemplirLeFormulaireDeCondition bit ,      
@RemplirLeFormulaireDeConditionValue varchar(100) ,      
@AnalyseCritiqueDeLaTache bit ,      
@Depressurises bit ,      
@Vides bit ,      
@ContournementDesGDA bit ,      
@Rinces bit ,      
@NettoyesLaVapeur bit ,      
@Purges bit ,      
@Ventiles bit ,      
@Aeres bit ,      
@Energies bit ,      
      
@Procedure bit ,      
@ProcedureValue varchar(100) ,      
@AutresCondition bit ,      
@AutresConditionValue varchar(100) ,      
@InterrupteursEtVannesCadenasses bit ,      
@InterrupteursEtVannesCadenassesValue varchar(100) ,      
@VerrouillagesParTravailleurs bit ,      
@SourcesDesenergisees bit ,      
@DepartsLocauxTestes bit ,      
@ConduitesDesaccouplees bit ,      
@ObturateursInstallees bit ,      
@Etiquette bit ,      
@EtiquetteValue varchar(100) ,      
@PVCISuncorEffectuee bit ,      
@PVCIEntExtEffectuee bit ,      
@Amiante bit ,      
@AcideSulfurique bit ,      
@Azote bit ,      
@Caustique bit ,      
@DioxydeDeSoufre bit ,      
@SBS bit ,      
@Soufre bit ,      
@EquipementsNonRinces bit ,      
@Hydrocarbures bit ,      
@HydrogeneSulfure bit ,      
@MonoxydeCarbone bit ,      
@Reflux bit ,      
@ProduitsVolatilsUtilises bit ,      
@Bacteries bit ,      
@Appareil bit ,      
@AppareilValue varchar(100) ,      
@InterferencesEntreTravaux bit ,      
@PiecesEnRotation bit ,      
@IncendieExplosion bit ,      
@ContrainteThermique bit ,      
@Radiations bit ,      
@Silice bit ,      
@Vanadium bit ,      
@AsphyxieIntoxication bit ,      
@AutresRisques bit ,      
@AutresRisquesValue varchar(100) ,      
@ElectriciteVolt bit ,      
@ElectriciteVoltValue varchar(100) ,      
@OutillageElectrique bit ,      
@TravailEnHauteur6EtPlus bit ,      
@VapeurCondensat bit,       
@Electrisation bit ,      
@LunettesMonocoques bit ,      
@Visiere bit ,      
@ProtectionAuditive bit ,      
@CagouleIgnifuge bit ,      
@Harnais2LiensDeRetenue bit ,      
@Gants bit ,      
@GantsValue varchar(100) ,      
@MasqueACartouches bit ,      
@MasqueACartouchesValue varchar(100) ,      
@EPIAntiArcCAT bit ,      
@EPIAntiArcCATValue varchar(100) ,      
@EPIAntiChoc bit ,      
@HabitProtecteur bit ,      
@HabitProtecteurValue varchar(100) ,      
@EcranDeflecteur bit ,      
@MALTDesEquipements bit ,      
@Rallonges bit ,      
@ApprobationPourEquipDeLevage bit ,      
@BarricadeRigide bit ,      
@AutresE bit ,      
@AutresEValue varchar(100) ,      
@AlarmeDCS bit ,      
@AlarmeDCSValue varchar(100) ,      
@EchelleSecurisee bit ,      
@EchafaudageApprouve bit ,      
@OutilDeLaiton bit ,      
@OutilDeLaitonManel bit ,      
@outilDeLaitonManelValue varchar(100) ,      
@PerimetreSecurite bit ,      
@PerimetreSecuriteValue varchar(100),      
@Radio bit ,      
@Signaleur bit ,      
@InstructionsSpeciales varchar(500) ,      
@SignatureOperateurSurLeTerrain bit ,      
@DetectionDesGazs bit ,      
@SignatureContremaitre bit ,      
@SignatureAutorise bit ,      
@NettoyageTransfertHorsSite bit ,      
@Soudage bit ,      
@Traitement bit ,      
@Cuissons bit ,      
@Percage bit ,      
@Chaufferette bit ,      
@Meulage bit ,      
@Nettoyage bit ,      
@AutresTravaux bit ,      
@AutresTravauxValue varchar(100),      
@TravauxDansZone bit ,      
@Combustibles bit ,      
@Ecran bit ,      
@Boyau bit ,      
@BoyauDe bit ,      
@Couverture bit ,      
@Extincteur bit ,      
@Bouche bit ,      
@RadioS bit ,      
@Surveillant bit ,      
@UtilisationMoteur bit ,      
@NettoyageAU bit ,      
@UtilisationElectronics bit ,      
@Radiographie bit ,      
@UtilisationOutlis bit ,      
@UtilisationEquipments bit ,      
@Demolition bit ,      
@AutresInstruction bit ,      
@AutresInstructionValue varchar(100),      
@EffondrementEnsevelissement   bit ,      
@MasqueSoudeur bit ,    
@GasTestFirstResultTime datetime=NULL,     
@GasTestSecondResultTime datetime=NULL,     
@GasTestThirdResultTime datetime=NULL,     
@GasTestFourthResultTime datetime=NULL   ,
@FeSValue bit    ,
@MudsAnswerTextBox varchar(max), 
 @MudsQuestionlabel varchar(max)   
)          
AS          
          
IF @ShouldCreatePermitNumber = 1          
 BEGIN          
  EXEC @PermitNumber = GetNewSeqVal_WorkPermitMudsPermitNumberSequence          
 END          
ELSE          
 BEGIN          
  SET @PermitNumber = (select PermitNumber from WorkPermitMuds WHERE Id = @Id)          
 END          
          
UPDATE WorkPermitMuds          
 SET           
  WorkPermitStatusId = @WorkPermitStatusId,          
  WorkPermitTypeId = @WorkPermitTypeId,          
  RequestedByGroupId = @RequestedByGroupId,          
  StartDateTime = @StartDateTime,          
  EndDateTime = @EndDateTime,          
  PermitNumber = @PermitNumber,          
  TemplateId = @TemplateId,          
  WorkOrderNumber = @WorkOrderNumber,          
  Trade = @Trade,         
  Company = @CompanyName,       
Company_1 = @CompanyName_1,       
  Company_2 = @CompanyName_2,       
  Description = @Description,          
  --UsePreviousPermitAnswered = @UsePreviousPermitAnswered,          
  LastModifiedDateTime = @LastModifiedDateTime,          
  LastModifiedByUserId = @LastModifiedByUserId,          
  IssuedDateTime = @IssuedDateTime ,      
 WorkPermitCloseComments = @WorkPermitCloseComments, 
 WorkpermitClosedById = @WorkpermitClosedById,
 ActionItemCloseById =@ActionItemCloseById,
 PermitCloseDateTime =@PermitCloseDateTime,
 ActionItemCloseDateTime =@ActionItemCloseDateTime,
 ActionItemCheckboxchecked =@ActionItemCheckboxchecked,    
NbTravail  = @NbTravail ,      
FormationCheck = @FormationCheck  ,      
NomsEnt = @NomsEnt ,      
NomsEnt_1 = @NomsEnt_1 ,      
NomsEnt_2 = @NomsEnt_2 ,      
NomsEnt_3 = @NomsEnt_3 ,      
Surveilant  = @Surveilant ,      
GasTestFirstResultTime=@GasTestFirstResultTime,    
GasTestSecondResultTime=@GasTestSecondResultTime,     
GasTestThirdResultTime=@GasTestThirdResultTime,     
GasTestFourthResultTime =@GasTestFourthResultTime    ,
FeSValue = @FeSValue    ,
MudsAnswerTextBox = @MudsAnswerTextBox ,
 MudsQuestionlabel = @MudsQuestionlabel 
           
 WHERE          
  Id = @Id          
          
          
UPDATE WorkPermitMudsDetails          
 SET          
          
 RemplirLeFormulaireDeCondition = @RemplirLeFormulaireDeCondition ,      
RemplirLeFormulaireDeConditionValue = @RemplirLeFormulaireDeConditionValue ,      
AnalyseCritiqueDeLaTache = @AnalyseCritiqueDeLaTache ,      
Depressurises = @Depressurises ,      
Vides = @Vides ,      
ContournementDesGDA = @ContournementDesGDA ,      
Rinces = @Rinces ,      
NettoyesLaVapeur = @NettoyesLaVapeur ,      
Purges = @Purges ,      
Ventiles = @Ventiles ,      
Aeres = @Aeres ,      
Energies = @Energies ,      
[Procedure] = @Procedure ,      
ProcedureValue = @ProcedureValue ,      
AutresCondition = @AutresCondition ,      
AutresConditionValue = @AutresConditionValue ,      
InterrupteursEtVannesCadenasses = @InterrupteursEtVannesCadenasses ,      
InterrupteursEtVannesCadenassesValue = @InterrupteursEtVannesCadenassesValue ,      
VerrouillagesParTravailleurs = @VerrouillagesParTravailleurs ,      
SourcesDesenergisees = @SourcesDesenergisees ,      
DepartsLocauxTestes = @DepartsLocauxTestes ,      
ConduitesDesaccouplees = @ConduitesDesaccouplees ,      
ObturateursInstallees = @ObturateursInstallees ,      
Etiquette = @Etiquette ,      
EtiquetteValue = @EtiquetteValue ,      
PVCISuncorEffectuee = @PVCISuncorEffectuee ,      
PVCIEntExtEffectuee = @PVCIEntExtEffectuee ,      
Amiante = @Amiante ,      
AcideSulfurique = @AcideSulfurique ,      
Azote = @Azote ,    
Caustique = @Caustique ,      
DioxydeDeSoufre = @DioxydeDeSoufre ,      
SBS = @SBS ,      
Soufre = @Soufre ,      
EquipementsNonRinces = @EquipementsNonRinces ,      
Hydrocarbures = @Hydrocarbures ,      
HydrogeneSulfure = @HydrogeneSulfure ,      
MonoxydeCarbone = @MonoxydeCarbone ,      
Reflux = @Reflux ,      
ProduitsVolatilsUtilises = @ProduitsVolatilsUtilises ,      
Bacteries = @Bacteries ,      
Appareil = @Appareil ,      
AppareilValue = @AppareilValue ,      
InterferencesEntreTravaux = @InterferencesEntreTravaux ,      
PiecesEnRotation = @PiecesEnRotation ,      
IncendieExplosion = @IncendieExplosion ,      
ContrainteThermique = @ContrainteThermique ,      
Radiations = @Radiations ,      
Silice = @Silice ,      
Vanadium = @Vanadium ,      
AsphyxieIntoxication = @AsphyxieIntoxication ,      
AutresRisques = @AutresRisques ,      
AutresRisquesValue = @AutresRisquesValue ,      
ElectriciteVolt = @ElectriciteVolt ,      
ElectriciteVoltValue = @ElectriciteVoltValue ,      
OutillageElectrique = @OutillageElectrique ,      
TravailEnHauteur6EtPlus = @TravailEnHauteur6EtPlus ,      
VapeurCondensat = @VapeurCondensat,      
Electrisation = @Electrisation ,      
LunettesMonocoques = @LunettesMonocoques ,      
Visiere = @Visiere ,      
ProtectionAuditive = @ProtectionAuditive ,      
CagouleIgnifuge = @CagouleIgnifuge ,      
Harnais2LiensDeRetenue = @Harnais2LiensDeRetenue ,      
Gants = @Gants ,      
GantsValue = @GantsValue ,      
MasqueACartouches = @MasqueACartouches ,      
MasqueACartouchesValue = @MasqueACartouchesValue ,      
EPIAntiArcCAT = @EPIAntiArcCAT ,      
EPIAntiArcCATValue = @EPIAntiArcCATValue ,      
EPIAntiChoc = @EPIAntiChoc ,      
HabitProtecteur = @HabitProtecteur ,      
HabitProtecteurValue = @HabitProtecteurValue ,      
EcranDeflecteur = @EcranDeflecteur ,      
MALTDesEquipements = @MALTDesEquipements ,      
Rallonges = @Rallonges ,      
ApprobationPourEquipDeLevage = @ApprobationPourEquipDeLevage ,      
BarricadeRigide = @BarricadeRigide ,      
AutresE = @AutresE ,      
AutresEValue = @AutresEValue ,      
AlarmeDCS = @AlarmeDCS ,      
AlarmeDCSValue = @AlarmeDCSValue ,      
EchelleSecurisee = @EchelleSecurisee ,      
EchafaudageApprouve = @EchafaudageApprouve ,      
OutilDeLaiton = @OutilDeLaiton ,      
OutilDeLaitonManel = @OutilDeLaitonManel ,      
outilDeLaitonManelValue = @outilDeLaitonManelValue ,      
PerimetreSecurite = @PerimetreSecurite ,      
PerimetreSecuriteValue = @PerimetreSecuriteValue,      
Radio = @Radio ,      
Signaleur = @Signaleur ,      
InstructionsSpeciales = @InstructionsSpeciales ,      
SignatureOperateurSurLeTerrain = @SignatureOperateurSurLeTerrain ,      
DetectionDesGazs = @DetectionDesGazs ,      
SignatureContremaitre = @SignatureContremaitre ,      
SignatureAutorise = @SignatureAutorise ,      
NettoyageTransfertHorsSite = @NettoyageTransfertHorsSite ,      
Soudage = @Soudage ,      
Traitement = @Traitement ,      
Cuissons = @Cuissons ,      
Percage = @Percage ,      
Chaufferette = @Chaufferette ,      
Meulage = @Meulage ,      
Nettoyage = @Nettoyage ,      
AutresTravaux = @AutresTravaux ,      
AutresTravauxValue = @AutresTravauxValue ,      
TravauxDansZone = @TravauxDansZone ,      
Combustibles = @Combustibles ,      
Ecran = @Ecran ,      
Boyau = @Boyau ,      
BoyauDe = @BoyauDe ,      
Couverture = @Couverture ,      
Extincteur = @Extincteur ,      
Bouche = @Bouche ,      
RadioS = @RadioS ,      
Surveillant = @Surveillant ,      
UtilisationMoteur = @UtilisationMoteur ,      
NettoyageAU = @NettoyageAU ,      
UtilisationElectronics = @UtilisationElectronics ,      
Radiographie = @Radiographie ,      
UtilisationOutlis = @UtilisationOutlis ,      
UtilisationEquipments = @UtilisationEquipments ,      
Demolition = @Demolition ,      
AutresInstruction = @AutresInstruction ,      
AutresInstructionValue = @AutresInstructionValue ,      
EffondrementEnsevelissement  = @EffondrementEnsevelissement ,      
MasqueSoudeur = @MasqueSoudeur      
      
 WHERE          
  Id = @Id      
        
  
  --AS Permit Update Clear All Sign        
 if(@WorkPermitStatusId IN(1,2))        
  Begin        
  UPdate WORKPERMITMUDSSIGN          
  SET Deleted=1 where WorkPermitId=@PermitNumber          
  END        
      
 GRANT EXEC ON UpdateWorkPermitMuds TO PUBLIC 