IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'UpdateWorkPermitMontrealTemplate')
	BEGIN
		DROP  Procedure  UpdateWorkPermitMontrealTemplate
	END
GO

CREATE Procedure [dbo].[UpdateWorkPermitMontrealTemplate]
(
    @Id bigint,
    @Name varchar(100),
	@TypeId int,
	@Active bit,
	@Deleted bit,
	@H2S tinyint,
	@Hydrocarbure tinyint,
	@Ammoniaque tinyint,
	@Corrosif tinyint,
	@CorrosifValue varchar(100),
	@Aromatique tinyint,
	@AromatiqueValue varchar(100),
	@AutresSubstances tinyint,
	@AutresSubstancesValue varchar(100),
	@ObtureOuDeBranche tinyint,
	@DepressuriseEtVidange tinyint,
	@EnPresenceDeGazInerte tinyint,
	@PurgeALaVapeur tinyint,
	@RinceALEau tinyint,
	@Excavation tinyint,
	@DessinsRequis tinyint,
	@DessinsRequisValue varchar(100),
	@CablesChauffantsMisHorsTension tinyint,
	@PompeOuVerinPneumatique tinyint,
	@ChaineEtCadenasseOuScelle tinyint,
	@InterrupteursElectriquesVerrouilles tinyint,
	@PurgeParUnGazInerte tinyint,
	@OutilsElectriquesOuABatteries tinyint,
	@BoiteEnergieZero tinyint,
	@BoiteEnergieZeroValue varchar(100),
	@OutilsPneumatiques tinyint,
	@MoteurACombustionInterne tinyint,
	@TravauxSuperposes tinyint,
	@FormulaireDespaceClosAffiche tinyint,
	@FormulaireDespaceClosAfficheValue varchar(100),
	@ExisteIlUneAnalyseDeTache tinyint,
	@PossibiliteDeSulfureDeFer tinyint,
	@AereVentile tinyint,
	@SoudureALelectricite tinyint,
	@BrulageAAcetylene tinyint,
	@Nacelle tinyint,
	@AutreConditions tinyint,
	@AutreConditionsValue varchar(100),
	@LunettesMonocoques tinyint,
	@HarnaisDeSecurite tinyint,
	@EcranFacial tinyint,
	@ProtectionAuditive tinyint,
	@Trepied tinyint,
	@DispositifAntiChute tinyint,
	@ProtectionRespiratoire tinyint,
	@ProtectionRespiratoireValue varchar(100),
	@Habits tinyint,
	@HabitsValue varchar(100),
	@AutreProtection tinyint,
	@AutreProtectionValue varchar(100),
	@Extincteur tinyint,
	@BouchesDegoutProtegees tinyint,
	@CouvertureAntiEtincelles tinyint,
	@SurveillantPourEtincelles tinyint,
	@PareEtincelles tinyint,
	@MiseAlaTerrePresDuLieuDeTravail tinyint,
	@BoyauAVapeur tinyint,
	@AutresEquipementDincendie tinyint,
	@AutresEquipementDincendieValue varchar(100),
	@Ventulateur tinyint,
	@Barrieres tinyint,
	@Surveillant tinyint,
	@SurveillantValue varchar(100),
	@RadioEmetteur tinyint,
	@PerimetreDeSecurite tinyint,
	@DetectionContinueDesGaz tinyint,
	@DetectionContinueDesGazValue varchar(100),
	@KlaxonSonore tinyint,
	@Localiser tinyint,
	@Amiante tinyint,
	@AutreEquipementsSecurite tinyint,
	@AutreEquipementsSecuriteValue varchar(100),
	@InstructionsSpeciales varchar(500),
	@SignatureOperateurSurLeTerrain tinyint,
	@DetectionDesGazs tinyint,
	@SignatureContremaitre tinyint,
	@SignatureAutorise tinyint,
	@NettoyageTransfertHorsSite tinyint
)
AS

UPDATE [WorkPermitMontrealTemplate]
  SET
	[Name] = @Name, 
	[TypeId] = @TypeId,
	[Active] = @Active,
	[Deleted] = @Deleted,
	[H2S] = @H2S,
	[Hydrocarbure] = @Hydrocarbure,
	[Ammoniaque] = @Ammoniaque,
	[Corrosif] = @Corrosif,
	[CorrosifValue] = @CorrosifValue,
	[Aromatique] = @Aromatique,
	[AromatiqueValue] = @AromatiqueValue,
	[AutresSubstances] = @AutresSubstances,
	[AutresSubstancesValue] = @AutresSubstancesValue,
	[ObtureOuDeBranche] = @ObtureOuDeBranche,
	[DepressuriseEtVidange] = @DepressuriseEtVidange,
	[EnPresenceDeGazInerte] = @EnPresenceDeGazInerte,
	[PurgeALaVapeur] = @PurgeALaVapeur,
	[RinceALEau] = @RinceALEau,
	[Excavation] = @Excavation,
	[DessinsRequis] = @DessinsRequis,
	[DessinsRequisValue] = @DessinsRequisValue,
	[CablesChauffantsMisHorsTension] = @CablesChauffantsMisHorsTension,
	[PompeOuVerinPneumatique] = @PompeOuVerinPneumatique,
	[ChaineEtCadenasseOuScelle] = @ChaineEtCadenasseOuScelle,
	[InterrupteursElectriquesVerrouilles] = @InterrupteursElectriquesVerrouilles,
	[PurgeParUnGazInerte] = @PurgeParUnGazInerte,
	[OutilsElectriquesOuABatteries] = @OutilsElectriquesOuABatteries,
	[BoiteEnergieZero] = @BoiteEnergieZero,
	[BoiteEnergieZeroValue] = @BoiteEnergieZeroValue,
	[OutilsPneumatiques] = @OutilsPneumatiques,
	[MoteurACombustionInterne] = @MoteurACombustionInterne,
	[TravauxSuperposes] = @TravauxSuperposes,
	[FormulaireDespaceClosAffiche] = @FormulaireDespaceClosAffiche,
	[FormulaireDespaceClosAfficheValue] = @FormulaireDespaceClosAfficheValue,
	[ExisteIlUneAnalyseDeTache] = @ExisteIlUneAnalyseDeTache,
	[PossibiliteDeSulfureDeFer] = @PossibiliteDeSulfureDeFer,
	[AereVentile] = @AereVentile,
	[SoudureALelectricite] = @SoudureALelectricite,
	[BrulageAAcetylene] = @BrulageAAcetylene,
	[Nacelle] = @Nacelle,
	[AutreConditions] = @AutreConditions,
	[AutreConditionsValue] = @AutreConditionsValue,
	[LunettesMonocoques] = @LunettesMonocoques,
	[HarnaisDeSecurite] = @HarnaisDeSecurite,
	[EcranFacial] = @EcranFacial,
	[ProtectionAuditive] = @ProtectionAuditive,
	[Trepied] = @Trepied,
	[DispositifAntiChute] = @DispositifAntiChute,
	[ProtectionRespiratoire] = @ProtectionRespiratoire,
	[ProtectionRespiratoireValue] = @ProtectionRespiratoireValue,
	[Habits] = @Habits,
	[HabitsValue] = @HabitsValue,
	[AutreProtection] = @AutreProtection,
	[AutreProtectionValue] = @AutreProtectionValue,
	[Extincteur] = @Extincteur,
	[BouchesDegoutProtegees] = @BouchesDegoutProtegees,
	[CouvertureAntiEtincelles] = @CouvertureAntiEtincelles,
	[SurveillantPourEtincelles] = @SurveillantPourEtincelles,
	[PareEtincelles] = @PareEtincelles,
	[MiseAlaTerrePresDuLieuDeTravail] = @MiseAlaTerrePresDuLieuDeTravail,
	[BoyauAVapeur] = @BoyauAVapeur,
	[AutresEquipementDincendie] = @AutresEquipementDincendie,
	[AutresEquipementDincendieValue] = @AutresEquipementDincendieValue,
	[Ventulateur] = @Ventulateur,
	[Barrieres] = @Barrieres,
	[Surveillant] = @Surveillant,
	[SurveillantValue] = @SurveillantValue,
	[RadioEmetteur] = @RadioEmetteur,
	[PerimetreDeSecurite] = @PerimetreDeSecurite,
	[DetectionContinueDesGaz] = @DetectionContinueDesGaz,
	[DetectionContinueDesGazValue] = @DetectionContinueDesGazValue,
	[KlaxonSonore] = @KlaxonSonore,
	[Localiser] = @Localiser,
	[Amiante] = @Amiante,
	[AutreEquipementsSecurite] = @AutreEquipementsSecurite,
	[AutreEquipementsSecuriteValue] = @AutreEquipementsSecuriteValue,
	[InstructionsSpeciales] = @InstructionsSpeciales,
	[SignatureOperateurSurLeTerrain] = @SignatureOperateurSurLeTerrain,
	[DetectionDesGazs] = @DetectionDesGazs,
	[SignatureContremaitre] = @SignatureContremaitre,
	[SignatureAutorise] = @SignatureAutorise,
	[NettoyageTransfertHorsSite] = @NettoyageTransfertHorsSite
where
  Id = @Id
GO
 