if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[UpdateProcedureDeviation]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[UpdateProcedureDeviation]
GO

CREATE Procedure [dbo].[UpdateProcedureDeviation]
(
	@Id bigint Output,
	@FormStatusId int,
	@ValidFromDateTime datetime,
	@ValidToDateTime datetime,
	@ApprovedDateTime datetime,
	@CreatedByUserId bigint,
	@CreatedDateTime datetime,
	@LastModifiedByUserId bigint,
	@LastModifiedDateTime datetime,
	@SiteId bigint,
	@DeviationType int,
	@PermanentRevisionRequired bit,
	@RevertedBackToOriginal bit,
	@LocationEquipmentNumber varchar(100),
	@NumberOfExtensions int,
	@OperatingProcedureNumber varchar(100),
	@OperatingProcedureTitle varchar(255),
	@OperatingProcedureLevel int,
	@Description varchar(MAX),
	@RichTextDescription varchar(MAX),
	@CauseDeterminationCategory varchar(100),
	@CauseDeterminationComments varchar(255),
	@FixDocumentDurationType int,
	@CorrectiveActionIlpNumber varchar(100),
	@CorrectiveActionWorkRequestNumber varchar(100),
	@CorrectiveActionOtherComments varchar(255),
	@AffectsToe bit,
	@RiskAssessmentAttendee1Type int,
	@RiskAssessmentAttendee1Name varchar(100),
	@RiskAssessmentAttendee2Type int,
	@RiskAssessmentAttendee2Name varchar(100),
	@RiskAssessmentAttendee3Type int,
	@RiskAssessmentAttendee3Name varchar(100),
	@RiskAssessmentAttendee4Type int,
	@RiskAssessmentAttendee4Name varchar(100),
	@RiskAssessmentAnswer1 bit,
	@RiskAssessmentAnswer2 bit,
	@RiskAssessmentAnswer3 bit,
	@RiskAssessmentAnswer4 bit,
	@RiskAssessmentAnswer5 bit,
	@RiskAssessmentComments varchar(255),
	@ImmediateApprovalsApprover1Type int,
	@ImmediateApprovalsApprover1Title varchar(100),
	@ImmediateApprovalsApprover1Name varchar(255),
	@ImmediateApprovalsApprover1ObtainedVia int,
	@ImmediateApprovalsApprover1ApprovedDateTime datetime,
	@ImmediateApprovalsApprover2Type int,
	@ImmediateApprovalsApprover2Title varchar(100),
	@ImmediateApprovalsApprover2Name varchar(255),
	@ImmediateApprovalsApprover2ObtainedVia int,
	@ImmediateApprovalsApprover2ApprovedDateTime datetime,
	@TemporaryApprovalsApprover1Type int,
	@TemporaryApprovalsApprover1Title varchar(100),
	@TemporaryApprovalsApprover1Name varchar(255),
	@TemporaryApprovalsApprover1ObtainedVia int,
	@TemporaryApprovalsApprover1ApprovedDateTime datetime,
	@TemporaryApprovalsApprover2Type int,
	@TemporaryApprovalsApprover2Title varchar(100),
	@TemporaryApprovalsApprover2Name varchar(255),
	@TemporaryApprovalsApprover2ObtainedVia int,
	@TemporaryApprovalsApprover2ApprovedDateTime datetime,
	@CancelledBy varchar(100),
	@CancelledDateTime datetime,
	@CancelledReason varchar(255)
)
AS

UPDATE FormProcedureDeviation
	SET 
	[FormStatusId] = @FormStatusId,
	[ValidFromDateTime] = @ValidFromDateTime,
	[ValidToDateTime] = @ValidToDateTime,
	[ApprovedDateTime] = @ApprovedDateTime,
	[CreatedByUserId] = @CreatedByUserId,
	[CreatedDateTime] = @CreatedDateTime,
	[LastModifiedByUserId] = @LastModifiedByUserId,
	[LastModifiedDateTime] = @LastModifiedDateTime,	
	[SiteId] = @SiteId,
	[DeviationType] = @DeviationType,
	[PermanentRevisionRequired] = @PermanentRevisionRequired,
	[RevertedBackToOriginal] = @RevertedBackToOriginal,
	[LocationEquipmentNumber] = @LocationEquipmentNumber,
	[NumberOfExtensions] = @NumberOfExtensions,
	[OperatingProcedureNumber] = @OperatingProcedureNumber,
	[OperatingProcedureTitle] = @OperatingProcedureTitle,
	[OperatingProcedureLevel] = @OperatingProcedureLevel,
	[Description] = @Description,
	[RichTextDescription] = @RichTextDescription,
	[CauseDeterminationCategory] = @CauseDeterminationCategory,
	[CauseDeterminationComments] = @CauseDeterminationComments,
	[FixDocumentDurationType] = @FixDocumentDurationType,
	[CorrectiveActionIlpNumber] = @CorrectiveActionIlpNumber,
	[CorrectiveActionWorkRequestNumber] = @CorrectiveActionWorkRequestNumber,
	[CorrectiveActionOtherComments] = @CorrectiveActionOtherComments,
	[AffectsToe] = @AffectsToe,	
	[RiskAssessmentAttendee1Type] = @RiskAssessmentAttendee1Type,
	[RiskAssessmentAttendee1Name] = @RiskAssessmentAttendee1Name,
	[RiskAssessmentAttendee2Type] = @RiskAssessmentAttendee2Type,
	[RiskAssessmentAttendee2Name] = @RiskAssessmentAttendee2Name,
	[RiskAssessmentAttendee3Type] = @RiskAssessmentAttendee3Type,
	[RiskAssessmentAttendee3Name] = @RiskAssessmentAttendee3Name,
	[RiskAssessmentAttendee4Type] = @RiskAssessmentAttendee4Type,
	[RiskAssessmentAttendee4Name] = @RiskAssessmentAttendee4Name,
	[RiskAssessmentAnswer1] = @RiskAssessmentAnswer1,
	[RiskAssessmentAnswer2] = @RiskAssessmentAnswer2,
	[RiskAssessmentAnswer3] = @RiskAssessmentAnswer3,
	[RiskAssessmentAnswer4] = @RiskAssessmentAnswer4,
	[RiskAssessmentAnswer5] = @RiskAssessmentAnswer5,
	[RiskAssessmentComments] = @RiskAssessmentComments,
	[ImmediateApprovalsApprover1Type] = @ImmediateApprovalsApprover1Type,
	[ImmediateApprovalsApprover1Title] = @ImmediateApprovalsApprover1Title,
	[ImmediateApprovalsApprover1Name] = @ImmediateApprovalsApprover1Name,
	[ImmediateApprovalsApprover1ObtainedVia] = @ImmediateApprovalsApprover1ObtainedVia,
	[ImmediateApprovalsApprover1ApprovedDateTime] = @ImmediateApprovalsApprover1ApprovedDateTime,
	[ImmediateApprovalsApprover2Type] = @ImmediateApprovalsApprover2Type,
	[ImmediateApprovalsApprover2Title] = @ImmediateApprovalsApprover2Title,
	[ImmediateApprovalsApprover2Name] = @ImmediateApprovalsApprover2Name,
	[ImmediateApprovalsApprover2ObtainedVia] = @ImmediateApprovalsApprover2ObtainedVia,
	[ImmediateApprovalsApprover2ApprovedDateTime] = @ImmediateApprovalsApprover2ApprovedDateTime,
	[TemporaryApprovalsApprover1Type] = @TemporaryApprovalsApprover1Type,
	[TemporaryApprovalsApprover1Title] = @TemporaryApprovalsApprover1Title,
	[TemporaryApprovalsApprover1Name] = @TemporaryApprovalsApprover1Name,
	[TemporaryApprovalsApprover1ObtainedVia] = @TemporaryApprovalsApprover1ObtainedVia,
	[TemporaryApprovalsApprover1ApprovedDateTime] = @TemporaryApprovalsApprover1ApprovedDateTime,
	[TemporaryApprovalsApprover2Type] = @TemporaryApprovalsApprover2Type,
	[TemporaryApprovalsApprover2Title] = @TemporaryApprovalsApprover2Title,
	[TemporaryApprovalsApprover2Name] = @TemporaryApprovalsApprover2Name,
	[TemporaryApprovalsApprover2ObtainedVia] = @TemporaryApprovalsApprover2ObtainedVia,
	[TemporaryApprovalsApprover2ApprovedDateTime] = @TemporaryApprovalsApprover2ApprovedDateTime,
	[CancelledBy] = @CancelledBy,
	[CancelledDateTime] = @CancelledDateTime,
	[CancelledReason] = @CancelledReason
	WHERE
		Id = @Id
GO

GRANT EXEC ON UpdateProcedureDeviation TO PUBLIC
GO