CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmonton_PermitRequestId]
ON [dbo].[WorkPermitEdmonton]
([PermitRequestId])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
)
ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmonton_DTO_Covering]
ON [dbo].[WorkPermitEdmonton]
([FunctionalLocationId], [RequestedStartDateTime] , [ExpiredDateTime] , [Deleted])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
)
ON [PRIMARY];
GO


GO

