CREATE NONCLUSTERED INDEX [_dta_index_TargetAlert_DTO]
ON [dbo].[TargetAlert]
([CreatedDateTime] , [FunctionalLocationID] , [TargetAlertStatusID] , [ID])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
)
ON [PRIMARY];
GO