insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('1 PUMP OPERATION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('2 PUMP OPERATION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('3D-119', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('3D121', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('3D96', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('48A FX ROLL MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('48B MOV ROLL MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('49A FX ROLL MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('49B MOV ROLL MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('4G69', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('74B MVBL FL CPLG', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('75B MVBL FL CPLG', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('76B MVBL HT MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('77B MVBL HT MTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82G307A PRI G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82G307B SEC G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82TM50A PRIM DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82TM50B SEC DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82TM51A PRI DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('82TM51B SEC DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ACCIDENT', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AGITATORS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('APL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('APRON FEEDER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AUTO SAMPLER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAIL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAIL BIRDS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAIL INV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAIL INVENTORY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAIL PURGE GAS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('AVAILABILITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BANKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BAY CLEANUP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BELT TRIM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BIN HANGUPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BIN PLUGGED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEND BPT', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEND D50', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEND FINES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEND OXY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLENDING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEW NOZZLE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLEW RUP DISC', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BLOWERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BOLSTER MTCE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BRAKES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BREAKDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BRIDGING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BROKEN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('BUCKET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CABLES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CAPACITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CAPACITY SYSTEM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CLEAN UP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('COFFEE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONDENSATE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONV 12T, 403', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONV I2T, 403', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONVEYOR 3T-10', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONVEYOR 3T-251', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CONVEYORS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('COUPLING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CPW', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CPW SUPPLY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CT', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('CYCLONES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DECANT POND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DIL TK LOW INV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DIRECTION GATE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DISCHRG PRESSURE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DISCS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DIST 3D119', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DIVERTER GATE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DRUMS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DRYERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('DYKE REPAIRS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('EAST RUNDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ELEC/INST', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ELECT', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ELECT, 402', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('E-LINE CONTROL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('EMERG POND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ENG PROGRAMS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ENGINE MTCE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('EQUIP FAILURE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('EXCEED OP LINE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('EXCESSIVE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FALSE TRIP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FEED DISTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FEED HANGUPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FEED QUALITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FIXED ROLL E/I', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FLA', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FLUID COUPLING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FLUSHING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROTH PUMPING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROTH QUALITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROTH TRANSFER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROTH/TAILS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROTH/TAILS PUMP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROZEN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROZEN LUMP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FROZEN TARSAND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('FUEL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('G306A PRI G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('G306B SEC G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GEOSOL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GLAND WATER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GLAND WATER SYS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GLAND WATER/PACK', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GREASE SYSTEM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GREEN WOOD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GROUND PREP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('GYPSUM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HANGUP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HARD TARSAND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HEATERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HI  HOOD LVL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HI CHUTE LVL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH D50', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH DENSITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH HC', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH INV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH LEVEL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH MINERAL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH TAIL LOSS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH TORQUE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH WATER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HIGH WOOD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HOLES/TEAR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HPW', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HPW SUPPLY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYD RELIEF LEAKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYD RELIEF MTRS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYD ROLL RLF E/I', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYD STAB RAM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYD TILT RAM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYDR JACKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('HYDRAULICS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('INSTR AIR SUPPLY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('IST > 90%', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('JACKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('L5 RUNDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LIGHTS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE 5 (3C-20)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE 5 (3C-21)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE 5 (3C-22F)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE A/B(3C-22A)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE A/B/C/D', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE C/D(3C-22C)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE FROZEN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE LEAKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE PREP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE SANDED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LINE SWITCHES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW INV <44% LVL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW INV <50% LVL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW INV <55% LVL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW RECOVERY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW SUPPLY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LOW TEMP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LSD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LSD PREPARATION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LUBE SYSTEM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('LUMPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MECH SEAL LEAKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MEETINGS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('METAL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MISC', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MIST ISSUES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MOVABLE ROLL E/I', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MOVES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MTCE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MTCE BREAKDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MTCE OPPORTUNE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('MTCE SCHEDULED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('NAT GAS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('NO FEED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('NO TARSAND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('NOZZLE PLUGGAGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OFFLINE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OP ISSUE/PLUG', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ORE BLENDING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ORE HANG-UPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OTHER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OVERSIZE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OVERSIZE TRUCK', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('OVERTARGET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('P16 OUTAGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PACKING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PADS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PETRIFIED WOOD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PIPELINE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PIPES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PIPING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PIPING VALVES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PIPING/VALVES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLANNED PROD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLANT 89 RUNNING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG CHUTE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG O/F LAUNDER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG PANWASH', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG U/F BOOTS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUGGAGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUGGED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUGGED CYCLONES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG-METAL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PLUG-RICH FEED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('POND CAPACITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('POND PUMPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PONDS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('POWER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PRESERVED WOOD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PRODUCTION PLAN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PROPULSION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PULLEY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PULLEY CLEANERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PUMPING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PUMPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('PWR FAILURE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('QUALITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('QUALITY > 3% BSW', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('RAKES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('RD BACKPRESSURE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('RECOVERY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('RED RATE-LUMPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('RELOCATES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('REPLACE SEGMENTS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('REPLACE TIPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ROAD CONDITIONS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ROLLER JAM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ROLLERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SAGGING HEAD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SANDED', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-A', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-B', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-C', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-D', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-E', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-F', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-G', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-H', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-J', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-K', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-L', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-M', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-N', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-O', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCAV BANK-P', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCRAPERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCREENS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCROLL FLUID', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCROLL JAM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SCROLL MOTORS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SEAL WATER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SEP CELL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SEPARATION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHFT CHANGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHIFT CHANGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHOVEL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHOVELS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHRTGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHRTGE PWR, 400', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHRTGE PWR,400', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SHUTDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SIDE TRAVEL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SIZER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SLEW', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SLUDGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SPILLAGE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SPLITTERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('STABILIZERS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('STARTUP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('STEAM', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP (3D-10A)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP (3D-10B)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP (3D-10C)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP (3D-10D)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SUMP (3D-10E)', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SURGE PILE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('SYSTEM CAPACITY', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T72A FX SAFESET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T72B MVBL SF/SET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T73A FX SF/SET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T73B MVBL SF/SET', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T74A FX FL CPLG', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T75A FX FL CPLG', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T76A FX HT DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T76B MVBL HT DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T77A FX HT DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('T77B MVBL HT DRV', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TAILINGS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TANK LOW', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TEETH', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TEMPERATURE', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TENSION', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG44A GEAR RDCR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG44B GEAR RDCR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG45A GEAR RDCR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG45B GEAR RDCR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG48A FX G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG48B MVBL G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG49A FX G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TG49B MVBL G/BX', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TIPS AND CAPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM44A MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM44B MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM45A MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM45B MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM76A HT MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TM77A HT MOTOR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRAMP STEEL', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRIPPED - LUMPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRIPS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRUCKS', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRUCK-SHVL OBSTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('TRUCK-SZR OBSTR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('UTILITIES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('VALVES', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('VFD', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('VFD,401', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WASTE WATER POND', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WATER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WEAR', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WEATHER', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WEST FD H2O >35%', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WEST RUNDOWN', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('WINTER FLUSHING', -1, GetDate(), 0);
insert into RestrictionReasonCode (name, lastmodifieduserid, lastmodifieddatetime, deleted) values ('ZERO SPEED', -1, GetDate(), 0);

GO
