//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8813
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Suncor.Olt.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RendererStringResources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RendererStringResources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Suncor.Olt.Common.Localization.RendererStringResources_fr", typeof(RendererStringResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif à partir du.
        /// </summary>
        public static string ActiveFrom {
            get {
                return ResourceManager.GetString("ActiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif jusqu&apos;au.
        /// </summary>
        public static string ActiveTo {
            get {
                return ResourceManager.GetString("ActiveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réel.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre réel.
        /// </summary>
        public static string ActualNumber {
            get {
                return ResourceManager.GetString("ActualNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi supplémentaire requis.
        /// </summary>
        public static string AdditionalFollowUpRequired {
            get {
                return ResourceManager.GetString("AdditionalFollowUpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes catégories activités.
        /// </summary>
        public static string AllBusinessCategories {
            get {
                return ResourceManager.GetString("AllBusinessCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permettre la sélection manuelle.
        /// </summary>
        public static string AllowManualSelection {
            get {
                return ResourceManager.GetString("AllowManualSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable Sections.
        /// </summary>
        public static string ApplicableSections {
            get {
                return ResourceManager.GetString("ApplicableSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuvé.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuvé par.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approbateur.
        /// </summary>
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secteur émetteur.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre attribué.
        /// </summary>
        public static string AssignedAmount {
            get {
                return ResourceManager.GetString("AssignedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigné à.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignation.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories activités associées.
        /// </summary>
        public static string AssociatedBusinessCategories {
            get {
                return ResourceManager.GetString("AssociatedBusinessCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GN-75B Form.
        /// </summary>
        public static string AssociatedFormGN75BNumber {
            get {
                return ResourceManager.GetString("AssociatedFormGN75BNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code raison associé.
        /// </summary>
        public static string AssociatedReasonCode {
            get {
                return ResourceManager.GetString("AssociatedReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT associé code raison.
        /// </summary>
        public static string AssociatedReasonCodeFloc {
            get {
                return ResourceManager.GetString("AssociatedReasonCodeFloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion automatique de ce  gabarit de registre.
        /// </summary>
        public static string AutoInsertTheLogTemplateForThisAssignment {
            get {
                return ResourceManager.GetString("AutoInsertTheLogTemplateForThisAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison disponibilité.
        /// </summary>
        public static string AvailabilityReason {
            get {
                return ResourceManager.GetString("AvailabilityReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires disponibles.
        /// </summary>
        public static string AvailableQuestionnaires {
            get {
                return ResourceManager.GetString("AvailableQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc terminé.
        /// </summary>
        public static string BlockCompleted {
            get {
                return ResourceManager.GetString("BlockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie activité.
        /// </summary>
        public static string BusinessCategory {
            get {
                return ResourceManager.GetString("BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulé.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur modifiée.
        /// </summary>
        public static string ChangedValue {
            get {
                return ResourceManager.GetString("ChangedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermé Par.
        /// </summary>
        public static string ClosedBy {
            get {
                return ResourceManager.GetString("ClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fermeture.
        /// </summary>
        public static string ClosedDate {
            get {
                return ResourceManager.GetString("ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiches de cokeur.
        /// </summary>
        public static string CokerCard {
            get {
                return ResourceManager.GetString("CokerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarques.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espace clos.
        /// </summary>
        public static string ConfinedSpace {
            get {
                return ResourceManager.GetString("ConfinedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compagnie.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corps de métier.
        /// </summary>
        public static string Craft {
            get {
                return ResourceManager.GetString("Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier.
        /// </summary>
        public static string CraftTrade {
            get {
                return ResourceManager.GetString("CraftTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche créée.
        /// </summary>
        public static string CreatedAssignment {
            get {
                return ResourceManager.GetString("CreatedAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date création.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/heure création.
        /// </summary>
        public static string CreatedDateTime {
            get {
                return ResourceManager.GetString("CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality.
        /// </summary>
        public static string Criticality {
            get {
                return ResourceManager.GetString("Criticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe champs personnalisés.
        /// </summary>
        public static string CustomFieldGroup {
            get {
                return ResourceManager.GetString("CustomFieldGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étape de cycle.
        /// </summary>
        public static string CycleStep {
            get {
                return ResourceManager.GetString("CycleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d’approbation.
        /// </summary>
        public static string DateApproved {
            get {
                return ResourceManager.GetString("DateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/heure.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écart.
        /// </summary>
        public static string Deviation {
            get {
                return ResourceManager.GetString("Deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure d&apos;instruction.
        /// </summary>
        public static string DirectiveDateTime {
            get {
                return ResourceManager.GetString("DirectiveDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable On.
        /// </summary>
        public static string DisableOn {
            get {
                return ResourceManager.GetString("DisableOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A répondu non à toutes les questions.
        /// </summary>
        public static string DoesNotHaveAYesAnswer {
            get {
                return ResourceManager.GetString("DoesNotHaveAYesAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fût.
        /// </summary>
        public static string Drum {
            get {
                return ResourceManager.GetString("Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date la plus proche.
        /// </summary>
        public static string EarliestDate {
            get {
                return ResourceManager.GetString("EarliestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié par.
        /// </summary>
        public static string EditedBy {
            get {
                return ResourceManager.GetString("EditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP.
        /// </summary>
        public static string EHS {
            get {
                return ResourceManager.GetString("EHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élément.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses de courriel.
        /// </summary>
        public static string EmailAddresses {
            get {
                return ResourceManager.GetString("EmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de fin.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;équipement.
        /// </summary>
        public static string EquipmentType {
            get {
                return ResourceManager.GetString("EquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date remise en service prévue.
        /// </summary>
        public static string EstimatedBackInService {
            get {
                return ResourceManager.GetString("EstimatedBackInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur réelle.
        /// </summary>
        public static string ExcelHeading_ActualValue {
            get {
                return ResourceManager.GetString("ExcelHeading_ActualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur réelle (enfreinte).
        /// </summary>
        public static string ExcelHeading_ActualValueViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_ActualValueViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse.
        /// </summary>
        public static string ExcelHeading_Answer {
            get {
                return ResourceManager.GetString("ExcelHeading_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By Name.
        /// </summary>
        public static string ExcelHeading_ApprovedByName {
            get {
                return ResourceManager.GetString("ExcelHeading_ApprovedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By Work Assignment.
        /// </summary>
        public static string ExcelHeading_ApprovedByWorkAssignment {
            get {
                return ResourceManager.GetString("ExcelHeading_ApprovedByWorkAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date/Time.
        /// </summary>
        public static string ExcelHeading_ApprovedDateTime {
            get {
                return ResourceManager.GetString("ExcelHeading_ApprovedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre attribué.
        /// </summary>
        public static string ExcelHeading_AssignedAmount {
            get {
                return ResourceManager.GetString("ExcelHeading_AssignedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignation.
        /// </summary>
        public static string ExcelHeading_Assignment {
            get {
                return ResourceManager.GetString("ExcelHeading_Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string ExcelHeading_Block {
            get {
                return ResourceManager.GetString("ExcelHeading_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Completed.
        /// </summary>
        public static string ExcelHeading_BlockCompleted {
            get {
                return ResourceManager.GetString("ExcelHeading_BlockCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string ExcelHeading_Comments {
            get {
                return ResourceManager.GetString("ExcelHeading_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par.
        /// </summary>
        public static string ExcelHeading_CreatedBy {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Badge.
        /// </summary>
        public static string ExcelHeading_CreatedByBadge {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedByBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Name.
        /// </summary>
        public static string ExcelHeading_CreatedByName {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Work Assignment.
        /// </summary>
        public static string ExcelHeading_CreatedByWorkAssignment {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedByWorkAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date création.
        /// </summary>
        public static string ExcelHeading_CreatedDate {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/heure créée.
        /// </summary>
        public static string ExcelHeading_CreatedDateTime {
            get {
                return ResourceManager.GetString("ExcelHeading_CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string ExcelHeading_Cycle {
            get {
                return ResourceManager.GetString("ExcelHeading_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ExcelHeading_Date {
            get {
                return ResourceManager.GetString("ExcelHeading_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définition active.
        /// </summary>
        public static string ExcelHeading_DefinitionActive {
            get {
                return ResourceManager.GetString("ExcelHeading_DefinitionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de définition.
        /// </summary>
        public static string ExcelHeading_DefinitionName {
            get {
                return ResourceManager.GetString("ExcelHeading_DefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ExcelHeading_Description {
            get {
                return ResourceManager.GetString("ExcelHeading_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur de cible.
        /// </summary>
        public static string ExcelHeading_DeviationAmount {
            get {
                return ResourceManager.GetString("ExcelHeading_DeviationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste technique de l&apos;écart.
        /// </summary>
        public static string ExcelHeading_DeviationFunctionalLocation {
            get {
                return ResourceManager.GetString("ExcelHeading_DeviationFunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID écart.
        /// </summary>
        public static string ExcelHeading_DeviationId {
            get {
                return ResourceManager.GetString("ExcelHeading_DeviationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;écart.
        /// </summary>
        public static string ExcelHeading_DeviationName {
            get {
                return ResourceManager.GetString("ExcelHeading_DeviationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction quotidienne.
        /// </summary>
        public static string ExcelHeading_Directive {
            get {
                return ResourceManager.GetString("ExcelHeading_Directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string ExcelHeading_Division {
            get {
                return ResourceManager.GetString("ExcelHeading_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballon.
        /// </summary>
        public static string ExcelHeading_Drum {
            get {
                return ResourceManager.GetString("ExcelHeading_Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié par.
        /// </summary>
        public static string ExcelHeading_EditedBy {
            get {
                return ResourceManager.GetString("ExcelHeading_EditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de fin.
        /// </summary>
        public static string ExcelHeading_End {
            get {
                return ResourceManager.GetString("ExcelHeading_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de fin.
        /// </summary>
        public static string ExcelHeading_EndTime {
            get {
                return ResourceManager.GetString("ExcelHeading_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement 1.
        /// </summary>
        public static string ExcelHeading_Equipment1 {
            get {
                return ResourceManager.GetString("ExcelHeading_Equipment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipement 2.
        /// </summary>
        public static string ExcelHeading_Equipment2 {
            get {
                return ResourceManager.GetString("ExcelHeading_Equipment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT .
        /// </summary>
        public static string ExcelHeading_FLOC {
            get {
                return ResourceManager.GetString("ExcelHeading_FLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form #.
        /// </summary>
        public static string ExcelHeading_FormNumber {
            get {
                return ResourceManager.GetString("ExcelHeading_FormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif d&apos;écart.
        /// </summary>
        public static string ExcelHeading_GapReason {
            get {
                return ResourceManager.GetString("ExcelHeading_GapReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Comments.
        /// </summary>
        public static string ExcelHeading_GeneralComments {
            get {
                return ResourceManager.GetString("ExcelHeading_GeneralComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écart caché.
        /// </summary>
        public static string ExcelHeading_HiddenDeviation {
            get {
                return ResourceManager.GetString("ExcelHeading_HiddenDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière enfreint.
        /// </summary>
        public static string ExcelHeading_LastViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_LastViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre.
        /// </summary>
        public static string ExcelHeading_Log {
            get {
                return ResourceManager.GetString("ExcelHeading_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de registre.
        /// </summary>
        public static string ExcelHeading_LogDate {
            get {
                return ResourceManager.GetString("ExcelHeading_LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure marquée comme lue.
        /// </summary>
        public static string ExcelHeading_MarkedAsReadTime {
            get {
                return ResourceManager.GetString("ExcelHeading_MarkedAsReadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max (enfreint).
        /// </summary>
        public static string ExcelHeading_MaxViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_MaxViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette - mesure.
        /// </summary>
        public static string ExcelHeading_MeasuredTag {
            get {
                return ResourceManager.GetString("ExcelHeading_MeasuredTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur mesurée.
        /// </summary>
        public static string ExcelHeading_MeasuredValue {
            get {
                return ResourceManager.GetString("ExcelHeading_MeasuredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min (enfreint).
        /// </summary>
        public static string ExcelHeading_MinViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_MinViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string ExcelHeading_Name {
            get {
                return ResourceManager.GetString("ExcelHeading_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTE/SOL max (enfreint).
        /// </summary>
        public static string ExcelHeading_NTESOLMaxViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_NTESOLMaxViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTE/SOL min (enfreint).
        /// </summary>
        public static string ExcelHeading_NTESOLMinViolated {
            get {
                return ResourceManager.GetString("ExcelHeading_NTESOLMinViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État de l&apos;installation.
        /// </summary>
        public static string ExcelHeading_PlantState {
            get {
                return ResourceManager.GetString("ExcelHeading_PlantState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de raison.
        /// </summary>
        public static string ExcelHeading_ReasonCode {
            get {
                return ResourceManager.GetString("ExcelHeading_ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de raison Poste technique.
        /// </summary>
        public static string ExcelHeading_ReasonCodeFunctionalLocation {
            get {
                return ResourceManager.GetString("ExcelHeading_ReasonCodeFunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur de la réponse.
        /// </summary>
        public static string ExcelHeading_Responder {
            get {
                return ResourceManager.GetString("ExcelHeading_Responder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / heure de la réponse.
        /// </summary>
        public static string ExcelHeading_ResponseDateTime {
            get {
                return ResourceManager.GetString("ExcelHeading_ResponseDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte de la réponse.
        /// </summary>
        public static string ExcelHeading_ResponseText {
            get {
                return ResourceManager.GetString("ExcelHeading_ResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string ExcelHeading_Section {
            get {
                return ResourceManager.GetString("ExcelHeading_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quart.
        /// </summary>
        public static string ExcelHeading_Shift {
            get {
                return ResourceManager.GetString("ExcelHeading_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        public static string ExcelHeading_Site {
            get {
                return ResourceManager.GetString("ExcelHeading_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de début.
        /// </summary>
        public static string ExcelHeading_Start {
            get {
                return ResourceManager.GetString("ExcelHeading_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de début.
        /// </summary>
        public static string ExcelHeading_StartTime {
            get {
                return ResourceManager.GetString("ExcelHeading_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string ExcelHeading_Status {
            get {
                return ResourceManager.GetString("ExcelHeading_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette.
        /// </summary>
        public static string ExcelHeading_Tag {
            get {
                return ResourceManager.GetString("ExcelHeading_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette de cible.
        /// </summary>
        public static string ExcelHeading_TargetTag {
            get {
                return ResourceManager.GetString("ExcelHeading_TargetTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur de cible.
        /// </summary>
        public static string ExcelHeading_TargetValue {
            get {
                return ResourceManager.GetString("ExcelHeading_TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string ExcelHeading_TotalHours {
            get {
                return ResourceManager.GetString("ExcelHeading_TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Block Comments.
        /// </summary>
        public static string ExcelHeading_TrainingBlockComments {
            get {
                return ResourceManager.GetString("ExcelHeading_TrainingBlockComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Code.
        /// </summary>
        public static string ExcelHeading_TrainingCode {
            get {
                return ResourceManager.GetString("ExcelHeading_TrainingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Date.
        /// </summary>
        public static string ExcelHeading_TrainingDate {
            get {
                return ResourceManager.GetString("ExcelHeading_TrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ExcelHeading_Type {
            get {
                return ResourceManager.GetString("ExcelHeading_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string ExcelHeading_Unit {
            get {
                return ResourceManager.GetString("ExcelHeading_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur.
        /// </summary>
        public static string ExcelHeading_User {
            get {
                return ResourceManager.GetString("ExcelHeading_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport de fiche du cokeur.
        /// </summary>
        public static string ExcelTab_CokerCardReport {
            get {
                return ResourceManager.GetString("ExcelTab_CokerCardReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions quotidiennes.
        /// </summary>
        public static string ExcelTab_Directives {
            get {
                return ResourceManager.GetString("ExcelTab_Directives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registres.
        /// </summary>
        public static string ExcelTab_Logs {
            get {
                return ResourceManager.GetString("ExcelTab_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport de restriction.
        /// </summary>
        public static string ExcelTab_RestrictionReport {
            get {
                return ResourceManager.GetString("ExcelTab_RestrictionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relève de quart.
        /// </summary>
        public static string ExcelTab_ShiftHandover {
            get {
                return ResourceManager.GetString("ExcelTab_ShiftHandover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport d&apos;alertes cibles.
        /// </summary>
        public static string ExcelTab_TargetAlertReport {
            get {
                return ResourceManager.GetString("ExcelTab_TargetAlertReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d’expiration.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du champ.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres section (2e niveau PT).
        /// </summary>
        public static string FilterSectionItem {
            get {
                return ResourceManager.GetString("FilterSectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres unité (3e niveau PT).
        /// </summary>
        public static string FilterUnitItem {
            get {
                return ResourceManager.GetString("FilterUnitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicateur.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        public static string Floc {
            get {
                return ResourceManager.GetString("Floc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT (Description).
        /// </summary>
        public static string FlocDescription {
            get {
                return ResourceManager.GetString("FlocDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi.
        /// </summary>
        public static string Follow_up {
            get {
                return ResourceManager.GetString("Follow-up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi requis.
        /// </summary>
        public static string FollowupRequired {
            get {
                return ResourceManager.GetString("FollowupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No de formule.
        /// </summary>
        public static string FormNumber {
            get {
                return ResourceManager.GetString("FormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de formule.
        /// </summary>
        public static string FormType {
            get {
                return ResourceManager.GetString("FormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste technique.
        /// </summary>
        public static string FunctionalLocation {
            get {
                return ResourceManager.GetString("FunctionalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postes techniques.
        /// </summary>
        public static string FunctionalLocations {
            get {
                return ResourceManager.GetString("FunctionalLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur écart de l&apos;unité.
        /// </summary>
        public static string Guv {
            get {
                return ResourceManager.GetString("Guv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A répondu oui à une question.
        /// </summary>
        public static string HasAYesAnswer {
            get {
                return ResourceManager.GetString("HasAYesAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training hours are irregular.
        /// </summary>
        public static string HasIrregularHours {
            get {
                return ResourceManager.GetString("HasIrregularHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazards and/or Requirements.
        /// </summary>
        public static string HazardsAndOrRequirements {
            get {
                return ResourceManager.GetString("HazardsAndOrRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte aide.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;heures.
        /// </summary>
        public static string HoursIntoLastCycle {
            get {
                return ResourceManager.GetString("HoursIntoLastCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILP was not recommended.
        /// </summary>
        public static string IlpIsNotRecommended {
            get {
                return ResourceManager.GetString("IlpIsNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILP was recommended.
        /// </summary>
        public static string IlpIsRecommended {
            get {
                return ResourceManager.GetString("IlpIsRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aire immédiate.
        /// </summary>
        public static string ImmediateArea {
            get {
                return ResourceManager.GetString("ImmediateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactif.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code incident.
        /// </summary>
        public static string IncidentId {
            get {
                return ResourceManager.GetString("IncidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancé par.
        /// </summary>
        public static string InitiatedBy {
            get {
                return ResourceManager.GetString("InitiatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans le fil.
        /// </summary>
        public static string InThread {
            get {
                return ResourceManager.GetString("InThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILP Recommended.
        /// </summary>
        public static string IsIlpRecommended {
            get {
                return ResourceManager.GetString("IsIlpRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Émis.
        /// </summary>
        public static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Émis par.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;émission.
        /// </summary>
        public static string IssuedDate {
            get {
                return ResourceManager.GetString("IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étapes travail.
        /// </summary>
        public static string JobSteps {
            get {
                return ResourceManager.GetString("JobSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier cycle.
        /// </summary>
        public static string LastCycleStep {
            get {
                return ResourceManager.GetString("LastCycleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier éditeur.
        /// </summary>
        public static string LastEditor {
            get {
                return ResourceManager.GetString("LastEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière importation.
        /// </summary>
        public static string LastImported {
            get {
                return ResourceManager.GetString("LastImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importé par.
        /// </summary>
        public static string LastImportedBy {
            get {
                return ResourceManager.GetString("LastImportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification par.
        /// </summary>
        public static string LastModifiedBy {
            get {
                return ResourceManager.GetString("LastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière soumission.
        /// </summary>
        public static string LastSubmitted {
            get {
                return ResourceManager.GetString("LastSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumis par.
        /// </summary>
        public static string LastSubmittedBy {
            get {
                return ResourceManager.GetString("LastSubmittedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière enfreint.
        /// </summary>
        public static string LastViolatedDateTime {
            get {
                return ResourceManager.GetString("LastViolatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date limite.
        /// </summary>
        public static string LatestDate {
            get {
                return ResourceManager.GetString("LatestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de registre.
        /// </summary>
        public static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de registre.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertes.
        /// </summary>
        public static string Losses {
            get {
                return ResourceManager.GetString("Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations non manuelles.
        /// </summary>
        public static string ManualNonOperations {
            get {
                return ResourceManager.GetString("ManualNonOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations manuelles.
        /// </summary>
        public static string ManualOperations {
            get {
                return ResourceManager.GetString("ManualOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesure.
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette - mesure.
        /// </summary>
        public static string MeasurementTag {
            get {
                return ResourceManager.GetString("MeasurementTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre minimal.
        /// </summary>
        public static string MinNumber {
            get {
                return ResourceManager.GetString("MinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTE/SOL Max.
        /// </summary>
        public static string NeverToExceedMax {
            get {
                return ResourceManager.GetString("NeverToExceedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTE/SOL Min.
        /// </summary>
        public static string NeverToExceedMin {
            get {
                return ResourceManager.GetString("NeverToExceedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun suivi supplémentaire requis.
        /// </summary>
        public static string NoAdditionalFollowUpRequired {
            get {
                return ResourceManager.GetString("NoAdditionalFollowUpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun suivi.
        /// </summary>
        public static string NoFollowUp {
            get {
                return ResourceManager.GetString("NoFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non dans le fil.
        /// </summary>
        public static string NotInThread {
            get {
                return ResourceManager.GetString("NotInThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode opérationnel.
        /// </summary>
        public static string OperationalMode {
            get {
                return ResourceManager.GetString("OperationalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. d&apos;opération.
        /// </summary>
        public static string OperationNumber {
            get {
                return ResourceManager.GetString("OperationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur initiale.
        /// </summary>
        public static string OriginalValue {
            get {
                return ResourceManager.GetString("OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Feedback.
        /// </summary>
        public static string OverallFeedback {
            get {
                return ResourceManager.GetString("OverallFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids %.
        /// </summary>
        public static string PercentageWeighting {
            get {
                return ResourceManager.GetString("PercentageWeighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptation du permis.
        /// </summary>
        public static string PermitAcceptor {
            get {
                return ResourceManager.GetString("PermitAcceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro permis.
        /// </summary>
        public static string PermitNumber {
            get {
                return ResourceManager.GetString("PermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Type.
        /// </summary>
        public static string PermitType {
            get {
                return ResourceManager.GetString("PermitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette pH.
        /// </summary>
        public static string PHTag {
            get {
                return ResourceManager.GetString("PHTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État de l&apos;installation.
        /// </summary>
        public static string PlantState {
            get {
                return ResourceManager.GetString("PlantState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglet principal par défaut.
        /// </summary>
        public static string PrimaryDefaultTab {
            get {
                return ResourceManager.GetString("PrimaryDefaultTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorité.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle de production.
        /// </summary>
        public static string ProcessControl {
            get {
                return ResourceManager.GetString("ProcessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cible de production.
        /// </summary>
        public static string ProductionTarget {
            get {
                return ResourceManager.GetString("ProductionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider_fr_olt.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSV.
        /// </summary>
        public static string PSV {
            get {
                return ResourceManager.GetString("PSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponses aux questions.
        /// </summary>
        public static string QuestionResponses {
            get {
                return ResourceManager.GetString("QuestionResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte - question.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de raison.
        /// </summary>
        public static string ReasonCode {
            get {
                return ResourceManager.GetString("ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommander pour
        ///registres des superviseurs.
        /// </summary>
        public static string RecommendedForSummary {
            get {
                return ResourceManager.GetString("RecommendedForSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommander pour registres des superviseurs.
        /// </summary>
        public static string RecommendedForSummary_NoNewLines {
            get {
                return ResourceManager.GetString("RecommendedForSummary_NoNewLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommander pour superviseurs.
        /// </summary>
        public static string RecommendedForSummaryHeading {
            get {
                return ResourceManager.GetString("RecommendedForSummaryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Périodique.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approbations restantes.
        /// </summary>
        public static string RemainingApprovals {
            get {
                return ResourceManager.GetString("RemainingApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandé.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandé par.
        /// </summary>
        public static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandé par l&apos;utilisateur.
        /// </summary>
        public static string RequestedByUser {
            get {
                return ResourceManager.GetString("RequestedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date demandée.
        /// </summary>
        public static string RequestedDate {
            get {
                return ResourceManager.GetString("RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approbation requise.
        /// </summary>
        public static string RequiresApproval {
            get {
                return ResourceManager.GetString("RequiresApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nécessite suivi :.
        /// </summary>
        public static string RequiresFollowUp {
            get {
                return ResourceManager.GetString("RequiresFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse requise.
        /// </summary>
        public static string ResponseRequired {
            get {
                return ResourceManager.GetString("ResponseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définition de restriction.
        /// </summary>
        public static string RestrictionDefinition {
            get {
                return ResourceManager.GetString("RestrictionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôle.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP.
        /// </summary>
        public static string SAP {
            get {
                return ResourceManager.GetString("SAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Notification.
        /// </summary>
        public static string SapNotification {
            get {
                return ResourceManager.GetString("SapNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification SAP par défaut.
        /// </summary>
        public static string SAPNotificationDefault {
            get {
                return ResourceManager.GetString("SAPNotificationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe de planification SAP.
        /// </summary>
        public static string SAPPlannerGroup {
            get {
                return ResourceManager.GetString("SAPPlannerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordre exécution SAP par défaut.
        /// </summary>
        public static string SAPWorkOrderDefault {
            get {
                return ResourceManager.GetString("SAPWorkOrderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordonnancement.
        /// </summary>
        public static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglet secondaire par défaut.
        /// </summary>
        public static string SecondaryDefaultTab {
            get {
                return ResourceManager.GetString("SecondaryDefaultTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT niveau section.
        /// </summary>
        public static string SectionLevelFloc {
            get {
                return ResourceManager.GetString("SectionLevelFloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionné.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure d&apos;envoi.
        /// </summary>
        public static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quart.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe de quart.
        /// </summary>
        public static string ShiftGroup {
            get {
                return ResourceManager.GetString("ShiftGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom abrégé.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponctuel.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de début.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumis par l&apos;utilisateur.
        /// </summary>
        public static string SubmittedByUser {
            get {
                return ResourceManager.GetString("SubmittedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervision.
        /// </summary>
        public static string Supervision {
            get {
                return ResourceManager.GetString("Supervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de Mise hors Service.
        /// </summary>
        public static string SystemDefeated {
            get {
                return ResourceManager.GetString("SystemDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée système.
        /// </summary>
        public static string SystemEntry {
            get {
                return ResourceManager.GetString("SystemEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipment hors service.
        /// </summary>
        public static string SystemToBeDefeated {
            get {
                return ResourceManager.GetString("SystemToBeDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom étiquette.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cible.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de cible.
        /// </summary>
        public static string TargetName {
            get {
                return ResourceManager.GetString("TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string TemplateNumber {
            get {
                return ResourceManager.GetString("TemplateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporairement désactivé.
        /// </summary>
        public static string TemporarilyInnactive {
            get {
                return ResourceManager.GetString("TemporarilyInnactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total des heures.
        /// </summary>
        public static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métiers.
        /// </summary>
        public static string Trades {
            get {
                return ResourceManager.GetString("Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc de formation.
        /// </summary>
        public static string TrainingBlock {
            get {
                return ResourceManager.GetString("TrainingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de la formation.
        /// </summary>
        public static string TrainingCode {
            get {
                return ResourceManager.GetString("TrainingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la formation.
        /// </summary>
        public static string TrainingDate {
            get {
                return ResourceManager.GetString("TrainingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin.
        /// </summary>
        public static string UNCPath {
            get {
                return ResourceManager.GetString("UNCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unités.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom utilisateur.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valide à partir du.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valide jusqu’au.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes .
        /// </summary>
        public static string VisibilityGroups {
            get {
                return ResourceManager.GetString("VisibilityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toujours Visible.
        /// </summary>
        public static string VisibleAlways {
            get {
                return ResourceManager.GetString("VisibleAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible uniquement dans les rapports.
        /// </summary>
        public static string VisibleOnlyOnReports {
            get {
                return ResourceManager.GetString("VisibleOnlyOnReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertir si assignation permis travail n&apos;est pas sélectionné pendant la registre.
        /// </summary>
        public static string WarnIfWorkAssignmentIsNotSelectedDuringLogIn {
            get {
                return ResourceManager.GetString("WarnIfWorkAssignmentIsNotSelectedDuringLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ordre exéc..
        /// </summary>
        public static string WODescription {
            get {
                return ResourceManager.GetString("WODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. ordre.
        /// </summary>
        public static string WONumber {
            get {
                return ResourceManager.GetString("WONumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aire des travaux.
        /// </summary>
        public static string WorkArea {
            get {
                return ResourceManager.GetString("WorkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignation.
        /// </summary>
        public static string WorkAssignment {
            get {
                return ResourceManager.GetString("WorkAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignations tâches.
        /// </summary>
        public static string WorkAssignments {
            get {
                return ResourceManager.GetString("WorkAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre de Travail.
        /// </summary>
        public static string WorkCentre {
            get {
                return ResourceManager.GetString("WorkCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ordre exécution.
        /// </summary>
        public static string WorkOrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui Non.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
