update WorkAssignment set Name = 'AM-OMD', RoleId = 1, Category = 'General' where Name = 'AM-OMD' and SiteId = 2 and Description = 'OMD Area Manager/Superintendent'
update WorkAssignment set Name = 'Chief - EP/AU', RoleId = 2, Category = 'General' where Name = 'CH' and SiteId = 2 and Description = 'Chief - EP/AU'
update WorkAssignment set Name = 'Chief - HO', RoleId = 2, Category = 'General' where Name = 'CH' and SiteId = 2 and Description = 'Chief - HO'
update WorkAssignment set Name = 'Chief - LO', RoleId = 2, Category = 'General' where Name = 'CH' and SiteId = 2 and Description = 'Chief - LO'
update WorkAssignment set Name = 'Chief - OMD', RoleId = 2, Category = 'General' where Name = 'CH' and SiteId = 2 and Description = 'Chief - OMD'
update WorkAssignment set Name = 'Controlman A - EP/AU', RoleId = 2, Category = 'General' where Name = 'CA' and SiteId = 2 and Description = 'Controlman A - EP/AU'
update WorkAssignment set Name = 'Controlman B - EP/AU', RoleId = 2, Category = 'General' where Name = 'CB' and SiteId = 2 and Description = 'Controlman B - EP/AU'
update WorkAssignment set Name = 'Crude - EP/AU', RoleId = 2, Category = 'General' where Name = 'CR' and SiteId = 2 and Description = 'Crude - EP/AU'
update WorkAssignment set Name = 'FCC - EP/AU', RoleId = 2, Category = 'General' where Name = 'FC' and SiteId = 2 and Description = 'FCC - EP/AU'
update WorkAssignment set Name = 'General Operator - EP/AU', RoleId = 2, Category = 'General' where Name = 'GO' and SiteId = 2 and Description = 'General Operator - EP/AU'
update WorkAssignment set Name = 'Lead Operator - EP/AU', RoleId = 2, Category = 'General' where Name = 'LD' and SiteId = 2 and Description = 'Lead Operator - EP/AU'
update WorkAssignment set Name = 'OMD East Supervisor', RoleId = 1, Category = 'General' where Name = 'PS-East' and SiteId = 2 and Description = 'OMD East Supervisor'
update WorkAssignment set Name = 'Operations Planning', RoleId = 2, Category = 'General' where Name = 'OP' and SiteId = 2 and Description = 'Operations Planning'
update WorkAssignment set Name = 'Operator A - HO', RoleId = 2, Category = 'General' where Name = 'A' and SiteId = 2 and Description = 'Operator A - HO'
update WorkAssignment set Name = 'Operator A - LO', RoleId = 2, Category = 'General' where Name = 'A' and SiteId = 2 and Description = 'Operator A - LO'
update WorkAssignment set Name = 'Operator A - OMD', RoleId = 2, Category = 'General' where Name = 'A' and SiteId = 2 and Description = 'Operator A - OMD'
update WorkAssignment set Name = 'Operator A- EP/AU', RoleId = 2, Category = 'General' where Name = 'A' and SiteId = 2 and Description = 'Operator A- EP/AU'
update WorkAssignment set Name = 'Operator B - HO', RoleId = 2, Category = 'General' where Name = 'B' and SiteId = 2 and Description = 'Operator B - HO'
update WorkAssignment set Name = 'Operator B - LO', RoleId = 2, Category = 'General' where Name = 'B' and SiteId = 2 and Description = 'Operator B - LO'
update WorkAssignment set Name = 'Operator B - OMD', RoleId = 2, Category = 'General' where Name = 'B' and SiteId = 2 and Description = 'Operator B - OMD'
update WorkAssignment set Name = 'Operator C - HO', RoleId = 2, Category = 'General' where Name = 'C' and SiteId = 2 and Description = 'Operator C - HO'
update WorkAssignment set Name = 'Operator C - LO', RoleId = 2, Category = 'General' where Name = 'C' and SiteId = 2 and Description = 'Operator C - LO'
update WorkAssignment set Name = 'Operator D - HO', RoleId = 2, Category = 'General' where Name = 'D' and SiteId = 2 and Description = 'Operator D - HO'
update WorkAssignment set Name = 'Operator D - LO', RoleId = 2, Category = 'General' where Name = 'D' and SiteId = 2 and Description = 'Operator D - LO'
update WorkAssignment set Name = 'Poly - EP/AU', RoleId = 2, Category = 'General' where Name = 'PY' and SiteId = 2 and Description = 'Poly - EP/AU'
update WorkAssignment set Name = 'Pumber B - Oil Movements', RoleId = 2, Category = 'General' where Name = 'PB' and SiteId = 2 and Description = 'Pumber B - Oil Movements'
update WorkAssignment set Name = 'Pumper A - Oil Movements', RoleId = 2, Category = 'General' where Name = 'PA' and SiteId = 2 and Description = 'Pumper A - Oil Movements'
update WorkAssignment set Name = 'Pumper Helper - Oil Movements', RoleId = 2, Category = 'General' where Name = 'PM' and SiteId = 2 and Description = 'Pumper Helper - Oil Movements'
update WorkAssignment set Name = 'Reformer - EP/AU', RoleId = 2, Category = 'General' where Name = 'RF' and SiteId = 2 and Description = 'Reformer - EP/AU'
update WorkAssignment set Name = 'Shift Supervisor East', RoleId = 1, Category = 'General' where Name = 'SS-East' and SiteId = 2 and Description = 'Shift Supervisor East'
update WorkAssignment set Name = 'Shift Supervisor West', RoleId = 1, Category = 'General' where Name = 'SS-West' and SiteId = 2 and Description = 'Shift Supervisor West'
update WorkAssignment set Name = 'test', RoleId = 2, Category = 'General' where Name = 'test' and SiteId = 2 and Description = 'test'
update WorkAssignment set Name = 'Trainee - HO', RoleId = 7, Category = 'General' where Name = 'TE' and SiteId = 2 and Description = 'Trainee - HO'
update WorkAssignment set Name = 'Trainee - LO', RoleId = 7, Category = 'General' where Name = 'TE' and SiteId = 2 and Description = 'Trainee - LO'
update WorkAssignment set Name = 'Trainee - OMD', RoleId = 7, Category = 'General' where Name = 'TE' and SiteId = 2 and Description = 'Trainee - OMD'
update WorkAssignment set Name = 'Turnaround - HO', RoleId = 2, Category = 'General' where Name = 'TU' and SiteId = 2 and Description = 'Turnaround - HO'
update WorkAssignment set Name = 'Turnaround - LO', RoleId = 2, Category = 'General' where Name = 'TU' and SiteId = 2 and Description = 'Turnaround - LO'
update WorkAssignment set Name = 'Turnaround - OMD', RoleId = 2, Category = 'General' where Name = 'TU' and SiteId = 2 and Description = 'Turnaround - OMD'
update WorkAssignment set Name = 'Turnaround- EP/AU', RoleId = 2, Category = 'General' where Name = 'TU' and SiteId = 2 and Description = 'Turnaround- EP/AU'
update WorkAssignment set Name = 'Utilities - EP/AU', RoleId = 2, Category = 'General' where Name = 'US' and SiteId = 2 and Description = 'Utilities - EP/AU'
update WorkAssignment set Name = 'West Plant Environmental Operator', RoleId = 2, Category = 'General' where Name = 'ENV-West' and SiteId = 2 and Description = 'West Plant Environmental Operator'
update WorkAssignment set Name = '91-1000 Area FLOC''s', RoleId = 2, Category = 'General' where Name = '91-1000 Area FLOC''s' and SiteId = 5 and Description = 'This will load the FLOC''s specific to th'
update WorkAssignment set Name = '91-3000 Area FLOC''s', RoleId = 2, Category = 'General' where Name = '91-3000 Area FLOC''s' and SiteId = 5 and Description = 'This will load the FLOC''s specific to th'
update WorkAssignment set Name = '92-1000 Area FLOC''s', RoleId = 2, Category = 'General' where Name = '92-1000 Area FLOC''s' and SiteId = 5 and Description = 'This will load the FLOC''s specific to the 92-1000 Area'
update WorkAssignment set Name = 'Plant 91 Control Room', RoleId = 2, Category = 'General' where Name = 'Plant 91 Control Room' and SiteId = 5 and Description = 'This will load the FLOC''s associated wit'
update WorkAssignment set Name = 'Plant 92 Control Room', RoleId = 2, Category = 'General' where Name = 'Plant 92 Control Room' and SiteId = 5 and Description = 'This will load the FLOC''s that are associated with plant 92'
update WorkAssignment set Name = 'Alkylation Unit', RoleId = 2, Category = 'General' where Name = 'WB' and SiteId = 1 and Description = 'Alkylation Unit'
update WorkAssignment set Name = 'Applications Plant 3/4', RoleId = 2, Category = 'General' where Name = 'Applications Plant 3/4' and SiteId = 1 and Description = 'Default FLOCs for Plant 3/4 Applications'
update WorkAssignment set Name = 'BTX', RoleId = 2, Category = 'General' where Name = 'XD' and SiteId = 1 and Description = 'BTX'
update WorkAssignment set Name = 'Console 1 - PLT#3/4', RoleId = 2, Category = 'General' where Name = 'G1' and SiteId = 1 and Description = 'Console 1 - PLT#3/4'
update WorkAssignment set Name = 'Console 2 - PLT#3/4', RoleId = 2, Category = 'General' where Name = 'G2' and SiteId = 1 and Description = 'Console 2 - PLT#3/4'
update WorkAssignment set Name = 'Console 3 - PLT#3/4', RoleId = 2, Category = 'General' where Name = 'G3' and SiteId = 1 and Description = 'Console 3 - PLT#3/4'
update WorkAssignment set Name = 'Console A - PLT#2', RoleId = 2, Category = 'General' where Name = 'CCA' and SiteId = 1 and Description = 'Console A - PLT#2'
update WorkAssignment set Name = 'Console B - PLT#2', RoleId = 2, Category = 'General' where Name = 'CCB' and SiteId = 1 and Description = 'Console B - PLT#2'
update WorkAssignment set Name = 'Crude - Vacuum', RoleId = 2, Category = 'General' where Name = 'XB' and SiteId = 1 and Description = 'Crude - Vacuum'
update WorkAssignment set Name = 'Crude Blending', RoleId = 2, Category = 'General' where Name = 'TD' and SiteId = 1 and Description = 'Crude Blending'
update WorkAssignment set Name = 'DHT', RoleId = 2, Category = 'General' where Name = 'GD' and SiteId = 1 and Description = 'DHT'
update WorkAssignment set Name = 'Gas/Alky Console', RoleId = 2, Category = 'General' where Name = 'WA' and SiteId = 1 and Description = 'Gas/Alky Console'
update WorkAssignment set Name = 'Gasoline Blending ', RoleId = 2, Category = 'General' where Name = 'TB' and SiteId = 1 and Description = 'Gasoline Blending '
update WorkAssignment set Name = 'GDS - Reformer', RoleId = 2, Category = 'General' where Name = 'WD' and SiteId = 1 and Description = 'GDS - Reformer'
update WorkAssignment set Name = 'HCC', RoleId = 2, Category = 'General' where Name = 'EC' and SiteId = 1 and Description = 'HCC'
update WorkAssignment set Name = 'Hydrogen', RoleId = 2, Category = 'General' where Name = 'HD' and SiteId = 1 and Description = 'Hydrogen'
update WorkAssignment set Name = 'Offsite Dispatcher', RoleId = 2, Category = 'General' where Name = 'TA' and SiteId = 1 and Description = 'Offsite Dispatcher'
update WorkAssignment set Name = 'Plant 1 Console', RoleId = 2, Category = 'General' where Name = 'EA' and SiteId = 1 and Description = 'Plant 1 Console'
update WorkAssignment set Name = 'Plant 1 Crude', RoleId = 2, Category = 'General' where Name = 'EB' and SiteId = 1 and Description = 'Plant 1 Crude'
update WorkAssignment set Name = 'Pretreater - Reformer', RoleId = 2, Category = 'General' where Name = 'XC' and SiteId = 1 and Description = 'Pretreater - Reformer'
update WorkAssignment set Name = 'Reaction & Fractionation', RoleId = 2, Category = 'General' where Name = 'HC' and SiteId = 1 and Description = 'Reaction & Fractionation'
update WorkAssignment set Name = 'Shift Engineer', RoleId = 5, Category = 'General' where Name = 'SE' and SiteId = 1 and Description = 'Shift Engineer'
update WorkAssignment set Name = 'Sulphur - PLT#3', RoleId = 2, Category = 'General' where Name = 'HE' and SiteId = 1 and Description = 'Sulphur - PLT#3'
update WorkAssignment set Name = 'Sulphur - PLT#4', RoleId = 2, Category = 'General' where Name = 'GS' and SiteId = 1 and Description = 'Sulphur - PLT#4'
update WorkAssignment set Name = 'Tank and Cavern Storage', RoleId = 2, Category = 'General' where Name = 'TC' and SiteId = 1 and Description = 'Tank and Cavern Storage'
update WorkAssignment set Name = 'Waste Water Treatment', RoleId = 2, Category = 'General' where Name = 'TE' and SiteId = 1 and Description = 'Waste Water Treatment'

GO

update WorkAssignment set Category = 'General' where Category is null

GO

GO
