DROP TABLE [dbo].[WorkPermitMontrealTemplate]
GO

CREATE TABLE [dbo].[WorkPermitMontrealTemplate] (
[Id] bigint IDENTITY(100, 1) NOT NULL,
[Name] varchar(100) NOT NULL,
[TypeId] int NOT NULL,
[Active] bit NOT NULL,
[Deleted] bit NOT NULL,
[H2S] tinyint NOT NULL,
[Hydrocarbure] tinyint NOT NULL,
[Ammoniaque] tinyint NOT NULL,
[Corrosif] tinyint NOT NULL,
[CorrosifValue] varchar(100) NULL,
[Aromatique] tinyint NOT NULL,
[AromatiqueValue] varchar(100) NULL,
[AutresSubstances] tinyint NOT NULL,
[AutresSubstancesValue] varchar(100) NULL,
[ObtureOuDeBranche] tinyint NOT NULL,
[DepressuriseEtVidange] tinyint NOT NULL,
[EnPresenceDeGazInerte] tinyint NOT NULL,
[PurgeALaVapeur] tinyint NOT NULL,
[RinceALEau] tinyint NOT NULL,
[Excavation] tinyint NOT NULL,
[DessinsRequis] tinyint NOT NULL,
[DessinsRequisValue] varchar(100) NULL,
[CablesChauffantsMisHorsTension] tinyint NOT NULL,
[PompeOuVerinPneumatique] tinyint NOT NULL,
[ChaineEtCadenasseOuScelle] tinyint NOT NULL,
[InterrupteursElectriquesVerrouilles] tinyint NOT NULL,
[PurgeParUnGazInerte] tinyint NOT NULL,
[OutilsElectriquesOuABatteries] tinyint NOT NULL,
[BoiteDeVerrouillage] tinyint NOT NULL,
[BoiteDeVerrouillageValue] varchar(100) NULL,
[OutilsPneumatiques] tinyint NOT NULL,
[MoteurACombustionInterne] tinyint NOT NULL,
[TravauxSuperposes] tinyint NOT NULL,
[FormulaireDespaceClosAffiche] tinyint NOT NULL,
[FormulaireDespaceClosAfficheValue] varchar(100) NULL,
[ExisteIlUneAnalyseDeTache] tinyint NOT NULL,
[PossibiliteDeSulfureDeFer] tinyint NOT NULL,
[AereVentile] tinyint NOT NULL,
[SoudureALelectricite] tinyint NOT NULL,
[BrulageAAcetylene] tinyint NOT NULL,
[Nacelle] tinyint NOT NULL,
[AutreConditions] tinyint NOT NULL,
[AutreConditionsValue] varchar(100) NULL,
[LunettesMonocoques] tinyint NOT NULL,
[HarnaisDeSecurite] tinyint NOT NULL,
[EcranFacial] tinyint NOT NULL,
[ProtectionAuditive] tinyint NOT NULL,
[Trepied] tinyint NOT NULL,
[DispositifAntiChute] tinyint NOT NULL,
[ProtectionRespiratoire] tinyint NOT NULL,
[ProtectionRespiratoireValue] varchar(100) NULL,
[Habits] tinyint NOT NULL,
[HabitsValue] varchar(100) NULL,
[AutreProtection] tinyint NOT NULL,
[AutreProtectionValue] varchar(100) NULL,
[Extincteur] tinyint NOT NULL,
[BouchesDegoutProtegees] tinyint NOT NULL,
[CouvertureAntiEtincelles] tinyint NOT NULL,
[SurveillantPourEtincelles] tinyint NOT NULL,
[PareEtincelles] tinyint NOT NULL,
[MiseAlaTerrePresDuLieuDeTravail] tinyint NOT NULL,
[BoyauAVapeur] tinyint NOT NULL,
[AutresEquipementDincendie] tinyint NOT NULL,
[AutresEquipementDincendieValue] varchar(100) NULL,
[Ventulateur] tinyint NOT NULL,
[Barrieres] tinyint NOT NULL,
[Surveillant] tinyint NOT NULL,
[SurveillantValue] varchar(100) NULL,
[RadioEmetteur] tinyint NOT NULL,
[ZoneBarricadee] tinyint NOT NULL,
[DetectionContinueDesGaz] tinyint NOT NULL,
[DetectionContinueDesGazValue] varchar(100) NULL,
[KlaxonSonore] tinyint  NOT NULL,
[Localiser] tinyint NOT NULL,
[Amiante] tinyint NOT NULL,
[AutreEquipementsSecurite] tinyint NOT NULL,
[AutreEquipementsSecuriteValue] varchar(100) NULL,
[InstructionsSpeciales] varchar(500) NULL,
[SignatureOperateurSurLeTerrain] tinyint NOT NULL,
[DetectionDesGazs] tinyint NOT NULL,
[SignatureContremaitre] tinyint NOT NULL,
[SignatureAutorise] tinyint NOT NULL,
CONSTRAINT [PK_WorkPermitMontrealTemplate]
PRIMARY KEY CLUSTERED ([Id] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
GO
