DROP INDEX [IDX_FormGN59History] 
ON [dbo].[FormGN59History];
GO

CREATE CLUSTERED INDEX [IDX_FormGN59History]
ON [dbo].[FormGN59History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_ConfinedSpaceHistory] 
ON [dbo].[ConfinedSpaceHistory];
GO

CREATE CLUSTERED INDEX [IDX_ConfinedSpaceHistory]
ON [dbo].[ConfinedSpaceHistory]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_FormGN7History] 
ON [dbo].[FormGN7History];
GO

CREATE CLUSTERED INDEX [IDX_FormGN7History]
ON [dbo].[FormGN7History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_FormOP14History] 
ON [dbo].[FormOP14History];
GO

CREATE CLUSTERED INDEX [IDX_FormOP14History]
ON [dbo].[FormOP14History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

CREATE CLUSTERED INDEX [IDX_FormGN24History]
ON [dbo].[FormGN24History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_FormGN59History] 
ON [dbo].[FormGN59History];
GO

CREATE CLUSTERED INDEX [IDX_FormGN59History]
ON [dbo].[FormGN59History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_WorkPermitLubesHistory] 
ON [dbo].[WorkPermitLubesHistory];
GO

CREATE CLUSTERED INDEX [IDX_WorkPermitLubesHistory]
ON [dbo].[WorkPermitLubesHistory]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO


GO

