DROP INDEX [IDX_SummaryLog_ReplyToLogId] ON [dbo].[SummaryLog];

ALTER TABLE dbo.SummaryLog ALTER COLUMN RootLogId BIGINT SPARSE NULL;
ALTER TABLE dbo.SummaryLog ALTER COLUMN ReplyToLogId BIGINT SPARSE NULL;

CREATE NONCLUSTERED INDEX [IDX_SummaryLog_ReplyToLogId]
ON [dbo].[SummaryLog]
([ReplyToLogId])
WHERE (([DELETED]=(0)))
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
)
ON [PRIMARY];
GO


GO

