CREATE NONCLUSTERED INDEX [IDX_FunctionalLocation_SiteId]
ON [dbo].[FunctionalLocation]
([SiteId] , [Level] , [OutOfService])
WHERE (DELETED = 0)
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE,
DROP_EXISTING = ON
)
ON [PRIMARY];
GO


GO

