CREATE CLUSTERED INDEX [IDX_FormGN6History]
ON [dbo].[FormGN6History]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX IDX_FormOilsandsTrainingHistory
ON FormOilsandsTrainingHistory

CREATE CLUSTERED INDEX IDX_FormOilsandsTrainingHistory
ON FormOilsandsTrainingHistory
([Id])
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
GO



GO

