
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('AUTF20-C', 'Automation Tech, FB SWS, Convergint', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('AUTOM', 'Automation', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('AWPML45', 'Aerial Work Platform, Manlift, 45ft', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('AWPSC26', 'Aerial Work Platform, Scissor Lift, 26ft', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('BM', 'Exchanger Contractor - Evtex', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CARF20-C', 'Carpenter, FB SWS, Chad''s Contracting', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('COORD', 'Coordinator', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('COORD3', 'Coordinator,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('COPF30-C', 'Crane Operator, Shared Services,TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CRANE', 'Crane 85 ton', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CRDF20-C', 'Coordinator, FB SWS, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CRDF40-C', 'Coordinator, Pads, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CRFT LAB', 'CRAFT LABOUR HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('CRM8', 'Crane, Mobile, 8T Carry Deck', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ECHEM1-C', 'Chemical Truck-1, Centrifugal Pump', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EHS', 'EH&S', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EHVT1-C', 'Hydro-Excavation Vacuum Truck-1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELE', 'Electrician', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELE1', 'Electrician, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELE1-C', 'Electrician, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELE2', 'Electrician, FB2', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELE3-C', 'Electrician,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELEF20-C', 'Electrician, FB SWS, Chad''s Contracting', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELEF40-C', 'Electrician, Pads, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ELETD-C', 'Electrical Trans, Distribution', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGELE', 'Engineer, Electrical', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGELE3', 'Engineer,Electrical,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGME', 'Engineer, Mechanical', 5, 0)

INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGME3', 'Engineer,Mechanical,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGPR1', 'Engineer, Process, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGPR3', 'Engineer,Process,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGREL', 'Engineer, Reliability', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ENGREL3', 'Engineer,Reliability,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EPTK1-C', 'Pressure Truck-1, Low PSI', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EPTK2-C', 'Pressure Truck-2, Medium PSI', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EPTK3-C', 'Pressure Truck-3, High PSI', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EQOPR-C', 'Equipment op, Contract (QUEST Smart Pig)', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EQUIPMNT', 'EQUIPMENT HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ESFT1-C', 'Sewer Flusher Truck-1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ESTK1-C', 'Steam Truck-1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EVAC1-C', 'Vacuum Truck-1, Low CFM Low Capacity', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EVAC2-C', 'Vacuum Truck-2, Low CFM High Capacity', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EVAC3-C', 'Vacuum Truck-3, High CFM Low Capacity', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EWJBB-C', 'Water Jet-1, Bundle Blaster', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EWJRF-C', 'Water Jet-2, Roto Fan', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('EWTK1-C', 'Water Truck-1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FACILITY', 'FACILITY HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FB-WELLS', 'Firebag Well Service work', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FCS1', 'Control systems, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FSC3', 'Control systems, FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FLM4', 'Forklift, Motor, 4T', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FTEF20-C', 'Fire Tech Elect, FB SWS, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('FTMF20-C', 'Fire Tech Mech, FB SWS, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('HSE', 'HSE Support', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('HSE3', 'HSE Support,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('HVAF20-C', 'HVAC Tech, FB SWS, Convergint', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('IH', 'Industrial Hygenist', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INLF30-C', 'Insulator, Shared Services, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INSPPE1', 'Inspector, Pressure Equipment, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INSPPE3', 'Inspector, Pressure Equip, FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INSPRE', 'Inspector, Rotating Equipment', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INSPRE1', 'Inspector, Rotating Equipment, FB1', 5, 0)

INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INSPRE3', 'Inspector Rotating Equipment,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INST', 'Instrument Technician', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INST1', 'Instrument Technician, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INST1-C', 'Instrument Technician, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INST2', 'Instrument Technician, FB2', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INST3-C', 'Instrument Tech,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('INTF40-C', 'Instrumentation, Pads, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LAB', 'Labourer, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LAB1-C', 'Labourer, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LAB3-C', 'Labourer,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LABF20-C', 'Laborer, FB SWS, Chad''s Contracting', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LABF40-C', 'Laborer, Pads, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('LVFC-C', 'LVF Coordinator, FB, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('MECH-C', 'Mechanic, FB, North Star Ford', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('MW', 'Millwright, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('MW1-C', 'Millwright, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('MW3-C', 'Millwright,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('MWRF40-C', 'Millwright, Pads, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('NDTINSP', 'NDT Inspection,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('OHP&V-C', 'Operators, Helpers Pressure & Vacuum', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('OPP&V-C', 'Operators, Pressure & Vacuum', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('OSPF01', 'Operations Supervisor, Firebag 1 TEC', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PF', 'Pipefitter, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PF1-C', 'Pipefitter, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PF3-C', 'Pipefitter,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PFTF40-C', 'Pipefitter, Pads, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PLANT WC', 'PLANT WC HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PLUF20-C', 'Plumber, FB SWS, Chad''s Contracting', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PM', 'Project Manager', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PRTEC1', 'Production Technician, FB1', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PRTEC1-C', 'Production Technician, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PRTEC3', 'Production Tech,FB3', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('PSVSHP-C', 'PSV Shop, FB', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('RELIAB', 'Reliability', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('SCFF30-C', 'Scaffolder, Shared Services, Safway', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('SUPEL3-C', 'Supervisor,Elec,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('SUPME3-C', 'Supervisor,Mech,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('SUPT LAB', 'SUPPORT LABOUR HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('TDCF20-C', 'Door Tech, FB SWS, Creative Door', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('TMSF30-C', 'Teamster, Shared Services, TAMS', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('TRNARND', 'TURNAROUND HIER NODE', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('WARESUP', 'Warehouse Supervisor', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('WEL', 'Welder, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('WEL1-C', 'Welder, FB1, Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('WEL3-C', 'Welder,FB3,Contract', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZBDLF01', 'Bundle Transporter, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZBMKF01', 'Boilermaker, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZBMKF02', 'Boilermaker, T/A, Contract 02', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZCTRF01', 'Coating Repair, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZDCSF01', 'DCS, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZDCSF02', 'DCS, T/A, Contract 02', 5, 0)

INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZDCSF03', 'DCS, T/A, Contract 03', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZEDCF01', 'Eddy Current, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZELEF01', 'Electrical, T/A. Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZELEF02', 'Electrical, T/A. Contract 02', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZELEF03', 'Electrical, T/A. Contract 03', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZINTF01', 'Instrumentation, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZINTF02', 'Instrumentation, T/A, Contract 02', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZINTF03', 'Instrumentation, T/A, Contract 03', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZITKF01', 'Tank Inspector, T/A , Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZMWRF01', 'Millrwright, T/A, Contract 01', 5, 0)
INSERT INTO dbo.CraftOrTrade (WorkCenter, [Name], SiteId, Deleted) VALUES ('ZMWRF02', 'Millrwright, T/A, Contract 02', 5, 0)








GO

