CREATE NONCLUSTERED INDEX [IDX_LogRead_UserId] ON [dbo].[LogRead] 
(
	[UserId] ASC,
	[LogId] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]



GO

