CREATE NONCLUSTERED INDEX [IDX_FunctionalLocation_Id]
ON [dbo].[FunctionalLocation]
([Id])
INCLUDE ([FullHierarchy])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
)
ON [PRIMARY];
GO


GO

