
-- give all Supervisors, Operators, and TATechs a print preference with 'ShowPrintDialog' off.  NumberOfCopies is ignored for Edmonton permits.  A null PrinterName means 'default printer'.

declare @UserIds TABLE(
  Id bigint NOT NULL
);

insert into @UserIds
select u.Id
from [User] u
where u.Username in (
'mschweitzer',
'depark',
'tmcintosh',
'bjbeaton',
'wducherer',
'rsjamieson',
'rmartin',
'hbergeron',
'bomckenzie',
'tridavies',
'ckemp',
'bzibrowski',
'reglin',
'ckerklaan',
'ssoundararaj',
'gsommerfeldt',
'ghatch',
'wmccartney',
'mpierce',
'nredekop',
'dkoester',
'jawhalen',
'kenders',
'rdickout',
'cachtymichuk',
'kyuskiw',
'rvirring',
'untambwe',
'ltrinh',
'jmacneil',
'bonixon',
'aevanochko',
'ecosby',
'rketsa',
'ktymchuk',
'lsgill',
'rlalonde',
'kgraham',
'gmckay',
'pcliff',
'tplaquin',
'lgore',
'asarafinchan',
'cebutler',
'cjabbour',
'damorin',
'bdiack',
'memoore',
'kpenner',
'ethomey',
'kjollineau',
'jstanding',
'rsolonenko',
'drpollard',
'rjcarlson',
'fjohnston',
'kholitzki',
'srathje',
'speddle',
'jatremblay',
'ehopkin',
'rtcameron',
'dwritchie',
'drhyno',
'bmelnyk',
'dneufeld',
'dborle',
'phuynh',
'dipatel',
'dmayor',
'aoquinn',
'jmorallo',
'tjardine',
'dmcdonald',
'ddixon',
'trankin',
'tforster',
'sastewart',
'vjackson',
'rcarignan',
'dharcourt',
'rdutil',
'mdbeaton',
'jtemple',
'nbishoff',
'bmisanchuk',
'tcroteau',
'kosmond',
'gflint',
'pjarvis',
'dolsen',
'jjuba',
'bbergstrom',
'bmelendezduk',
'jlanders',
'ggarnier',
'kvagi',
'bgyselinck',
'temes',
'tcarmichael',
'wsnyder',
'jwhelen',
'rkluge',
'skingston',
'mallanach',
'bwerbiski',
'aredekop',
'cheinz',
'sequinton',
'dalipinski',
'tlee',
'nunderwood',
'kcollins',
'mjabbour',
'rmackney',
'bkutcher',
'mandruchow',
'rhayes',
'jlyon',
'rshears',
'jmeadahl',
'nbthomas',
'tdumont',
'sdach',
'jlangner',
'khelmer',
'kmckay',
'bethomson',
'rpurewal',
'bcbelliveau',
'jchughes',
'rweber',
'jtchen',
'tllarson',
'gmulcahey',
'cbremault',
'glmiller',
'cwagner',
'mfixsen',
'swlee',
'grexin',
'pfodchuk',
'dslade',
'lmaher',
'dfairweather',
'swatts',
'rhaug',
'rbigelow',
'clopez',
'gtellier',
'jcherniawski',
'csparsons',
'rburry',
'wbell',
'rbrisson',
'mgruszczynsk',
'amacdonald',
'jmelnyk',
'dbalfour',
'lwhitnell',
'pwilderman',
'kasierra',
'jgiourmetaki',
'ajabber',
'bralee',
'nmedina',
'jkluthe',
'pdziwisz',
'phoang',
'hdo',
'sstroshin',
'lhoffmann',
'bkaziuk',
'bmarks',
'pgallego',
'eskjel',
'halier',
'kthakur',
'dristock',
'bfield',
'fsommer',
'stgriffin',
'nbradfield',
'ppeters',
'tandemichael',
'adeed',
'dfleck',
'gapatel',
'tojones',
'mcroft',
'mflamand',
'tsidam',
'ksparling',
'KLamden',
'kenknight',
'wbrennan',
'trjones',
'mroste',
'nlemoine',
'cgretzan',
'bjay',
'cblatz',
'hramyar',
'cbone',
'relm',
'dlthompson',
'rcallicott',
'damackay',
'drayner',
'dpoole',
'tparayko',
'bkniaz',
'jrhughes',
'ggoodfellow',
'cplaquin',
'tromaniuk',
'tbaillie',
'vbond',
'dwashburn',
'mdyer',
'gsoetaert',
'scpeever')


declare @UserId as bigint;

declare UserIdCursor cursor for select Id from @UserIds;
open UserIdCursor
fetch next from UserIdCursor into @UserId;
while (@@FETCH_STATUS = 0)
begin

declare @CountOfExisting as int;
select @CountOfExisting = count(*) from UserPrintPreference upp where upp.UserId = @UserId;

-- If the user already has a print preference, update it to have ShowPrintDialog off.  Otherwise insert a new preference.
if (@CountOfExisting = 0)
  begin
    insert into UserPrintPreference (UserId, PrinterName, NumberOfCopies, ShowPrintDialog) values (@UserId, null, 1, 0);
  end
else
  begin
    update UserPrintPreference set ShowPrintDialog = 0 where UserId = @UserId;
  end
  
fetch next from UserIdCursor into @UserId;
end
close UserIdCursor
deallocate UserIdCursor

GO

