

IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 4)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,4,0) 
END
GO
IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 5)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,5,0) 
END
GO
IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 6)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,6,0) 
END
GO
IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 7)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,7,0) 
END
GO
IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 8)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,8,0) 
END
GO
IF NOT EXISTS ( SELECT * FROM WORKPERMITCLOSECONFIGURATION WHERE SITEID = 15 AND STATUSID = 9)
BEGIN
INSERT INTO WORKPERMITCLOSECONFIGURATION VALUES (15,9,0) 
END
GO



