if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertProcedureDeviation]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[InsertProcedureDeviation]
GO

CREATE Procedure [dbo].[InsertProcedureDeviation]
(
	@Id bigint Output,
	@FormStatusId int,
	@ValidFromDateTime datetime,
	@ValidToDateTime datetime,
	@ApprovedDateTime datetime = NULL,
	@CreatedByUserId bigint,
	@CreatedDateTime datetime,
	@LastModifiedByUserId bigint,
	@LastModifiedDateTime datetime,
	@SiteId bigint,
	@DeviationType int,
	@PermanentRevisionRequired bit,
	@RevertedBackToOriginal bit,
	@LocationEquipmentNumber varchar(100),
	@NumberOfExtensions int,
	@OperatingProcedureNumber varchar(100),
	@OperatingProcedureTitle varchar(255),
	@OperatingProcedureLevel int,
	@Description varchar(MAX),
	@RichTextDescription varchar(MAX),
	@CauseDeterminationCategory varchar(100),
	@CauseDeterminationComments varchar(255),
	@FixDocumentDurationType int,
	@CorrectiveActionIlpNumber varchar(100),
	@CorrectiveActionWorkRequestNumber varchar(100),
	@CorrectiveActionOtherComments varchar(255),
	@AffectsToe bit,
	@RiskAssessmentAttendee1Type int,
	@RiskAssessmentAttendee1Name varchar(100),
	@RiskAssessmentAttendee2Type int,
	@RiskAssessmentAttendee2Name varchar(100),
	@RiskAssessmentAttendee3Type int,
	@RiskAssessmentAttendee3Name varchar(100),
	@RiskAssessmentAttendee4Type int,
	@RiskAssessmentAttendee4Name varchar(100),
	@RiskAssessmentAnswer1 bit,
	@RiskAssessmentAnswer2 bit,
	@RiskAssessmentAnswer3 bit,
	@RiskAssessmentAnswer4 bit,
	@RiskAssessmentAnswer5 bit,
	@RiskAssessmentComments varchar(255),
	@ImmediateApprovalsApprover1Type int,
	@ImmediateApprovalsApprover1Title varchar(100),
	@ImmediateApprovalsApprover1Name varchar(255),
	@ImmediateApprovalsApprover1ObtainedVia int,
	@ImmediateApprovalsApprover1ApprovedDateTime datetime,
	@ImmediateApprovalsApprover2Type int,
	@ImmediateApprovalsApprover2Title varchar(100),
	@ImmediateApprovalsApprover2Name varchar(255),
	@ImmediateApprovalsApprover2ObtainedVia int,
	@ImmediateApprovalsApprover2ApprovedDateTime datetime,
	@TemporaryApprovalsApprover1Type int,
	@TemporaryApprovalsApprover1Title varchar(100),
	@TemporaryApprovalsApprover1Name varchar(255),
	@TemporaryApprovalsApprover1ObtainedVia int,
	@TemporaryApprovalsApprover1ApprovedDateTime datetime,
	@TemporaryApprovalsApprover2Type int,
	@TemporaryApprovalsApprover2Title varchar(100),
	@TemporaryApprovalsApprover2Name varchar(255),
	@TemporaryApprovalsApprover2ObtainedVia int,
	@TemporaryApprovalsApprover2ApprovedDateTime datetime,
	@CancelledBy varchar(100),
	@CancelledDateTime datetime = NULL,
	@CancelledReason varchar(255)
)
AS

DECLARE @NewFormId bigint
BEGIN
	EXEC @NewFormId = GetNewSeqVal_FormOilsandsIdSequence
END

INSERT INTO FormProcedureDeviation
(
	[Id],
	[FormStatusId],
	[ValidFromDateTime],
	[ValidToDateTime],
	[ApprovedDateTime],
	[CreatedByUserId],
	[CreatedDateTime],
	[LastModifiedByUserId],
	[LastModifiedDateTime],	
	[SiteId],
	[DeviationType],
	[PermanentRevisionRequired],
	[RevertedBackToOriginal],
	[LocationEquipmentNumber],
	[NumberOfExtensions],
	[OperatingProcedureNumber],
	[OperatingProcedureTitle],
	[OperatingProcedureLevel],
	[Description],
	[RichTextDescription],
	[CauseDeterminationCategory],
	[CauseDeterminationComments],
	[FixDocumentDurationType],
	[CorrectiveActionIlpNumber],
	[CorrectiveActionWorkRequestNumber],
	[CorrectiveActionOtherComments],
	[AffectsToe],
	[RiskAssessmentAttendee1Type],
	[RiskAssessmentAttendee1Name],
	[RiskAssessmentAttendee2Type],
	[RiskAssessmentAttendee2Name],
	[RiskAssessmentAttendee3Type],
	[RiskAssessmentAttendee3Name],
	[RiskAssessmentAttendee4Type],
	[RiskAssessmentAttendee4Name],
	[RiskAssessmentAnswer1],
	[RiskAssessmentAnswer2],
	[RiskAssessmentAnswer3],
	[RiskAssessmentAnswer4],
	[RiskAssessmentAnswer5],
	[RiskAssessmentComments],
	[ImmediateApprovalsApprover1Type],
	[ImmediateApprovalsApprover1Title],
	[ImmediateApprovalsApprover1Name],
	[ImmediateApprovalsApprover1ObtainedVia],
	[ImmediateApprovalsApprover1ApprovedDateTime],
	[ImmediateApprovalsApprover2Type],
	[ImmediateApprovalsApprover2Title],
	[ImmediateApprovalsApprover2Name],
	[ImmediateApprovalsApprover2ObtainedVia],
	[ImmediateApprovalsApprover2ApprovedDateTime],
	[TemporaryApprovalsApprover1Type],
	[TemporaryApprovalsApprover1Title],
	[TemporaryApprovalsApprover1Name],
	[TemporaryApprovalsApprover1ObtainedVia],
	[TemporaryApprovalsApprover1ApprovedDateTime],
	[TemporaryApprovalsApprover2Type],
	[TemporaryApprovalsApprover2Title],
	[TemporaryApprovalsApprover2Name],
	[TemporaryApprovalsApprover2ObtainedVia],
	[TemporaryApprovalsApprover2ApprovedDateTime],
	[CancelledBy],
	[CancelledDateTime],
	[CancelledReason],
	[Deleted]
)
VALUES
(
	@NewFormId,
	@FormStatusId,
	@ValidFromDateTime,
	@ValidToDateTime,
	@ApprovedDateTime,
	@CreatedByUserId,
	@CreatedDateTime,
	@LastModifiedByUserId,
	@LastModifiedDateTime,	
	@SiteId,
	@DeviationType,
	@PermanentRevisionRequired,
	@RevertedBackToOriginal,
	@LocationEquipmentNumber,
	@NumberOfExtensions,
	@OperatingProcedureNumber,
	@OperatingProcedureTitle,
	@OperatingProcedureLevel,
	@Description,
	@RichTextDescription,
	@CauseDeterminationCategory,
	@CauseDeterminationComments,
	@FixDocumentDurationType,
	@CorrectiveActionIlpNumber,
	@CorrectiveActionWorkRequestNumber,
	@CorrectiveActionOtherComments,
	@AffectsToe,
	@RiskAssessmentAttendee1Type,
	@RiskAssessmentAttendee1Name,
	@RiskAssessmentAttendee2Type,
	@RiskAssessmentAttendee2Name,
	@RiskAssessmentAttendee3Type,
	@RiskAssessmentAttendee3Name,
	@RiskAssessmentAttendee4Type,
	@RiskAssessmentAttendee4Name,
	@RiskAssessmentAnswer1,
	@RiskAssessmentAnswer2,
	@RiskAssessmentAnswer3,
	@RiskAssessmentAnswer4,
	@RiskAssessmentAnswer5,
	@RiskAssessmentComments,
	@ImmediateApprovalsApprover1Type,
	@ImmediateApprovalsApprover1Title,
	@ImmediateApprovalsApprover1Name,
	@ImmediateApprovalsApprover1ObtainedVia,
	@ImmediateApprovalsApprover1ApprovedDateTime,
	@ImmediateApprovalsApprover2Type,
	@ImmediateApprovalsApprover2Title,
	@ImmediateApprovalsApprover2Name,
	@ImmediateApprovalsApprover2ObtainedVia,
	@ImmediateApprovalsApprover2ApprovedDateTime,
	@TemporaryApprovalsApprover1Type,
	@TemporaryApprovalsApprover1Title,
	@TemporaryApprovalsApprover1Name,
	@TemporaryApprovalsApprover1ObtainedVia,
	@TemporaryApprovalsApprover1ApprovedDateTime,
	@TemporaryApprovalsApprover2Type,
	@TemporaryApprovalsApprover2Title,
	@TemporaryApprovalsApprover2Name,
	@TemporaryApprovalsApprover2ObtainedVia,
	@TemporaryApprovalsApprover2ApprovedDateTime,
	@CancelledBy,
	@CancelledDateTime,
	@CancelledReason,
	0
);

SET @Id=@NewFormId; 

GO

GRANT EXEC ON InsertProcedureDeviation TO PUBLIC
GO
