 
  
IF OBJECT_ID('InsertPermitRequestFortHills', 'P') IS NOT NULL
DROP PROC InsertPermitRequestFortHills
GO 

              
                    
CREATE Procedure [dbo].[InsertPermitRequestFortHills]                                
    (                                
@Id bigint Output,                   
@IssuedToSuncor bit,                  
@IssuedToCompany bit,                  
@Company varchar(50) =   NULL,                  
@Occupation varchar(50),                  
@NumberOfWorkers int =  NULL,                  
@GroupId bigint ,                  
@SourceId int ,                  
@WorkOrderNumber varchar(25) =  NULL,                  
@WorkPermitTypeId int ,                  
@PriorityId int ,                   
@FunctionalLocationId bigint ,                  
@Location varchar(100) ,                  
@RequestedStartDate datetime ,                                                    
@RequestedEndDate datetime ,                                                    
@EquipmentNo  int =  NULL,                             
@JobCoordinator varchar(25) =  NULL,                  
@CoOrdContactNumber varchar(10) =  NULL,                  
@Locknumber  varchar(10) =  NULL,                  
@IsolationNumber  varchar(10) =  NULL,                  
@Description varchar(max) =  NULL,                  
@SAPDescription varchar(max) =  NULL,                  
@FlameResistantWorkWear bit =  NULL,                  
@ChemicalSuit bit,                  
@FireWatch bit,                  
@FireBlanket bit,                  
@SuppliedBreathingAir bit,                  
@AirMover bit,                  
@PersonalFlotationDevice bit,                  
@HearingProtection bit,                  
@Other1 varchar(30) =  NULL,                  
@MonoGoggles bit ,                  
@ConfinedSpaceMoniter bit ,                  
@FireExtinguisher bit ,                  
@SparkContainment bit ,                  
@BottleWatch bit ,                  
@StandbyPerson bit ,                  
@WorkingAlone bit ,                  
@SafetyGloves bit ,                  
@Other2 varchar(30) =  NULL,                  
@FaceShield bit ,                  
@FallProtection bit ,                  
@ChargedFireHouse bit ,             
@CoveredSewer bit,            
@AirPurifyingRespirator bit,                  
@SingalPerson bit ,                  
@CommunicationDevice bit ,                  
@ReflectiveStrips bit ,                  
@Other3 varchar(30) =  NULL,                  
@HazardsAndOrRequirements varchar(max) =  NULL,                  
@ConfinedSpace bit ,                  
@ConfinedSpaceClass varchar(25) =  NULL,                  
@GoundDisturbance bit ,                  
@FireProtectionAuthorization bit ,                  
@CriticalOrSeriousLifts bit ,                  
@VehicleEntry bit ,                  
@IndustrialRadiography bit ,                  
@ElectricalEncroachment bit ,                  
@MSDS bit ,                  
@OthersPartE varchar(30) =  NULL,                  
@MechanicallyIsolated bit ,                  
@BlindedOrBlanked bit ,                  
@DoubleBlockedandBled bit ,                  
@DrainedAndDepressurised bit ,                  
@PurgedorNeutralised bit ,                  
@ElectricallyIsolated bit ,                  
@TestBumped bit ,                  
@NuclearSource bit ,                  
@ReceiverStafingRequirements bit ,                  
@SAPWorkCentre varchar(40) =  NULL,                  
@DoNotMerge bit ,                  
@CompletionStatusId int ,                  
@LastImportedByUserId bigint =  NULL,                  
@LastImportedDateTime datetime =  NULL,                  
@LastSubmittedByUserId bigint =  NULL,                  
@LastSubmittedDateTime datetime =  NULL,                  
@CreatedByUserId bigint ,                  
@CreatedDateTime datetime ,                  
@LastModifiedByUserId bigint ,                  
@LastModifiedDateTime datetime ,                  
@IsModified bit,    
@LockBoxnumberChecked bit,    
@PartCWorkSectionNotApplicableToJob bit,    
@PartDWorkSectionNotApplicableToJob bit,    
@PartEWorkSectionNotApplicableToJob bit           
--@EndDate Datetime                             
 )                                
AS                                
                                     
                                
INSERT INTO PermitRequestFortHills                                
(                                
IssuedToSuncor,         
IssuedToCompany,                   
Company,                  
Occupation,                    
NumberOfWorkers,                  
GroupId,                   
WorkOrderNumber,                  
DataSourceId,                   
WorkPermitTypeId,                  
PriorityId,                  
FunctionalLocationId,                  
Location,                   
RequestedStartDate,      
RequestedEndDate,    
EquipmentNo,                  
--Craft,                  
--CrewSize,                  
JobCoordinator,                  
CoOrdContactNumber,                  
--EmergencyAssemblyArea,                  
--EmergencyMeetingPoint,                  
--EmergencyContactNumber,                  
--Locknumber,                  
--IsolationNumber,                  
TaskDescription,                  
SAPDescription,                   
FlameResistantWorkWear,                   
ChemicalSuit,                    
FireWatch,                    
FireBlanket,                    
SuppliedBreathingAir,                    
AirMover,                    
PersonalFlotationDevice,                  
HearingProtection,                    
Other1,                  
MonoGoggles,                    
ConfinedSpaceMoniter,                    
FireExtinguisher,                    
SparkContainment,                    
BottleWatch,                    
StandbyPerson,                    
WorkingAlone,                    
SafetyGloves,                    
Other2,                  
FaceShield,                    
FallProtection,                    
ChargedFireHouse,            
CoveredSewer,             
AirPurifyingRespirator,                     
SingalPerson,                    
CommunicationDevice,                    
ReflectiveStrips,                    
Other3,                  
HazardsAndOrRequirements,                  
ConfinedSpace,                  
ConfinedSpaceClass,                  
GoundDisturbance,                  
FireProtectionAuthorization,                    
CriticalOrSeriousLifts,                  
VehicleEntry,                    
IndustrialRadiography,                    
ElectricalEncroachment,                  
MSDS,                    
OthersPartE,                  
MechanicallyIsolated,                    
BlindedOrBlanked,                    
DoubleBlockedandBled,                    
DrainedAndDepressurised,                    
PurgedorNeutralised,                    
ElectricallyIsolated,                    
TestBumped,                    
NuclearSource,                    
ReceiverStafingRequirements,                    
SAPWorkCentre,                  
DoNotMerge,                    
CompletionStatusId,                   
LastImportedByUserId,                  
LastImportedDateTime,                  
LastSubmittedByUserId,                  
LastSubmittedDateTime,                  
CreatedByUserId,                   
CreatedDateTime,                   
LastModifiedByUserId,                  
LastModifiedDateTime,                  
IsModified,                   
Deleted,    
LockBoxnumberChecked,    
PartEWorkSectionNotApplicable,  
PartDWorkSectionNotApplicable,  
PartCWorkSectionNotApplicable                  
)                                
VALUES                                
(                               
@IssuedToSuncor,                    
@IssuedToCompany ,                   
@Company,                  
@Occupation,                    
@NumberOfWorkers,                  
@GroupId,                   
@WorkOrderNumber,                  
@SourceId,                   
@WorkPermitTypeId,                  
@PriorityId,                  
@FunctionalLocationId,                  
@Location,                   
@RequestedStartDate,     
@RequestedEndDate,                                                 
@EquipmentNo,                  
--@Craft,              
--@CrewSize,                  
@JobCoordinator,                  
@CoOrdContactNumber,                  
--@EmergencyAssemblyArea,                  
--@EmergencyMeetingPoint,                  
--@EmergencyContactNumber,                  
--@Locknumber,                  
--@IsolationNumber,                  
@Description,                  
@SAPDescription,                  
@FlameResistantWorkWear,                   
@ChemicalSuit,                    
@FireWatch,                    
@FireBlanket,                    
@SuppliedBreathingAir,                    
@AirMover,                    
@PersonalFlotationDevice,                  
@HearingProtection,                    
@Other1,                  
@MonoGoggles,                    
@ConfinedSpaceMoniter,                    
@FireExtinguisher,                    
@SparkContainment,                    
@BottleWatch,                    
@StandbyPerson,                    
@WorkingAlone,                    
@SafetyGloves,                    
@Other2,                  
@FaceShield,                    
@FallProtection,                    
@ChargedFireHouse,              
@CoveredSewer,             
@AirPurifyingRespirator,                   
@SingalPerson,                    
@CommunicationDevice,                    
@ReflectiveStrips,                    
@Other3,                  
@HazardsAndOrRequirements,                  
@ConfinedSpace,                  
@ConfinedSpaceClass,                  
@GoundDisturbance,                  
@FireProtectionAuthorization,                    
@CriticalOrSeriousLifts,                  
@VehicleEntry,                    
@IndustrialRadiography,                    
@ElectricalEncroachment,                  
@MSDS,                    
@OthersPartE,                  
@MechanicallyIsolated,                    
@BlindedOrBlanked,                    
@DoubleBlockedandBled,                    
@DrainedAndDepressurised,                    
@PurgedorNeutralised,                    
@ElectricallyIsolated,                    
@TestBumped,                    
@NuclearSource,                    
@ReceiverStafingRequirements,                    
@SAPWorkCentre,                  
@DoNotMerge,                    
@CompletionStatusId,                   
@LastImportedByUserId,                  
@LastImportedDateTime,                  
@LastSubmittedByUserId,                  
@LastSubmittedDateTime,                  
@CreatedByUserId,                   
@CreatedDateTime,                   
@LastModifiedByUserId,                  
@LastModifiedDateTime,                  
@IsModified,                   
0,    
@LockBoxnumberChecked,    
@PartCWorkSectionNotApplicableToJob,    
@PartDWorkSectionNotApplicableToJob,    
@PartEWorkSectionNotApplicableToJob  
)                                
SET @Id= SCOPE_IDENTITY()                             
                           
                                
GRANT EXEC ON [InsertPermitRequestFortHills] TO PUBLIC 