//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace Com.Suncor.Olt.SAP.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SuncorCommonWebService_WebServiceBinding", Namespace="slg1.suncor.com")]
    public partial class SuncorCommonWebService_WebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitSapLogRequestOperationCompleted;
        
        /// <remarks/>
        public SuncorCommonWebService_WebServiceService() {
            this.Url = "http://wmdev001:5651/soap/webservice";
        }
        
        /// <remarks/>
        public event SubmitSapLogRequestCompletedEventHandler SubmitSapLogRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SapLogRequestOutput", Namespace="slg1.suncor.com")]
        public SapLogRequestOutput SubmitSapLogRequest([System.Xml.Serialization.XmlElementAttribute("SubmitSapLogRequest", Namespace="slg1.suncor.com")] SapLogRequestInput SubmitSapLogRequest1) {
            object[] results = this.Invoke("SubmitSapLogRequest", new object[] {
                        SubmitSapLogRequest1});
            return ((SapLogRequestOutput)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSubmitSapLogRequest(SapLogRequestInput SubmitSapLogRequest1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SubmitSapLogRequest", new object[] {
                        SubmitSapLogRequest1}, callback, asyncState);
        }
        
        /// <remarks/>
        public SapLogRequestOutput EndSubmitSapLogRequest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SapLogRequestOutput)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitSapLogRequestAsync(SapLogRequestInput SubmitSapLogRequest1) {
            this.SubmitSapLogRequestAsync(SubmitSapLogRequest1, null);
        }
        
        /// <remarks/>
        public void SubmitSapLogRequestAsync(SapLogRequestInput SubmitSapLogRequest1, object userState) {
            if ((this.SubmitSapLogRequestOperationCompleted == null)) {
                this.SubmitSapLogRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitSapLogRequestOperationCompleted);
            }
            this.InvokeAsync("SubmitSapLogRequest", new object[] {
                        SubmitSapLogRequest1}, this.SubmitSapLogRequestOperationCompleted, userState);
        }
        
        private void OnSubmitSapLogRequestOperationCompleted(object arg) {
            if ((this.SubmitSapLogRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitSapLogRequestCompleted(this, new SubmitSapLogRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/SuncorCommonWebService/WebService/SubmitSapLogRequest")]
    public partial class SapLogRequestInput {
        
        private string sourceReferenceField;
        
        private string integrationNameField;
        
        private string objectSLG1Field;
        
        private string subObjectSLG1Field;
        
        private string messageColourField;
        
        private string messageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sourceReference {
            get {
                return this.sourceReferenceField;
            }
            set {
                this.sourceReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string integrationName {
            get {
                return this.integrationNameField;
            }
            set {
                this.integrationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objectSLG1 {
            get {
                return this.objectSLG1Field;
            }
            set {
                this.objectSLG1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string subObjectSLG1 {
            get {
                return this.subObjectSLG1Field;
            }
            set {
                this.subObjectSLG1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string messageColour {
            get {
                return this.messageColourField;
            }
            set {
                this.messageColourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/SuncorCommonWebService/WebService/SubmitSapLogRequest")]
    public partial class SapLogRequestOutput {
        
        private string successField;
        
        private string statusField;
        
        private string dateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void SubmitSapLogRequestCompletedEventHandler(object sender, SubmitSapLogRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitSapLogRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitSapLogRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SapLogRequestOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SapLogRequestOutput)(this.results[0]));
            }
        }
    }
}
