//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Suncor.Olt.Remote.Integration
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.suncor.com", ConfigurationName="MrSapUtils_PortType")]
    public interface MrSapUtils_PortType
    {
    
        // CODEGEN: Parameter 'mrPlantFindOut' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="SapCommonSoaRequest_WS_MrSapUtils_Binder_mrPlantFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mrPlantFindOut")]
        mrPlantFindResponse mrPlantFind(mrPlantFindRequest request);
    
        // CODEGEN: Parameter 'mrWorkCenterFindOut' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="SapCommonSoaRequest_WS_MrSapUtils_Binder_mrWorkCenterFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mrWorkCenterFindOut")]
        mrWorkCenterFindResponse mrWorkCenterFind(mrWorkCenterFindRequest request);
    
        // CODEGEN: Parameter 'mrWorkOrderFindOut' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="SapCommonSoaRequest_WS_MrSapUtils_Binder_mrWorkOrderFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mrWorkOrderFindOut")]
        mrWorkOrderFindResponse mrWorkOrderFind(mrWorkOrderFindRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrPlantFindReq
    {
    
        private reqSoapHeader headerField;
    
        private mrPlantFindReqBody mrPlantFindReqBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public reqSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public mrPlantFindReqBody mrPlantFindReqBody
        {
            get
            {
                return this.mrPlantFindReqBodyField;
            }
            set
            {
                this.mrPlantFindReqBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class reqSoapHeader
    {
    
        private string initiatedByField;
    
        private string initiatedSystemField;
    
        private string systemTransactionKeyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string InitiatedBy
        {
            get
            {
                return this.initiatedByField;
            }
            set
            {
                this.initiatedByField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string InitiatedSystem
        {
            get
            {
                return this.initiatedSystemField;
            }
            set
            {
                this.initiatedSystemField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string SystemTransactionKey
        {
            get
            {
                return this.systemTransactionKeyField;
            }
            set
            {
                this.systemTransactionKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class Operations
    {
    
        private string operationKeyNoField;
    
        private string operationNumberField;
    
        private string suboperationField;
    
        private string earliestStartDateField;
    
        private string earliestStartTimeField;
    
        private string earliestFinishDateField;
    
        private string earliestFinishTimeField;
    
        private string longTextField;
    
        private string workPermitTypeField;
    
        private string workPermitAttribField;
    
        private string workCenterIDField;
    
        private string workCenterNameField;
    
        private string workCenterTextField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OperationKeyNo
        {
            get
            {
                return this.operationKeyNoField;
            }
            set
            {
                this.operationKeyNoField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OperationNumber
        {
            get
            {
                return this.operationNumberField;
            }
            set
            {
                this.operationNumberField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Suboperation
        {
            get
            {
                return this.suboperationField;
            }
            set
            {
                this.suboperationField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EarliestStartDate
        {
            get
            {
                return this.earliestStartDateField;
            }
            set
            {
                this.earliestStartDateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EarliestStartTime
        {
            get
            {
                return this.earliestStartTimeField;
            }
            set
            {
                this.earliestStartTimeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string EarliestFinishDate
        {
            get
            {
                return this.earliestFinishDateField;
            }
            set
            {
                this.earliestFinishDateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string EarliestFinishTime
        {
            get
            {
                return this.earliestFinishTimeField;
            }
            set
            {
                this.earliestFinishTimeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string LongText
        {
            get
            {
                return this.longTextField;
            }
            set
            {
                this.longTextField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string WorkPermitType
        {
            get
            {
                return this.workPermitTypeField;
            }
            set
            {
                this.workPermitTypeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string WorkPermitAttrib
        {
            get
            {
                return this.workPermitAttribField;
            }
            set
            {
                this.workPermitAttribField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string WorkCenterID
        {
            get
            {
                return this.workCenterIDField;
            }
            set
            {
                this.workCenterIDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string WorkCenterName
        {
            get
            {
                return this.workCenterNameField;
            }
            set
            {
                this.workCenterNameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string WorkCenterText
        {
            get
            {
                return this.workCenterTextField;
            }
            set
            {
                this.workCenterTextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class WorkOrderDetails
    {
    
        private string wONumberField;
    
        private string shortTextField;
    
        private string functionalLocationField;
    
        private string equipmentNumberField;
    
        private string plantIDField;
    
        private string languageCodeField;
    
        private string priorityField;

        private string plannerGroup;
    
        private Operations[] operationsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WONumber", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WONumber
        {
            get
            {
                return this.wONumberField;
            }
            set
            {
                this.wONumberField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ShortText
        {
            get
            {
                return this.shortTextField;
            }
            set
            {
                this.shortTextField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FunctionalLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FunctionalLocation
        {
            get
            {
                return this.functionalLocationField;
            }
            set
            {
                this.functionalLocationField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EquipmentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EquipmentNumber
        {
            get
            {
                return this.equipmentNumberField;
            }
            set
            {
                this.equipmentNumberField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlantID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantID
        {
            get
            {
                return this.plantIDField;
            }
            set
            {
                this.plantIDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LanguageCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Priority", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PlannerGroup", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string PlannerGroup
        {
            get
            {
                return this.plannerGroup;
            }
            set
            {
                this.plannerGroup = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfOperationsItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Operations[] Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class WorkOrderRecordList
    {
    
        private string headerField;
    
        private string processStatusField;
    
        private string processMsgField;
    
        private WorkOrderDetails[] workOrderDetailsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string processStatus
        {
            get
            {
                return this.processStatusField;
            }
            set
            {
                this.processStatusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string processMsg
        {
            get
            {
                return this.processMsgField;
            }
            set
            {
                this.processMsgField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfWorkOrderDetailsItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WorkOrderDetails[] WorkOrderDetails
        {
            get
            {
                return this.workOrderDetailsField;
            }
            set
            {
                this.workOrderDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class WorkOrderOLTdata
    {
    
        private WorkOrderRecordList[] workOrderRecordListField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfWorkOrderRecordListItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WorkOrderRecordList[] WorkOrderRecordList
        {
            get
            {
                return this.workOrderRecordListField;
            }
            set
            {
                this.workOrderRecordListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrWorkOrderFindRspBody
    {
    
        private string sapCallStatusField;
    
        private string sapCallMsgField;
    
        private string numberOfRecordsField;
    
        private WorkOrderOLTdata workOrderOLTdataField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string sapCallStatus
        {
            get
            {
                return this.sapCallStatusField;
            }
            set
            {
                this.sapCallStatusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string sapCallMsg
        {
            get
            {
                return this.sapCallMsgField;
            }
            set
            {
                this.sapCallMsgField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numberOfRecords
        {
            get
            {
                return this.numberOfRecordsField;
            }
            set
            {
                this.numberOfRecordsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public WorkOrderOLTdata WorkOrderOLTdata
        {
            get
            {
                return this.workOrderOLTdataField;
            }
            set
            {
                this.workOrderOLTdataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrWorkOrderFindRsp
    {
    
        private rspSoapHeader headerField;
    
        private mrWorkOrderFindRspBody mrWorkOrderFindRspBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public rspSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mrWorkOrderFindRspBody mrWorkOrderFindRspBody
        {
            get
            {
                return this.mrWorkOrderFindRspBodyField;
            }
            set
            {
                this.mrWorkOrderFindRspBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class rspSoapHeader
    {
    
        private string callStatusField;
    
        private string callMsgField;
    
        private string initTimestampField;
    
        private string compTimestampField;
    
        private string processIdField;
    
        private string systemTransactionKeyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string CallStatus
        {
            get
            {
                return this.callStatusField;
            }
            set
            {
                this.callStatusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string CallMsg
        {
            get
            {
                return this.callMsgField;
            }
            set
            {
                this.callMsgField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string InitTimestamp
        {
            get
            {
                return this.initTimestampField;
            }
            set
            {
                this.initTimestampField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string CompTimestamp
        {
            get
            {
                return this.compTimestampField;
            }
            set
            {
                this.compTimestampField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ProcessId
        {
            get
            {
                return this.processIdField;
            }
            set
            {
                this.processIdField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string SystemTransactionKey
        {
            get
            {
                return this.systemTransactionKeyField;
            }
            set
            {
                this.systemTransactionKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrWorkOrderFindReqBody
    {
    
        private string plantIdField;
    
        private string workOrderDateField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string plantId
        {
            get
            {
                return this.plantIdField;
            }
            set
            {
                this.plantIdField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string workOrderDate
        {
            get
            {
                return this.workOrderDateField;
            }
            set
            {
                this.workOrderDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrWorkOrderFindReq
    {
    
        private reqSoapHeader headerField;
    
        private mrWorkOrderFindReqBody mrWorkOrderFindReqBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public reqSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public mrWorkOrderFindReqBody mrWorkOrderFindReqBody
        {
            get
            {
                return this.mrWorkOrderFindReqBodyField;
            }
            set
            {
                this.mrWorkOrderFindReqBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class workCenterList
    {
    
        private string pLANTField;
    
        private string wORK_CENTERField;
    
        private string rESPONSIBLEField;
    
        private string wC_CATEGORYField;
    
        private string wC_DESCField;
    
        private string lANGField;
    
        private string wCH_NAMEField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string WORK_CENTER
        {
            get
            {
                return this.wORK_CENTERField;
            }
            set
            {
                this.wORK_CENTERField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string RESPONSIBLE
        {
            get
            {
                return this.rESPONSIBLEField;
            }
            set
            {
                this.rESPONSIBLEField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string WC_CATEGORY
        {
            get
            {
                return this.wC_CATEGORYField;
            }
            set
            {
                this.wC_CATEGORYField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string WC_DESC
        {
            get
            {
                return this.wC_DESCField;
            }
            set
            {
                this.wC_DESCField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string LANG
        {
            get
            {
                return this.lANGField;
            }
            set
            {
                this.lANGField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string WCH_NAME
        {
            get
            {
                return this.wCH_NAMEField;
            }
            set
            {
                this.wCH_NAMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrWorkCenterFindRspBody
    {
    
        private string sapCallStatusField;
    
        private string sapCallMsgField;
    
        private string numberOfRecordsField;
    
        private workCenterList[] workCenterListField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string sapCallStatus
        {
            get
            {
                return this.sapCallStatusField;
            }
            set
            {
                this.sapCallStatusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string sapCallMsg
        {
            get
            {
                return this.sapCallMsgField;
            }
            set
            {
                this.sapCallMsgField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numberOfRecords
        {
            get
            {
                return this.numberOfRecordsField;
            }
            set
            {
                this.numberOfRecordsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfworkCenterListItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public workCenterList[] workCenterList
        {
            get
            {
                return this.workCenterListField;
            }
            set
            {
                this.workCenterListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrWorkCenterFindRsp
    {
    
        private rspSoapHeader headerField;
    
        private mrWorkCenterFindRspBody mrWorkCenterFindRspBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public rspSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mrWorkCenterFindRspBody mrWorkCenterFindRspBody
        {
            get
            {
                return this.mrWorkCenterFindRspBodyField;
            }
            set
            {
                this.mrWorkCenterFindRspBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class workCenterCriterion
    {
    
        private string fieldNameField;
    
        private string incOrExcField;
    
        private string operandField;
    
        private string val1Field;
    
        private string val2Field;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string fieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string incOrExc
        {
            get
            {
                return this.incOrExcField;
            }
            set
            {
                this.incOrExcField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string operand
        {
            get
            {
                return this.operandField;
            }
            set
            {
                this.operandField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string val1
        {
            get
            {
                return this.val1Field;
            }
            set
            {
                this.val1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string val2
        {
            get
            {
                return this.val2Field;
            }
            set
            {
                this.val2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrWorkCenterFindReqBody
    {
    
        private string plantIdField;
    
        private string languageField;
    
        private workCenterCriterion[] searchCriteriaListField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string plantId
        {
            get
            {
                return this.plantIdField;
            }
            set
            {
                this.plantIdField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfworkCenterCriterionItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public workCenterCriterion[] searchCriteriaList
        {
            get
            {
                return this.searchCriteriaListField;
            }
            set
            {
                this.searchCriteriaListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrWorkCenterFindReq
    {
    
        private reqSoapHeader headerField;
    
        private mrWorkCenterFindReqBody mrWorkCenterFindReqBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public reqSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public mrWorkCenterFindReqBody mrWorkCenterFindReqBody
        {
            get
            {
                return this.mrWorkCenterFindReqBodyField;
            }
            set
            {
                this.mrWorkCenterFindReqBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class plantList
    {
    
        private string mANDTField;
    
        private string wERKSField;
    
        private string nAME1Field;
    
        private string bWKEYField;
    
        private string kUNNRField;
    
        private string lIFNRField;
    
        private string fABKLField;
    
        private string nAME2Field;
    
        private string sTRASField;
    
        private string pFACHField;
    
        private string pSTLZField;
    
        private string oRT01Field;
    
        private string eKORGField;
    
        private string vKORGField;
    
        private string cHAZVField;
    
        private string kKOWKField;
    
        private string kORDBField;
    
        private string bEDPLField;
    
        private string lAND1Field;
    
        private string rEGIOField;
    
        private string cOUNCField;
    
        private string cITYCField;
    
        private string aDRNRField;
    
        private string iWERKField;
    
        private string tXJCDField;
    
        private string vTWEGField;
    
        private string sPARTField;
    
        private string sPRASField;
    
        private string wKSOPField;
    
        private string aWSLSField;
    
        private string cHAZV_OLDField;
    
        private string vLFKZField;
    
        private string bZIRKField;
    
        private string zONE1Field;
    
        private string tAXIWField;
    
        private string bZQHLField;
    
        private string lET01Field;
    
        private string lET02Field;
    
        private string lET03Field;
    
        private string tXNAM_MA1Field;
    
        private string tXNAM_MA2Field;
    
        private string tXNAM_MA3Field;
    
        private string bETOLField;
    
        private string j_1BBRANCHField;
    
        private string vTBFIField;
    
        private string fPRFWField;
    
        private string aCHVMField;
    
        private string dVSARTField;
    
        private string nODETYPEField;
    
        private string nSCHEMAField;
    
        private string pKOSAField;
    
        private string mISCHField;
    
        private string mGVUPDField;
    
        private string vSTELField;
    
        private string mGVLAUPDField;
    
        private string mGVLAREVALField;
    
        private string sOURCINGField;
    
        private string oILIVALField;
    
        private string oIHVTYPEField;
    
        private string oIHCREDIPIField;
    
        private string sTORETYPEField;
    
        private string dEP_STOREField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string MANDT
        {
            get
            {
                return this.mANDTField;
            }
            set
            {
                this.mANDTField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string NAME1
        {
            get
            {
                return this.nAME1Field;
            }
            set
            {
                this.nAME1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string BWKEY
        {
            get
            {
                return this.bWKEYField;
            }
            set
            {
                this.bWKEYField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string KUNNR
        {
            get
            {
                return this.kUNNRField;
            }
            set
            {
                this.kUNNRField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string LIFNR
        {
            get
            {
                return this.lIFNRField;
            }
            set
            {
                this.lIFNRField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string FABKL
        {
            get
            {
                return this.fABKLField;
            }
            set
            {
                this.fABKLField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string NAME2
        {
            get
            {
                return this.nAME2Field;
            }
            set
            {
                this.nAME2Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string STRAS
        {
            get
            {
                return this.sTRASField;
            }
            set
            {
                this.sTRASField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string PFACH
        {
            get
            {
                return this.pFACHField;
            }
            set
            {
                this.pFACHField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string PSTLZ
        {
            get
            {
                return this.pSTLZField;
            }
            set
            {
                this.pSTLZField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string ORT01
        {
            get
            {
                return this.oRT01Field;
            }
            set
            {
                this.oRT01Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string EKORG
        {
            get
            {
                return this.eKORGField;
            }
            set
            {
                this.eKORGField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string VKORG
        {
            get
            {
                return this.vKORGField;
            }
            set
            {
                this.vKORGField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string CHAZV
        {
            get
            {
                return this.cHAZVField;
            }
            set
            {
                this.cHAZVField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string KKOWK
        {
            get
            {
                return this.kKOWKField;
            }
            set
            {
                this.kKOWKField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string KORDB
        {
            get
            {
                return this.kORDBField;
            }
            set
            {
                this.kORDBField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string BEDPL
        {
            get
            {
                return this.bEDPLField;
            }
            set
            {
                this.bEDPLField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string LAND1
        {
            get
            {
                return this.lAND1Field;
            }
            set
            {
                this.lAND1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string REGIO
        {
            get
            {
                return this.rEGIOField;
            }
            set
            {
                this.rEGIOField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string COUNC
        {
            get
            {
                return this.cOUNCField;
            }
            set
            {
                this.cOUNCField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string CITYC
        {
            get
            {
                return this.cITYCField;
            }
            set
            {
                this.cITYCField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string ADRNR
        {
            get
            {
                return this.aDRNRField;
            }
            set
            {
                this.aDRNRField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string IWERK
        {
            get
            {
                return this.iWERKField;
            }
            set
            {
                this.iWERKField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public string TXJCD
        {
            get
            {
                return this.tXJCDField;
            }
            set
            {
                this.tXJCDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public string VTWEG
        {
            get
            {
                return this.vTWEGField;
            }
            set
            {
                this.vTWEGField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public string SPART
        {
            get
            {
                return this.sPARTField;
            }
            set
            {
                this.sPARTField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public string SPRAS
        {
            get
            {
                return this.sPRASField;
            }
            set
            {
                this.sPRASField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public string WKSOP
        {
            get
            {
                return this.wKSOPField;
            }
            set
            {
                this.wKSOPField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string AWSLS
        {
            get
            {
                return this.aWSLSField;
            }
            set
            {
                this.aWSLSField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public string CHAZV_OLD
        {
            get
            {
                return this.cHAZV_OLDField;
            }
            set
            {
                this.cHAZV_OLDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public string VLFKZ
        {
            get
            {
                return this.vLFKZField;
            }
            set
            {
                this.vLFKZField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public string BZIRK
        {
            get
            {
                return this.bZIRKField;
            }
            set
            {
                this.bZIRKField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=33)]
        public string ZONE1
        {
            get
            {
                return this.zONE1Field;
            }
            set
            {
                this.zONE1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=34)]
        public string TAXIW
        {
            get
            {
                return this.tAXIWField;
            }
            set
            {
                this.tAXIWField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=35)]
        public string BZQHL
        {
            get
            {
                return this.bZQHLField;
            }
            set
            {
                this.bZQHLField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=36)]
        public string LET01
        {
            get
            {
                return this.lET01Field;
            }
            set
            {
                this.lET01Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=37)]
        public string LET02
        {
            get
            {
                return this.lET02Field;
            }
            set
            {
                this.lET02Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=38)]
        public string LET03
        {
            get
            {
                return this.lET03Field;
            }
            set
            {
                this.lET03Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=39)]
        public string TXNAM_MA1
        {
            get
            {
                return this.tXNAM_MA1Field;
            }
            set
            {
                this.tXNAM_MA1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=40)]
        public string TXNAM_MA2
        {
            get
            {
                return this.tXNAM_MA2Field;
            }
            set
            {
                this.tXNAM_MA2Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=41)]
        public string TXNAM_MA3
        {
            get
            {
                return this.tXNAM_MA3Field;
            }
            set
            {
                this.tXNAM_MA3Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=42)]
        public string BETOL
        {
            get
            {
                return this.bETOLField;
            }
            set
            {
                this.bETOLField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=43)]
        public string J_1BBRANCH
        {
            get
            {
                return this.j_1BBRANCHField;
            }
            set
            {
                this.j_1BBRANCHField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=44)]
        public string VTBFI
        {
            get
            {
                return this.vTBFIField;
            }
            set
            {
                this.vTBFIField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=45)]
        public string FPRFW
        {
            get
            {
                return this.fPRFWField;
            }
            set
            {
                this.fPRFWField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=46)]
        public string ACHVM
        {
            get
            {
                return this.aCHVMField;
            }
            set
            {
                this.aCHVMField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=47)]
        public string DVSART
        {
            get
            {
                return this.dVSARTField;
            }
            set
            {
                this.dVSARTField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=48)]
        public string NODETYPE
        {
            get
            {
                return this.nODETYPEField;
            }
            set
            {
                this.nODETYPEField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=49)]
        public string NSCHEMA
        {
            get
            {
                return this.nSCHEMAField;
            }
            set
            {
                this.nSCHEMAField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=50)]
        public string PKOSA
        {
            get
            {
                return this.pKOSAField;
            }
            set
            {
                this.pKOSAField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=51)]
        public string MISCH
        {
            get
            {
                return this.mISCHField;
            }
            set
            {
                this.mISCHField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=52)]
        public string MGVUPD
        {
            get
            {
                return this.mGVUPDField;
            }
            set
            {
                this.mGVUPDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=53)]
        public string VSTEL
        {
            get
            {
                return this.vSTELField;
            }
            set
            {
                this.vSTELField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=54)]
        public string MGVLAUPD
        {
            get
            {
                return this.mGVLAUPDField;
            }
            set
            {
                this.mGVLAUPDField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=55)]
        public string MGVLAREVAL
        {
            get
            {
                return this.mGVLAREVALField;
            }
            set
            {
                this.mGVLAREVALField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=56)]
        public string SOURCING
        {
            get
            {
                return this.sOURCINGField;
            }
            set
            {
                this.sOURCINGField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=57)]
        public string OILIVAL
        {
            get
            {
                return this.oILIVALField;
            }
            set
            {
                this.oILIVALField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=58)]
        public string OIHVTYPE
        {
            get
            {
                return this.oIHVTYPEField;
            }
            set
            {
                this.oIHVTYPEField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=59)]
        public string OIHCREDIPI
        {
            get
            {
                return this.oIHCREDIPIField;
            }
            set
            {
                this.oIHCREDIPIField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=60)]
        public string STORETYPE
        {
            get
            {
                return this.sTORETYPEField;
            }
            set
            {
                this.sTORETYPEField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=61)]
        public string DEP_STORE
        {
            get
            {
                return this.dEP_STOREField;
            }
            set
            {
                this.dEP_STOREField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrPlantFindRspBody
    {
    
        private string sapCallStatusField;
    
        private string sapCallMsgField;
    
        private string numberOfRecordsField;
    
        private plantList[] plantListField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string sapCallStatus
        {
            get
            {
                return this.sapCallStatusField;
            }
            set
            {
                this.sapCallStatusField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string sapCallMsg
        {
            get
            {
                return this.sapCallMsgField;
            }
            set
            {
                this.sapCallMsgField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string numberOfRecords
        {
            get
            {
                return this.numberOfRecordsField;
            }
            set
            {
                this.numberOfRecordsField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfplantListItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public plantList[] plantList
        {
            get
            {
                return this.plantListField;
            }
            set
            {
                this.plantListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class MrPlantFindRsp
    {
    
        private rspSoapHeader headerField;
    
        private mrPlantFindRspBody mrPlantFindRspBodyField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public rspSoapHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mrPlantFindRspBody mrPlantFindRspBody
        {
            get
            {
                return this.mrPlantFindRspBodyField;
            }
            set
            {
                this.mrPlantFindRspBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class plantCriterion
    {
    
        private string fieldNameField;
    
        private string incOrExcField;
    
        private string operandField;
    
        private string val1Field;
    
        private string val2Field;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string fieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string incOrExc
        {
            get
            {
                return this.incOrExcField;
            }
            set
            {
                this.incOrExcField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string operand
        {
            get
            {
                return this.operandField;
            }
            set
            {
                this.operandField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string val1
        {
            get
            {
                return this.val1Field;
            }
            set
            {
                this.val1Field = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string val2
        {
            get
            {
                return this.val2Field;
            }
            set
            {
                this.val2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.suncor.com")]
    public partial class mrPlantFindReqBody
    {
    
        private plantCriterion[] searchCriteriaListField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfplantCriterionItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public plantCriterion[] searchCriteriaList
        {
            get
            {
                return this.searchCriteriaListField;
            }
            set
            {
                this.searchCriteriaListField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrPlantFind", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrPlantFindRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrPlantFindReq mrPlantFindIn;
    
        public mrPlantFindRequest()
        {
        }
    
        public mrPlantFindRequest(MrPlantFindReq mrPlantFindIn)
        {
            this.mrPlantFindIn = mrPlantFindIn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrPlantFindResponse", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrPlantFindResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrPlantFindRsp mrPlantFindOut;
    
        public mrPlantFindResponse()
        {
        }
    
        public mrPlantFindResponse(MrPlantFindRsp mrPlantFindOut)
        {
            this.mrPlantFindOut = mrPlantFindOut;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrWorkCenterFind", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrWorkCenterFindRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrWorkCenterFindReq mrWorkCenterFindIn;
    
        public mrWorkCenterFindRequest()
        {
        }
    
        public mrWorkCenterFindRequest(MrWorkCenterFindReq mrWorkCenterFindIn)
        {
            this.mrWorkCenterFindIn = mrWorkCenterFindIn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrWorkCenterFindResponse", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrWorkCenterFindResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrWorkCenterFindRsp mrWorkCenterFindOut;
    
        public mrWorkCenterFindResponse()
        {
        }
    
        public mrWorkCenterFindResponse(MrWorkCenterFindRsp mrWorkCenterFindOut)
        {
            this.mrWorkCenterFindOut = mrWorkCenterFindOut;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrWorkOrderFind", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrWorkOrderFindRequest
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrWorkOrderFindReq mrWorkOrderFindIn;
    
        public mrWorkOrderFindRequest()
        {
        }
    
        public mrWorkOrderFindRequest(MrWorkOrderFindReq mrWorkOrderFindIn)
        {
            this.mrWorkOrderFindIn = mrWorkOrderFindIn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mrWorkOrderFindResponse", WrapperNamespace="http://www.suncor.com", IsWrapped=true)]
    public partial class mrWorkOrderFindResponse
    {
    
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.suncor.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MrWorkOrderFindRsp mrWorkOrderFindOut;
    
        public mrWorkOrderFindResponse()
        {
        }
    
        public mrWorkOrderFindResponse(MrWorkOrderFindRsp mrWorkOrderFindOut)
        {
            this.mrWorkOrderFindOut = mrWorkOrderFindOut;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MrSapUtils_PortTypeChannel : MrSapUtils_PortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MrSapUtils_PortTypeClient : System.ServiceModel.ClientBase<MrSapUtils_PortType>, MrSapUtils_PortType
    {
    
        public MrSapUtils_PortTypeClient()
        {
        }
    
        public MrSapUtils_PortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
        {
        }
    
        public MrSapUtils_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public MrSapUtils_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public MrSapUtils_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
        {
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mrPlantFindResponse MrSapUtils_PortType.mrPlantFind(mrPlantFindRequest request)
        {
            return base.Channel.mrPlantFind(request);
        }
    
        public MrPlantFindRsp mrPlantFind(MrPlantFindReq mrPlantFindIn)
        {
            mrPlantFindRequest inValue = new mrPlantFindRequest();
            inValue.mrPlantFindIn = mrPlantFindIn;
            mrPlantFindResponse retVal = ((MrSapUtils_PortType)(this)).mrPlantFind(inValue);
            return retVal.mrPlantFindOut;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mrWorkCenterFindResponse MrSapUtils_PortType.mrWorkCenterFind(mrWorkCenterFindRequest request)
        {
            return base.Channel.mrWorkCenterFind(request);
        }
    
        public MrWorkCenterFindRsp mrWorkCenterFind(MrWorkCenterFindReq mrWorkCenterFindIn)
        {
            mrWorkCenterFindRequest inValue = new mrWorkCenterFindRequest();
            inValue.mrWorkCenterFindIn = mrWorkCenterFindIn;
            mrWorkCenterFindResponse retVal = ((MrSapUtils_PortType)(this)).mrWorkCenterFind(inValue);
            return retVal.mrWorkCenterFindOut;
        }
    
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mrWorkOrderFindResponse MrSapUtils_PortType.mrWorkOrderFind(mrWorkOrderFindRequest request)
        {
            return base.Channel.mrWorkOrderFind(request);
        }
    
        public MrWorkOrderFindRsp mrWorkOrderFind(MrWorkOrderFindReq mrWorkOrderFindIn)
        {
            mrWorkOrderFindRequest inValue = new mrWorkOrderFindRequest();
            inValue.mrWorkOrderFindIn = mrWorkOrderFindIn;
            mrWorkOrderFindResponse retVal = ((MrSapUtils_PortType)(this)).mrWorkOrderFind(inValue);
            return retVal.mrWorkOrderFindOut;
        }
    }
}