insert ShiftHandoverConfiguration (Name,Deleted )  select 'TDS Operator Handover Questions',0
insert ShiftHandoverConfiguration (Name,Deleted )  select 'TDS Supervisor Handover Questions',0
insert ShiftHandoverConfiguration (Name,Deleted )  select 'TDS Dispatcher / Ops Coord Handover Questions',0

insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Operator Handover Questions' and w.name = 'Firebag OM Technician' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Operator Handover Questions' and w.name = 'Firebag Protection Specialist' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Operator Handover Questions' and w.name = 'Oilsands OM Technician' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Operator Handover Questions' and w.name = 'Oilsands Protection Specialist' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Supervisor Handover Questions' and w.name = 'Firebag Shift Supervisor' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Supervisor Handover Questions' and w.name = 'Oilsands Shift Supervisor' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Dispatcher / Ops Coord Handover Questions' and w.name = 'Ops Coordinator' and w.siteid = 6
insert ShiftHandoverConfigurationWorkAssignment ( ShiftHandoverConfigurationId,WorkAssignmentId )  select g.id, w.id from ShiftHandoverConfiguration g, WorkAssignment w where g.name = 'TDS Dispatcher / Ops Coord Handover Questions' and w.name = 'SCC Operator' and w.siteid = 6

insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 0, 'Were there any Environmental, Health or Safety concerns during this shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Mitigation' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Operator Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 1, 'Were there any unplanned outages during the shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Restoration Issues' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Operator Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 2, 'Was there any ongoing work that requires completion during the next shift?', 'Details should be in log and may include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) Notification or Work Order #' + CHAR(13) + CHAR(10) + '2) Summary of the work' + CHAR(13) + CHAR(10) + '3) Materials Required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Operator Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 0, 'Were there any Environmental, Health or Safety concerns during this shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Mitigation' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Supervisor Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 1, 'Were there any unplanned outages during the shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Restoration Issues' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Supervisor Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 2, 'Was there any ongoing work that requires completion during the next shift?', 'Details should be in log and may include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) Notification or Work Order #' + CHAR(13) + CHAR(10) + '2) Summary of the work' + CHAR(13) + CHAR(10) + '3) Materials Required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Supervisor Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 3, 'Were there any recorded incidents that were reportable to AESO during your shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Restoration Issues' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Supervisor Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 0, 'Were there any Environmental, Health or Safety concerns during this shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Mitigation' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Dispatcher / Ops Coord Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 1, 'Were there any unplanned outages during the shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Restoration Issues' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Dispatcher / Ops Coord Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 2, 'Were there any recorded incidents that were reportable to AESO during your shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) ILP # (if any)' + CHAR(13) + CHAR(10) + '2) Location' + CHAR(13) + CHAR(10) + '3) Description' + CHAR(13) + CHAR(10) + '4) Cause (if known)' + CHAR(13) + CHAR(10) + '5) Restoration Issues' + CHAR(13) + CHAR(10) + '6) Follow up required', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Dispatcher / Ops Coord Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 3, 'Are there any upcoming switching events for the next shift?', 'Details would include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) Where' + CHAR(13) + CHAR(10) + '2) When' + CHAR(13) + CHAR(10) + '3) Switch order development complete', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Dispatcher / Ops Coord Handover Questions'
insert into ShiftHandoverQuestion (ShiftHandoverConfigurationId, DisplayOrder, Text, HelpText, Deleted, IsCurrentQuestionVersion) select distinct g.id, 4, 'Were there any alarms or trips inhibited or disabled during your shift?', 'Details should be in log and may include:' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) + '1) Location' + CHAR(13) + CHAR(10) + '2) Equipment #' + CHAR(13) + CHAR(10) + '3) Is it still disabled at the end of the shift', 0, 1 from ShiftHandoverConfiguration g inner join ShiftHandoverConfigurationWorkAssignment shcwa on shcwa.ShifthandoverConfigurationId = g.Id inner join WorkAssignment wa on wa.Id = shcwa.WorkAssignmentId  where wa.SiteId = 6 and g.name = 'TDS Dispatcher / Ops Coord Handover Questions'
GO