INSERT INTO TargetDefinitionHistory
	(
	Id,
	Name,
	NeverToExceedMax,
	NeverToExceedMin,
	MaxValue,
	MinValue,
	NeverToExceedMaxFrequency,
	NeverToExceedMinFrequency,
	MaxValueFrequency,
	MinValueFrequency,
	TargetDefinitionValue,
	GapUnitValue,
	TargetDefinitionStatusID,
	TargetCategoryID,
	TagID,
	FunctionalLocationID,
	LastModifiedUserId,
	LastModifiedDateTime,
	GenerateActionItem,
	Description,
	Schedule,
	AlertRequired,
	RequiresApproval,
	RequiresResponseWhenAlerted,
	IsActive,
	OperationalModeId,
	AssociatedTargets,
	DocumentLinks,
	PreApprovedNeverToExceedMin,
	PreApprovedNeverToExceedMax,
	PreApprovedMin,
	PreApprovedMax,
	PriorityId) 
	VALUES 
	(1,
	N'TestData Target',
	null,
	21.00,
	100.00,
	null,
	1,
	1,
	100,
	1,
	'50',
	50.00,
	1,
	1,
	1,
	1,
	1,
	'2005-01-01 00:00:00',
	1,
	N' ',
	'schedule',
	1,
	1,
	1,
	0,
	2,
	null,
	null,
	null,
	null,
	null,
	null,
	1)
	
INSERT INTO TargetDefinitionHistory
	(Id,Name,NeverToExceedMax,NeverToExceedMin,MaxValue,
	MinValue,NeverToExceedMaxFrequency,NeverToExceedMinFrequency,MaxValueFrequency,MinValueFrequency,
	TargetDefinitionValue,GapUnitValue,TargetDefinitionStatusID,TargetCategoryID,TagID,
	FunctionalLocationID,LastModifiedUserId,LastModifiedDateTime,GenerateActionItem,Description,
	Schedule,AlertRequired,RequiresApproval,RequiresResponseWhenAlerted,IsActive,
	OperationalModeId,AssociatedTargets,DocumentLinks,PreApprovedNeverToExceedMin,PreApprovedNeverToExceedMax,
	PreApprovedMin,PreApprovedMax,PriorityId) 
	VALUES (1,N'Modified Test Data Target',null,21.00,100.00,
	null,1,1,100,1,
	'50',50.00,1,1,1,
	1,1,'2005-01-01 00:00:00',1,N' ',
	'schedule changed',	1,1,1,0,
	2,null,null,null,null,
	null,null,1)
GO
