INSERT INTO WorkPermitMontrealTemplate (
   [Name]
  ,TypeId
  ,Active
  ,Deleted
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,TemplateNumber
) SELECT 
   [Name]
  ,6
  ,1
  ,0
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,(SELECT MAX(TemplateNumber) + 1 FROM WorkPermitMontrealTemplate)
FROM
  WorkPermitMontrealTemplate where Active = 1 and deleted = 0 and TemplateNumber = 3
GO

INSERT INTO WorkPermitMontrealTemplate (
   [Name]
  ,TypeId
  ,Active
  ,Deleted
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,TemplateNumber
) SELECT 
   [Name]
  ,7
  ,1
  ,0
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,(SELECT MAX(TemplateNumber) + 1 FROM WorkPermitMontrealTemplate)
FROM
  WorkPermitMontrealTemplate where Active = 1 and deleted = 0 and TemplateNumber = 2
GO  

INSERT INTO WorkPermitMontrealTemplate (
   [Name]
  ,TypeId
  ,Active
  ,Deleted
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,TemplateNumber
) SELECT 
   [Name]
  ,7
  ,1
  ,0
  ,H2S
  ,Hydrocarbure
  ,Ammoniaque
  ,Corrosif
  ,CorrosifValue
  ,Aromatique
  ,AromatiqueValue
  ,AutresSubstances
  ,AutresSubstancesValue
  ,ObtureOuDeBranche
  ,DepressuriseEtVidange
  ,EnPresenceDeGazInerte
  ,PurgeALaVapeur
  ,RinceALEau
  ,Excavation
  ,DessinsRequis
  ,DessinsRequisValue
  ,CablesChauffantsMisHorsTension
  ,PompeOuVerinPneumatique
  ,ChaineEtCadenasseOuScelle
  ,InterrupteursElectriquesVerrouilles
  ,PurgeParUnGazInerte
  ,OutilsElectriquesOuABatteries
  ,BoiteEnergieZero
  ,BoiteEnergieZeroValue
  ,OutilsPneumatiques
  ,MoteurACombustionInterne
  ,TravauxSuperposes
  ,FormulaireDespaceClosAffiche
  ,FormulaireDespaceClosAfficheValue
  ,ExisteIlUneAnalyseDeTache
  ,PossibiliteDeSulfureDeFer
  ,AereVentile
  ,SoudureALelectricite
  ,BrulageAAcetylene
  ,Nacelle
  ,AutreConditions
  ,AutreConditionsValue
  ,LunettesMonocoques
  ,HarnaisDeSecurite
  ,EcranFacial
  ,ProtectionAuditive
  ,Trepied
  ,DispositifAntiChute
  ,ProtectionRespiratoire
  ,ProtectionRespiratoireValue
  ,Habits
  ,HabitsValue
  ,AutreProtection
  ,AutreProtectionValue
  ,Extincteur
  ,BouchesDegoutProtegees
  ,CouvertureAntiEtincelles
  ,SurveillantPourEtincelles
  ,PareEtincelles
  ,MiseAlaTerrePresDuLieuDeTravail
  ,BoyauAVapeur
  ,AutresEquipementDincendie
  ,AutresEquipementDincendieValue
  ,Ventulateur
  ,Barrieres
  ,Surveillant
  ,SurveillantValue
  ,RadioEmetteur
  ,PerimetreDeSecurite
  ,DetectionContinueDesGaz
  ,DetectionContinueDesGazValue
  ,KlaxonSonore
  ,Localiser
  ,Amiante
  ,AutreEquipementsSecurite
  ,AutreEquipementsSecuriteValue
  ,InstructionsSpeciales
  ,SignatureOperateurSurLeTerrain
  ,DetectionDesGazs
  ,SignatureContremaitre
  ,SignatureAutorise
  ,(SELECT MAX(TemplateNumber) + 1 FROM WorkPermitMontrealTemplate)
FROM
  WorkPermitMontrealTemplate where Active = 1 and deleted = 0 and TemplateNumber = 21
GO
 


GO

