

CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmontonDetails_FormGN7] ON [dbo].[WorkPermitEdmontonDetails] 
(
	[FormGN7Id] ASC
) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]

go

CREATE NONCLUSTERED INDEX [IDX_WorkPermitEdmontonDetails_FormGN59] ON [dbo].[WorkPermitEdmontonDetails] 
(
	[FormGN59Id] ASC
) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]

go



GO

