if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[UpdateWorkPermitMontreal]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	drop procedure [dbo].[UpdateWorkPermitMontreal]
GO

CREATE Procedure [dbo].[UpdateWorkPermitMontreal]
(
	@Id bigint,
	@PermitNumber bigint Output,
	@ShouldCreatePermitNumber bit,
	@WorkPermitStatusId tinyint,
	@WorkPermitTypeId bigint,
	@RequestedByGroupId bigint = NULL,
	@StartDateTime DateTime,
	@EndDateTime DateTime,
	@TemplateId bigint = NULL,
	@WorkOrderNumber VARCHAR(12) = NULL,
	@Trade varchar(100),
	@Description VARCHAR(400),
	@LastModifiedDateTime DateTime,
	@LastModifiedByUserId bigint,
	@IssuedDateTime datetime = null,
	@H2S bit,
	@Hydrocarbure bit,
	@Ammoniaque bit,
	@Corrosif bit,
	@CorrosifValue VARCHAR(100),
	@Aromatique bit,
	@AromatiqueValue VARCHAR(100),
	@AutresSubstances bit,
	@AutresSubstancesValue VARCHAR(100),
	@ObtureOuDebranche bit,
	@DepressuriseEtVidange bit,
	@EnPresenceDeGazInerte bit,
	@PurgeALaVapeur bit,
	@RinceALeau bit,
	@Excavation bit,
	@DessinsRequis bit,
	@DessinsRequisValue VARCHAR(100),
	@CablesChauffantsMisHorsTension bit,
	@PompeOuVerinPneumatique bit,
	@ChaineEtCadenasseOuScelle bit,
	@InterrupteursElectriquesVerrouilles bit,
	@PurgeParUnGazInerte bit,
	@OutilsElectriquesOuABatteries bit,
	@BoiteEnergieZero bit,
	@BoiteEnergieZeroValue VARCHAR(100),
	@OutilsPneumatiques bit,
	@MoteurACombustionInterne bit,
	@TravauxSuperPoses bit,
	@FormulaireDespaceClosAffiche bit,
	@FormulaireDespaceClosAfficheValue VARCHAR(100),
	@ExisteIlUneAnalyseDeTache bit,
	@PossibiliteDeSulfureDeFer bit,
	@AereVentile bit,
	@SoudureALelectricite bit,
	@BrulageAAcetylene bit,
	@Nacelle bit,
	@AutreConditions bit,
	@AutreConditionsValue VARCHAR(100),
	@LunettesMonocoques bit,
	@HarnaisDeSecurite bit,
	@EcranFacial bit,
	@ProtectionAuditive bit,
	@Trepied bit,
	@DispositifAntichute bit,
	@ProtectionRespiratoire bit,
	@ProtectionRespiratoireValue VARCHAR(100),
	@Habits bit,
	@HabitsValue VARCHAR(100),
	@AutreProtection bit,
	@AutreProtectionValue VARCHAR(100),
	@Extincteur bit,
	@BouchesDegoutProtegees bit,
	@CouvertureAntiEtincelles bit,
	@SurveillantPouretincelles bit,
	@PareEtincelles bit,
	@MiseAlaTerrePresDuLieuDeTravail bit,
	@BoyauAVapeur bit,
	@AutresEquipementDincendie bit,
	@AutresEquipementDincendieValue VARCHAR(100),
	@Ventulateur bit,
	@Barrieres bit,
	@Surveillant bit,
	@SurveillantValue VARCHAR(100),
	@RadioEmetteur bit,
	@PerimetreDeSecurite bit,
	@DetectionContinueDesGaz bit,
	@DetectionContinueDesGazValue VARCHAR(100),
	@KlaxonSonore bit,
	@Localiser bit,
	@Amiante bit,
	@AutreEquipementsSecurite bit,
	@AutreEquipementsSecuriteValue VARCHAR(100),
	@InstructionsSpeciales VARCHAR(500),
	@SignatureOperateurSurLeTerrain bit,
	@DetectionDesGazs bit,
	@SignatureContremaitre bit,
	@SignatureAutorise bit,
	@UsePreviousPermitAnswered bit,
	@NettoyageTransfertHorsSite bit
)
AS

IF @ShouldCreatePermitNumber = 1
	BEGIN
		EXEC @PermitNumber = GetNewSeqVal_WorkPermitMontrealPermitNumberSequence
	END
ELSE
	BEGIN
		SET @PermitNumber = (select PermitNumber from WorkPermitMontreal WHERE Id = @Id)
	END

UPDATE WorkPermitMontreal
	SET 
		WorkPermitStatusId = @WorkPermitStatusId,
		WorkPermitTypeId = @WorkPermitTypeId,
		RequestedByGroupId = @RequestedByGroupId,
		StartDateTime = @StartDateTime,
		EndDateTime = @EndDateTime,
		PermitNumber = @PermitNumber,
		TemplateId = @TemplateId,
		WorkOrderNumber = @WorkOrderNumber,
		Trade = @Trade,
		Description = @Description,
		UsePreviousPermitAnswered = @UsePreviousPermitAnswered,
		LastModifiedDateTime = @LastModifiedDateTime,
		LastModifiedByUserId = @LastModifiedByUserId,
		IssuedDateTime = @IssuedDateTime
	WHERE
		Id = @Id


UPDATE WorkPermitMontrealDetails
	SET
 	H2S = @H2S,
	Hydrocarbure = @Hydrocarbure,
	Ammoniaque = @Ammoniaque,
	Corrosif = @Corrosif,
	CorrosifValue = @CorrosifValue,
	Aromatique = @Aromatique,
	AromatiqueValue = @AromatiqueValue,
	AutresSubstances = @AutresSubstances,
	AutresSubstancesValue = @AutresSubstancesValue,
	
	ObtureOuDebranche = @ObtureOuDebranche,
	DepressuriseEtVidange = @DepressuriseEtVidange,
	EnPresenceDeGazInerte = @EnPresenceDeGazInerte,
	PurgeALaVapeur = @PurgeALaVapeur,
	RinceALeau = @RinceALeau,
	Excavation = @Excavation,
	DessinsRequis = @DessinsRequis,
	DessinsRequisValue = @DessinsRequisValue,
	CablesChauffantsMisHorsTension = @CablesChauffantsMisHorsTension,
	PompeOuVerinPneumatique = @PompeOuVerinPneumatique,
	
	ChaineEtCadenasseOuScelle = @ChaineEtCadenasseOuScelle,
	InterrupteursElectriquesVerrouilles = @InterrupteursElectriquesVerrouilles,
	PurgeParUnGazInerte = @PurgeParUnGazInerte,
	OutilsElectriquesOuABatteries = @OutilsElectriquesOuABatteries,
	BoiteEnergieZero = @BoiteEnergieZero,
	BoiteEnergieZeroValue = @BoiteEnergieZeroValue,
	OutilsPneumatiques = @OutilsPneumatiques,
	MoteurACombustionInterne = @MoteurACombustionInterne,
	TravauxSuperPoses = @TravauxSuperPoses,
	
	FormulaireDespaceClosAffiche = @FormulaireDespaceClosAffiche,
	FormulaireDespaceClosAfficheValue = @FormulaireDespaceClosAfficheValue,
	ExisteIlUneAnalyseDeTache = @ExisteIlUneAnalyseDeTache,
	PossibiliteDeSulfureDeFer = @PossibiliteDeSulfureDeFer,
	AereVentile = @AereVentile,
	SoudureALelectricite = @SoudureALelectricite,
	BrulageAAcetylene = @BrulageAAcetylene,
	Nacelle = @Nacelle,
	AutreConditions = @AutreConditions,
	AutreConditionsValue = @AutreConditionsValue,
	
	LunettesMonocoques = @LunettesMonocoques,
	HarnaisDeSecurite = @HarnaisDeSecurite,
	EcranFacial = @EcranFacial,
	ProtectionAuditive = @ProtectionAuditive,
	Trepied = @Trepied,
	DispositifAntichute = @DispositifAntichute,
	ProtectionRespiratoire = @ProtectionRespiratoire,
	ProtectionRespiratoireValue = @ProtectionRespiratoireValue,
	Habits = @Habits,
	HabitsValue = @HabitsValue,
	AutreProtection = @AutreProtection,
	AutreProtectionValue = @AutreProtectionValue,
	
	Extincteur = @Extincteur,
	BouchesDegoutProtegees = @BouchesDegoutProtegees,
	CouvertureAntiEtincelles = @CouvertureAntiEtincelles,
	SurveillantPouretincelles = @SurveillantPouretincelles,
	PareEtincelles = @PareEtincelles,
	MiseAlaTerrePresDuLieuDeTravail = @MiseAlaTerrePresDuLieuDeTravail,
	BoyauAVapeur = @BoyauAVapeur,
	AutresEquipementDincendie = @AutresEquipementDincendie,
	AutresEquipementDincendieValue = @AutresEquipementDincendieValue,
	
	Ventulateur = @Ventulateur,
	Barrieres = @Barrieres,
	Surveillant = @Surveillant,
	SurveillantValue = @SurveillantValue,
	RadioEmetteur = @RadioEmetteur,
	PerimetreDeSecurite = @PerimetreDeSecurite,
	DetectionContinueDesGaz = @DetectionContinueDesGaz,
	DetectionContinueDesGazValue = @DetectionContinueDesGazValue,
	KlaxonSonore = @KlaxonSonore,
	Localiser = @Localiser,
	Amiante = @Amiante,
	AutreEquipementsSecurite = @AutreEquipementsSecurite,
	AutreEquipementsSecuriteValue = @AutreEquipementsSecuriteValue,
	
	InstructionsSpeciales = @InstructionsSpeciales,
	SignatureOperateurSurLeTerrain = @SignatureOperateurSurLeTerrain,
	DetectionDesGazs = @DetectionDesGazs,
	SignatureContremaitre = @SignatureContremaitre,
	SignatureAutorise = @SignatureAutorise,
	NettoyageTransfertHorsSite = @NettoyageTransfertHorsSite
	WHERE
		Id = @Id
GO	

GRANT EXEC ON UpdateWorkPermitMontreal TO PUBLIC
GO