insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('AN6', 'Analyzer Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM1', 'Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM1-C', 'Boilermaker Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM2', 'Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM2-C', 'Boilermaker Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM3', 'Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM3-C', 'Boilermaker Synthetic Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM4', 'Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM4-C', 'Boilermaker Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM5', 'Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM5-C', 'Boilermaker Pumping&Shipping, Contract', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM6', 'Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BM6-C', 'Boilermaker Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW1', 'Boilermaker Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW1-C', 'Boilermaker Welder Heavy Oils, Contracto', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW2', 'Boilermaker Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW2-C', 'Boilermaker Welder Light Oils, Contracto', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW3', 'Boilermaker Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW3-C', 'Boilermaker Welder Synthetic Oils, Contr', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW4', 'Boilermaker Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW4-C', 'Boilermaker Welder Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW5', 'Boilermaker Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW5-C', 'Boilermaker Welder Pumping&Shipping, C', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW6', 'Boilermaker Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BMW6-C', 'Boilermaker Welder Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT1', 'Building Trades, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT1-C', 'Building Trades Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT2', 'Building Trades, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT2-C', 'Building Trades Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT3', 'Building Trades, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT3-C', 'Building Trades Synthetic Oils, Contract', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT4', 'Building Trades, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT4-C', 'Building Trades Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT5', 'Building Trades, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT5-C', 'Building Trades Pumping&Shipping, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT6', 'Building Trades, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('BT6-C', 'Building Trades Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CAN601', 'CON Analyzer Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM101', 'CON Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM201', 'CON Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM301', 'CON Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM401', 'CON Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM501', 'CON Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBM601', 'CON Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW101', 'CON Boilermaker Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW201', 'CON Boilermaker Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW301', 'CON Boilermaker Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW401', 'CON Boilermaker Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW501', 'CON Boilermaker Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBMW601', 'CON Boilermaker Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT101', 'CON Building Trades, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT201', 'CON Building Trades, CIVIL', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT301', 'CON CIVIL - EARTH WORK', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT401', 'CON Building Trades, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT501', 'CON Building Trades, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CBT601', 'CON Building Trades, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CDCS601', 'CON DCS Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL101', 'CON Electrician, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL201', 'CON Electrician, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL301', 'CON Electrician, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL401', 'CON Electrician, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL501', 'CON Electrician, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEL601', 'CON Electrician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CEO601', 'CON Equipment Operator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL101', 'CON Insulator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL201', 'CON Insulator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL301', 'CON Insulator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL401', 'CON Insulator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL501', 'CON Insulator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIL601', 'CON Insulator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIN601', 'CON Instrument Tech', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CIW601', 'CON Iron Worker, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA101', 'CON Labourer Maint, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA201', 'CON Labourer Maint, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA301', 'CON Labourer Maint, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA401', 'CON Labourer Maint, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA501', 'CON Labourer Maint, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CLA601', 'CON Labourer Maint, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CMA101', 'CON Machinist, HEAVY OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CMW101', 'CON Millwright, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CMW601', 'CON Millwright, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF101', 'CON Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF201', 'CON Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF301', 'CON Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF401', 'CON Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF501', 'CON Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPF601', 'CON Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW101', 'CON Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW201', 'CON Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW301', 'CON Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW401', 'CON Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW501', 'CON Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CPFW601', 'CON Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC101', 'CON Scaffolder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC201', 'CON Scaffolder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC301', 'CON Scaffolder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC401', 'CON Scaffolder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC501', 'CON Scaffolder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSC601', 'CON Scaffolder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('DCS6', 'DCS Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL1', 'Electrician, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL1-C', 'Electrician Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL2', 'Electrician, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL2-C', 'Electrician Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL3', 'Electrician, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL3-C', 'Electrician Synthetic Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL4', 'Electrician, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL4-C', 'Electrician Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL5', 'Electrician, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL5-C', 'Electrician/Pumping/Shipping Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL6', 'Electrician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EL6-C', 'Electrician Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EO6', 'Equipment Operator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EO6-C', 'Equipment Operator, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL1', 'Insulator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL1-C', 'Insulator Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL2', 'Insulator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL2-C', 'Insulator Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL3', 'Insulator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL3-C', 'Insulator Synthetic Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL4', 'Insulator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL4-C', 'Insulator Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL5', 'Insulator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL5-C', 'Insulator Pumping&Shipping, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL6', 'Insulator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IL6-C', 'Insulator Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN1', 'Instrument Tech, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN1-C', 'Instrument Tech Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN2', 'Instrument Tech, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN2-C', 'Instrument Tech Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN3', 'Instrument Tech, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN3-C', 'Instrument Tech Synthetic Oils,Contract', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN4', 'Instrument Tech, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN4-C', 'Instrument Tech Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN5', 'Instrument Tech, Pumping & Shippin', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN5-C', 'Instrument Tech Pumping&Shipping, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN6', 'Instrument Tech, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IN6-C', 'Instrument Tech Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('IW6-C', 'Iron Worker, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA1', 'Labourer Maint, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA1-C', 'Labourer Maint. Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA2', 'Labourer Maint, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA2-C', 'Labourer Maint. Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA3', 'Labourer Maint, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA3-C', 'Labourer Maint. Synthetic Oils, Contract', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA4', 'Labourer Maint, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA4-C', 'Labourer Maint. Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA5', 'Labourer Maint, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA5-C', 'Labourer Maint. Pumping&Shipping, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA6', 'Labourer Maint, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LA6-C', 'Labourer Maint. Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MA6', 'Machinist, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MA6-C', 'Machinist, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW1', 'Millwright, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW1-C', 'Millwright Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW2', 'Millwright, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW2-C', 'Millwright Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW3', 'Millwright, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW3-C', 'Millwright Synthetic Oils,Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW4', 'Millwright, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW4-C', 'Millwright Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW5', 'Millwright, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW5-C', 'Millwright Pumping&Shipping, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW6', 'Millwright, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MW6-C', 'Millwright Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF1', 'Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF1-C', 'Pipefitter Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF2', 'Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF2-C', 'Pipefitter Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF3', 'Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF3-C', 'Pipefitter Synthetic Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF4', 'Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF4-C', 'Pipefitter Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF5', 'Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF5-C', 'Pipefitter Pumping&Shipping, Contracto', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF6', 'Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PF6-C', 'Pipefitter Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW1', 'Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW1-C', 'Pipefitter Welder Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW2', 'Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW2-C', 'Pipefitter Welder Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW3', 'Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW3-C', 'PF Welder Synthetic Oils, Contract', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW4', 'Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW4-C', 'Pipefitter Welder Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW5', 'Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW5-C', 'Pipefitter Welder Pumping&Shipping, Co', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW6', 'Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PFW6-C', 'Pipefitter Welder Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC1', 'Scaffolder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC1-C', 'Scaffolder Heavy Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC2', 'Scaffolder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC2-C', 'Scaffolder Light Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC3', 'Scaffolder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC3-C', 'Scaffolder Synthetic Oils, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC4', 'Scaffolder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC4-C', 'Scaffolder Utilities, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC5', 'Scaffolder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC5-C', 'Scaffolder Pumping&Shipping, Contracto', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC6', 'Scaffolder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SC6-C', 'Scaffolder Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZAN601', 'T/A Analyzer Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM101', 'T/A Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM102', 'T/A Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM103', 'T/A Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM104', 'T/A Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM105', 'T/A Boilermaker, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM201', 'T/A Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM202', 'T/A Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM203', 'T/A Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM204', 'T/A Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM205', 'T/A Boilermaker, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM301', 'T/A Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM302', 'T/A Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM303', 'T/A Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM304', 'T/A Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM305', 'T/A Boilermaker, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM401', 'T/A Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM402', 'T/A Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM403', 'T/A Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM404', 'T/A Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM405', 'T/A Boilermaker, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM501', 'T/A Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM502', 'T/A Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM503', 'T/A Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM504', 'T/A Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM505', 'T/A Boilermaker, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM601', 'T/A Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM602', 'T/A Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM603', 'T/A Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM604', 'T/A Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBM605', 'T/A Boilermaker, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW101', 'T/A Boilermaker Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW201', 'T/A Boilermaker Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW301', 'T/A Boilermaker Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW401', 'T/A Boilermaker Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW501', 'T/A Boilermaker Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBMW601', 'T/A Boilermaker Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT101', 'T/A Building Trades, HO Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT201', 'T/A Building Trades, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT301', 'T/A Building Trades, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT401', 'T/A Building Trades, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT501', 'T/A Building Trades, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBT601', 'T/A Building Trades, Suncor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZDCS601', 'T/A DCS Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZDCS602', 'T/A DCS Technician LIGHT OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZDCS603', 'T/A DCS Technician, SYNTHETIC OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZDCS604', 'T/A DCS Technician, Central UTILITIES', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZDCS605', 'T/A DCS Technician, PUMPING & SHIPPING', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL101', 'T/A Electrician SUNCOR', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL102', 'T/A Electrician, GRP 2 heavy', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL103', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL201', 'T/A Electrician, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL202', 'T/A Electrician, GRP 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL203', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL301', 'T/A Electrician, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL302', 'T/A Electrician, GRP 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL303', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL401', 'T/A Electrician, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL402', 'T/A Electrician, GRP 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL403', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL501', 'T/A Electrician, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL502', 'T/A Electrician, GRP 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL503', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL601', 'T/A Electrician CG', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL602', 'T/A Electrician, GRP 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEL603', 'T/A Electrician, GRP 3', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZEO601', 'T/A Equipment Operator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL101', 'T/A Insulator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL201', 'T/A Insulator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL301', 'T/A Insulator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL401', 'T/A Insulator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL501', 'T/A Insulator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIL601', 'T/A Insulator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN101', 'T/A Instrument Technician, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN201', 'T/A Instrument Technician, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN301', 'T/A Instrument Technician,Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN401', 'T/A Instrument Technician, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN501', 'T/A Instrument Tech, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIN601', 'T/A Instrument Technician, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZIW601', 'T/A Iron Worker, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA101', 'T/A Labourer Maint, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA201', 'T/A Labourer Maint, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA301', 'T/A Labourer Maint, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA401', 'T/A Labourer Maint, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA501', 'T/A Labourer Maint, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZLA601', 'T/A Labourer Maint, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA101', 'T/A Machinist, HEAVY OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA201', 'T/A Machinist,  LIGHTS OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA301', 'T/A Machinist,  SYNTHETIC OILS', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA401', 'T/A Machinist, UTILITIES', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA501', 'T/A Machinist, PUMPING & SHIPPING', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMA601', 'T/A Machinist, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW101', 'T/A Millwright, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW201', 'T/A Millwright, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW301', 'T/A Millwright, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW401', 'T/A Millwright, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW501', 'T/A Millwright, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMW601', 'T/A Millwright, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF101', 'T/A Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF102', 'T/A Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF103', 'T/A Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF104', 'T/A Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF105', 'T/A Pipefitter, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF201', 'T/A Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF202', 'T/A Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF203', 'T/A Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF204', 'T/A Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF205', 'T/A Pipefitter, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF301', 'T/A Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF302', 'T/A Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF303', 'T/A Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF304', 'T/A Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF305', 'T/A Pipefitter, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF401', 'T/A Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF402', 'T/A Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF403', 'T/A Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF404', 'T/A Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF405', 'T/A Pipefitter, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF501', 'T/A Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF502', 'T/A Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF503', 'T/A Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF504', 'T/A Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF505', 'T/A Pipefitter, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF601', 'T/A Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF602', 'T/A Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF603', 'T/A Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF604', 'T/A Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPF605', 'T/A Pipefitter, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW101', 'T/A Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW102', 'T/A Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW103', 'T/A Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW104', 'T/A Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW105', 'T/A Pipefitter Welder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW201', 'T/A Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW202', 'T/A Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW203', 'T/A Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW204', 'T/A Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW205', 'T/A Pipefitter Welder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW301', 'T/A Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW302', 'T/A Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW303', 'T/A Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW304', 'T/A Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW305', 'T/A Pipefitter Welder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW401', 'T/A Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW402', 'T/A Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW403', 'T/A Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW404', 'T/A Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW405', 'T/A Pipefitter Welder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW501', 'T/A Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW502', 'T/A Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW503', 'T/A Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW504', 'T/A Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW505', 'T/A Pipefitter Welder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW601', 'T/A Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW602', 'T/A Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW603', 'T/A Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW604', 'T/A Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPFW605', 'T/A Pipefitter Welder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC101', 'T/A Scaffolder, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC201', 'T/A Scaffolder, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC301', 'T/A Scaffolder, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC401', 'T/A Scaffolder, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC501', 'T/A Scaffolder, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSC601', 'T/A Scaffolder, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSUIL601', 'CON Supervision, Insulation, Central, Co', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSUME601', 'CON Supervision, Mechanical, Central, Co', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CSUSC601', 'CON Supervision, Scaffold, Central, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('INSP', 'Inspector', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LABE06', 'Laboratory', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC1', 'Maint. Coordinator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC2', 'Maint. Coordinator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC3', 'Maint. Coordinator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC4', 'Maint. Coordinator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC4-1', 'Maint. Coordinator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC5', 'Maint. Coordinator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MC6', 'Maint. Coordinator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP1', 'Operations, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP2', 'Operations, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP3', 'Operations, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP4', 'Operations, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP5', 'Operations, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('OP6', 'Operations, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YBMKSP01', 'T/A Boilermaker Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YBMKSP02', 'T/A Boilermaker Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YCVSP01', 'T/A Control Valve Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YCVSP02', 'T/A Control Valve Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YELESP01', 'T/A Electrical Shop', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YPIPSP01', 'T/A Pipe Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YPIPSP02', 'T/A Pipe Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YPNTSP01', 'T/A Painting Shop', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YPSVSP01', 'T/A PSV Valve Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('YPSVSP02', 'T/A PSV Valve Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZCAT01', 'T/A Catalyst Service, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZCHEM01', 'T/A Chemical Clean, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZCV101', 'T/A Control Valve Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZCV201', 'T/A Control Valve Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZINS601', 'T/A Visual Inspector, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZINSLP01', 'Inspector, Liquid Penetrant', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZINSMP01', 'Inspector, Magnetic Particle', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZINSRT01', 'Inspector, Radiographic', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZINSTS01', 'Inspector, UT Thickness Survey', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZISOL01', 'T/A Isolation Plugs, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC101', 'T/A Coordinator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC201', 'T/A Coordinator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC301', 'T/A Coordinator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC401', 'T/A Coordinator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC501', 'T/A Coordinator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMC601', 'T/A Coordinator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMF01', 'T/A Machining Field, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZMPI01', 'T/A NDT Inspector, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR101', 'T/A Operator, Heavy Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR201', 'T/A Operator, Light Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR301', 'T/A Operator, Synthetic Oils', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR401', 'T/A Operator, Utilities', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR501', 'T/A Operator, Pumping&Shipping', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZOPR601', 'T/A Operator, Central', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZPIG01', 'T/A Pigging, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZRE01', 'T/A Refractory Service, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZRV101', 'T/A PSV Shop 1', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZRV201', 'T/A  PSV Shop 2', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSB01', 'T/A Sandblasting, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSR01', 'T/A Stress Relieving, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSUIL601', 'T/A Supervision, Insulation, Central, Co', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSUME601', 'T/A Supervision, Mechanical, Central, Co', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSUSC601', 'T/A Supervision, Scaffold, Central, Cont', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZSW601', 'T/A Safety Watch, Central, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZUTI01', 'T/A UT Inspector, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CTQ01', 'CON Torquing & Tensioner', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('CVAC01', 'CON Vacuum Truck', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EBMTK', '10 TON BOOM TRUCK', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EBNDLPL', 'PULLER, BUNDLE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRN125', 'CRANE, 125 TON', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRN25', 'CRANE, 25 TON', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRN50', 'CRANE, 50 TON', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRN60', 'CRANE, 60 TON', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRN80', 'CRANE, 80 TON', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ECRYDK', '8 Ton Carry Deck Crane', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EEXCV', 'EXCAVATOR,HYDRAULIC', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EFGRDL', 'GRADALL', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EGRDRCT', 'GRADER,CAT', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EGRVLTRL', 'TANDEM,GRAVEL W/ TRI-AXLE TRAILER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EGRVPKR', '15 Ton Pickers', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EHPPMP', 'PUMP,HIGH PRESS 300HP 0-10,000 PSI', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EHPTRK', 'TRUCK,HIGH PRESSURE (0-15,000 PSI)', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EIBC', 'IBC,INTERNAL BUNDLE CLEANER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ELODR', 'John Deere Loader', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ELODRCT', 'LOADER,CAT', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EPACKR', 'PACKER,SHEEPSFOOT 66"', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ESANDR', 'TRUCK,1-TON WITH SANDER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ESHTRK', 'UNIT,SEPTIC HAULING', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ESKDSTR', 'CASE 430SKID STEER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ETNDTRK', 'TRUCK,GRAVEL TANDEM', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ETRKDZR', 'DOZER,TRACK 550G', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ETVTRK', 'TRUCK,TURBO VAC', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EUHPTRK', 'TRUCK,ULTRA HIGH PRESS 36-40,000 PSI', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EVACGZ', 'VACUUM,SUPERSUCKER/GUZZLER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWJBB', 'BLASTER,BUNDLE H.P.', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWJRF', 'FAN,ROTO', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWJSTMR', 'STEAMER,(WET/DRY)', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWMBB', 'BLASTER,MINI BUNDLE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWTRTRK', 'TRUCK,WATER', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EWVAC', 'VACUUM,WET VAC (3,000 GAL)', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EZMBMC', 'Caterpillar Zoom Boom TH580B', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZBP01', 'T/A Bundle Pulling, Contractor', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZCRN01', 'T/A CRANE planning', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZJCF01', 'T/A Jet Cleaning Field', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZTQ01', 'T/A Torquing & Tensioner', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZVAC01', 'T/A Vacuum Truck', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('ZWC01', 'T/A Water Cutter', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('EQUIP_WC', 'EQUIP WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LABOR_WC', 'LABOR WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('MAINT_WC', 'MAINT WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('PLANT_WC', 'PLANT WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('SUPPT_WC', 'SUPPORT WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('T/A WC', 'T/A WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('Z_T/A_WC', 'TURNAROUND WC HIER NODE', 8, 0);
insert into CraftOrTrade (WorkCenter, Name, SiteId, Deleted) values ('LOGCRFED', 'Edmonton Logistics', 8, 0);



GO

