
IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WorkPermitFortHillsGroup]') AND type in (N'U'))
BEGIN

CREATE TABLE [dbo].[WorkPermitFortHillsGroup](
	[Id] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[DisplayOrder] [int] NOT NULL,
	[Deleted] [bit] NOT NULL,
	[DefaultToDayShiftOnSapImport] [bit] NOT NULL,
 CONSTRAINT [PK_WorkPermitFortHillsGroup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]


END



IF NOT (SELECT COUNT(*) FROM WORKPERMITFORTHILLSGROUP)>0
BEGIN
INSERT INTO WORKPERMITFORTHILLSGROUP (NAME,DISPLAYORDER,DELETED,DEFAULTTODAYSHIFTONSAPIMPORT) VALUES ('Maintenance',0,0,1),('Construction',1,0,1),('Turnaround',2,0,0),('Outage',3,0,0),('(Not Set)',4,1,0)
END
