

IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[WORKPERMITSIGN]') AND type in (N'U'))
BEGIN
Create TABLE WORKPERMITSIGN
(
 ID bigint Identity(1,1),
 WorkPermitId Varchar(100),
 
 ISSUER_FNAME  Nvarchar(500),
 ISSUER_LNAME   Nvarchar(500),
 ISSUER_BADGENUMBER NVARCHAR(100),
 ISSUER_BADGETYPE VARCHAR(100),
 ISSUER_SOURCE   VARCHAR(100),
 NEXT_LVL_ISSUER_FNAME  Nvarchar(500),
 NEXT_LVL_ISSUER_LNAME  Nvarchar(500),
 NEXT_LVL_ISSUER_BADGENUMBER NVARCHAR(100),
 NEXT_LVL_ISSUER_BADGETYPE VARCHAR(100),
 NEXT_LVL_ISSUER_SOURCE VARCHAR(100),
 PERMIT_RECEIVER_FNAME  Nvarchar(500),
 PERMIT_RECEIVER_LNAME  Nvarchar(500),
 PERMIT_RECEIVER_BADGENUMBER NVARCHAR(100), 
 PERMIT_RECEIVER_BADGETYPE VARCHAR(100),
 PERMIT_RECEIVER_SOURCE VARCHAR(100),
 CROSS_ZONE_AUTHO_FNAME  Nvarchar(500),
 CROSS_ZONE_AUTHO_LNAME  Nvarchar(500),
 CROSS_ZONE_AUTHO_BADGENUMBER NVARCHAR(100),
 CROSS_ZONE_AUTHO_BADGETYPE VARCHAR(100),
 CROSS_ZONE_AUTHO_SOURCE VARCHAR(100),
 IMMIDIATE_FNAME  Nvarchar(500),
 IMMIDIATE_LNAME  Nvarchar(500),
 IMMIDIATE_BADGENUMBER NVARCHAR(100),
 IMMIDIATE_BADGETYPE VARCHAR(100),
 IMMIDIATE_SOURCE VARCHAR(100),
 CONFINED_FNAME  Nvarchar(500),
 CONFINED_LNAME  Nvarchar(500),
 CONFINED_BADGENUMBER NVARCHAR(100),
 CONFINED_BADGETYPE VARCHAR(100),
 CONFINED_SOURCE VARCHAR(500),
 Deleted bit default(0),
 UpdatedBy int,
 CreatedBy int,
 CreatedDate Datetime,
 UpdatedDate Datetime,
 SiteId Int,

 
 )
END
