//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Suncor.Olt.Remote.Integration
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OpmToeDefinition", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class OpmToeDefinition : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CauseDescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsequenceDescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectiveActionDescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionalLocationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistorianTagField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPMPubHistoryURLLinkField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ToeLimitValueField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToeNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToeTypeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ToeVersionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToeVersionPublishDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitOfMeasureField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CauseDescription
        {
            get
            {
                return this.CauseDescriptionField;
            }
            set
            {
                this.CauseDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsequenceDescription
        {
            get
            {
                return this.ConsequenceDescriptionField;
            }
            set
            {
                this.ConsequenceDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrectiveActionDescription
        {
            get
            {
                return this.CorrectiveActionDescriptionField;
            }
            set
            {
                this.CorrectiveActionDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionalLocation
        {
            get
            {
                return this.FunctionalLocationField;
            }
            set
            {
                this.FunctionalLocationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HistorianTag
        {
            get
            {
                return this.HistorianTagField;
            }
            set
            {
                this.HistorianTagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPMPubHistoryURLLink
        {
            get
            {
                return this.OPMPubHistoryURLLinkField;
            }
            set
            {
                this.OPMPubHistoryURLLinkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ToeLimitValue
        {
            get
            {
                return this.ToeLimitValueField;
            }
            set
            {
                this.ToeLimitValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToeName
        {
            get
            {
                return this.ToeNameField;
            }
            set
            {
                this.ToeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToeType
        {
            get
            {
                return this.ToeTypeField;
            }
            set
            {
                this.ToeTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ToeVersion
        {
            get
            {
                return this.ToeVersionField;
            }
            set
            {
                this.ToeVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToeVersionPublishDate
        {
            get
            {
                return this.ToeVersionPublishDateField;
            }
            set
            {
                this.ToeVersionPublishDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitOfMeasure
        {
            get
            {
                return this.UnitOfMeasureField;
            }
            set
            {
                this.UnitOfMeasureField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OPMExcursion", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class OPMExcursion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AverageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DurationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineerCommentsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExcursionIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionalLocationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistorianTagField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IlpNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedDateTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPMTrendURLLinkField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PeakField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ToeLimitValueField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToeNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToeTypeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ToeVersionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitOfMeasureField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Average
        {
            get
            {
                return this.AverageField;
            }
            set
            {
                this.AverageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngineerComments
        {
            get
            {
                return this.EngineerCommentsField;
            }
            set
            {
                this.EngineerCommentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExcursionId
        {
            get
            {
                return this.ExcursionIdField;
            }
            set
            {
                this.ExcursionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionalLocation
        {
            get
            {
                return this.FunctionalLocationField;
            }
            set
            {
                this.FunctionalLocationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HistorianTag
        {
            get
            {
                return this.HistorianTagField;
            }
            set
            {
                this.HistorianTagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IlpNumber
        {
            get
            {
                return this.IlpNumberField;
            }
            set
            {
                this.IlpNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdatedDateTime
        {
            get
            {
                return this.LastUpdatedDateTimeField;
            }
            set
            {
                this.LastUpdatedDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPMTrendURLLink
        {
            get
            {
                return this.OPMTrendURLLinkField;
            }
            set
            {
                this.OPMTrendURLLinkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Peak
        {
            get
            {
                return this.PeakField;
            }
            set
            {
                this.PeakField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ToeLimitValue
        {
            get
            {
                return this.ToeLimitValueField;
            }
            set
            {
                this.ToeLimitValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToeName
        {
            get
            {
                return this.ToeNameField;
            }
            set
            {
                this.ToeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToeType
        {
            get
            {
                return this.ToeTypeField;
            }
            set
            {
                this.ToeTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ToeVersion
        {
            get
            {
                return this.ToeVersionField;
            }
            set
            {
                this.ToeVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitOfMeasure
        {
            get
            {
                return this.UnitOfMeasureField;
            }
            set
            {
                this.UnitOfMeasureField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OPMTagValue", Namespace = "http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class OPMTagValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimeStampField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality
        {
            get
            {
                return this.QualityField;
            }
            set
            {
                this.QualityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExceptionFaultContract", Namespace = "http://schemas.datacontract.org/2004/07/OPMXHQWCF")]
    [System.SerializableAttribute()]
    public partial class ExceptionFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "Com.Suncor.Olt.Remote.Integration.IOPMXHQService")]
    public interface IOPMXHQService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinition", ReplyAction = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinitionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Com.Suncor.Olt.Remote.Integration.ExceptionFaultContract), Action = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinitionExceptionFaultContractFault", Name = "ExceptionFaultContract", Namespace = "http://schemas.datacontract.org/2004/07/OPMXHQWCF")]
        Com.Suncor.Olt.Remote.Integration.OpmToeDefinition GetOpmToeDefinition(string historianTag, System.Nullable<long> versionId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinitions", ReplyAction = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinitionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Com.Suncor.Olt.Remote.Integration.ExceptionFaultContract), Action = "http://tempuri.org/IOPMXHQService/GetOpmToeDefinitionsExceptionFaultContractFault" +
            "", Name = "ExceptionFaultContract", Namespace = "http://schemas.datacontract.org/2004/07/OPMXHQWCF")]
        Com.Suncor.Olt.Remote.Integration.OpmToeDefinition[] GetOpmToeDefinitions(string historianTag, System.Nullable<long> versionId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOPMXHQService/GetOpmExcursions", ReplyAction = "http://tempuri.org/IOPMXHQService/GetOpmExcursionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Com.Suncor.Olt.Remote.Integration.ExceptionFaultContract), Action = "http://tempuri.org/IOPMXHQService/GetOpmExcursionsExceptionFaultContractFault", Name = "ExceptionFaultContract", Namespace = "http://schemas.datacontract.org/2004/07/OPMXHQWCF")]
        Com.Suncor.Olt.Remote.Integration.OPMExcursion[] GetOpmExcursions(System.Nullable<System.DateTime> dateAndTimeQueryFrom);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IOPMXHQService/GetCurrentTagValue", ReplyAction = "http://tempuri.org/IOPMXHQService/GetCurrentTagValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Com.Suncor.Olt.Remote.Integration.ExceptionFaultContract), Action = "http://tempuri.org/IOPMXHQService/GetCurrentTagValueExceptionFaultContractFault", Name = "ExceptionFaultContract", Namespace = "http://schemas.datacontract.org/2004/07/OPMXHQWCF")]
        Com.Suncor.Olt.Remote.Integration.OPMTagValue GetCurrentTagValue(string historianTag);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOPMXHQServiceChannel : Com.Suncor.Olt.Remote.Integration.IOPMXHQService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OPMXHQServiceClient : System.ServiceModel.ClientBase<Com.Suncor.Olt.Remote.Integration.IOPMXHQService>, Com.Suncor.Olt.Remote.Integration.IOPMXHQService
    {

        public OPMXHQServiceClient()
        {
        }

        public OPMXHQServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public OPMXHQServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OPMXHQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OPMXHQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public Com.Suncor.Olt.Remote.Integration.OpmToeDefinition GetOpmToeDefinition(string historianTag, System.Nullable<long> versionId)
        {
            return base.Channel.GetOpmToeDefinition(historianTag, versionId);
        }

        public Com.Suncor.Olt.Remote.Integration.OpmToeDefinition[] GetOpmToeDefinitions(string historianTag, System.Nullable<long> versionId)
        {
            return base.Channel.GetOpmToeDefinitions(historianTag, versionId);
        }

        public Com.Suncor.Olt.Remote.Integration.OPMExcursion[] GetOpmExcursions(System.Nullable<System.DateTime> dateAndTimeQueryFrom)
        {
            return base.Channel.GetOpmExcursions(dateAndTimeQueryFrom);
        }

        public Com.Suncor.Olt.Remote.Integration.OPMTagValue GetCurrentTagValue(string historianTag)
        {
            return base.Channel.GetCurrentTagValue(historianTag);
        }
    }
}
