if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[InsertPermitRequestEdmontonHistory]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[InsertPermitRequestEdmontonHistory]
GO

CREATE Procedure [dbo].[InsertPermitRequestEdmontonHistory]      
    (      
    @Id bigint,      
 @EndDate datetime,      
 @PriorityId int,      
 @WorkOrderNumber varchar(12) = NULL,      
 @OperationNumber varchar(max) = NULL,      
 @SubOperationNumber varchar(max) = NULL,      
 @Description varchar(8000),      
 @SAPDescription varchar(8000) = NULL,      
 @Company varchar(50) = NULL,      
 @LastImportedByUserId int = NULL,      
 @LastImportedDateTime datetime = NULL,      
 @LastSubmittedByUserId int = NULL,      
 @LastSubmittedDateTime datetime = NULL,      
 @LastModifiedByUserId int,      
 @LastModifiedDateTime datetime,      
 @IssuedToSuncor bit,      
 @Occupation varchar(50),      
 @NumberOfWorkers int = NULL,      
 @Group varchar(50) = null,      
 @WorkPermitTypeId int,       
 @FunctionalLocation varchar(200),      
 @Location varchar(100),      
 @AreaLabel varchar(40) = NULL,      
 @DocumentLinks varchar(max) = NULL,      
 @AlkylationEntryClassOfClothing varchar(25) = NULL,      
 @FlarePitEntryType varchar(25) = NULL,      
 @ConfinedSpaceCardNumber varchar(15) = NULL,      
 @ConfinedSpaceClass varchar(25) = NULL,      
 @RescuePlanFormNumber varchar(15) = NULL,      
 @VehicleEntryTotal int = NULL,      
 @VehicleEntryType varchar(30) = NULL,      
 @SpecialWorkFormNumber varchar(15) = NULL,      
 @SpecialWorkType varchar(100) = NULL,      
 @FormGN59Id bigint = NULL,       
 @FormGN7Id bigint = NULL,      
 @FormGN24Id bigint = NULL,      
 @FormGN6Id bigint = NULL,      
 @FormGN75AId bigint = NULL,      
 @FormGN1TradeChecklistDisplayNumber varchar(32) = NULL,      
 @GN59 bit,      
 @GN7 bit,      
 @GN24 bit,      
 @GN6 bit,      
 @GN75A bit,      
 @GN1 bit,      
 @GN11 varchar(50),      
 @GN24_Deprecated varchar(50),      
 @GN6_Deprecated varchar(50),      
 @GN27 varchar(50),      
 @GN75_Deprecated varchar(50),      
 @AlkylationEntry bit,      
 @FlarePitEntry bit,      
 @ConfinedSpace bit,      
 @RescuePlan bit,      
 @VehicleEntry bit,      
 @SpecialWork bit,       
 @RequestedStartDate datetime,      
 @RequestedStartTimeDay datetime = NULL,      
 @RequestedStartTimeNight datetime = NULL,      
 @HazardsAndOrRequirements varchar(500) = NULL,      
 @OtherAreasAndOrUnitsAffectedArea varchar(50) = NULL,      
 @OtherAreasAndOrUnitsAffectedPersonNotified varchar(30) = NULL,      
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob bit,      
 @FaceShield bit,      
 @Goggles bit,      
 @RubberBoots bit,      
 @RubberGloves bit,      
 @RubberSuit bit,      
 @SafetyHarnessLifeline bit,      
 @HighVoltagePPE bit,       
 @Other1 varchar(30) = NULL,      
 @EquipmentGrounded bit,      
 @FireBlanket bit,      
 @FireExtinguisher bit,      
 @FireMonitorManned bit,      
 @FireWatch bit,      
 @SewersDrainsCovered bit,      
 @SteamHose bit,      
 @Other2 varchar(30) = NULL,      
 @AirPurifyingRespirator bit,      
 @BreathingAirApparatus bit,      
 @DustMask bit,      
 @LifeSupportSystem bit,      
 @SafetyWatch bit,      
 @ContinuousGasMonitor bit,      
 @WorkersMonitor bit,      
 @WorkersMonitorNumber varchar(10) = null,      
 @BumpTestMonitorPriorToUse bit,       
 @Other3 varchar(30) = NULL,      
 @AirMover bit,      
 @BarriersSigns bit,      
 @RadioChannel bit,      
 @RadioChannelNumber varchar(10) = null,      
 @AirHorn bit,      
 @MechVentilationComfortOnly bit,      
 @AsbestosMMCPrecautions bit,       
 @Other4 varchar(30) = NULL,      
 @CompletionStatusId int,      
       
 @RoadAccessOnPermit bit ,        
 @RoadAccessOnPermitFormNumber varchar(10) = NULL,        
 @RoadAccessOnPermitType varchar(50) = NULL ,    
     
 @SpecialWorkName VARCHAR(100)      
    
)      
AS      
    
     
      
if(@SpecialWorkType Is Null)      
Begin       
 SET @SpecialWorkType = @SpecialWorkName      
End      
      
      
INSERT INTO PermitRequestEdmontonHistory      
(      
 Id,      
 EndDate,      
 PriorityId,      
 WorkOrderNumber,      
 OperationNumber,      
 SubOperationNumber,      
 TaskDescription,      
 SAPDescription,      
 Company,      
 LastImportedByUserId,      
 LastImportedDateTime,      
 LastSubmittedByUserId,      
 LastSubmittedDateTime,      
 LastModifiedByUserId,      
 LastModifiedDateTime,      
 IssuedToSuncor,      
 Occupation,      
 NumberOfWorkers,      
 [Group],      
 WorkPermitTypeId,       
 FunctionalLocation,      
 Location,      
 AreaLabel,      
 DocumentLinks,      
 AlkylationEntryClassOfClothing,      
 FlarePitEntryType,      
 ConfinedSpaceCardNumber,      
 ConfinedSpaceClass,      
 RescuePlanFormNumber,      
 VehicleEntryTotal,      
 VehicleEntryType,      
 SpecialWorkFormNumber,      
 SpecialWorkType,      
 FormGN59Id,       
 FormGN7Id,      
 FormGN24Id,      
 FormGN6Id,      
 FormGN75AId,      
 FormGN1TradeChecklistDisplayNumber,      
 GN59,      
 GN7,      
 GN24,      
 GN6,      
 GN75A,      
 GN1,      
 GN11,      
 GN24_Deprecated,      
 GN6_Deprecated,      
 GN27,      
 GN75_Deprecated,      
 AlkylationEntry,      
 FlarePitEntry,      
 ConfinedSpace,      
 RescuePlan,      
 VehicleEntry,      
 SpecialWork,       
 RequestedStartDate,      
 RequestedStartTimeDay,      
 RequestedStartTimeNight,      
 HazardsAndOrRequirements,      
 OtherAreasAndOrUnitsAffectedArea,      
 OtherAreasAndOrUnitsAffectedPersonNotified,      
 WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,      
 FaceShield,      
 Goggles,      
 RubberBoots,      
 RubberGloves,      
 RubberSuit,      
 SafetyHarnessLifeline,      
 HighVoltagePPE,      
 Other1,       
 EquipmentGrounded,      
 FireBlanket,      
 FireExtinguisher,      
 FireMonitorManned,      
 FireWatch,      
 SewersDrainsCovered,      
 SteamHose,      
 Other2,      
 AirPurifyingRespirator,      
 BreathingAirApparatus,      
 DustMask,      
 LifeSupportSystem,      
 SafetyWatch,      
 ContinuousGasMonitor,      
 WorkersMonitor,      
 WorkersMonitorNumber,      
 BumpTestMonitorPriorToUse,      
 Other3,      
 AirMover,      
 BarriersSigns,      
 RadioChannel,      
 RadioChannelNumber,      
 AirHorn,      
 MechVentilationComfortOnly,      
 AsbestosMMCPrecautions,      
 Other4,      
 CompletionStatusId,      
 RoadAccessOnPermit1 ,        
 RoadAccessOnPermitFormNumber1,        
 RoadAccessOnPermitType1      
)      
VALUES      
(       
 @Id,      
 @EndDate,      
 @PriorityId,      
 @WorkOrderNumber,      
 @OperationNumber,      
 @SubOperationNumber,      
 @Description,      
 @SAPDescription,      
 @Company,      
 @LastImportedByUserId,      
 @LastImportedDateTime,      
 @LastSubmittedByUserId,      
 @LastSubmittedDateTime,      
 @LastModifiedByUserId,      
 @LastModifiedDateTime,      
 @IssuedToSuncor,      
 @Occupation,      
 @NumberOfWorkers,      
 @Group,      
 @WorkPermitTypeId,       
 @FunctionalLocation,      
 @Location,      
 @AreaLabel,      
 @DocumentLinks,      
 @AlkylationEntryClassOfClothing,      
 @FlarePitEntryType,      
 @ConfinedSpaceCardNumber,      
 @ConfinedSpaceClass,      
 @RescuePlanFormNumber,      
 @VehicleEntryTotal,      
 @VehicleEntryType,      
 @SpecialWorkFormNumber,      
 @SpecialWorkType,      
 @FormGN59Id,      
 @FormGN7Id,      
 @FormGN24Id,      
 @FormGN6Id,      
 @FormGN75AId,      
 @FormGN1TradeChecklistDisplayNumber,      
 @GN59,      
 @GN7,      
 @GN24,      
 @GN6,      
 @GN75A,      
 @GN1,      
 @GN11,      
 @GN24_Deprecated,      
 @GN6_Deprecated,      
 @GN27,      
 @GN75_Deprecated,      
 @AlkylationEntry,      
 @FlarePitEntry,      
 @ConfinedSpace,      
 @RescuePlan,      
 @VehicleEntry,      
 @SpecialWork,        
 @RequestedStartDate,      
 @RequestedStartTimeDay,      
 @RequestedStartTimeNight,      
 @HazardsAndOrRequirements,      
 @OtherAreasAndOrUnitsAffectedArea,      
 @OtherAreasAndOrUnitsAffectedPersonNotified,      
 @WorkersMinimumSafetyRequirementsSectionNotApplicableToJob,      
 @FaceShield,      
 @Goggles,      
 @RubberBoots,      
 @RubberGloves,      
 @RubberSuit,      
 @SafetyHarnessLifeline,      
 @HighVoltagePPE,      
 @Other1,       
 @EquipmentGrounded,      
 @FireBlanket,      
 @FireExtinguisher,      
 @FireMonitorManned,      
 @FireWatch,      
 @SewersDrainsCovered,   
 @SteamHose,      
 @Other2,       
 @AirPurifyingRespirator,      
 @BreathingAirApparatus,      
 @DustMask,      
 @LifeSupportSystem,      
 @SafetyWatch,      
 @ContinuousGasMonitor,      
 @WorkersMonitor,      
 @WorkersMonitorNumber,      
 @BumpTestMonitorPriorToUse,      
 @Other3,       
 @AirMover,      
 @BarriersSigns,      
 @RadioChannel,      
 @RadioChannelNumber,      
 @AirHorn,      
 @MechVentilationComfortOnly,      
 @AsbestosMMCPrecautions,      
 @Other4,      
 @CompletionStatusId,      
 @RoadAccessOnPermit ,        
 @RoadAccessOnPermitFormNumber,        
 @RoadAccessOnPermitType      
)      
SET @Id= SCOPE_IDENTITY()       
      
      
GRANT EXEC ON [InsertPermitRequestEdmontonHistory] TO PUBLIC  
GO
