IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WorkPermitFortHillsHistory]') AND type in (N'U'))

BEGIN

CREATE TABLE [dbo].[WorkPermitFortHillsHistory](
	[Id] [bigint] NOT NULL,
	[WorkPermitStatusId] [int] NOT NULL,
	[DataSourceId] [int] NOT NULL,
	[Company] [varchar](50) NULL,
	[Occupation] [varchar](50) NULL,
	[NumberOfWorkers] [int] NULL,
	[WorkPermitTypeId] [int] NOT NULL,
	[FunctionalLocation] [varchar](200) NOT NULL,
	[Location] [varchar](50) NULL,
	[RequestedStartDateTime] [datetime] NOT NULL,
	[IssuedDateTime] [datetime] NULL,
	[ExpiredDateTime] [datetime] NOT NULL,
	[PermitNumber] [bigint] NULL,
	[WorkOrderNumber] [varchar](25) NULL,
	[OperationNumber] [varchar](max) NULL,
	[SubOperationNumber] [varchar](max) NULL,
	[TaskDescription] [varchar](max) NULL,
	[HazardsAndOrRequirements] [varchar](2000) NULL,
	[LastModifiedByUserId] [bigint] NOT NULL,
	[LastModifiedDateTime] [datetime] NOT NULL,
	[IssuedToSuncor] [bit] NOT NULL,
	[IssuedToCompany] [bit] NOT NULL,
	[Group] [varchar](50) NULL,
	[PriorityId] [int] NOT NULL,
	[EquipmentNo] [int] NULL,
	[Craft] [varchar](25) NULL,
	[CrewSize] [int] NULL,
	[JobCoordinator] [varchar](25) NULL,
	[CoOrdContactNumber] [varchar](10) NULL,
	[EmergencyAssemblyArea] [varchar](25) NULL,
	[EmergencyMeetingPoint] [varchar](25) NULL,
	[EmergencyContactNumber] [varchar](10) NULL,
	[Locknumber] [varchar](10) NULL,
	[IsolationNumber] [varchar](10) NULL,
	[RevalidationDateTime] [datetime] NULL,
	[ExtensionDateTime] [datetime] NULL,
	[FlameResistantWorkWear] [bit] NOT NULL,
	[ChemicalSuit] [bit] NOT NULL,
	[FireWatch] [bit] NOT NULL,
	[FireBlanket] [bit] NOT NULL,
	[SuppliedBreathingAir] [bit] NOT NULL,
	[AirMover] [bit] NOT NULL,
	[PersonalFlotationDevice] [bit] NOT NULL,
	[HearingProtection] [bit] NOT NULL,
	[Other1] [varchar](30) NULL,
	[MonoGoggles] [bit] NOT NULL,
	[ConfinedSpaceMoniter] [bit] NOT NULL,
	[FireExtinguisher] [bit] NOT NULL,
	[SparkContainment] [bit] NOT NULL,
	[BottleWatch] [bit] NOT NULL,
	[StandbyPerson] [bit] NOT NULL,
	[WorkingAlone] [bit] NOT NULL,
	[SafetyGloves] [bit] NOT NULL,
	[Other2] [varchar](30) NULL,
	[FaceShield] [bit] NOT NULL,
	[FallProtection] [bit] NOT NULL,
	[ChargedFireHouse] [bit] NOT NULL,
	[CoveredSewer] [bit] NOT NULL,
	[AirPurifyingRespirator] [bit] NOT NULL,
	[SingalPerson] [bit] NOT NULL,
	[CommunicationDevice] [bit] NOT NULL,
	[ReflectiveStrips] [bit] NOT NULL,
	[Other3] [varchar](30) NULL,
	[ConfinedSpace] [bit] NOT NULL,
	[ConfinedSpaceClass] [varchar](25) NULL,
	[GoundDisturbance] [bit] NOT NULL,
	[FireProtectionAuthorization] [bit] NOT NULL,
	[CriticalOrSeriousLifts] [bit] NOT NULL,
	[VehicleEntry] [bit] NOT NULL,
	[IndustrialRadiography] [bit] NOT NULL,
	[ElectricalEncroachment] [bit] NOT NULL,
	[MSDS] [bit] NOT NULL,
	[OthersPartE] [varchar](30) NULL,
	[MechanicallyIsolated] [bit] NOT NULL,
	[BlindedOrBlanked] [bit] NOT NULL,
	[DoubleBlockedandBled] [bit] NOT NULL,
	[DrainedAndDepressurised] [bit] NOT NULL,
	[PurgedorNeutralised] [bit] NOT NULL,
	[ElectricallyIsolated] [bit] NOT NULL,
	[TestBumped] [bit] NOT NULL,
	[NuclearSource] [bit] NOT NULL,
	[ReceiverStafingRequirements] [bit] NOT NULL,
	[PermitAcceptor] [varchar](30) NULL,
	[ShiftSupervisor] [varchar](30) NULL,
	[Frequency] [varchar](10) NULL,
	[TesterName] [varchar](50) NULL,
	[Oxygen] [bit] NULL,
	[LEL] [bit] NULL,
	[H2SPPM] [bit] NULL,
	[CoPPM] [bit] NULL,
	[So2PPM] [bit] NULL,
	[Other1PartGValue] [varchar](50) NULL,
	[Other2PartGValue] [varchar](50) NULL,
	[PermitRequester][varchar](50) NULL,
	[AreaAuthority][varchar](50) NULL,
	[COAuthorizingIssuer][varchar](50) NULL,
	[AddationalAuthority][varchar](50) NULL,
	[PermitRequesterContact][varchar](10) NULL,
	[AreaAuthorityContact][varchar](10) NULL,
	[COAuthorizingIssuerContact][varchar](10) NULL,
	[AddationalAuthorityContact][varchar](10) NULL,
	[IsFieldTourRequired][bit]NULL,
	[FieldTourConductedBy][VARCHAR](25) NULL,
) ON [PRIMARY]

--GO

--SET ANSI_PADDING OFF
--GO

--ALTER TABLE [dbo].[WorkPermitFortHillsHistory]  WITH CHECK ADD  CONSTRAINT [FK_WorkPermitFortHillsHistory_LastModifiedByUser] FOREIGN KEY([LastModifiedByUserId])
--REFERENCES [dbo].[User] ([Id])
--GO

--ALTER TABLE [dbo].[WorkPermitFortHillsHistory] CHECK CONSTRAINT [FK_WorkPermitFortHillsHistory_LastModifiedByUser]
--GO

END
