CREATE CLUSTERED INDEX [IDX_WorkPermitHistory_Extension]
ON [dbo].[WorkPermitHistory_Extension]
([Id])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO

DROP INDEX [IDX_WorkPermitHistory] ON [dbo].[WorkPermitHistory];
GO

CREATE CLUSTERED INDEX [IDX_WorkPermitHistory] 
ON [dbo].[WorkPermitHistory]
([Id])
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 90,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
GO



GO

